<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Why one-hot vectors cannot generalize across words, how featurized word embeddings fix that, and how analogy reasoning and the embedding matrix work.">

<title>Introduction to Word Embeddings – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../ai/deep-learning/sequence-models/learning-word-embeddings-word2vec-and-glove" rel="next">
<link href="../../../ai/deep-learning/sequence-models/lab-improvise-a-jazz-solo" rel="prev">
<link href="../../../media/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-09af6f1c3ba400237d3ba77e487e1b25.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-43798084b7368a40096bd6648f6381c9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css?v=10149509">
<meta property="og:title" content="Introduction to Word Embeddings – H’s Notes">
<meta property="og:description" content="Why one-hot vectors cannot generalize across words, how featurized word embeddings fix that, and how analogy reasoning and the embedding matrix work.">
<meta property="og:image" content="https://oliabak.com/ai/deep-learning/sequence-models/introduction-to-word-embeddings_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta property="og:image:alt" content="A schematic two-dimensional scatter of fourteen labeled words. People words man, woman, king, and queen cluster together, animals dog, cat, and fish cluster together, numbers one, two, three, and four cluster together, and fruits grape, apple, and orange cluster together.">
<meta name="twitter:title" content="Introduction to Word Embeddings – H’s Notes">
<meta name="twitter:description" content="Why one-hot vectors cannot generalize across words, how featurized word embeddings fix that, and how analogy reasoning and the embedding matrix work.">
<meta name="twitter:image" content="https://oliabak.com/ai/deep-learning/sequence-models/introduction-to-word-embeddings_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:image:alt" content="A schematic two-dimensional scatter of fourteen labeled words. People words man, woman, king, and queen cluster together, animals dog, cat, and fish cluster together, numbers one, two, three, and four cluster together, and fruits grape, apple, and orange cluster together.">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://oliabak.com/ai/deep-learning/sequence-models/introduction-to-word-embeddings">
<script type="application/ld+json" data-breadcrumbs="1">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Artificial Intelligence",
      "item": "https://oliabak.com/ai/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Deep Learning",
      "item": "https://oliabak.com/ai/deep-learning/"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Sequence Models",
      "item": "https://oliabak.com/ai/deep-learning/sequence-models/"
    },
    {
      "@type": "ListItem",
      "position": 4,
      "name": "Introduction to Word Embeddings",
      "item": "https://oliabak.com/ai/deep-learning/sequence-models/introduction-to-word-embeddings"
    }
  ]
}
</script>
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../../networking/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccde-written/">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccie-data-center/">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../networking/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-routing/">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-switching/">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/kali-linux/">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../../ai/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/supervised-machine-learning/">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/advanced-learning-algorithms/">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/unsupervised-learning/">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/federated-learning/">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/neural-networks-and-deep-learning/">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/improving-deep-neural-networks/">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/structuring-machine-learning-projects/">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/convolutional-neural-networks/">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/sequence-models/">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../../math/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/linear-algebra/">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/calculus/">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/probability/">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/statistics/">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../../tools/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../../tools/client-info">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/asn-conversion">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/subnet-calculator">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/network-toolkit">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/pastebin">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/short-links">
 <span class="dropdown-text">Short Links</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/qr-code">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/fancy-text">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/copy-paste-values">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Classroom</li>
        <li>
    <a class="dropdown-item" href="../../../tools/randomizer">
 <span class="dropdown-text">Randomizer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../../tools/function-graphs">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/math-formula">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/latex-preview">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/markdown-preview">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/eclipse-atlas">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/planetarium">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../../tools/svg-preview">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/color-pallet">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/typography">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/tshirt-design">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../../tools/chess">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/reassess-your-chess">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/daily-chess">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../about">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/dashboard">
 <span class="dropdown-text">Dashboard</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../../about/roadmap">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/about-this-website">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/">Deep Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/">Sequence Models</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/introduction-to-word-embeddings">Introduction to Word Embeddings</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/deep-learning/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/deep-learning/sequence-models/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sequence Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/recurrent-neural-networks" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recurrent Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/rnn-architectures-and-language-models" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RNN Architectures and Language Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/vanishing-gradients-gru-and-lstm" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vanishing Gradients, GRUs, and LSTMs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/bidirectional-and-deep-rnns" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bidirectional and Deep RNNs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-building-your-recurrent-neural-network" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Building Your Recurrent Neural Network Step by Step</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-character-level-language-model" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Character Level Language Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-improvise-a-jazz-solo" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Improvise a Jazz Solo with an LSTM Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/introduction-to-word-embeddings" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Introduction to Word Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/learning-word-embeddings-word2vec-and-glove" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Word Embeddings with Word2vec and GloVe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/sentiment-classification-and-debiasing" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sentiment Classification and Debiasing Word Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-operations-on-word-vectors" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Operations on Word Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-emojify" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Emojify</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/sequence-to-sequence-models" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sequence to Sequence Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/beam-search" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Beam Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/bleu-score" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BLEU Score</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/attention-model" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Attention Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/speech-recognition-and-trigger-word-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Speech Recognition and Trigger Word Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-neural-machine-translation" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Neural Machine Translation with Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-trigger-word-detection" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Trigger Word Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/transformer-network" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transformer Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-transformer-network" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Building a Transformer Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-fine-tuning-a-pretrained-transformer" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Fine-Tuning a Pretrained Transformer</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#word-representation" id="toc-word-representation" class="nav-link active" data-scroll-target="#word-representation">Word Representation</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#using-word-embeddings" id="toc-using-word-embeddings" class="nav-link" data-scroll-target="#using-word-embeddings">Using Word Embeddings</a>
  <ul class="collapse">
  <li><a href="#transfer-learning-with-embeddings" id="toc-transfer-learning-with-embeddings" class="nav-link" data-scroll-target="#transfer-learning-with-embeddings">Transfer Learning with Embeddings</a></li>
  <li><a href="#relation-to-face-encoding" id="toc-relation-to-face-encoding" class="nav-link" data-scroll-target="#relation-to-face-encoding">Relation to Face Encoding</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#properties-of-word-embeddings" id="toc-properties-of-word-embeddings" class="nav-link" data-scroll-target="#properties-of-word-embeddings">Properties of Word Embeddings</a>
  <ul class="collapse">
  <li><a href="#cosine-similarity" id="toc-cosine-similarity" class="nav-link" data-scroll-target="#cosine-similarity">Cosine Similarity</a></li>
  <li><a href="#generality-of-analogies" id="toc-generality-of-analogies" class="nav-link" data-scroll-target="#generality-of-analogies">Generality of Analogies</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#embedding-matrix" id="toc-embedding-matrix" class="nav-link" data-scroll-target="#embedding-matrix">Embedding Matrix</a>
  <ul class="collapse">
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<script src="../../../theme-toggle.js?v=3505170f"></script>
<script src="../../../auth.js?v=37e2729f"></script>
<script src="../../../site-metrics.js?v=9d1b4053"></script>
<script src="../../../giscus-note.js?v=e94ec728"></script>
<script src="../../../resume-reading.js?v=c40ebfea"></script>
<script src="../../../sidebar-active.js?v=62f05be2"></script>
<script src="../../../search-scope.js?v=13576411"></script>
<script src="../../../review-numbering.js?v=50100e67"></script>
<script src="../../../nav-columns.js?v=a9beef4d"></script>
<script src="../../../activation-colors.js?v=a9e5b12e"></script>
<script src="../../../visit-history.js?v=85edd45a"></script>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/">Deep Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/">Sequence Models</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/introduction-to-word-embeddings">Introduction to Word Embeddings</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Introduction to Word Embeddings</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">sequence-models</div>
    <div class="quarto-category">nlp</div>
    <div class="quarto-category">word-embeddings</div>
    <div class="quarto-category">transfer-learning</div>
    <div class="quarto-category">cosine-similarity</div>
  </div>
  </div>

<div>
  <div class="description">
    Why one-hot vectors cannot generalize across words, how featurized word embeddings fix that, and how analogy reasoning and the embedding matrix work.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Aug 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (!meta) return;

  // Published, and Modified only where a page actually sets date-modified.
  // Two pages do, about-this-website and roadmap, and both carry it on
  // purpose because they describe a site that keeps changing.
  function readCell(sel) {
    var el = meta.querySelector(sel);
    if (!el) return "";
    var cell = el.closest("div");
    var body = cell && cell.querySelector(".quarto-title-meta-contents");
    return ((body || el).textContent || "").trim();
  }
  var published = readCell(".date");
  var modified = readCell(".date-modified");

  var html = '<span class="quarto-title-meta-item">82 min <span class="rt-info" tabindex="0" aria-describedby="reading-time-method"><span aria-hidden="true">&#9432;</span><span class="rt-tooltip" id="reading-time-method" role="tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></span><span class="quarto-title-meta-item">5,600 words</span><span class="quarto-title-meta-item">difficulty 3/5</span>';
  function esc(t) {
    return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  if (published) {
    html += '<span class="quarto-title-meta-item">published ' + esc(published) + '</span>';
  }
  if (modified && modified !== published) {
    html += '<span class="quarto-title-meta-item">updated ' + esc(modified) + '</span>';
  }

  var line = document.createElement("div");
  line.className = "quarto-title-meta-line site-meta";
  line.innerHTML = html;
  meta.insertBefore(line, meta.firstChild);
});
</script>

<p>The previous pages built up RNNs, GRUs, LSTMs, and their bidirectional and deep variants. Many of those ideas can now be applied to natural language processing, which is one of the areas of AI most transformed by deep learning. The key idea on this page is the <span class="term" tabindex="0" data-def="A dense, learned vector representation of a word, where words with similar meanings end up with similar vectors."><strong>word embedding</strong></span>, a way of representing words that lets an algorithm notice on its own that man is to woman as king is to queen. Word embeddings also let you build NLP applications with relatively small labeled training sets.</p>
<section id="word-representation" class="level2">
<h2 class="anchored" data-anchor-id="word-representation">Word Representation</h2>
<p>So far words have been represented using a <a href="../../../ai/deep-learning/sequence-models/recurrent-neural-networks#representing-words">vocabulary</a> of, say, 10,000 words, and each word has been written as a one-hot vector. If <code>man</code> is word number 5391 in the dictionary, then it is represented by a vector with a 1 in position 5391 and zeros everywhere else. The notation for that vector is <span class="math inline">\(o_{5391}\)</span>, where <span class="math inline">\(o\)</span> stands for one-hot. If <code>woman</code> is word number 9853, it is represented by <span class="math inline">\(o_{9853}\)</span>, which has a 1 in position 9853 and zeros elsewhere. The words <code>king</code> (4914), <code>queen</code> (7157), <code>apple</code> (456), and <code>orange</code> (6257) are represented the same way.</p>
<p>One of the weaknesses of this representation is that it treats each word as a thing unto itself, and it does not let an algorithm generalize across words. Suppose a language model has learned that when it sees</p>
<blockquote class="blockquote">
<p>I want a glass of orange ______</p>
</blockquote>
<p>the next word is very likely <code>juice</code>. Even so, if that same model now sees</p>
<blockquote class="blockquote">
<p>I want a glass of apple ______</p>
</blockquote>
<p>then as far as it knows, the relationship between <code>apple</code> and <code>orange</code> is no closer than the relationship between any other pair of words, such as <code>man</code> and <code>orange</code> or <code>queen</code> and <code>orange</code>. So it is not easy for the learning algorithm to generalize from knowing that orange juice is a popular phrase to guessing that apple juice might be one too.</p>
<p>The reason is arithmetic. The inner product between any two different one-hot vectors is zero, because wherever one vector has its single 1, the other has a 0. Take <code>king</code> and <code>queen</code>, and the inner product is zero. Take <code>apple</code> and <code>orange</code>, and the inner product is zero as well. The Euclidean distance between any pair of these vectors is also the same for every pair. Nothing in the representation says that <code>apple</code> and <code>orange</code> are more similar to each other than <code>king</code> and <code>orange</code> are.</p>
<p>So it would be much better to learn a <span class="term" tabindex="0" data-def="A representation where each coordinate is a learned feature value, so that similar words end up with similar coordinates."><strong>featurized representation</strong></span> for each word instead. For every word in the dictionary, learn a set of features and a value for each of them.</p>
<p>Start with gender. Let gender run from <span class="math inline">\(-1\)</span> for male to <span class="math inline">\(+1\)</span> for female. Then the gender value for <code>man</code> might be <span class="math inline">\(-1\)</span> and for <code>woman</code> <span class="math inline">\(+1\)</span>. Learning these values might give <span class="math inline">\(-0.95\)</span> for <code>king</code> and <span class="math inline">\(+0.97\)</span> for <code>queen</code>, while <code>apple</code> and <code>orange</code> come out essentially genderless. Another feature could be how royal these things are. The words <code>man</code> and <code>woman</code> are not really royal, so their values sit close to zero, while <code>king</code> and <code>queen</code> are highly royal, and <code>apple</code> and <code>orange</code> are not royal at all. Age is another. The words <code>man</code> and <code>woman</code> do not say much about age, so those values are close to zero, while kings and queens are almost always adults, and <code>apple</code> and <code>orange</code> are neutral with respect to age. A fourth feature could ask whether the word names a food. A man is not a food, a woman is not a food, and neither are kings and queens, but apples and oranges are.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>man (5391)</th>
<th>woman (9853)</th>
<th>king (4914)</th>
<th>queen (7157)</th>
<th>apple (456)</th>
<th>orange (6257)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Gender</td>
<td>-1</td>
<td>1</td>
<td>-0.95</td>
<td>0.97</td>
<td>0.00</td>
<td>0.01</td>
</tr>
<tr class="even">
<td>Royal</td>
<td>0.01</td>
<td>0.02</td>
<td>0.93</td>
<td>0.95</td>
<td>-0.01</td>
<td>0.00</td>
</tr>
<tr class="odd">
<td>Age</td>
<td>0.03</td>
<td>0.02</td>
<td>0.70</td>
<td>0.69</td>
<td>0.03</td>
<td>-0.02</td>
</tr>
<tr class="even">
<td>Food</td>
<td>0.09</td>
<td>0.01</td>
<td>0.02</td>
<td>0.01</td>
<td>0.95</td>
<td>0.97</td>
</tr>
</tbody>
</table>
<p>There can be many other features as well, ranging from size, to cost, to whether the thing is alive, to whether the word is an action, a noun, a verb, or something else. You can imagine coming up with a great many features. For the sake of illustration, say there are 300 different features. That turns each column of the table above into a list of 300 numbers, a 300-dimensional vector representing that word. The notation <span class="math inline">\(e_{5391}\)</span> denotes that vector for <code>man</code>, and <span class="math inline">\(e_{9853}\)</span> denotes the 300-dimensional vector for <code>woman</code>.</p>
<p>Now look at what happens to <code>apple</code> and <code>orange</code> under this representation. Their columns are quite similar. Some features will differ, because the color of an orange is not the color of an apple, and the taste is not the same, but by and large a lot of the features of <code>apple</code> and <code>orange</code> take on very similar values. That increases the odds that a learning algorithm which has figured out that orange juice is a thing will also quickly figure out that apple juice is a thing. The representation lets it generalize across different words.</p>
<p>Once each word has a 300-dimensional vector, one popular thing to do is to embed that 300-dimensional data into a two-dimensional space so that it can be visualized. A common algorithm for this is t-SNE, due to <a href="https://www.jmlr.org/papers/v9/vandermaaten08a.html">van der Maaten and Hinton (2008)</a>.</p>
<div id="ae4fe9cd" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="introduction-to-word-embeddings_files/figure-html/cell-2-output-1.svg" class="img-fluid figure-img" alt="A schematic two-dimensional scatter of fourteen labeled words. People words man, woman, king, and queen cluster together, animals dog, cat, and fish cluster together, numbers one, two, three, and four cluster together, and fruits grape, apple, and orange cluster together."></p>
<figcaption>Schematic of what a t-SNE plot of word embeddings looks like. The positions are illustrative rather than a real projection, and the point is that related concepts land near each other.</figcaption>
</figure>
</div>
</div>
</div>
<p>Words like <code>man</code> and <code>woman</code> get grouped together, <code>king</code> and <code>queen</code> get grouped together, animals get grouped together, fruits end up close to each other, and numbers like one, two, three, and four sit near each other as well. A word embedding algorithm learns similar features for concepts that feel like they ought to be related, and those concepts end up mapped to similar feature vectors.</p>
<p>The term <strong>embedding</strong> comes from the geometry. Think of a 300-dimensional space. Every word, such as <code>orange</code>, has a 300-dimensional feature vector, so the word <code>orange</code> gets embedded at a point in that space, and the word <code>apple</code> gets embedded at a different point. To visualize the result, an algorithm like t-SNE maps those points down to a much lower-dimensional space where the data can actually be plotted.</p>
<p>One honest caveat. The features that a learning algorithm ends up with will not have an easy interpretation like component one is gender, component two is royal, and component three is age. Exactly what each coordinate represents is harder to figure out. What matters is that the featurized representation still lets an algorithm work out that <code>apple</code> and <code>orange</code> are more similar than <code>king</code> and <code>orange</code>.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<div id="word-rep-review-q1">
<p><strong>1. Why can a model trained on one-hot vectors not transfer what it knows about orange juice to apple juice?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="word-rep-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>Because a one-hot vector encodes only the position of a word in the dictionary, and nothing about its meaning. The inner product of any two different one-hot vectors is zero, and the Euclidean distance between any pair is identical. So <code>apple</code> and <code>orange</code> look exactly as unrelated to each other as <code>apple</code> and <code>queen</code> do, and there is no signal for the model to generalize along.</p>
</div>
</details>
<hr>
<div id="word-rep-review-q2">
<p><strong>1. What is the difference between <span class="math inline">\(o_{6257}\)</span> and <span class="math inline">\(e_{6257}\)</span>?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="word-rep-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Both refer to the word <code>orange</code>, which sits at position 6257 in a 10,000-word vocabulary. <span class="math inline">\(o_{6257}\)</span> is the one-hot vector, 10,000-dimensional, with a single 1 at position 6257 and zeros everywhere else. <span class="math inline">\(e_{6257}\)</span> is the embedding, a much shorter dense vector (300-dimensional in the running example) whose entries are learned feature values.</p>
</div>
</details>
<hr>
<div id="word-rep-review-q3">
<p><strong>1. In the featurized table, why do the columns for <code>apple</code> and <code>orange</code> look so much alike?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="word-rep-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>Because most of the features that describe them agree. Both are genderless, neither is royal, both are age-neutral, and both are strongly food. A few features would differ, such as color and taste, but the bulk of the 300 coordinates take on very similar values. That similarity is exactly what lets a model generalize from orange juice to apple juice.</p>
</div>
</details>
<hr>
<div id="word-rep-review-q4">
<p><strong>1. What is t-SNE?</strong></p>
<ol type="a">
<li><p>A linear transformation that allows us to solve analogies on word vectors</p></li>
<li><p>A non-linear dimensionality reduction technique</p></li>
<li><p>An open-source sequence modeling library</p></li>
<li><p>A supervised learning algorithm for learning word embeddings</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="word-rep-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p><strong>b.</strong> t-SNE is purely a visualization step. It takes the 300-dimensional embeddings that some other algorithm has already learned and maps them down to two dimensions so that a human can look at them. It is non-linear, and it plays no part in learning the embeddings, which rules out options a and d.</p>
</div>
</details>
<hr>
<div id="word-rep-review-q5">
<p><strong>1. True or false. Suppose you learn a word embedding for a vocabulary of 60,000 words. Then the embedding vectors could be 60,000 dimensional, so as to capture the full range of variation and meaning in those words.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="word-rep-review-q5">
Answer
</summary>
<div class="review-answer-body">
<p><strong>False</strong> is the keyed answer, though the wording repays a careful reading. Taken permissively, “could” is defensible, since nothing stops you from training a 60,000-dimensional dense embedding, and it would still carry the meaningful geometry a one-hot vector lacks. What the question is really testing is the reason attached to the claim, the idea that you need one dimension per vocabulary word in order to capture the full range of meaning. That part is false. Word vector dimensions are usually far smaller than the vocabulary, which is why the running example pairs a 10,000-word vocabulary with a 300-dimensional embedding. A 60,000-dimensional vector for a 60,000-word vocabulary would be exactly as long as the one-hot vector it was meant to replace, throwing away the compactness that made the featurized representation attractive.</p>
</div>
</details>
</section>
</section>
<section id="using-word-embeddings" class="level2">
<h2 class="anchored" data-anchor-id="using-word-embeddings">Using Word Embeddings</h2>
<p>The next question is how to take these representations and plug them into an NLP application. Continue with the named entity recognition example, where the task is to detect people’s names. Given the sentence <code>Sally Johnson is an orange farmer</code>, the model should work out that <code>Sally Johnson</code> is a person’s name and output a 1 for those two words.</p>
<div class="wide-network-hint">
<p>On a small screen, scroll horizontally to inspect all six time steps.</p>
</div>
<div class="wide-network-figure" role="region" aria-label="Scrollable named entity recognition RNN diagram" tabindex="0">
<div id="c63749d9" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="introduction-to-word-embeddings_files/figure-html/cell-3-output-1.svg" class="img-fluid figure-img" alt="Six words, Sally, Johnson, is, an, orange, and farmer, each feed a recurrent cell. The cells pass activations left to right. The outputs above the cells read 1, 1, 0, 0, 0, 0."></p>
<figcaption>Named entity recognition over a six-word sentence. The first two words are labeled 1 because they form a person’s name.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p>One clue that <code>Sally Johnson</code> has to be a person rather than, say, the name of a corporation is that an orange farmer is a person. Previously the inputs <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, and so on were one-hot vectors. Now use the embedding vectors instead. After training a model that takes word embeddings as its inputs, a new sentence such as <code>Robert Lin is an apple farmer</code> becomes easy, because knowing that <code>apple</code> and <code>orange</code> are very similar makes it straightforward for the algorithm to generalize and figure out that <code>Robert Lin</code> is also a person’s name.</p>
<p>The more interesting case is a test sentence with much less common words. Suppose the test set contains <code>Robert Lin is a durian cultivator</code>. A durian is a rare type of fruit, popular in Singapore and a few other countries. With a small labeled training set for the named entity recognition task, you might never have seen the word <code>durian</code> or the word <code>cultivator</code> at all during training. But if the word embedding tells you that a durian is a fruit, so it is like an orange, and that a cultivator is someone who cultivates, so it is like a farmer, then the model can still generalize from having seen an orange farmer to knowing that a durian cultivator is probably a person too.</p>
<p>The reason word embeddings can do this is the data they are learned from. Algorithms for learning word embeddings can examine very large text corpora found off the internet, perhaps a billion words, and up to 100 billion words would be quite reasonable. Those are very large training sets of unlabeled text. By examining enormous amounts of unlabeled text, which can be downloaded more or less for free, an algorithm can work out that <code>orange</code> and <code>durian</code> are similar, and that <code>farmer</code> and <code>cultivator</code> are similar, and learn embeddings that group them together.</p>
<section id="transfer-learning-with-embeddings" class="level3">
<h3 class="anchored" data-anchor-id="transfer-learning-with-embeddings">Transfer Learning with Embeddings</h3>
<p>Having discovered that <code>orange</code> and <code>durian</code> are both fruits by reading massive amounts of internet text, you can take that word embedding and apply it to a named entity recognition task with a much smaller training set, maybe 100,000 words or even fewer. This is <a href="../../../ai/deep-learning/structuring-machine-learning-projects/learning-from-multiple-tasks#transfer-learning">transfer learning</a>, where knowledge learned from huge amounts of free unlabeled text is carried over to a task with a relatively small labeled training set. Transfer learning with word embeddings takes three steps.</p>
<ol type="1">
<li>Learn word embeddings from a very large text corpus, roughly 1 to 100 billion words. Alternatively, download pre-trained word embeddings online, several of which are published under permissive licenses.</li>
<li>Transfer the embedding to the new task, where the labeled training set is much smaller, say 100,000 words. Rather than a 10,000-dimensional one-hot vector per word, the model now sees a 300-dimensional dense vector. The one-hot vector is sparse and the embedding is dense, and the embedding is far shorter.</li>
<li>Optionally, as you train on the new task, continue to fine tune the word embeddings with the new data. In practice this is worth doing only when the new task has a fairly large data set. If the labeled data set for step 2 is small, fine tuning the embeddings is usually not worth the bother.</li>
</ol>
<p>Word embeddings make the biggest difference when the task being carried out has a relatively small training set. They have proven useful for many standard NLP tasks, including named entity recognition, text summarization, co-reference resolution, and parsing. They have been less useful for language modeling and machine translation, especially when there is a lot of data dedicated to that specific task. This matches what transfer learning does in general. Transferring from task A to task B is most useful when there is a ton of data for A and a relatively small data set for B, which is true for a lot of NLP tasks and less true for some language modeling and machine translation settings.</p>
<p>One note on the figure above. It was drawn as a unidirectional RNN for simplicity. A real named entity recognition system should use a <a href="../../../ai/deep-learning/sequence-models/bidirectional-and-deep-rnns#bidirectional-rnns">bidirectional RNN</a> instead.</p>
</section>
<section id="relation-to-face-encoding" class="level3">
<h3 class="anchored" data-anchor-id="relation-to-face-encoding">Relation to Face Encoding</h3>
<p>Word embeddings have an interesting relationship to the face encoding ideas from the convolutional networks course. In <a href="../../../ai/deep-learning/convolutional-neural-networks/siamese-networks-and-the-triplet-loss">face recognition</a>, a Siamese network architecture learns a 128-dimensional representation for different faces, and those encodings are then compared to figure out whether two pictures show the same person.</p>
<p>The words <em>encoding</em> and <em>embedding</em> mean fairly similar things, and the face recognition literature uses <em>encoding</em> to refer to those vectors <span class="math inline">\(f(x^{(i)})\)</span> and <span class="math inline">\(f(x^{(j)})\)</span>. The terms are used somewhat interchangeably.</p>
<p>There is one real difference, and it is about how the algorithms are used rather than about the terminology. For face recognition, the goal is a neural network that can take any face picture as input, even a picture it has never seen before, and compute an encoding for that new picture. For word embeddings, the vocabulary is fixed at, say, 10,000 words, and what gets learned is a fixed vector <span class="math inline">\(e_1\)</span> through <span class="math inline">\(e_{10000}\)</span>, one embedding per word in the vocabulary. Face recognition faces an unlimited sea of pictures it could encounter in the future, while natural language processing has a fixed vocabulary and declares everything outside it an unknown word.</p>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<div id="using-embeddings-review-q1">
<p><strong>1. The training set never contained the words <code>durian</code> or <code>cultivator</code>. How can the model still label <code>Robert Lin</code> as a person in <code>Robert Lin is a durian cultivator</code>?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="using-embeddings-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>The word embedding was not learned from the labeled training set. It was learned from a very large unlabeled corpus, perhaps 1 to 100 billion words of internet text, where <code>durian</code> and <code>cultivator</code> do appear. That corpus places <span class="math inline">\(e_{\text{durian}}\)</span> near <span class="math inline">\(e_{\text{orange}}\)</span> and <span class="math inline">\(e_{\text{cultivator}}\)</span> near <span class="math inline">\(e_{\text{farmer}}\)</span>. The named entity model saw an orange farmer during training, and the similar embeddings carry that pattern over.</p>
</div>
</details>
<hr>
<div id="using-embeddings-review-q2">
<p><strong>1. When is step 3, fine tuning the embeddings on the new task, worth doing?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="using-embeddings-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Only when the new task has a fairly large labeled data set. With a small data set there is not enough signal to improve embeddings that were learned from billions of words, so the usual choice is to leave them fixed.</p>
</div>
</details>
<hr>
<div id="using-embeddings-review-q3">
<p><strong>1. Why do word embeddings help less with machine translation than with named entity recognition?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="using-embeddings-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>Because transfer learning pays off when task A has far more data than task B. Named entity recognition typically has a small labeled set, so a billion-word corpus adds a great deal. Machine translation and language modeling projects often have very large dedicated data sets of their own, so there is less for a transferred embedding to add.</p>
</div>
</details>
<hr>
<div id="using-embeddings-review-q4">
<p><strong>1. What is the real difference between a face encoding and a word embedding?</strong></p>
<ol type="a">
<li><p>Face encodings are learned and word embeddings are hand-designed</p></li>
<li><p>A face network encodes any input image, including one never seen before, while a word embedding is a fixed table covering only the vocabulary</p></li>
<li><p>Face encodings are dense and word embeddings are sparse</p></li>
<li><p>There is no difference beyond the choice of word</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="using-embeddings-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p><strong>b.</strong> The terms <em>encoding</em> and <em>embedding</em> are used interchangeably, so the difference is not in the vocabulary. A Siamese face network is a function that computes an encoding for an arbitrary new picture, which it must be, because there is an unlimited sea of faces it could meet. A word embedding is a fixed set of vectors <span class="math inline">\(e_1\)</span> through <span class="math inline">\(e_{10000}\)</span>, one per vocabulary entry, and anything outside that list becomes the unknown word token.</p>
</div>
</details>
<hr>
<div id="using-embeddings-review-q5">
<p><strong>1. You have trained word embeddings on a text dataset of <span class="math inline">\(t_1\)</span> words, and you have a separate labeled dataset of <span class="math inline">\(t_2\)</span> words for some language task. Under which circumstance would you expect the word embeddings to help?</strong></p>
<ol type="a">
<li><p>When <span class="math inline">\(t_1\)</span> is smaller than <span class="math inline">\(t_2\)</span></p></li>
<li><p>When <span class="math inline">\(t_1\)</span> is equal to <span class="math inline">\(t_2\)</span></p></li>
<li><p>When <span class="math inline">\(t_1\)</span> is larger than <span class="math inline">\(t_2\)</span></p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="using-embeddings-review-q5">
Answer
</summary>
<div class="review-answer-body">
<p><strong>c.</strong> Transfer learning is most useful when the source task has far more data than the target task, so the embedding has the most to add when the unlabeled corpus <span class="math inline">\(t_1\)</span> is much larger than the labeled set <span class="math inline">\(t_2\)</span>. As <span class="math inline">\(t_2\)</span> grows toward <span class="math inline">\(t_1\)</span>, the labeled data increasingly covers the same ground on its own and there is less left for the embedding to contribute.</p>
</div>
</details>
</section>
</section>
<section id="properties-of-word-embeddings" class="level2">
<h2 class="anchored" data-anchor-id="properties-of-word-embeddings">Properties of Word Embeddings</h2>
<p>One of the most fascinating properties of word embeddings is that they can help with analogy reasoning. Building an analogy reasoning system is probably not the most important NLP application on its own, but it conveys a strong sense of what word embeddings are actually doing.</p>
<p>Pose the question, man is to woman as king is to what? Most people say queen. The question is whether an algorithm can work that out automatically.</p>
<p>Here is how. Return to the featurized table from earlier, and for this example pretend the embeddings are only four-dimensional rather than the 50 to 1,000 dimensions that would be more typical. Write <span class="math inline">\(e_{\text{man}}\)</span> for the embedding of <code>man</code>, which is the same vector as <span class="math inline">\(e_{5391}\)</span>, and similarly for the other three words. Now subtract.</p>
<p><span class="math display">\[
e_{\text{man}} - e_{\text{woman}} =
\begin{bmatrix} -1 \\ 0.01 \\ 0.03 \\ 0.09 \end{bmatrix} -
\begin{bmatrix} 1 \\ 0.02 \\ 0.02 \\ 0.01 \end{bmatrix} =
\begin{bmatrix} -2 \\ -0.01 \\ 0.01 \\ 0.08 \end{bmatrix} \approx
\begin{bmatrix} -2 \\ 0 \\ 0 \\ 0 \end{bmatrix}
\]</span></p>
<p><span class="math display">\[
e_{\text{king}} - e_{\text{queen}} =
\begin{bmatrix} -0.95 \\ 0.93 \\ 0.70 \\ 0.02 \end{bmatrix} -
\begin{bmatrix} 0.97 \\ 0.95 \\ 0.69 \\ 0.01 \end{bmatrix} =
\begin{bmatrix} -1.92 \\ -0.02 \\ 0.01 \\ 0.01 \end{bmatrix} \approx
\begin{bmatrix} -2 \\ 0 \\ 0 \\ 0 \end{bmatrix}
\]</span></p>
<p>Both differences come out to roughly the same vector. Gender contributes about <span class="math inline">\(-2\)</span> in each case, royalty cancels because kings and queens are about equally royal, and the age and food differences are close to zero. What this captures is that the main difference between <code>man</code> and <code>woman</code> is gender, and the main difference between <code>king</code> and <code>queen</code>, as represented by these vectors, is also gender.</p>
<p>So one way to carry out analogy reasoning is to compute <span class="math inline">\(e_{\text{man}} - e_{\text{woman}}\)</span>, then look for a word <span class="math inline">\(w\)</span> whose embedding makes</p>
<p><span class="math display">\[e_{\text{man}} - e_{\text{woman}} \approx e_{\text{king}} - e_{w}\]</span></p>
<p>hold as closely as possible. It turns out that when <code>queen</code> is the word plugged in, the left side really is close to the right side. This result was first pointed out by <a href="https://aclanthology.org/N13-1090/">Mikolov et al.&nbsp;(2013)</a>, and it has been one of the most remarkable and influential findings about word embeddings.</p>
<p>Geometrically, the word embeddings live in a 300-dimensional space. The word <code>man</code> is a point in that space, <code>woman</code> is another point, <code>king</code> is a third, and <code>queen</code> is a fourth. The vector difference between <code>man</code> and <code>woman</code> is very similar to the vector difference between <code>king</code> and <code>queen</code>, and that arrow is essentially the direction that represents a difference in gender. The four points therefore form a parallelogram.</p>
<div id="6f107754" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="introduction-to-word-embeddings_files/figure-html/cell-4-output-1.svg" class="img-fluid figure-img" alt="Two schematic panels. The left panel plots man, woman, king, and queen as the corners of a parallelogram, with the arrow from man to woman parallel to the arrow from king to queen. The right panel plots the same four words on a t-SNE style map, where the two arrows point in visibly different directions."></p>
<figcaption>Schematic comparison. Left, the parallelogram relationship as it holds in the original embedding space. Right, the same words after t-SNE, where the non-linear mapping has broken it. Both layouts are illustrative rather than a real projection.</figcaption>
</figure>
</div>
</div>
</div>
<p>To turn this into an algorithm, find the word <span class="math inline">\(w\)</span> that makes <span class="math inline">\(e_{\text{man}} - e_{\text{woman}} \approx e_{\text{king}} - e_{w}\)</span> hold. Move <span class="math inline">\(e_w\)</span> to one side and the other three terms to the other, and the problem becomes finding the word whose embedding is most similar to a particular target vector.</p>
<p><span class="math display">\[w = \arg\max_{w}\ \text{sim}\!\left(e_{w},\ e_{\text{king}} - e_{\text{man}} + e_{\text{woman}}\right)\]</span></p>
<p>Given some appropriate similarity function, maximizing it over the whole vocabulary should pick out <code>queen</code>, and the remarkable thing is that this actually works. Depending on the details of the task, research papers report anywhere from about 30% to 75% accuracy on analogy tasks like these, where an attempt counts as correct only if the algorithm guesses the exact right word.</p>
<p>One clarification about the plots above. As noted earlier, t-SNE takes 300-dimensional data and maps it into two dimensions in a very non-linear way. After that mapping, you should not expect the parallelogram relationships to survive. It is in the original 300-dimensional space that these relationships can be relied on. A parallelogram may happen to hold after t-SNE, but because the mapping is non-linear, most of them will be broken, and it is not something to count on.</p>
<section id="cosine-similarity" class="level3">
<h3 class="anchored" data-anchor-id="cosine-similarity">Cosine Similarity</h3>
<p>The similarity function most commonly used here is <span class="term" tabindex="0" data-def="A similarity measure between two vectors, equal to their inner product divided by the product of their lengths, which is the cosine of the angle between them."><strong>cosine similarity</strong></span>. For two vectors <span class="math inline">\(u\)</span> and <span class="math inline">\(v\)</span> it is defined as</p>
<p><span class="math display">\[\text{sim}(u, v) = \frac{u^{T} v}{\lVert u \rVert_2 \, \lVert v \rVert_2}\]</span></p>
<p>Ignoring the denominator for a moment, the numerator is just the <a href="../../../math/linear-algebra/vector-algebra#dot-product">inner product</a> between <span class="math inline">\(u\)</span> and <span class="math inline">\(v\)</span>, so if <span class="math inline">\(u\)</span> and <span class="math inline">\(v\)</span> are very similar, their inner product tends to be large. The reason for the name is that the whole expression is the cosine of the angle <span class="math inline">\(\phi\)</span> between the two vectors.</p>
<div id="63cae674" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="introduction-to-word-embeddings_files/figure-html/cell-5-output-1.svg" class="img-fluid figure-img" alt="Two panels. The left panel shows vectors u and v drawn from a common origin with the angle phi marked between them. The right panel plots the cosine of phi against phi from 0 to 180 degrees, passing through 1 at 0 degrees, 0 at 90 degrees, and negative 1 at 180 degrees."></p>
<figcaption>Cosine similarity is the cosine of the angle between two vectors, so it runs from 1 for identical directions down to -1 for opposite ones.</figcaption>
</figure>
</div>
</div>
</div>
<p>If the angle between the two vectors is 0, the cosine similarity is 1. If the angle is 90 degrees, the cosine similarity is 0. If they point in completely opposite directions, at 180 degrees, it comes out to <span class="math inline">\(-1\)</span>. That is where the name comes from, and it works quite well for analogy reasoning tasks.</p>
<p>You could also use squared Euclidean distance, <span class="math inline">\(\lVert u - v \rVert^{2}\)</span>, instead. Technically that is a measure of dissimilarity rather than similarity, so you would take its negative, and it works reasonably well too, although cosine similarity is used a bit more often. The main difference between the two is how they normalize the lengths of <span class="math inline">\(u\)</span> and <span class="math inline">\(v\)</span>.</p>
</section>
<section id="generality-of-analogies" class="level3">
<h3 class="anchored" data-anchor-id="generality-of-analogies">Generality of Analogies</h3>
<p>One of the remarkable results about word embeddings is how general the analogy relationships they learn turn out to be.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Analogy</th>
<th>Relationship captured</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Man is to Woman as Boy is to Girl</td>
<td>Gender</td>
</tr>
<tr class="even">
<td>Ottawa is to Canada as Nairobi is to Kenya</td>
<td>Capital city to country</td>
</tr>
<tr class="odd">
<td>Big is to Bigger as Tall is to Taller</td>
<td>Comparative form</td>
</tr>
<tr class="even">
<td>Yen is to Japan as Ruble is to Russia</td>
<td>Currency to country</td>
</tr>
</tbody>
</table>
<p>All of these can be learned just by running a word embedding algorithm over a large text corpus. Nobody supplies the categories, and the algorithm spots the patterns by itself.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<div id="properties-review-q1">
<p><strong>1. Why is <span class="math inline">\(e_{\text{man}} - e_{\text{woman}}\)</span> approximately equal to <span class="math inline">\(e_{\text{king}} - e_{\text{queen}}\)</span>?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="properties-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>Because the only feature that differs substantially within each pair is gender. Royalty is about equal within each pair, so it cancels, and so do age and food. Subtracting leaves roughly <span class="math inline">\([-2, 0, 0, 0]^{T}\)</span> in both cases, which is the direction that encodes a change in gender.</p>
</div>
</details>
<hr>
<div id="properties-review-q2">
<p><strong>1. Starting from <span class="math inline">\(e_{\text{man}} - e_{\text{woman}} \approx e_{\text{king}} - e_{w}\)</span>, derive the expression that is maximized to find <span class="math inline">\(w\)</span>.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="properties-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Move <span class="math inline">\(e_w\)</span> to the left side and the other three terms to the right, which gives <span class="math inline">\(e_{w} \approx e_{\text{king}} - e_{\text{man}} + e_{\text{woman}}\)</span>. The word is then whichever vocabulary entry has the embedding closest to that target vector. <span class="math display">\[w = \arg\max_{w}\ \text{sim}\!\left(e_{w},\ e_{\text{king}} - e_{\text{man}} + e_{\text{woman}}\right)\]</span></p>
</div>
</details>
<hr>
<div id="properties-review-q3">
<p><strong>1. A t-SNE plot of your embeddings shows man, woman, king, and queen but the four do not form a parallelogram. Is something wrong with the embeddings?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="properties-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>No.&nbsp;t-SNE maps 300 dimensions down to 2 in a highly non-linear way, and that mapping does not preserve parallelogram relationships. Most of them will be broken by the projection. The relationship should be checked in the original 300-dimensional space, not on the picture.</p>
</div>
</details>
<hr>
<div id="properties-review-q4">
<p><strong>1. Two embeddings sit at 90 degrees to each other. What is their cosine similarity, and what does that say about them?</strong></p>
<ol type="a">
<li><p>1, they are the same word</p></li>
<li><p>0, they are unrelated as far as the embedding is concerned</p></li>
<li><p>-1, they are opposites</p></li>
<li><p>It cannot be determined without the vector lengths</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="properties-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p><strong>b.</strong> The cosine of 90 degrees is 0, so the similarity is 0 and the two words carry no shared direction in the embedding space. Option d is wrong because the denominator <span class="math inline">\(\lVert u \rVert_2 \lVert v \rVert_2\)</span> divides the lengths out, which is exactly the point of normalizing.</p>
</div>
</details>
<hr>
<div id="properties-review-q5">
<p><strong>1. Which of these equations should hold for a good word embedding? Select all that apply.</strong></p>
<ol type="a">
<li><p><span class="math inline">\(e_{\text{man}} - e_{\text{aunt}} \approx e_{\text{woman}} - e_{\text{uncle}}\)</span></p></li>
<li><p><span class="math inline">\(e_{\text{man}} - e_{\text{woman}} \approx e_{\text{aunt}} - e_{\text{uncle}}\)</span></p></li>
<li><p><span class="math inline">\(e_{\text{man}} - e_{\text{uncle}} \approx e_{\text{woman}} - e_{\text{aunt}}\)</span></p></li>
<li><p><span class="math inline">\(e_{\text{man}} - e_{\text{woman}} \approx e_{\text{uncle}} - e_{\text{aunt}}\)</span></p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="properties-review-q5">
Answer
</summary>
<div class="review-answer-body">
<p><strong>c and d.</strong> The analogy is man is to woman as uncle is to aunt, so both sides of a correct equation must run in the same direction. Option d states it directly, male minus female on each side. Option c is the same equation rearranged, moving <span class="math inline">\(e_{\text{uncle}}\)</span> to the left and <span class="math inline">\(e_{\text{woman}}\)</span> to the right, which is the other pair of opposite sides of the same parallelogram.</p>
<p>Options a and b both cross the genders. Option b keeps male minus female on the left but flips to female minus male on the right, so the two differences point in opposite directions. Option a pairs <code>man</code> with <code>aunt</code> and <code>woman</code> with <code>uncle</code>, which mixes a gender difference with a family-relation difference on both sides.</p>
</div>
</details>
</section>
</section>
<section id="embedding-matrix" class="level2">
<h2 class="anchored" data-anchor-id="embedding-matrix">Embedding Matrix</h2>
<p>Now formalize the problem of learning a good word embedding. When you implement an algorithm to learn a word embedding, what you end up learning is an <span class="term" tabindex="0" data-def="A matrix whose columns are the learned embedding vectors, one column per word in the vocabulary."><strong>embedding matrix</strong></span>.</p>
<p>Take the usual 10,000-word vocabulary, holding <code>a</code>, <code>aaron</code>, on through <code>orange</code>, on to <code>zulu</code>, plus an unknown word token. What gets learned is an embedding matrix <span class="math inline">\(E\)</span>, which is 300 by 10,000 for a 10,000-word vocabulary, or 300 by 10,001 if the unknown word token counts as one extra entry. The columns of this matrix are the embeddings for the different words in the vocabulary.</p>
<p>The word <code>orange</code> is number 6257 in the vocabulary, so <span class="math inline">\(o_{6257}\)</span> is the one-hot vector with zeros everywhere and a 1 in position 6257. That is a 10,000-dimensional vector with a 1 in just one place.</p>
<div id="f1ee2140" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="introduction-to-word-embeddings_files/figure-html/cell-6-output-1.svg" class="img-fluid figure-img" alt="A wide rectangle labeled E, 300 rows by 10,000 columns, with one column highlighted and labeled orange. It is multiplied by a tall narrow one-hot vector that holds a single 1 at position 6257. The result is a short narrow 300 by 1 vector matching the highlighted column."></p>
<figcaption>Multiplying the embedding matrix by a one-hot vector selects a single column, which is the embedding of that word.</figcaption>
</figure>
</div>
</div>
</div>
<p>Multiply <span class="math inline">\(E\)</span> by <span class="math inline">\(o_{6257}\)</span> and the result is a 300-dimensional vector, because <span class="math inline">\(E\)</span> is <span class="math inline">\(300 \times 10{,}000\)</span> and <span class="math inline">\(o_{6257}\)</span> is <span class="math inline">\(10{,}000 \times 1\)</span>, so the product has shape <span class="math inline">\(300 \times 1\)</span>.</p>
<p>Work out the first element of that vector. It is the first row of <span class="math inline">\(E\)</span> multiplied by <span class="math inline">\(o_{6257}\)</span>. Every element of <span class="math inline">\(o_{6257}\)</span> is zero except element 6257, so the sum is zero times the first entry of the row, plus zero times the second, and so on, plus 1 times the entry in column 6257, plus zero times everything after it. The result is whatever sits in row 1 under the <code>orange</code> column. For the second element, take the second row of <span class="math inline">\(E\)</span> and repeat, and again every term drops out except the entry in column 6257. Continue down all 300 rows and the whole <code>orange</code> column has been selected.</p>
<p><span class="math display">\[E \cdot o_{6257} = e_{6257}\]</span></p>
<p>More generally, for any word <span class="math inline">\(j\)</span> in the vocabulary, <span class="math inline">\(E \cdot o_j = e_j\)</span>, the 300-dimensional embedding vector for word <span class="math inline">\(j\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Do not actually implement it as a matrix multiply
</div>
</div>
<div class="callout-body-container callout-body">
<p>Writing the relationship as <span class="math inline">\(E \cdot o_j\)</span> is the clearest way to see why the column comes out, but it is a wasteful way to compute it. Multiplying a <span class="math inline">\(300 \times 10{,}000\)</span> matrix by a vector that is zero in 9,999 of its 10,000 positions throws away almost all of the arithmetic it performs. In practice, use a specialized function that looks column <span class="math inline">\(j\)</span> up directly, which is what a deep learning framework’s embedding layer does.</p>
</div>
</div>
<p>The remaining question is where <span class="math inline">\(E\)</span> comes from, which is a matter of choosing an algorithm to learn it.</p>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<div id="embedding-matrix-review-q1">
<p><strong>1. What are the shapes of <span class="math inline">\(E\)</span>, <span class="math inline">\(o_j\)</span>, and <span class="math inline">\(e_j\)</span> for a 10,000-word vocabulary with 300-dimensional embeddings?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="embedding-matrix-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p><span class="math inline">\(E\)</span> is <span class="math inline">\(300 \times 10{,}000\)</span>, one column per word. <span class="math inline">\(o_j\)</span> is <span class="math inline">\(10{,}000 \times 1\)</span>, a one-hot column vector. Their product <span class="math inline">\(e_j\)</span> is <span class="math inline">\(300 \times 1\)</span>, which is the embedding of word <span class="math inline">\(j\)</span>. Adding an unknown word token makes <span class="math inline">\(E\)</span> <span class="math inline">\(300 \times 10{,}001\)</span> and <span class="math inline">\(o_j\)</span> <span class="math inline">\(10{,}001 \times 1\)</span>, and <span class="math inline">\(e_j\)</span> keeps its shape.</p>
</div>
</details>
<hr>
<div id="embedding-matrix-review-q2">
<p><strong>1. Explain why <span class="math inline">\(E \cdot o_{6257}\)</span> picks out the <code>orange</code> column rather than mixing several columns together.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="embedding-matrix-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Each element of the product is one row of <span class="math inline">\(E\)</span> dotted with <span class="math inline">\(o_{6257}\)</span>. That dot product multiplies every entry of the row by the matching entry of <span class="math inline">\(o_{6257}\)</span>, and all of those entries are zero except the one at position 6257, which is 1. So every term vanishes except the entry in column 6257. Repeating this for all 300 rows reads out column 6257 exactly, with no contribution from any other column.</p>
</div>
</details>
<hr>
<div id="embedding-matrix-review-q3">
<p><strong>1. Let <span class="math inline">\(A\)</span> be an embedding matrix, and let <span class="math inline">\(o_{4567}\)</span> be a one-hot vector corresponding to word 4567. To get the embedding of word 4567, why not just call <code>A * o_4567</code> in Python?</strong></p>
<ol type="a">
<li><p>This does not handle unknown words (<code>&lt;UNK&gt;</code>)</p></li>
<li><p>None of the answers are correct, calling the Python snippet as described above is fine</p></li>
<li><p>The correct formula is <span class="math inline">\(A^{T} o_{4567}\)</span></p></li>
<li><p>It is computationally wasteful</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="embedding-matrix-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p><strong>d.</strong> Out of 10,000 multiplications per row, 9,999 involve a zero and contribute nothing, so nearly all the arithmetic is thrown away. A dedicated lookup reads column 4567 straight out of the matrix instead.</p>
<p>The other options fail for separate reasons. Option a is wrong because the unknown word token has its own column in <span class="math inline">\(A\)</span> just like every other vocabulary entry, so the product handles it no differently. Option b is wrong because the call is not fine. Beyond the waste, <code>*</code> is elementwise multiplication in NumPy rather than a matrix product, so the snippet does not even return a 300-dimensional embedding. Option c is wrong on shapes. With <span class="math inline">\(A\)</span> of shape <span class="math inline">\(300 \times 10{,}000\)</span> and <span class="math inline">\(o_{4567}\)</span> of shape <span class="math inline">\(10{,}000 \times 1\)</span>, the product <span class="math inline">\(A \, o_{4567}\)</span> already conforms, while <span class="math inline">\(A^{T} o_{4567}\)</span> would try to multiply a <span class="math inline">\(10{,}000 \times 300\)</span> matrix by a <span class="math inline">\(10{,}000 \times 1\)</span> vector and is undefined.</p>
</div>
</details>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Mikolov, T., Yih, W., &amp; Zweig, G. (2013). Linguistic regularities in continuous space word representations. In <em>Proceedings of the 2013 Conference of the North American Chapter of the Association for Computational Linguistics: Human Language Technologies</em> (pp.&nbsp;746-751). Association for Computational Linguistics. <a href="https://aclanthology.org/N13-1090/" class="uri">https://aclanthology.org/N13-1090/</a></li>
<li>van der Maaten, L., &amp; Hinton, G. (2008). Visualizing data using t-SNE. <em>Journal of Machine Learning Research, 9</em>(86), 2579-2605. <a href="https://www.jmlr.org/papers/v9/vandermaaten08a.html" class="uri">https://www.jmlr.org/papers/v9/vandermaaten08a.html</a></li>
</ul>


<div id="section-progress-widget" class="section-progress-widget" hidden="">
  <p class="section-progress-label">Progress through this page</p>
  <progress class="section-progress" value="40" max="100" aria-label="40 percent through this page"></progress>
  <p class="section-progress-detail">40% (1067 of 2610 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.hidden = false; sb.appendChild(w); }
});
</script>

</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://oliabak.com/giscus-theme-dark.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../ai/deep-learning/sequence-models/lab-improvise-a-jazz-solo" class="pagination-link" aria-label="Improvise a Jazz Solo with an LSTM Network">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Improvise a Jazz Solo with an LSTM Network</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../ai/deep-learning/sequence-models/learning-word-embeddings-word2vec-and-glove" class="pagination-link" aria-label="Learning Word Embeddings with Word2vec and GloVe">
        <span class="nav-page-text">Learning Word Embeddings with Word2vec and GloVe</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>H’s Notes</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../about">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/dashboard">
<p>Dashboard</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/roadmap">
<p>Roadmap</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>