<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Sequence problems and their notation, why a standard network fails on them, and how a recurrent neural network runs forward and backward through time.">

<title>Recurrent Neural Networks – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../ai/deep-learning/sequence-models/rnn-architectures-and-language-models" rel="next">
<link href="../../../ai/deep-learning/sequence-models/" rel="prev">
<link href="../../../media/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-09af6f1c3ba400237d3ba77e487e1b25.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-43798084b7368a40096bd6648f6381c9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css?v=10149509">
<meta property="og:title" content="Recurrent Neural Networks – H’s Notes">
<meta property="og:description" content="Sequence problems and their notation, why a standard network fails on them, and how a recurrent neural network runs forward and backward through time.">
<meta property="og:image" content="https://oliabak.com/ai/deep-learning/sequence-models/recurrent-neural-networks_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Recurrent Neural Networks – H’s Notes">
<meta name="twitter:description" content="Sequence problems and their notation, why a standard network fails on them, and how a recurrent neural network runs forward and backward through time.">
<meta name="twitter:image" content="https://oliabak.com/ai/deep-learning/sequence-models/recurrent-neural-networks_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://oliabak.com/ai/deep-learning/sequence-models/recurrent-neural-networks">
<script type="application/ld+json" data-breadcrumbs="1">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Artificial Intelligence",
      "item": "https://oliabak.com/ai/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Deep Learning",
      "item": "https://oliabak.com/ai/deep-learning/"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Sequence Models",
      "item": "https://oliabak.com/ai/deep-learning/sequence-models/"
    },
    {
      "@type": "ListItem",
      "position": 4,
      "name": "Recurrent Neural Networks",
      "item": "https://oliabak.com/ai/deep-learning/sequence-models/recurrent-neural-networks"
    }
  ]
}
</script>
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../../networking/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccde-written/">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccie-data-center/">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../networking/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-routing/">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-switching/">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/kali-linux/">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../../ai/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/supervised-machine-learning/">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/advanced-learning-algorithms/">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/unsupervised-learning/">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/federated-learning/">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/neural-networks-and-deep-learning/">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/improving-deep-neural-networks/">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/structuring-machine-learning-projects/">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/convolutional-neural-networks/">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/sequence-models/">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../../math/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/linear-algebra/">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/calculus/">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/probability/">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/statistics/">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../../tools/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../../tools/client-info">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/asn-conversion">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/subnet-calculator">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/network-toolkit">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/pastebin">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/short-links">
 <span class="dropdown-text">Short Links</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/qr-code">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/fancy-text">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/copy-paste-values">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Classroom</li>
        <li>
    <a class="dropdown-item" href="../../../tools/randomizer">
 <span class="dropdown-text">Randomizer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../../tools/function-graphs">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/math-formula">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/latex-preview">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/markdown-preview">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/eclipse-atlas">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/planetarium">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../../tools/svg-preview">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/color-pallet">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/typography">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/tshirt-design">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../../tools/chess">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/reassess-your-chess">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/daily-chess">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../about">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/dashboard">
 <span class="dropdown-text">Dashboard</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../../about/roadmap">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/about-this-website">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/">Deep Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/">Sequence Models</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/recurrent-neural-networks">Recurrent Neural Networks</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/deep-learning/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/deep-learning/sequence-models/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sequence Models</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/recurrent-neural-networks" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Recurrent Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/rnn-architectures-and-language-models" class="sidebar-item-text sidebar-link">
 <span class="menu-text">RNN Architectures and Language Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/vanishing-gradients-gru-and-lstm" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Vanishing Gradients, GRUs, and LSTMs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/bidirectional-and-deep-rnns" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bidirectional and Deep RNNs</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-building-your-recurrent-neural-network" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Building Your Recurrent Neural Network Step by Step</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-character-level-language-model" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Character Level Language Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-improvise-a-jazz-solo" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Improvise a Jazz Solo with an LSTM Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/introduction-to-word-embeddings" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to Word Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/learning-word-embeddings-word2vec-and-glove" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Learning Word Embeddings with Word2vec and GloVe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/sentiment-classification-and-debiasing" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sentiment Classification and Debiasing Word Embeddings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-operations-on-word-vectors" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Operations on Word Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-emojify" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Emojify</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/sequence-to-sequence-models" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sequence to Sequence Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/beam-search" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Beam Search</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/bleu-score" class="sidebar-item-text sidebar-link">
 <span class="menu-text">BLEU Score</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/attention-model" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Attention Model</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/speech-recognition-and-trigger-word-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Speech Recognition and Trigger Word Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-neural-machine-translation" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Neural Machine Translation with Attention</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-trigger-word-detection" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Trigger Word Detection</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/transformer-network" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Transformer Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-transformer-network" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Building a Transformer Network</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/sequence-models/lab-fine-tuning-a-pretrained-transformer" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Fine-Tuning a Pretrained Transformer</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sequence-data-examples" id="toc-sequence-data-examples" class="nav-link active" data-scroll-target="#sequence-data-examples">Sequence Data Examples</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#notation" id="toc-notation" class="nav-link" data-scroll-target="#notation">Notation</a>
  <ul class="collapse">
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#representing-words" id="toc-representing-words" class="nav-link" data-scroll-target="#representing-words">Representing Words</a>
  <ul class="collapse">
  <li><a href="#unknown-words" id="toc-unknown-words" class="nav-link" data-scroll-target="#unknown-words">Unknown Words</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#why-not-a-standard-network" id="toc-why-not-a-standard-network" class="nav-link" data-scroll-target="#why-not-a-standard-network">Why Not a Standard Network?</a>
  <ul class="collapse">
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#recurrent-neural-network-structure" id="toc-recurrent-neural-network-structure" class="nav-link" data-scroll-target="#recurrent-neural-network-structure">Recurrent Neural Network Structure</a>
  <ul class="collapse">
  <li><a href="#two-ways-to-draw-the-same-network" id="toc-two-ways-to-draw-the-same-network" class="nav-link" data-scroll-target="#two-ways-to-draw-the-same-network">Two Ways to Draw the Same Network</a></li>
  <li><a href="#shared-parameters" id="toc-shared-parameters" class="nav-link" data-scroll-target="#shared-parameters">Shared Parameters</a></li>
  <li><a href="#one-weakness-of-this-architecture" id="toc-one-weakness-of-this-architecture" class="nav-link" data-scroll-target="#one-weakness-of-this-architecture">One Weakness of This Architecture</a></li>
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#forward-propagation" id="toc-forward-propagation" class="nav-link" data-scroll-target="#forward-propagation">Forward Propagation</a>
  <ul class="collapse">
  <li><a href="#review-questions-5" id="toc-review-questions-5" class="nav-link" data-scroll-target="#review-questions-5">Review Questions</a></li>
  </ul></li>
  <li><a href="#simplified-notation" id="toc-simplified-notation" class="nav-link" data-scroll-target="#simplified-notation">Simplified Notation</a>
  <ul class="collapse">
  <li><a href="#review-questions-6" id="toc-review-questions-6" class="nav-link" data-scroll-target="#review-questions-6">Review Questions</a></li>
  </ul></li>
  <li><a href="#computation-graph" id="toc-computation-graph" class="nav-link" data-scroll-target="#computation-graph">Computation Graph</a></li>
  <li><a href="#loss-function" id="toc-loss-function" class="nav-link" data-scroll-target="#loss-function">Loss Function</a>
  <ul class="collapse">
  <li><a href="#review-questions-7" id="toc-review-questions-7" class="nav-link" data-scroll-target="#review-questions-7">Review Questions</a></li>
  </ul></li>
  <li><a href="#backpropagation-through-time" id="toc-backpropagation-through-time" class="nav-link" data-scroll-target="#backpropagation-through-time">Backpropagation Through Time</a>
  <ul class="collapse">
  <li><a href="#review-questions-8" id="toc-review-questions-8" class="nav-link" data-scroll-target="#review-questions-8">Review Questions</a></li>
  </ul></li>
  <li><a href="#course-roadmap" id="toc-course-roadmap" class="nav-link" data-scroll-target="#course-roadmap">Course Roadmap</a>
  <ul class="collapse">
  <li><a href="#review-questions-9" id="toc-review-questions-9" class="nav-link" data-scroll-target="#review-questions-9">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<script src="../../../theme-toggle.js?v=3505170f"></script>
<script src="../../../auth.js?v=37e2729f"></script>
<script src="../../../site-metrics.js?v=9d1b4053"></script>
<script src="../../../giscus-note.js?v=e94ec728"></script>
<script src="../../../resume-reading.js?v=c40ebfea"></script>
<script src="../../../sidebar-active.js?v=62f05be2"></script>
<script src="../../../search-scope.js?v=13576411"></script>
<script src="../../../review-numbering.js?v=50100e67"></script>
<script src="../../../nav-columns.js?v=a9beef4d"></script>
<script src="../../../activation-colors.js?v=a9e5b12e"></script>
<script src="../../../visit-history.js?v=85edd45a"></script>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/">Deep Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/">Sequence Models</a></li><li class="breadcrumb-item"><a href="../../../ai/deep-learning/sequence-models/recurrent-neural-networks">Recurrent Neural Networks</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Recurrent Neural Networks</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">sequence-models</div>
    <div class="quarto-category">rnn</div>
    <div class="quarto-category">nlp</div>
    <div class="quarto-category">notation</div>
    <div class="quarto-category">forward-propagation</div>
    <div class="quarto-category">backpropagation</div>
  </div>
  </div>

<div>
  <div class="description">
    Sequence problems and their notation, why a standard network fails on them, and how a recurrent neural network runs forward and backward through time.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Aug 22, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (!meta) return;

  // Published, and Modified only where a page actually sets date-modified.
  // Two pages do, about-this-website and roadmap, and both carry it on
  // purpose because they describe a site that keeps changing.
  function readCell(sel) {
    var el = meta.querySelector(sel);
    if (!el) return "";
    var cell = el.closest("div");
    var body = cell && cell.querySelector(".quarto-title-meta-contents");
    return ((body || el).textContent || "").trim();
  }
  var published = readCell(".date");
  var modified = readCell(".date-modified");

  var html = '<span class="quarto-title-meta-item">116 min <span class="rt-info" tabindex="0" aria-describedby="reading-time-method"><span aria-hidden="true">&#9432;</span><span class="rt-tooltip" id="reading-time-method" role="tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></span><span class="quarto-title-meta-item">7,000 words</span><span class="quarto-title-meta-item">difficulty 3/5</span>';
  function esc(t) {
    return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  if (published) {
    html += '<span class="quarto-title-meta-item">published ' + esc(published) + '</span>';
  }
  if (modified && modified !== published) {
    html += '<span class="quarto-title-meta-item">updated ' + esc(modified) + '</span>';
  }

  var line = document.createElement("div");
  line.className = "quarto-title-meta-line site-meta";
  line.innerHTML = html;
  meta.insertBefore(line, meta.firstChild);
});
</script>

<p>This fifth and final course of the specialization covers sequence models, one of the most exciting areas in deep learning. Models such as recurrent neural networks, or RNNs, have transformed speech recognition, natural language processing, and other areas, and this course builds them up from scratch.</p>
<p>A good place to start is with a few examples of where sequence models are useful.</p>
<section id="sequence-data-examples" class="level2">
<h2 class="anchored" data-anchor-id="sequence-data-examples">Sequence Data Examples</h2>
<p>In <strong>speech recognition</strong> you are given an input audio clip <span class="math inline">\(X\)</span> and asked to map it to a text transcript <span class="math inline">\(Y\)</span>. Both the input and the output here are sequence data, because <span class="math inline">\(X\)</span> is an audio clip that plays out over time and <span class="math inline">\(Y\)</span> is a sequence of words. Sequence models such as recurrent neural networks, and the variations covered later, have been very useful for speech recognition.</p>
<p><strong>Music generation</strong> is another problem with sequence data. In this case only the output <span class="math inline">\(Y\)</span> is a sequence. The input can be the empty set, or it can be a single integer, maybe referring to the genre of music you want to generate, or maybe the first few notes of the piece you want. So <span class="math inline">\(X\)</span> can be nothing or just an integer, while the output <span class="math inline">\(Y\)</span> is a sequence.</p>
<p>In <strong>sentiment classification</strong> the input <span class="math inline">\(X\)</span> is a sequence. Given a phrase such as “There is nothing to like in this movie”, how many stars do you think the review will be?</p>
<p>Sequence models are also very useful for <strong>DNA sequence analysis</strong>. Your DNA is represented by the four letters A, C, G, and T, and given a DNA sequence you might ask which part of it corresponds to a protein.</p>
<p>In <strong>machine translation</strong> you are given an input sentence, “Voulez-vous chanter avec moi?”, and asked to output the translation in a different language.</p>
<p>In <strong>video activity recognition</strong> you might be given a sequence of video frames and asked to recognize the activity taking place.</p>
<p>And in <strong>named entity recognition</strong> you might be given a sentence and asked to identify the people mentioned in it.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Application</th>
<th>Input <span class="math inline">\(X\)</span></th>
<th>Output <span class="math inline">\(Y\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Speech recognition</td>
<td>Audio clip (sequence)</td>
<td>Text transcript (sequence)</td>
</tr>
<tr class="even">
<td>Music generation</td>
<td>Nothing, or a single integer</td>
<td>Sequence of notes (sequence)</td>
</tr>
<tr class="odd">
<td>Sentiment classification</td>
<td>Review text (sequence)</td>
<td>Star rating</td>
</tr>
<tr class="even">
<td>DNA sequence analysis</td>
<td>DNA sequence (sequence)</td>
<td>Labels marking protein regions (sequence)</td>
</tr>
<tr class="odd">
<td>Machine translation</td>
<td>Sentence in one language (sequence)</td>
<td>Sentence in another language (sequence)</td>
</tr>
<tr class="even">
<td>Video activity recognition</td>
<td>Video frames (sequence)</td>
<td>Activity label</td>
</tr>
<tr class="odd">
<td>Named entity recognition</td>
<td>Sentence (sequence)</td>
<td>Labels marking names (sequence)</td>
</tr>
</tbody>
</table>
<p>All of these problems can be addressed as supervised learning with labeled data <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> as the training set. But as the list shows, there are a lot of different types of sequence problems. In some of them both the input <span class="math inline">\(X\)</span> and the output <span class="math inline">\(Y\)</span> are sequences, and in that case <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> can have different lengths, as in machine translation, or the same length, as in named entity recognition. In others only <span class="math inline">\(X\)</span> or only <span class="math inline">\(Y\)</span> is a sequence. Sequence models apply to all of these settings.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<div id="sequence-data-review-q1">
<p><strong>1. In music generation, which side of the problem is sequence data, and what can the input be?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="sequence-data-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>Only the output <span class="math inline">\(Y\)</span> is a sequence, because the model produces a sequence of notes. The input <span class="math inline">\(X\)</span> can be the empty set, or a single integer standing for the genre of music you want, or the first few notes of the piece you want.</p>
</div>
</details>
<hr>
<div id="sequence-data-review-q2">
<p><strong>1. Give an example from the list where <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are both sequences but do not have to be the same length, and one where they do have the same length.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="sequence-data-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Machine translation has both sides as sequences with different lengths, because a sentence and its translation need not contain the same number of words. Named entity recognition has both sides as sequences of the same length, because the model produces one output per input word.</p>
</div>
</details>
<hr>
<div id="sequence-data-review-q3">
<p><strong>1. Sentiment classification reads “There is nothing to like in this movie” and predicts a star rating. Which of the following describes this problem?</strong></p>
<ol type="a">
<li><p>Only the input <span class="math inline">\(X\)</span> is a sequence</p></li>
<li><p>Only the output <span class="math inline">\(Y\)</span> is a sequence</p></li>
<li><p>Both <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> are sequences of the same length</p></li>
<li><p>Neither <span class="math inline">\(X\)</span> nor <span class="math inline">\(Y\)</span> is a sequence</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="sequence-data-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p><strong>a.</strong> The input is a phrase, which is sequence data, while the output is a single number of stars. Option b describes music generation, option c describes named entity recognition, and option d would not be a sequence problem at all.</p>
</div>
</details>
</section>
</section>
<section id="notation" class="level2">
<h2 class="anchored" data-anchor-id="notation">Notation</h2>
<p>A good motivating example is <span class="term" tabindex="0" data-def="A task that finds and labels the names of people, companies, locations, times, countries, and currencies inside a piece of text."><strong>named entity recognition</strong></span>. Suppose you want to build a sequence model that takes a sentence such as “Harry Potter and Hermione Granger invented a new spell” and automatically tells you where the people’s names are. Harry Potter and Hermione Granger are characters from the Harry Potter novels by J. K. Rowling.</p>
<p>Named entity recognition is used by search engines, for example, to index all of the people mentioned in the last 24 hours of news articles so that those articles can be looked up appropriately. The same systems are used to find company names, times, locations, country names, and currency names in many different types of text.</p>
<p>Given the input <span class="math inline">\(x\)</span>, you want the model to output a <span class="math inline">\(y\)</span> that has one output per input word. The target output tells you, for each of the input words, whether it is part of a person’s name.</p>
<div id="f12a5f3a" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-2-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>One output per input word, marking the words that are part of a person’s name.</figcaption>
</figure>
</div>
</div>
</div>
<p>Technically this may not be the best output representation. There are more sophisticated representations that tell you not just whether a word is part of a person’s name, but where the names start and end, so that you know Harry Potter starts here and ends here, and Hermione Granger starts here and ends here. For this motivating example the simpler output representation is enough.</p>
<p>The input is a sequence of nine words, so there will eventually be nine sets of features to represent those nine words. To index into the positions in the sequence, write <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, <span class="math inline">\(x^{\langle 3 \rangle}\)</span>, and so on up to <span class="math inline">\(x^{\langle 9 \rangle}\)</span>. A position somewhere in the middle of the sequence is written <span class="math inline">\(x^{\langle t \rangle}\)</span>. The letter <span class="math inline">\(t\)</span> hints that these are temporal sequences, and the same index <span class="math inline">\(t\)</span> is used whether the sequence is temporal or not. The outputs are indexed the same way, from <span class="math inline">\(y^{\langle 1 \rangle}\)</span> up to <span class="math inline">\(y^{\langle 9 \rangle}\)</span>.</p>
<p>Two more symbols record how long the sequences are. <span class="math inline">\(T_x\)</span> denotes the length of the input sequence, so in this case there are nine words and <span class="math inline">\(T_x = 9\)</span>, and <span class="math inline">\(T_y\)</span> denotes the length of the output sequence. In this example <span class="math inline">\(T_x = T_y\)</span>, but as the previous section showed, <span class="math inline">\(T_x\)</span> and <span class="math inline">\(T_y\)</span> can be different.</p>
<p>Earlier courses used <span class="math inline">\(x^{(i)}\)</span> to denote the <span class="math inline">\(i\)</span>-th training example. Putting the two pieces together, <span class="math inline">\(x^{(i)\langle t \rangle}\)</span> refers to element <span class="math inline">\(t\)</span> in the input sequence of training example <span class="math inline">\(i\)</span>. Different examples in your training set can have different lengths, so <span class="math inline">\(T_x^{(i)}\)</span> is the input sequence length for training example <span class="math inline">\(i\)</span>. In the same way, <span class="math inline">\(y^{(i)\langle t \rangle}\)</span> is element <span class="math inline">\(t\)</span> in the output sequence of example <span class="math inline">\(i\)</span>, and <span class="math inline">\(T_y^{(i)}\)</span> is the length of that output sequence. For the nine-word sentence above, <span class="math inline">\(T_x^{(i)} = 9\)</span>, while a different training example holding a sentence of fifteen words would have <span class="math inline">\(T_x^{(i)} = 15\)</span>.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(x^{\langle t \rangle}\)</span></td>
<td>Element <span class="math inline">\(t\)</span> of the input sequence</td>
</tr>
<tr class="even">
<td><span class="math inline">\(y^{\langle t \rangle}\)</span></td>
<td>Element <span class="math inline">\(t\)</span> of the output sequence</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(T_x\)</span></td>
<td>Length of the input sequence</td>
</tr>
<tr class="even">
<td><span class="math inline">\(T_y\)</span></td>
<td>Length of the output sequence</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(x^{(i)\langle t \rangle}\)</span></td>
<td>Element <span class="math inline">\(t\)</span> of the input sequence of training example <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(y^{(i)\langle t \rangle}\)</span></td>
<td>Element <span class="math inline">\(t\)</span> of the output sequence of training example <span class="math inline">\(i\)</span></td>
</tr>
<tr class="odd">
<td><span class="math inline">\(T_x^{(i)}\)</span></td>
<td>Input sequence length of training example <span class="math inline">\(i\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(T_y^{(i)}\)</span></td>
<td>Output sequence length of training example <span class="math inline">\(i\)</span></td>
</tr>
</tbody>
</table>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<div id="notation-review-q1">
<p><strong>1. For the sentence “Harry Potter and Hermione Granger invented a new spell”, what are <span class="math inline">\(T_x\)</span> and <span class="math inline">\(T_y\)</span>, and does that equality hold for every sequence problem?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="notation-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>The sentence has nine words and the model produces one label per word, so <span class="math inline">\(T_x = 9\)</span> and <span class="math inline">\(T_y = 9\)</span>. The equality does not hold in general. In machine translation the translated sentence can be longer or shorter than the original, and in sentiment classification the output is a single rating rather than a sequence.</p>
</div>
</details>
<hr>
<div id="notation-review-q2">
<p><strong>1. What does <span class="math inline">\(x^{(2)\langle 3 \rangle}\)</span> mean, and how is it different from <span class="math inline">\(x^{(3)\langle 2 \rangle}\)</span>?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="notation-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>The round-bracket superscript indexes the training example and the angle-bracket superscript indexes the position inside that example’s sequence. So <span class="math inline">\(x^{(2)\langle 3 \rangle}\)</span> is the third word of the second training example, while <span class="math inline">\(x^{(3)\langle 2 \rangle}\)</span> is the second word of the third training example. They point at different words in different sentences.</p>
</div>
</details>
<hr>
<div id="notation-review-q3">
<p><strong>1. Why does the notation need <span class="math inline">\(T_x^{(i)}\)</span> rather than a single <span class="math inline">\(T_x\)</span> for the whole training set?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="notation-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>Because different training examples can have different lengths. One sentence in the training set may hold nine words and another may hold fifteen, so the length has to be recorded per example.</p>
</div>
</details>
<hr>
<div id="notation-review-q4">
<p><strong>1. Your training examples are sentences. Which expression refers to the <span class="math inline">\(l\)</span>-th word of the <span class="math inline">\(k\)</span>-th training example?</strong></p>
<ol type="a">
<li><p><span class="math inline">\(x^{\langle k \rangle (l)}\)</span></p></li>
<li><p><span class="math inline">\(x^{(k)\langle l \rangle}\)</span></p></li>
<li><p><span class="math inline">\(x^{(l)\langle k \rangle}\)</span></p></li>
<li><p><span class="math inline">\(x^{\langle l \rangle (k)}\)</span></p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="notation-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p><strong>b.</strong> The round brackets index the training example and the angle brackets index the position inside that example’s sequence, and the example index is written first. So <span class="math inline">\(x^{(k)\langle l \rangle}\)</span> selects training example <span class="math inline">\(k\)</span>, then word <span class="math inline">\(l\)</span> within it. Options a and d put the two brackets in the wrong order, and option c swaps the roles of <span class="math inline">\(k\)</span> and <span class="math inline">\(l\)</span>.</p>
</div>
</details>
</section>
</section>
<section id="representing-words" class="level2">
<h2 class="anchored" data-anchor-id="representing-words">Representing Words</h2>
<p>This is the first serious step into natural language processing, so the next question is how to represent an individual word in a sentence.</p>
<p>To represent a word, the first thing to do is come up with a <span class="term" tabindex="0" data-def="A fixed list of the words a model is able to represent, each one assigned a position. Also called a dictionary."><strong>vocabulary</strong></span>, sometimes also called a dictionary. That means making a list of the words that you will use in your representations. The first word in the vocabulary is <code>a</code>, the second is <code>Aaron</code>, a little further down is the word <code>and</code>, then eventually <code>Harry</code>, then <code>Potter</code>, and all the way down to maybe the last word <code>Zulu</code>.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Position</th>
<th>Word</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>a</td>
</tr>
<tr class="even">
<td>2</td>
<td>Aaron</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>367</td>
<td>and</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>4,075</td>
<td>Harry</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>6,830</td>
<td>Potter</td>
</tr>
<tr class="odd">
<td>…</td>
<td>…</td>
</tr>
<tr class="even">
<td>10,000</td>
<td>Zulu</td>
</tr>
</tbody>
</table>
<p>So <code>a</code> is word one, <code>Aaron</code> is word two, <code>and</code> sits at position 367, <code>Harry</code> at 4,075, <code>Potter</code> at 6,830, and <code>Zulu</code> is the last word at 10,000. This example uses a dictionary of size 10,000 words, which is quite small by modern NLP standards. For commercial applications, dictionary sizes of 30,000 to 50,000 are more common and 100,000 is not uncommon, while some of the large internet companies use dictionary sizes of a million words or even bigger. A round 10,000 is convenient for illustration.</p>
<p>One way to build this dictionary is to look through your training set and find the top 10,000 occurring words. Another is to look through online dictionaries that tell you the most common 10,000 words in the English language.</p>
<p>Once the dictionary exists, you can use <span class="term" tabindex="0" data-def="A vector as long as the vocabulary, holding a single 1 at the position of the word it represents and 0 everywhere else."><strong>one-hot representations</strong></span> to represent each of these words. For example, <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, which represents the word <code>Harry</code>, is a vector of all zeros except for a 1 in position 4,075, because that is the position of <code>Harry</code> in the dictionary. Then <span class="math inline">\(x^{\langle 2 \rangle}\)</span> is again a vector of all zeros except for a 1 in position 6,830 for <code>Potter</code>. The word <code>and</code> sits at position 367, so <span class="math inline">\(x^{\langle 3 \rangle}\)</span> is a vector with a 1 in position 367 and zeros everywhere else. The seventh word of the sentence is <code>a</code>, which is the very first entry of the dictionary, so <span class="math inline">\(x^{\langle 7 \rangle}\)</span> has a 1 in position 1 and zeros everywhere else. Each of these is a 10,000-dimensional vector, because the vocabulary has 10,000 words.</p>
<div id="9c24170e" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-3-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Each word becomes a 10,000-dimensional vector with a single 1.</figcaption>
</figure>
</div>
</div>
</div>
<p>In this representation, <span class="math inline">\(x^{\langle t \rangle}\)</span> for each value of <span class="math inline">\(t\)</span> in a sentence is a one-hot vector. It is called one-hot because exactly one entry is on and every other entry is zero, and there are nine of them to represent the nine words in this sentence. The goal is to take this representation of <span class="math inline">\(X\)</span> and learn a mapping, using a sequence model, to the target output <span class="math inline">\(y\)</span>. This is done as a supervised learning problem, trained on labeled data with both <span class="math inline">\(x\)</span> and <span class="math inline">\(y\)</span> given.</p>
<section id="unknown-words" class="level3">
<h3 class="anchored" data-anchor-id="unknown-words">Unknown Words</h3>
<p>One last detail, which comes back in a later video, is what happens when you encounter a word that is not in your vocabulary. The answer is that you create a new token, a new fake word called Unknown Word, written <span class="math inline">\(\langle \text{UNK} \rangle\)</span>, to stand for every word that is not in your vocabulary.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<div id="representing-words-review-q1">
<p><strong>1. The sentence is “Harry Potter and Hermione Granger invented a new spell” and the vocabulary has 10,000 words. What does <span class="math inline">\(x^{\langle 7 \rangle}\)</span> look like?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="representing-words-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>The seventh word is <code>a</code>, which is the first entry in the dictionary. So <span class="math inline">\(x^{\langle 7 \rangle}\)</span> is a 10,000-dimensional vector holding a 1 in position 1 and a 0 in every other position.</p>
</div>
</details>
<hr>
<div id="representing-words-review-q2">
<p><strong>1. Two ways of building a 10,000-word vocabulary were mentioned. What are they?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="representing-words-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>You can look through your own training set and take the 10,000 most frequently occurring words, or you can look through an online dictionary that lists the most common 10,000 words in the English language.</p>
</div>
</details>
<hr>
<div id="representing-words-review-q3">
<p><strong>1. A word appears in a test sentence but was never added to the vocabulary. How is it represented?</strong></p>
<ol type="a">
<li><p>It is dropped from the sentence</p></li>
<li><p>It is mapped to the special token <span class="math inline">\(\langle \text{UNK} \rangle\)</span></p></li>
<li><p>It is given a vector of all zeros</p></li>
<li><p>The vocabulary is grown by one entry</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="representing-words-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p><strong>b.</strong> A new fake word called Unknown Word, written <span class="math inline">\(\langle \text{UNK} \rangle\)</span>, stands in for every word that is not in the vocabulary. Dropping the word would change the length of the sequence, an all-zero vector would not be a one-hot vector, and growing the vocabulary would change the dimension of every input vector.</p>
</div>
</details>
<hr>
<div id="representing-words-review-q4">
<p><strong>1. Why is a one-hot vector for this example 10,000 numbers long rather than nine?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="representing-words-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p>The length of a one-hot vector is set by the size of the vocabulary, not by the length of the sentence. The vocabulary holds 10,000 words, so each vector needs 10,000 slots in order to mark which one of those words it is. The sentence length of nine only decides how many such vectors you need, which is one per word.</p>
</div>
</details>
<p>With this notation in place, the next step is to build a model that learns the mapping from <span class="math inline">\(X\)</span> to <span class="math inline">\(Y\)</span>.</p>
</section>
</section>
<section id="why-not-a-standard-network" class="level2">
<h2 class="anchored" data-anchor-id="why-not-a-standard-network">Why Not a Standard Network?</h2>
<p>One thing you could try is a standard neural network. In the named entity recognition example there were nine input words, so you could imagine taking those nine words, maybe the nine one-hot vectors, and feeding them into a standard network with a few hidden layers, which eventually outputs the nine values, zero or one, that tell you whether each word is part of a person’s name.</p>
<div id="2968a300" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-4-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>A standard network applied to a sequence, one input word per input unit.</figcaption>
</figure>
</div>
</div>
</div>
<p>This turns out not to work well, and there are two main problems.</p>
<p><strong>Inputs and outputs can be different lengths in different examples.</strong> It is not as though every example has the same input length <span class="math inline">\(T_x\)</span> or the same output length <span class="math inline">\(T_y\)</span>. If every sentence has some maximum length, you could pad or zero-pad every input up to that maximum length, but this still does not seem like a good representation.</p>
<p><strong>A naive architecture does not share features learned across different positions of text.</strong> Suppose the network has learned that the word <code>Harry</code> appearing in position one is a sign that it is part of a person’s name. It would be nice if it automatically figured out that <code>Harry</code> appearing in some other position <span class="math inline">\(x^{\langle t \rangle}\)</span> also means the word might be a person’s name. This is similar to what happens in <a href="../../../ai/deep-learning/convolutional-neural-networks/convolutions-and-edge-detection">convolutional neural networks</a>, where things learned for one part of an image generalize quickly to other parts of the image, and a similar effect is wanted for sequence data.</p>
<p>A better representation also reduces the number of parameters in the model. Each input is a 10,000-dimensional one-hot vector, so the total input size is the maximum number of words times 10,000, which makes for a very large input layer. The weight matrix of that first layer ends up having an enormous number of parameters.</p>
<p>A recurrent neural network does not have either of these disadvantages.</p>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<div id="standard-network-review-q1">
<p><strong>1. Why is zero-padding every sentence up to a maximum length not a satisfying fix for the first problem?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="standard-network-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>It makes the shapes line up, but it is still not a good representation. Every example is forced into the same fixed-width input regardless of how long it actually is, and the padding carries no information while still consuming input units and parameters.</p>
</div>
</details>
<hr>
<div id="standard-network-review-q2">
<p><strong>1. What does “sharing features across positions” mean, and which earlier architecture already does something similar?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="standard-network-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>It means that something the network learns about a word at one position should apply automatically when that word shows up at a different position. If <code>Harry</code> at position one signals a person’s name, then <code>Harry</code> at position five should too, without the network having to learn it separately. Convolutional networks do the analogous thing for images, where a feature learned for one part of an image generalizes to other parts.</p>
</div>
</details>
<hr>
<div id="standard-network-review-q3">
<p><strong>1. With a 10,000-word vocabulary and a maximum sentence length of 100 words, roughly how large is the input layer of the standard network above?</strong></p>
<ol type="a">
<li><p>10,000 units</p></li>
<li><p>100 units</p></li>
<li><p>1,000,000 units</p></li>
<li><p>10,100 units</p></li>
</ol>
</div>
<details class="review-answer">
<summary aria-describedby="standard-network-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p><strong>c.</strong> Each word is a 10,000-dimensional one-hot vector and there are up to 100 of them, so the input is <span class="math inline">\(100 \times 10{,}000 = 1{,}000{,}000\)</span> units. The first weight matrix therefore has an enormous number of parameters, which is the third reason to want a better representation.</p>
</div>
</details>
</section>
</section>
<section id="recurrent-neural-network-structure" class="level2">
<h2 class="anchored" data-anchor-id="recurrent-neural-network-structure">Recurrent Neural Network Structure</h2>
<p>Suppose you read the sentence from left to right. The first word you read is <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, and what you do is take that first word and feed it into a neural network layer. There is a hidden layer, and you can have the network try to predict the output <span class="math inline">\(\hat{y}^{\langle 1 \rangle}\)</span>, which says whether this is part of a person’s name or not.</p>
<p>What a recurrent neural network does is this. When it goes on to read the second word in the sentence, <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, instead of predicting <span class="math inline">\(\hat{y}^{\langle 2 \rangle}\)</span> using only <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, it also gets some information from what was computed at time step one. In particular, the activation value from time step one is passed on to time step two. At the next time step the network takes the third word <span class="math inline">\(x^{\langle 3 \rangle}\)</span> and tries to output a prediction <span class="math inline">\(\hat{y}^{\langle 3 \rangle}\)</span>, and so on up to the last time step, where it takes <span class="math inline">\(x^{\langle T_x \rangle}\)</span> together with the activation <span class="math inline">\(a^{\langle T_x - 1 \rangle}\)</span> carried over from the step before it, and outputs <span class="math inline">\(\hat{y}^{\langle T_y \rangle}\)</span>. In this example <span class="math inline">\(T_x = T_y\)</span>, and the architecture changes a bit when <span class="math inline">\(T_x\)</span> and <span class="math inline">\(T_y\)</span> are not identical.</p>
<p>To kick the whole thing off you also need a made-up activation at time zero, <span class="math inline">\(a^{\langle 0 \rangle}\)</span>. This is usually a vector of zeros. Some researchers initialize <span class="math inline">\(a^{\langle 0 \rangle}\)</span> randomly, and there are other ways to initialize it, but a vector of zeros as the fake time-zero activation is the most common choice.</p>
<div id="c3391c22" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-5-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>The unrolled recurrent network, with the same parameters reused at every time step.</figcaption>
</figure>
</div>
</div>
</div>
<section id="two-ways-to-draw-the-same-network" class="level3">
<h3 class="anchored" data-anchor-id="two-ways-to-draw-the-same-network">Two Ways to Draw the Same Network</h3>
<p>In some research papers and some books you see this type of network drawn with a different diagram, in which at every time step you input <span class="math inline">\(x\)</span> and output <span class="math inline">\(\hat{y}\)</span>, sometimes with a <span class="math inline">\(t\)</span> index. To denote the recurrent connection, people draw a loop that feeds the layer back into the cell, and sometimes a shaded box to denote a time delay of one step.</p>
<div id="3a4cef6d" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-6-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Two Ways to Draw the Same Network.</figcaption>
</figure>
</div>
</div>
</div>
<p>The recurrent diagrams on the right are harder to interpret, so these notes draw the unrolled diagram on the left throughout. If you see something like the diagram on the right in a textbook or a research paper, the way to think about it is to mentally unroll it into the diagram on the left.</p>
</section>
<section id="shared-parameters" class="level3">
<h3 class="anchored" data-anchor-id="shared-parameters">Shared Parameters</h3>
<p>The recurrent neural network scans through the data from left to right, and the parameters it uses at each time step are shared. The parameters governing the connection from <span class="math inline">\(x^{\langle 1 \rangle}\)</span> to the hidden layer are written <span class="math inline">\(W_{ax}\)</span>, and the same <span class="math inline">\(W_{ax}\)</span> is used at every time step. The horizontal connections that carry the activations are governed by <span class="math inline">\(W_{aa}\)</span>, again the same at every time step, and <span class="math inline">\(W_{ya}\)</span> governs the output predictions.</p>
<p>What this means is that when the network makes the prediction for <span class="math inline">\(\hat{y}^{\langle 3 \rangle}\)</span>, it gets information not only from <span class="math inline">\(x^{\langle 3 \rangle}\)</span> but also from <span class="math inline">\(x^{\langle 1 \rangle}\)</span> and <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, because the information in <span class="math inline">\(x^{\langle 1 \rangle}\)</span> can pass along the horizontal connections to help with the prediction at time three.</p>
</section>
<section id="one-weakness-of-this-architecture" class="level3">
<h3 class="anchored" data-anchor-id="one-weakness-of-this-architecture">One Weakness of This Architecture</h3>
<p>This RNN only uses the information that is earlier in the sequence to make a prediction. When predicting <span class="math inline">\(\hat{y}^{\langle 3 \rangle}\)</span> it does not use information about the words <span class="math inline">\(x^{\langle 4 \rangle}\)</span>, <span class="math inline">\(x^{\langle 5 \rangle}\)</span>, <span class="math inline">\(x^{\langle 6 \rangle}\)</span>, and so on.</p>
<p>This is a problem. Consider the sentence “He said, Teddy Roosevelt was a great president.” To decide whether the word <code>Teddy</code> is part of a person’s name, it would be really useful to know not just the first two words but the later words as well, because the sentence could also have been “He said, teddy bears are on sale.” Given only the first three words it is not possible to know for sure whether <code>Teddy</code> is part of a person’s name. In the first example it is, and in the second example it is not, and you cannot tell the difference by looking only at the first three words.</p>
<p>So one limitation of this particular structure is that the prediction at a certain time uses information from the inputs earlier in the sequence but not information later in the sequence. This is addressed later by bidirectional recurrent neural networks, or BRNNs. For now this simpler unidirectional architecture is enough to explain the key concepts.</p>
</section>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<div id="rnn-structure-review-q1">
<p><strong>1. What is <span class="math inline">\(a^{\langle 0 \rangle}\)</span> and what is it normally set to?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="rnn-structure-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>It is a made-up activation at time zero, needed to kick off the recurrence, because the first cell expects an incoming activation from the step before it. It is usually a vector of zeros. Some researchers initialize it randomly, but zeros is the most common choice.</p>
</div>
</details>
<hr>
<div id="rnn-structure-review-q2">
<p><strong>1. The network predicts <span class="math inline">\(\hat{y}^{\langle 3 \rangle}\)</span>. Which inputs does that prediction actually depend on?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="rnn-structure-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>It depends on <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, and <span class="math inline">\(x^{\langle 3 \rangle}\)</span>. The information from the earlier words reaches time step three through the horizontal activation connections. It does not depend on <span class="math inline">\(x^{\langle 4 \rangle}\)</span> or anything later, which is the weakness that bidirectional RNNs later fix.</p>
</div>
</details>
<hr>
<div id="rnn-structure-review-q3">
<p><strong>1. Why do the sentences “He said, Teddy Roosevelt was a great president” and “He said, teddy bears are on sale” make the same point about this architecture?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="rnn-structure-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>Both begin with the same three words, and in one of them <code>Teddy</code> is part of a person’s name while in the other it is not. A unidirectional RNN predicting at position three has seen only those three words, so it has no way to tell the two cases apart. The information that settles it comes later in the sentence.</p>
</div>
</details>
<hr>
<div id="rnn-structure-review-q4">
<p><strong>1. How does parameter sharing across time steps address the second problem with the standard network?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="rnn-structure-review-q4">
Answer
</summary>
<div class="review-answer-body">
<p>The same <span class="math inline">\(W_{ax}\)</span>, <span class="math inline">\(W_{aa}\)</span>, and <span class="math inline">\(W_{ya}\)</span> are used at every position, so whatever the network learns about a word is applied at every position it can appear in. It also keeps the parameter count from growing with the length of the sequence, because a longer sentence reuses the same matrices rather than needing new ones.</p>
</div>
</details>
</section>
</section>
<section id="forward-propagation" class="level2">
<h2 class="anchored" data-anchor-id="forward-propagation">Forward Propagation</h2>
<p>Here is what forward propagation looks like written out. You start with <span class="math inline">\(a^{\langle 0 \rangle}\)</span> equal to the vector of all zeros. To compute <span class="math inline">\(a^{\langle 1 \rangle}\)</span> you apply an activation function <span class="math inline">\(g\)</span> to <span class="math inline">\(W_{aa}\)</span> times <span class="math inline">\(a^{\langle 0 \rangle}\)</span>, plus <span class="math inline">\(W_{ax}\)</span> times <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, plus a bias <span class="math inline">\(b_a\)</span>. Then the prediction at time one uses some activation function, possibly a different one, applied to <span class="math inline">\(W_{ya}\)</span> times <span class="math inline">\(a^{\langle 1 \rangle}\)</span> plus <span class="math inline">\(b_y\)</span>.</p>
<p><span class="math display">\[a^{\langle 1 \rangle} = g\!\left(W_{aa}\,a^{\langle 0 \rangle} + W_{ax}\,x^{\langle 1 \rangle} + b_a\right)\]</span></p>
<p><span class="math display">\[\hat{y}^{\langle 1 \rangle} = g\!\left(W_{ya}\,a^{\langle 1 \rangle} + b_y\right)\]</span></p>
<p>The notation convention for the subscripts on these matrices works like this. In <span class="math inline">\(W_{ax}\)</span>, the second index <span class="math inline">\(x\)</span> means that this matrix is going to be multiplied by some <span class="math inline">\(x\)</span>-like quantity, and the first index <span class="math inline">\(a\)</span> means that it is used to compute some <span class="math inline">\(a\)</span>-like quantity. Similarly, <span class="math inline">\(W_{ya}\)</span> is multiplied by an <span class="math inline">\(a\)</span>-like quantity to compute a <span class="math inline">\(y\)</span>-like quantity.</p>
<p>The activation function used to compute the activations is often a tanh in the case of an RNN, and ReLU is sometimes used as well, although tanh is a pretty common choice. There are other ways of preventing the vanishing gradient problem, which come up later this week.</p>
<p>The choice of the output activation function depends on what type of output <span class="math inline">\(y\)</span> you have. If it is a binary classification problem you would use a sigmoid, and if you have a <span class="math inline">\(k\)</span>-way classification problem it could be a softmax. For the named entity recognition task, where <span class="math inline">\(y\)</span> was either 0 or 1, the second <span class="math inline">\(g\)</span> would be a sigmoid. You could write <span class="math inline">\(g_2\)</span> to distinguish the two activation functions, though that is usually left implicit.</p>
<p>More generally, at time <span class="math inline">\(t\)</span>:</p>
<p><span class="math display">\[a^{\langle t \rangle} = g\!\left(W_{aa}\,a^{\langle t-1 \rangle} + W_{ax}\,x^{\langle t \rangle} + b_a\right)\]</span></p>
<p><span class="math display">\[\hat{y}^{\langle t \rangle} = g\!\left(W_{ya}\,a^{\langle t \rangle} + b_y\right)\]</span></p>
<p>These equations define forward propagation. You start with <span class="math inline">\(a^{\langle 0 \rangle}\)</span> as the vector of all zeros, then use <span class="math inline">\(a^{\langle 0 \rangle}\)</span> and <span class="math inline">\(x^{\langle 1 \rangle}\)</span> to compute <span class="math inline">\(a^{\langle 1 \rangle}\)</span> and <span class="math inline">\(\hat{y}^{\langle 1 \rangle}\)</span>, then take <span class="math inline">\(x^{\langle 2 \rangle}\)</span> and use it with <span class="math inline">\(a^{\langle 1 \rangle}\)</span> to compute <span class="math inline">\(a^{\langle 2 \rangle}\)</span> and <span class="math inline">\(\hat{y}^{\langle 2 \rangle}\)</span>, and so on, carrying out forward propagation from the left to the right of the diagram.</p>
<section id="review-questions-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-5">Review Questions</h3>
<div id="forward-prop-review-q1">
<p><strong>1. In the symbol <span class="math inline">\(W_{ya}\)</span>, what does each of the two subscript letters tell you?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="forward-prop-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>The second letter says what the matrix gets multiplied by and the first says what it helps compute. So <span class="math inline">\(W_{ya}\)</span> is multiplied by an <span class="math inline">\(a\)</span>-like quantity, the activation, and is used to produce a <span class="math inline">\(y\)</span>-like quantity, the prediction. The same reading applies to <span class="math inline">\(W_{ax}\)</span>, which multiplies an <span class="math inline">\(x\)</span>-like quantity to help compute an <span class="math inline">\(a\)</span>-like quantity.</p>
</div>
</details>
<hr>
<div id="forward-prop-review-q2">
<p><strong>1. Which activation function is the common choice inside the recurrence, and what decides the activation function on the output?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="forward-prop-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Tanh is the common choice for computing the activations, and ReLU is sometimes used. The output activation is decided by the type of <span class="math inline">\(y\)</span>. A binary classification problem uses a sigmoid, and a <span class="math inline">\(k\)</span>-way classification problem uses a softmax. Named entity recognition has <span class="math inline">\(y\)</span> equal to 0 or 1, so it uses a sigmoid.</p>
</div>
</details>
<hr>
<div id="forward-prop-review-q3">
<p><strong>1. Write the two forward propagation equations at a general time step <span class="math inline">\(t\)</span>.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="forward-prop-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p><span class="math display">\[a^{\langle t \rangle} = g\!\left(W_{aa}\,a^{\langle t-1 \rangle} + W_{ax}\,x^{\langle t \rangle} + b_a\right)\]</span> <span class="math display">\[\hat{y}^{\langle t \rangle} = g\!\left(W_{ya}\,a^{\langle t \rangle} + b_y\right)\]</span> The activation at time <span class="math inline">\(t\)</span> combines the activation carried over from time <span class="math inline">\(t-1\)</span> with the input at time <span class="math inline">\(t\)</span>, and the prediction at time <span class="math inline">\(t\)</span> is computed from that activation.</p>
</div>
</details>
</section>
</section>
<section id="simplified-notation" class="level2">
<h2 class="anchored" data-anchor-id="simplified-notation">Simplified Notation</h2>
<p>To help in developing more complex networks later, the notation can be simplified a little. The activation equation gets rewritten as</p>
<p><span class="math display">\[a^{\langle t \rangle} = g\!\left(W_a\,[\,a^{\langle t-1 \rangle},\, x^{\langle t \rangle}\,] + b_a\right)\]</span></p>
<p>and the quantities on the left and right are meant to be equivalent to what was written before. The way <span class="math inline">\(W_a\)</span> is defined is by taking the matrix <span class="math inline">\(W_{aa}\)</span> and the matrix <span class="math inline">\(W_{ax}\)</span> and putting them side by side, stacking them horizontally.</p>
<p>For example, if <span class="math inline">\(a\)</span> is 100-dimensional and, in the running example, <span class="math inline">\(x\)</span> is 10,000-dimensional, then <span class="math inline">\(W_{aa}\)</span> is a <span class="math inline">\(100 \times 100\)</span> matrix and <span class="math inline">\(W_{ax}\)</span> is a <span class="math inline">\(100 \times 10{,}000\)</span> matrix. Stacking those two together gives a <span class="math inline">\(W_a\)</span> that is <span class="math inline">\(100 \times 10{,}100\)</span>. The notation <span class="math inline">\([\,a^{\langle t-1 \rangle}, x^{\langle t \rangle}\,]\)</span> means taking the two vectors and stacking them together, so the 100-dimensional <span class="math inline">\(a^{\langle t-1 \rangle}\)</span> sits on top of the 10,000-dimensional <span class="math inline">\(x^{\langle t \rangle}\)</span> and the result is a 10,100-dimensional vector.</p>
<div id="80b08690" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-7-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Two matrices stacked side by side, two vectors stacked on top of each other.</figcaption>
</figure>
</div>
</div>
</div>
<p>You can check for yourself that this matrix times this vector gives back the original quantity. The stacked matrix <span class="math inline">\([\,W_{aa} \mid W_{ax}\,]\)</span> multiplied by the stacked vector <span class="math inline">\([\,a^{\langle t-1 \rangle},\, x^{\langle t \rangle}\,]\)</span> is equal to <span class="math inline">\(W_{aa}\,a^{\langle t-1 \rangle} + W_{ax}\,x^{\langle t \rangle}\)</span>, which is exactly what was there before.</p>
<p>The advantage of this notation is that rather than carrying around two parameter matrices, <span class="math inline">\(W_{aa}\)</span> and <span class="math inline">\(W_{ax}\)</span>, you compress them into a single parameter matrix <span class="math inline">\(W_a\)</span>, which simplifies the notation when developing more complex models. The output equation gets rewritten in a similar way.</p>
<p><span class="math display">\[\hat{y}^{\langle t \rangle} = g\!\left(W_y\,a^{\langle t \rangle} + b_y\right)\]</span></p>
<p>Now there is just one subscript in <span class="math inline">\(W_y\)</span> and <span class="math inline">\(b_y\)</span>, and it denotes what type of output quantity is being computed. So <span class="math inline">\(W_y\)</span> indicates a weight matrix for computing a <span class="math inline">\(y\)</span>-like quantity, and <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span> indicate the parameters for computing an <span class="math inline">\(a\)</span>-like activation quantity.</p>
<section id="review-questions-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-6">Review Questions</h3>
<div id="simplified-notation-review-q1">
<p><strong>1. <span class="math inline">\(a\)</span> is 100-dimensional and <span class="math inline">\(x\)</span> is 10,000-dimensional. What are the shapes of <span class="math inline">\(W_a\)</span> and of the stacked vector <span class="math inline">\([\,a^{\langle t-1 \rangle}, x^{\langle t \rangle}\,]\)</span>?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="simplified-notation-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p><span class="math inline">\(W_{aa}\)</span> is <span class="math inline">\(100 \times 100\)</span> and <span class="math inline">\(W_{ax}\)</span> is <span class="math inline">\(100 \times 10{,}000\)</span>, so placing them side by side gives a <span class="math inline">\(W_a\)</span> of shape <span class="math inline">\(100 \times 10{,}100\)</span>. Stacking the 100-dimensional activation on top of the 10,000-dimensional input gives a vector of length 10,100. Multiplying the two gives a 100-dimensional result, which is the right shape for <span class="math inline">\(a^{\langle t \rangle}\)</span>.</p>
</div>
</details>
<hr>
<div id="simplified-notation-review-q2">
<p><strong>1. Show why <span class="math inline">\(W_a\,[\,a^{\langle t-1 \rangle}, x^{\langle t \rangle}\,]\)</span> is the same as <span class="math inline">\(W_{aa}\,a^{\langle t-1 \rangle} + W_{ax}\,x^{\langle t \rangle}\)</span>.</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="simplified-notation-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Multiplying a horizontally stacked matrix by a vertically stacked vector splits into the sum of the two blockwise products. <span class="math display">\[[\,W_{aa} \mid W_{ax}\,] \begin{bmatrix} a^{\langle t-1 \rangle} \\ x^{\langle t \rangle} \end{bmatrix} = W_{aa}\,a^{\langle t-1 \rangle} + W_{ax}\,x^{\langle t \rangle}\]</span> The first 100 columns of <span class="math inline">\(W_a\)</span> meet the first 100 entries of the stacked vector, which is exactly <span class="math inline">\(W_{aa}\,a^{\langle t-1 \rangle}\)</span>, and the remaining 10,000 columns meet the remaining 10,000 entries, which is <span class="math inline">\(W_{ax}\,x^{\langle t \rangle}\)</span>.</p>
</div>
</details>
<hr>
<div id="simplified-notation-review-q3">
<p><strong>1. What is gained by the simplified notation?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="simplified-notation-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>Instead of carrying two parameter matrices around, you carry one. That keeps the equations short when more complex models are built later. The subscripts also become simpler, since <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span> produce an activation-like quantity and <span class="math inline">\(W_y\)</span> and <span class="math inline">\(b_y\)</span> produce an output-like quantity.</p>
</div>
</details>
<p>That is a basic recurrent neural network. What remains is backpropagation, and how you learn with these RNNs.</p>
</section>
</section>
<section id="computation-graph" class="level2">
<h2 class="anchored" data-anchor-id="computation-graph">Computation Graph</h2>
<p>When you implement an RNN in one of the programming frameworks, the framework will often take care of backpropagation automatically, but it is still useful to have a rough sense of what it is doing. You have seen how, for forward propagation, the activations are computed from left to right through the network, producing all of the predictions. In backpropagation, as you might already have guessed, the calculations are carried out in basically the opposite direction of the forward propagation arrows.</p>
<p>Start by laying out the forward pass as a computation graph. You are given the input sequence <span class="math inline">\(x^{\langle 1 \rangle}\)</span>, <span class="math inline">\(x^{\langle 2 \rangle}\)</span>, <span class="math inline">\(x^{\langle 3 \rangle}\)</span>, up to <span class="math inline">\(x^{\langle T_x \rangle}\)</span>. Using <span class="math inline">\(x^{\langle 1 \rangle}\)</span> and <span class="math inline">\(a^{\langle 0 \rangle}\)</span> you compute the activation <span class="math inline">\(a^{\langle 1 \rangle}\)</span>, then <span class="math inline">\(x^{\langle 2 \rangle}\)</span> together with <span class="math inline">\(a^{\langle 1 \rangle}\)</span> is used to compute <span class="math inline">\(a^{\langle 2 \rangle}\)</span>, then <span class="math inline">\(a^{\langle 3 \rangle}\)</span>, and so on, with the final step combining <span class="math inline">\(a^{\langle T_x - 1 \rangle}\)</span> and <span class="math inline">\(x^{\langle T_x \rangle}\)</span> to give <span class="math inline">\(a^{\langle T_x \rangle}\)</span>.</p>
<p>To actually compute <span class="math inline">\(a^{\langle 1 \rangle}\)</span> you also need the parameters <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span>. Those same parameters are used at every single time step, so <span class="math inline">\(a^{\langle 2 \rangle}\)</span>, <span class="math inline">\(a^{\langle 3 \rangle}\)</span>, and all the activations up to the last time step depend on <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span>.</p>
<p>Given <span class="math inline">\(a^{\langle 1 \rangle}\)</span>, the network can then compute the first prediction <span class="math inline">\(\hat{y}^{\langle 1 \rangle}\)</span>, and then <span class="math inline">\(\hat{y}^{\langle 2 \rangle}\)</span>, <span class="math inline">\(\hat{y}^{\langle 3 \rangle}\)</span>, and so on up to <span class="math inline">\(\hat{y}^{\langle T_y \rangle}\)</span>. To compute <span class="math inline">\(\hat{y}\)</span> you need the parameters <span class="math inline">\(W_y\)</span> and <span class="math inline">\(b_y\)</span>, and those feed into every one of those nodes.</p>
<div id="cd37a069" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-8-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Forward propagation, with one loss per time step summed into the overall loss.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="loss-function" class="level2">
<h2 class="anchored" data-anchor-id="loss-function">Loss Function</h2>
<p>To compute backpropagation you need a loss function. Start by defining an element-wise loss, which applies to a certain word in the sequence. Suppose that word is a person’s name, so <span class="math inline">\(y^{\langle t \rangle}\)</span> is one, and the network outputs some probability of maybe 0.1 of that particular word being a person’s name.</p>
<p>This is defined as the standard logistic regression loss, also called the <a href="../../../ai/deep-learning/neural-networks-and-deep-learning/logistic-regression-as-a-neural-network">cross entropy loss</a>. It may look familiar from binary classification problems seen earlier.</p>
<p><span class="math display">\[\mathcal{L}^{\langle t \rangle}\!\left(\hat{y}^{\langle t \rangle},\, y^{\langle t \rangle}\right) = -\,y^{\langle t \rangle} \log \hat{y}^{\langle t \rangle} - \left(1 - y^{\langle t \rangle}\right) \log\!\left(1 - \hat{y}^{\langle t \rangle}\right)\]</span></p>
<p>This is the loss associated with a single prediction at a single position, at a single time step <span class="math inline">\(t\)</span>, for a single word.</p>
<p>Now define the overall loss of the entire sequence. <span class="math inline">\(\mathcal{L}\)</span> is the sum over all <span class="math inline">\(t\)</span> from one to <span class="math inline">\(T_y\)</span> of the losses for the individual time steps. In this example <span class="math inline">\(T_x\)</span> is equal to <span class="math inline">\(T_y\)</span>.</p>
<p><span class="math display">\[\mathcal{L}\!\left(\hat{y},\, y\right) = \sum_{t=1}^{T_y} \mathcal{L}^{\langle t \rangle}\!\left(\hat{y}^{\langle t \rangle},\, y^{\langle t \rangle}\right)\]</span></p>
<p>Written without the superscript <span class="math inline">\(t\)</span>, this is the loss for the entire sequence. In the computation graph above, given <span class="math inline">\(\hat{y}^{\langle 1 \rangle}\)</span> you compute the loss for the first time step, then the loss for the second time step, the loss for the third, and so on to the loss for the final time step. Lastly you take all of those and sum them up to compute the final <span class="math inline">\(\mathcal{L}\)</span>.</p>
<section id="review-questions-7" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-7">Review Questions</h3>
<div id="loss-review-q1">
<p><strong>1. A word at time step <span class="math inline">\(t\)</span> is part of a person’s name, so <span class="math inline">\(y^{\langle t \rangle} = 1\)</span>, and the network outputs <span class="math inline">\(\hat{y}^{\langle t \rangle} = 0.1\)</span>. What does the loss at that step reduce to?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="loss-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>With <span class="math inline">\(y^{\langle t \rangle} = 1\)</span> the second term vanishes, so the loss reduces to <span class="math inline">\(-\log \hat{y}^{\langle t \rangle} = -\log 0.1 \approx 2.30\)</span>. A confident and correct prediction near 1 would give a loss near 0, so this large value reflects that the network was confidently wrong at that position.</p>
</div>
</details>
<hr>
<div id="loss-review-q2">
<p><strong>1. Why is the overall loss a sum rather than a single number computed at the end of the sequence?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="loss-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>In this architecture the network makes one prediction per time step, and each one can be right or wrong on its own. Each position therefore has its own loss, and the loss for the whole sequence is the sum of those per-timestep losses.</p>
</div>
</details>
</section>
</section>
<section id="backpropagation-through-time" class="level2">
<h2 class="anchored" data-anchor-id="backpropagation-through-time">Backpropagation Through Time</h2>
<p>This is the computation graph, and from the earlier examples of backpropagation it should not be surprising that backpropagation then just requires doing computations, or passing messages, in the opposite directions. For all of the forward propagation arrows, you end up carrying out the reverse. The overall loss sends a gradient back into each <span class="math inline">\(\mathcal{L}^{\langle t \rangle}\)</span>, each of those sends one down into <span class="math inline">\(\hat{y}^{\langle t \rangle}\)</span>, from there into <span class="math inline">\(a^{\langle t \rangle}\)</span>, and from <span class="math inline">\(a^{\langle t \rangle}\)</span> back into <span class="math inline">\(a^{\langle t-1 \rangle}\)</span>. That allows you to compute all the appropriate quantities, take the derivatives with respect to the parameters <span class="math inline">\(W_a\)</span>, <span class="math inline">\(b_a\)</span>, <span class="math inline">\(W_y\)</span>, and <span class="math inline">\(b_y\)</span>, and update them using gradient descent.</p>
<div id="0f52eae9" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="recurrent-neural-networks_files/figure-html/cell-9-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Backpropagation runs against every forward arrow, and the recursion along the activations runs right to left.</figcaption>
</figure>
</div>
</div>
</div>
<p>In this backpropagation procedure, the most significant message, the most significant recursive calculation, is the one that goes from right to left along the activations. That is what gives the algorithm its name, <strong>backpropagation through time</strong>. The motivation for the name is that in forward propagation you scan from left to right with increasing indices of the time <span class="math inline">\(t\)</span>, whereas in backpropagation you go from right to left, going backwards in time. That phrase makes it sound like you need a time machine to implement it, but backprop through time is one of the coolest names for an algorithm.</p>
<section id="review-questions-8" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-8">Review Questions</h3>
<div id="bptt-review-q1">
<p><strong>1. Where does the name “backpropagation through time” come from?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="bptt-review-q1">
Answer
</summary>
<div class="review-answer-body">
<p>Forward propagation scans the sequence from left to right with increasing <span class="math inline">\(t\)</span>, so it moves forward in time. The most significant recursive calculation in backpropagation runs the other way, from right to left along the activations, which amounts to moving backwards in time.</p>
</div>
</details>
<hr>
<div id="bptt-review-q2">
<p><strong>1. The parameters <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span> appear at every time step. What does that mean for their gradients?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="bptt-review-q2">
Answer
</summary>
<div class="review-answer-body">
<p>Because the same <span class="math inline">\(W_a\)</span> and <span class="math inline">\(b_a\)</span> are used to compute every activation from <span class="math inline">\(a^{\langle 1 \rangle}\)</span> through <span class="math inline">\(a^{\langle T_x \rangle}\)</span>, every time step contributes to their gradient. The contributions from all the time steps combine before the parameters are updated by gradient descent, which is the same thing the shared weights do for <span class="math inline">\(W_y\)</span> and <span class="math inline">\(b_y\)</span> on the output side.</p>
</div>
</details>
<hr>
<div id="bptt-review-q3">
<p><strong>1. If a framework handles backpropagation automatically, why bother with the computation graph at all?</strong></p>
</div>
<details class="review-answer">
<summary aria-describedby="bptt-review-q3">
Answer
</summary>
<div class="review-answer-body">
<p>The framework does the mechanics, but a rough sense of how backprop works in RNNs explains where the cost and the difficulties come from. Seeing that the recursion runs the length of the sequence is what makes the vanishing gradient problem, discussed later this week, understandable rather than mysterious.</p>
</div>
</details>
<p>So far the only case seen is the one where the length of the input sequence is equal to the length of the output sequence.</p>
</section>
</section>
<section id="course-roadmap" class="level2">
<h2 class="anchored" data-anchor-id="course-roadmap">Course Roadmap</h2>
<p>This is Course 5, the last of the five in the <a href="../../../ai/deep-learning/">Deep Learning Specialization</a>, and it is about data that arrives in order. Audio, sentences, music, and DNA all have the property that the meaning depends on the sequence, and none of the architectures from the earlier courses handle that well. The material is organized in four parts.</p>
<ol type="1">
<li><strong>Recurrent neural networks.</strong> This page builds the RNN itself, its notation, and forward and backward propagation through time. Then <a href="../../../ai/deep-learning/sequence-models/rnn-architectures-and-language-models">RNN architectures and language models</a> covers the different input and output shapes a sequence problem can take, <a href="../../../ai/deep-learning/sequence-models/vanishing-gradients-gru-and-lstm">vanishing gradients, GRU, and LSTM</a> fixes the RNN’s central weakness with gated units, and <a href="../../../ai/deep-learning/sequence-models/bidirectional-and-deep-rnns">bidirectional and deep RNNs</a> stacks them up. Three labs go with this part, <a href="../../../ai/deep-learning/sequence-models/lab-building-your-recurrent-neural-network">building an RNN step by step</a>, a <a href="../../../ai/deep-learning/sequence-models/lab-character-level-language-model">character level language model</a>, and <a href="../../../ai/deep-learning/sequence-models/lab-improvise-a-jazz-solo">improvising a jazz solo</a>.</li>
<li><strong>Word embeddings.</strong> How a network represents a word as something more useful than an arbitrary index. <a href="../../../ai/deep-learning/sequence-models/introduction-to-word-embeddings">Introduction to word embeddings</a>, <a href="../../../ai/deep-learning/sequence-models/learning-word-embeddings-word2vec-and-glove">learning them with word2vec and GloVe</a>, and <a href="../../../ai/deep-learning/sequence-models/sentiment-classification-and-debiasing">sentiment classification and debiasing</a>, which covers what happens when a model learns the prejudices present in its training text. Labs on <a href="../../../ai/deep-learning/sequence-models/lab-operations-on-word-vectors">operations on word vectors</a> and <a href="../../../ai/deep-learning/sequence-models/lab-emojify">Emojify</a> go with it.</li>
<li><strong>Sequence to sequence models and attention.</strong> <a href="../../../ai/deep-learning/sequence-models/sequence-to-sequence-models">Sequence to sequence models</a> turn one sequence into another, <a href="../../../ai/deep-learning/sequence-models/beam-search">beam search</a> picks a good output rather than a greedy one, and the <a href="../../../ai/deep-learning/sequence-models/bleu-score">BLEU score</a> measures whether it was any good. The <a href="../../../ai/deep-learning/sequence-models/attention-model">attention model</a> is the key idea of the whole course, and <a href="../../../ai/deep-learning/sequence-models/speech-recognition-and-trigger-word-detection">speech recognition and trigger word detection</a> applies it to audio. Labs cover <a href="../../../ai/deep-learning/sequence-models/lab-neural-machine-translation">neural machine translation with attention</a> and <a href="../../../ai/deep-learning/sequence-models/lab-trigger-word-detection">trigger word detection</a>.</li>
<li><strong>Transformer network.</strong> <a href="../../../ai/deep-learning/sequence-models/transformer-network">The transformer</a> takes attention and throws away the recurrence entirely, which is the architecture behind essentially every modern language model. Two labs finish the specialization, <a href="../../../ai/deep-learning/sequence-models/lab-transformer-network">building a transformer</a> and <a href="../../../ai/deep-learning/sequence-models/lab-fine-tuning-a-pretrained-transformer">fine-tuning a pretrained one</a>.</li>
</ol>
<p>The order matters here more than in the other courses. Each part exists because of a problem with the part before it, and the transformer at the end is much easier to understand once you have felt what the RNN could not do.</p>
<p>Each section of these notes ends with review questions. Use them to check your understanding as you go.</p>
<section id="review-questions-9" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-9">Review Questions</h3>
<p><strong>1. Why does this course build RNNs before transformers, given that transformers replaced them?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because each part of the course answers a problem raised by the part before it. The RNN introduces the vocabulary of sequence modeling and then runs into vanishing gradients and a strict step-by-step bottleneck. Attention and then the transformer are much easier to understand as responses to those specific failures than as an architecture presented cold.</p>
</div>
</div>
</div>


<div id="section-progress-widget" class="section-progress-widget" hidden="">
  <p class="section-progress-label">Progress through this page</p>
  <progress class="section-progress" value="4" max="100" aria-label="4 percent through this page"></progress>
  <p class="section-progress-detail">4% (116 of 2610 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.hidden = false; sb.appendChild(w); }
});
</script>

</section>
</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://oliabak.com/giscus-theme-dark.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../ai/deep-learning/sequence-models/" class="pagination-link" aria-label="Sequence Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Sequence Models</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../ai/deep-learning/sequence-models/rnn-architectures-and-language-models" class="pagination-link" aria-label="RNN Architectures and Language Models">
        <span class="nav-page-text">RNN Architectures and Language Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>H’s Notes</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../about">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/dashboard">
<p>Dashboard</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/roadmap">
<p>Roadmap</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>