project:
  type: website

website:
  title: "Hossein's Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: math/index.qmd
        text: Math
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



