project:
  type: website

website:
  title: "Hossein's Notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: math/index.qmd
        text: Math
      - about.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-fold: false
    code-tools: true



