<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-18">
<meta name="description" content="Density estimation with Gaussians to flag unusual examples: the full algorithm, evaluating it with a small labeled set, when to prefer it over supervised learning, and how to tune features.">

<title>Anomaly Detection – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" rel="next">
<link href="../../machine-learning/unsupervised-learning/clustering.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Anomaly Detection – Hossein’s Notes">
<meta property="og:description" content="Density estimation with Gaussians to flag unusual examples: the full algorithm, evaluating it with a small labeled set, when to prefer it over supervised learning, and how to tune features.">
<meta property="og:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/anomaly-detection_files/figure-html/cell-2-output-1.png">
<meta property="og:site_name" content="Hossein’s Notes">
<meta property="og:image:height" content="437">
<meta property="og:image:width" content="596">
<meta name="twitter:title" content="Anomaly Detection – Hossein’s Notes">
<meta name="twitter:description" content="Density estimation with Gaussians to flag unusual examples: the full algorithm, evaluating it with a small labeled set, when to prefer it over supervised learning, and how to tune features.">
<meta name="twitter:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/anomaly-detection_files/figure-html/cell-2-output-1.png">
<meta name="twitter:image-height" content="437">
<meta name="twitter:image-width" content="596">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-agentic-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Agentic AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-agentic-ai">    
        <li>
    <a class="dropdown-item" href="../../agentic/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/frameworks.html">
 <span class="dropdown-text">Frameworks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/agent-architecture.html">
 <span class="dropdown-text">Agent Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/async-io.html">
 <span class="dropdown-text">Async I/O</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/unsupervised-learning/anomaly-detection.html">Anomaly Detection</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/anomaly-detection.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Anomaly Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering-in-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering in Practice</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/content-based-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Content-Based Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/principal-components-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Principal Components Analysis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#finding-unusual-events" id="toc-finding-unusual-events" class="nav-link active" data-scroll-target="#finding-unusual-events">Finding Unusual Events</a>
  <ul class="collapse">
  <li><a href="#density-estimation" id="toc-density-estimation" class="nav-link" data-scroll-target="#density-estimation">Density Estimation</a></li>
  <li><a href="#applications-of-anomaly-detection" id="toc-applications-of-anomaly-detection" class="nav-link" data-scroll-target="#applications-of-anomaly-detection">Applications of Anomaly Detection</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#the-gaussian-distribution" id="toc-the-gaussian-distribution" class="nav-link" data-scroll-target="#the-gaussian-distribution">The Gaussian Distribution</a>
  <ul class="collapse">
  <li><a href="#estimating-the-parameters-from-data" id="toc-estimating-the-parameters-from-data" class="nav-link" data-scroll-target="#estimating-the-parameters-from-data">Estimating the Parameters from Data</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#the-anomaly-detection-algorithm" id="toc-the-anomaly-detection-algorithm" class="nav-link" data-scroll-target="#the-anomaly-detection-algorithm">The Anomaly Detection Algorithm</a>
  <ul class="collapse">
  <li><a href="#the-full-algorithm" id="toc-the-full-algorithm" class="nav-link" data-scroll-target="#the-full-algorithm">The Full Algorithm</a></li>
  <li><a href="#a-worked-example" id="toc-a-worked-example" class="nav-link" data-scroll-target="#a-worked-example">A Worked Example</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#developing-and-evaluating-an-anomaly-detection-system" id="toc-developing-and-evaluating-an-anomaly-detection-system" class="nav-link" data-scroll-target="#developing-and-evaluating-an-anomaly-detection-system">Developing and Evaluating an Anomaly Detection System</a>
  <ul class="collapse">
  <li><a href="#example-split-for-the-aircraft-engines" id="toc-example-split-for-the-aircraft-engines" class="nav-link" data-scroll-target="#example-split-for-the-aircraft-engines">Example Split for the Aircraft Engines</a></li>
  <li><a href="#evaluating-on-the-cross-validation-or-test-set" id="toc-evaluating-on-the-cross-validation-or-test-set" class="nav-link" data-scroll-target="#evaluating-on-the-cross-validation-or-test-set">Evaluating on the Cross Validation or Test Set</a></li>
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#anomaly-detection-versus-supervised-learning" id="toc-anomaly-detection-versus-supervised-learning" class="nav-link" data-scroll-target="#anomaly-detection-versus-supervised-learning">Anomaly Detection versus Supervised Learning</a>
  <ul class="collapse">
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#choosing-what-features-to-use" id="toc-choosing-what-features-to-use" class="nav-link" data-scroll-target="#choosing-what-features-to-use">Choosing What Features to Use</a>
  <ul class="collapse">
  <li><a href="#make-the-features-more-gaussian" id="toc-make-the-features-more-gaussian" class="nav-link" data-scroll-target="#make-the-features-more-gaussian">Make the Features More Gaussian</a></li>
  <li><a href="#error-analysis-for-anomaly-detection" id="toc-error-analysis-for-anomaly-detection" class="nav-link" data-scroll-target="#error-analysis-for-anomaly-detection">Error Analysis for Anomaly Detection</a></li>
  <li><a href="#combining-features" id="toc-combining-features" class="nav-link" data-scroll-target="#combining-features">Combining Features</a></li>
  <li><a href="#review-questions-5" id="toc-review-questions-5" class="nav-link" data-scroll-target="#review-questions-5">Review Questions</a></li>
  </ul></li>
  <li><a href="#lab-anomaly-detection" id="toc-lab-anomaly-detection" class="nav-link" data-scroll-target="#lab-anomaly-detection">Lab: Anomaly Detection</a>
  <ul class="collapse">
  <li><a href="#problem-statement-and-dataset" id="toc-problem-statement-and-dataset" class="nav-link" data-scroll-target="#problem-statement-and-dataset">Problem Statement and Dataset</a></li>
  <li><a href="#exercise-1-estimating-the-gaussian-parameters" id="toc-exercise-1-estimating-the-gaussian-parameters" class="nav-link" data-scroll-target="#exercise-1-estimating-the-gaussian-parameters">Exercise 1: Estimating the Gaussian Parameters</a></li>
  <li><a href="#exercise-2-selecting-the-threshold-varepsilon" id="toc-exercise-2-selecting-the-threshold-varepsilon" class="nav-link" data-scroll-target="#exercise-2-selecting-the-threshold-varepsilon">Exercise 2: Selecting the Threshold <span class="math inline">\(\varepsilon\)</span></a></li>
  <li><a href="#a-harder-high-dimensional-dataset" id="toc-a-harder-high-dimensional-dataset" class="nav-link" data-scroll-target="#a-harder-high-dimensional-dataset">A Harder, High-Dimensional Dataset</a></li>
  <li><a href="#review-questions-6" id="toc-review-questions-6" class="nav-link" data-scroll-target="#review-questions-6">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Anomaly Detection</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">unsupervised-learning</div>
  </div>
  </div>

<div>
  <div class="description">
    Density estimation with Gaussians to flag unusual examples: the full algorithm, evaluating it with a small labeled set, when to prefer it over supervised learning, and how to tune features.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~176 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level and capped at 3 hours.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~8,900 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>After <a href="../../machine-learning/unsupervised-learning/clustering.html">clustering</a>, here is the second unsupervised learning algorithm of this course. An <strong>anomaly detection</strong> algorithm looks at an unlabeled dataset of <em>normal</em> events and thereby learns to detect, or to raise a red flag for, an unusual or <strong>anomalous</strong> event. This page builds the whole system: modeling the data with <strong>Gaussian distributions</strong>, the algorithm itself, how to evaluate and tune it with a small number of labeled anomalies, when to choose it over supervised learning, and how to choose good features for it.</p>
<section id="finding-unusual-events" class="level2">
<h2 class="anchored" data-anchor-id="finding-unusual-events">Finding Unusual Events</h2>
<p>Here is a motivating example. Some of Andrew Ng’s friends were working on using anomaly detection to detect possible problems with <strong>aircraft engines</strong> being manufactured. You really want a freshly made aircraft engine to be reliable, because an engine failure has very negative consequences, so it is worth checking whether an engine seems anomalous before it ships.</p>
<p>After an aircraft engine rolls off the assembly line, a number of features can be computed for it. Say feature <span class="math inline">\(x_1\)</span> measures the <strong>heat</strong> generated by the engine and feature <span class="math inline">\(x_2\)</span> measures the <strong>vibration intensity</strong> (real systems use additional features too, but two keeps the pictures simple). Aircraft engine manufacturers do not make many bad engines, so the easy data to collect is the features <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span> of <span class="math inline">\(m\)</span> engines that are probably just fine, normal engines rather than flawed ones.</p>
<p>The anomaly detection problem is: after the learning algorithm has seen these <span class="math inline">\(m\)</span> examples of how engines typically behave, if a brand new engine rolls off the assembly line with feature vector <span class="math inline">\(\vec{x}_{test}\)</span>, does it look similar to the ones manufactured before? Is it probably okay, or is there something really weird about it that should make us inspect it even more carefully before it gets installed on an airplane?</p>
<div id="851303f7" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-2-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>If the new engine’s heat and vibration land in the middle of the cloud of previous engines, it looks very similar to the others, probably nothing to worry about. But if its signature lands far away from anything seen before, this looks like an <strong>anomaly</strong>, better inspect it more carefully before installing it on an airplane.</p>
<section id="density-estimation" class="level3">
<h3 class="anchored" data-anchor-id="density-estimation">Density Estimation</h3>
<p>The most common way to carry out anomaly detection is a technique called <strong>density estimation</strong>. Given the training set of <span class="math inline">\(m\)</span> examples, the first thing to do is build a model for the <strong>probability of <span class="math inline">\(\vec{x}\)</span></strong>. The learning algorithm tries to figure out which values of the features have <strong>high probability</strong>, and which values are less likely, that is, have a lower chance of being seen in the dataset. In the engine data, points in a small ellipse in the middle of the cloud are quite likely, points in a bigger ellipse around it a little less likely, points in an even bigger one less likely still, and points outside all of them are quite unlikely.</p>
<div id="d0004d50" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-3-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Having learned the model <span class="math inline">\(p(\vec{x})\)</span>, when the new test example <span class="math inline">\(\vec{x}_{test}\)</span> arrives, compute its probability <span class="math inline">\(p(\vec{x}_{test})\)</span> and compare it against some small threshold number, called <strong>epsilon</strong> (<span class="math inline">\(\varepsilon\)</span>):</p>
<ul>
<li>If <span class="math inline">\(p(\vec{x}_{test}) &lt; \varepsilon\)</span>, the value of <span class="math inline">\(\vec{x}_{test}\)</span> is very unlikely relative to what has been seen before, so <strong>raise a flag</strong>, this could be an anomaly.</li>
<li>If <span class="math inline">\(p(\vec{x}_{test}) \geq \varepsilon\)</span>, the example looks similar to previous ones, it looks <strong>okay</strong>, not an anomaly.</li>
</ul>
<p>Examples near the middle of the data have high probability, so they pass, while an example far outside the cloud has very low probability, so it gets flagged. (How the regions of higher and lower probability actually get computed from the training set is exactly what the next sections build up.)</p>
</section>
<section id="applications-of-anomaly-detection" class="level3">
<h3 class="anchored" data-anchor-id="applications-of-anomaly-detection">Applications of Anomaly Detection</h3>
<p>Anomaly detection is one of those algorithms that is very widely used, even though people do not seem to talk about it that much.</p>
<ul>
<li><strong>Fraud detection.</strong> If you run a website, let <span class="math inline">\(\vec{x}^{(i)}\)</span> be the features of user <span class="math inline">\(i\)</span>’s activities, such as how often they log in, how many pages they visit, how many transactions they make, how many posts they write, or their typing speed (some users type implausibly many characters per second). Modeling <span class="math inline">\(p(\vec{x})\)</span> from data captures typical user behavior, and unusual users get a closer look. In the common workflow, an account is <em>not</em> automatically turned off just for looking anomalous; instead the security team takes a closer look, or extra checks kick in, such as asking the user to verify their identity with a phone number or pass a CAPTCHA to prove they are human. The same idea is used to spot <strong>financial fraud</strong>, an unusual pattern of purchases is well worth a careful review.</li>
<li><strong>Manufacturing.</strong> Beyond aircraft engines, many factories routinely use anomaly detection on whatever they just made, printed circuit boards, smartphones, motors, and more, to catch a unit that behaves strangely and deserves inspection before shipping to the customer.</li>
<li><strong>Monitoring computers in data centers.</strong> If <span class="math inline">\(\vec{x}^{(i)}\)</span> holds features of machine <span class="math inline">\(i\)</span>, such as memory use, number of disk accesses per second, CPU load, network traffic, or even ratios like CPU load to network traffic, then a computer behaving very differently from the others may have a failing disk or network card, or may even have been hacked into.</li>
</ul>
<p>Andrew Ng’s first commercial application of anomaly detection was helping a telco flag cell towers behaving unusually (so a technician could restore coverage sooner), and he has also used it for fraudulent financial transactions and for finding anomalous manufactured parts. It is a very useful tool to have in the tool chest, and to make it work, the first ingredient is a way to model <span class="math inline">\(p(\vec{x})\)</span>: the <strong>Gaussian distribution</strong>.</p>
</section>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. What kind of data does an anomaly detection algorithm learn from, and what question does it answer about a new example <span class="math inline">\(\vec{x}_{test}\)</span>?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It learns from an <em>unlabeled</em> dataset of <span class="math inline">\(m\)</span> examples that are assumed to be normal events, like measurements from engines that are almost all fine. For a new example it answers: does <span class="math inline">\(\vec{x}_{test}\)</span> look similar to the examples seen before, or is it unusual enough that it should be flagged for closer inspection?</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is density estimation, and how does the threshold <span class="math inline">\(\varepsilon\)</span> turn it into an anomaly detector?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Density estimation means building a model of <span class="math inline">\(p(\vec{x})\)</span>, which feature values have high probability of appearing in the dataset and which have low probability. The detector then computes <span class="math inline">\(p(\vec{x}_{test})\)</span> for a new example and flags it as an anomaly if <span class="math inline">\(p(\vec{x}_{test}) &lt; \varepsilon\)</span>, a small threshold; if <span class="math inline">\(p(\vec{x}_{test}) \geq \varepsilon\)</span>, the example is considered okay.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In fraud detection, why is an account usually not shut down automatically the moment it looks anomalous?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because a low <span class="math inline">\(p(\vec{x})\)</span> only means the behavior is <em>unusual</em>, not proven fraudulent. The standard workflow routes the account to a security team for a closer look, or triggers additional checks such as identity verification via a phone number or a CAPTCHA, so that legitimate but atypical users are not wrongly cut off.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of the following are applications of anomaly detection mentioned here? (Choose all that apply.)</strong></p>
<ol type="a">
<li><p>Flagging a freshly manufactured engine whose heat and vibration look unlike previous engines</p></li>
<li><p>Predicting tomorrow’s temperature from historical weather data</p></li>
<li><p>Spotting a data center machine whose behavior suggests a hardware failure or a hack</p></li>
<li><p>Finding fake accounts or unusual purchase patterns on a website</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a, c, and d.</strong> Predicting temperature (b) is a supervised regression problem with a known target to predict, not a matter of flagging unusual examples against a model of normal behavior.</p>
</div>
</div>
</div>
</section>
</section>
<section id="the-gaussian-distribution" class="level2">
<h2 class="anchored" data-anchor-id="the-gaussian-distribution">The Gaussian Distribution</h2>
<p>To apply anomaly detection, we need the <strong>Gaussian distribution</strong>, which is also called the <strong>normal distribution</strong>, the two names mean exactly the same thing, and the <strong>bell-shaped distribution</strong> refers to the same thing too. This is the very same distribution built up from scratch, with its own derivation of the formula below, in the <a href="../../math/probability/normal-distribution.html">probability course’s normal distribution page</a>, so the summary here is a refresher of that page applied to a new problem, rather than a first introduction.</p>
<p>Say <span class="math inline">\(x\)</span> is a number, and if <span class="math inline">\(x\)</span> is a random number (sometimes called a <strong>random variable</strong>), it can take on random values. If the probability of <span class="math inline">\(x\)</span> is given by a Gaussian distribution with <strong>mean</strong> parameter <span class="math inline">\(\mu\)</span> and <strong>variance</strong> <span class="math inline">\(\sigma^2\)</span>, then <span class="math inline">\(p(x)\)</span> looks like a bell-shaped curve. The center of the curve is at the mean <span class="math inline">\(\mu\)</span>, and the width of the curve is governed by <span class="math inline">\(\sigma\)</span>. Technically <span class="math inline">\(\sigma\)</span> is called the <strong>standard deviation</strong>, and its square <span class="math inline">\(\sigma^2\)</span> is called the <strong>variance</strong> of the distribution, exactly the <a href="../../math/probability/variance.html">variance</a> from the probability course. The formula for the curve is</p>
<p><span class="math display">\[
p(x) = \frac{1}{\sqrt{2\pi}\,\sigma} \, e^{-\frac{(x - \mu)^2}{2\sigma^2}}
\]</span></p>
<p>where <span class="math inline">\(\pi\)</span> is 3.14159… (about <span class="math inline">\(22/7\)</span>, the ratio of a circle’s circumference to its diameter). For any given values of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span>, plotting this function of <span class="math inline">\(x\)</span> gives the bell-shaped curve centered at <span class="math inline">\(\mu\)</span> with width determined by <span class="math inline">\(\sigma\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Same distribution, different notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>The probability course writes this as <span class="math inline">\(X \sim N(\mu, \sigma^2)\)</span> and calls the formula <span class="math inline">\(f(x)\)</span>, its <strong>probability density function</strong>. These machine learning notes write the same formula as <span class="math inline">\(p(x)\)</span> instead of <span class="math inline">\(f(x)\)</span>, purely a notational habit of this field, nothing about the distribution itself changes. Setting <span class="math inline">\(\mu = 0\)</span> and <span class="math inline">\(\sigma = 1\)</span> here gives the same <a href="../../math/probability/normal-distribution.html#standard-normal-distribution">standard normal distribution</a> covered there, and the same <a href="../../math/probability/normal-distribution.html#standardization">standardization</a> trick, <span class="math inline">\(z = \frac{x - \mu}{\sigma}\)</span>, reappears below as the term inside the exponent.</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>What does <span class="math inline">\(p(x)\)</span> really mean?
</div>
</div>
<div class="callout-body-container callout-body">
<p>One way to interpret it: if you drew, say, 100 numbers from this probability distribution and plotted a histogram of them, the histogram would look vaguely bell-shaped. The curve itself is what the histogram becomes with not 100 or a million but a practically <em>infinite</em> number of draws sorted into very fine histogram bins.</p>
</div>
</div>
<p>Here is how different choices of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> affect the curve.</p>
<div id="e730dfc5" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-4-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Probabilities always have to sum to one, so the <strong>area under the curve is always equal to 1</strong>. That is why when the Gaussian becomes skinnier (smaller <span class="math inline">\(\sigma\)</span>) it has to become taller, and when it becomes wider (larger <span class="math inline">\(\sigma\)</span>) it becomes shorter. Changing <span class="math inline">\(\mu\)</span> moves the center without changing the width.</p>
<section id="estimating-the-parameters-from-data" class="level3">
<h3 class="anchored" data-anchor-id="estimating-the-parameters-from-data">Estimating the Parameters from Data</h3>
<p>Applying this to anomaly detection means going in the other direction: given a dataset of <span class="math inline">\(m\)</span> examples where each <span class="math inline">\(x^{(i)}\)</span> is a number, find a good choice of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> so that the Gaussian looks like a plausible source of the data. The estimates are</p>
<p><span class="math display">\[
\mu = \frac{1}{m} \sum_{i=1}^{m} x^{(i)}
\qquad\qquad
\sigma^2 = \frac{1}{m} \sum_{i=1}^{m} \left(x^{(i)} - \mu\right)^2
\]</span></p>
<p>that is, <span class="math inline">\(\mu\)</span> is just the <strong>average</strong> of the training examples, and <span class="math inline">\(\sigma^2\)</span> is the average of the <strong>squared differences</strong> between the examples and that <span class="math inline">\(\mu\)</span>.</p>
<div id="f687604e" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-5-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Implementing those two formulas in code produces a Gaussian centered on the data with a matching spread, a distribution the 11 training examples plausibly might have been drawn from.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span><span class="math inline">\(\frac{1}{m}\)</span> or <span class="math inline">\(\frac{1}{m-1}\)</span>?
</div>
</div>
<div class="callout-body-container callout-body">
<p>These two formulas have a name: they are the <strong>maximum likelihood estimates</strong> (MLE) of <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span>, worked out from scratch, including exactly why the MLE for the mean always lands on the sample average, on the <a href="../../math/statistics/point-estimation.html#mle-gaussian-example">statistics course’s MLE page</a>. That page’s Gaussian example is this same <span class="math inline">\(\hat\mu = \frac{1}{m}\sum x^{(i)}\)</span> formula, just derived rather than stated.</p>
<p>The variance formula is where a subtlety hides. Dividing by <span class="math inline">\(m\)</span>, as done here, is what MLE actually gives, but it is a <strong>biased</strong> estimate of the true population variance, it tends to run a little low, because it measures spread around <span class="math inline">\(\mu\)</span>’s own estimate <span class="math inline">\(\hat\mu\)</span> rather than the true unknown <span class="math inline">\(\mu\)</span>. The <a href="../../math/statistics/sample-variance.html">sample variance page</a> derives that bias concretely and introduces <strong>Bessel’s correction</strong>, dividing by <span class="math inline">\(m - 1\)</span> instead, as the fix. So the two conventions are not arbitrary alternatives, <span class="math inline">\(\frac{1}{m}\)</span> is what MLE produces and what these notes (like the course) always use, while <span class="math inline">\(\frac{1}{m-1}\)</span> is the bias-corrected version some statistics classes prefer. As that page also notes, once <span class="math inline">\(m\)</span> is reasonably large the two barely differ, dividing by 1,000 versus 999 changes almost nothing, which is exactly why it makes very little difference in practice here. If none of that rings a bell, don’t worry about it.</p>
</div>
</div>
<p>You can probably guess what comes next. An example landing near the peak of the fitted curve has high <span class="math inline">\(p(x)\)</span>, okay, not really anomalous, a lot like the others. An example far in the tail has much lower <span class="math inline">\(p(x)\)</span>, the height of the curve there is small, so it is pretty unusual compared to the examples seen, and therefore more anomalous.</p>
<p>So far this handles <span class="math inline">\(x\)</span> being a single number, as if there were only one feature. Practical anomaly detection applications usually have many features, two, three, or a much larger number <span class="math inline">\(n\)</span>. The next section takes what a single Gaussian does and uses it to build the full algorithm that handles multiple features.</p>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. Write the formula for the Gaussian distribution and say what <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> control about the curve’s shape.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[p(x) = \frac{1}{\sqrt{2\pi}\,\sigma} \, e^{-\frac{(x-\mu)^2}{2\sigma^2}}\]</span> The mean <span class="math inline">\(\mu\)</span> sets the center of the bell-shaped curve, and the standard deviation <span class="math inline">\(\sigma\)</span> sets its width; <span class="math inline">\(\sigma^2\)</span> is called the variance. Changing <span class="math inline">\(\mu\)</span> slides the curve left or right without changing its shape.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does the Gaussian get taller when <span class="math inline">\(\sigma\)</span> shrinks?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because probabilities must sum to one, the area under the curve always equals 1. Squeezing the curve narrower removes area from the sides, so the peak has to rise to keep the total area the same; likewise a wider curve must be shorter.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Given training examples <span class="math inline">\(x^{(1)}, \dots, x^{(m)}\)</span>, how are <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma^2\)</span> estimated?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\mu = \frac{1}{m}\sum_{i=1}^{m} x^{(i)}\)</span>, the plain average of the examples, and <span class="math inline">\(\sigma^2 = \frac{1}{m}\sum_{i=1}^{m}(x^{(i)} - \mu)^2\)</span>, the average squared difference from that mean. These are the maximum likelihood estimates; dividing by <span class="math inline">\(m-1\)</span> instead of <span class="math inline">\(m\)</span> (as some statistics courses prefer) makes very little practical difference.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. After fitting a Gaussian to the data, how does the height of the curve at a point relate to whether that point is anomalous?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The curve’s height at <span class="math inline">\(x\)</span> is <span class="math inline">\(p(x)\)</span>. Near the center of the fitted Gaussian the height is large, so examples there are considered normal. Far out in the tails the height is small, meaning such values were rarely (if ever) seen in training, so an example there is much more likely to be flagged as an anomaly.</p>
</div>
</div>
</div>
</section>
</section>
<section id="the-anomaly-detection-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="the-anomaly-detection-algorithm">The Anomaly Detection Algorithm</h2>
<p>Now that the Gaussian handles a single number, here is the anomaly detection algorithm for a training set <span class="math inline">\(\vec{x}^{(1)}\)</span> through <span class="math inline">\(\vec{x}^{(m)}\)</span> where each example has <span class="math inline">\(n\)</span> features, so each <span class="math inline">\(\vec{x}^{(i)}\)</span> is a vector of <span class="math inline">\(n\)</span> numbers. In the aircraft engine example, heat and vibration give <span class="math inline">\(n = 2\)</span>, but for many practical applications <span class="math inline">\(n\)</span> can be dozens or even hundreds of features.</p>
<p>Given this training set, density estimation means building a model for <span class="math inline">\(p(\vec{x})\)</span>, the probability of any given feature vector. The model is the <strong>product of a Gaussian for each feature</strong>:</p>
<p><span class="math display">\[
p(\vec{x}) = p(x_1; \mu_1, \sigma_1^2) \times p(x_2; \mu_2, \sigma_2^2) \times p(x_3; \mu_3, \sigma_3^2) \times \cdots \times p(x_n; \mu_n, \sigma_n^2)
\]</span></p>
<p>Each feature <span class="math inline">\(x_j\)</span> gets its own two parameters, <span class="math inline">\(\mu_j\)</span> and <span class="math inline">\(\sigma_j^2\)</span>, the mean and variance of that feature. In the engine example, <span class="math inline">\(\mu_1, \sigma_1^2\)</span> describe the heat feature and <span class="math inline">\(\mu_2, \sigma_2^2\)</span> describe the totally different vibration feature.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Why multiply probabilities?
</div>
</div>
<div class="callout-body-container callout-body">
<p>Here is one example to build intuition. Suppose there is a <span class="math inline">\(\frac{1}{10}\)</span> chance that an engine runs unusually hot, and a <span class="math inline">\(\frac{1}{20}\)</span> chance that it vibrates really hard. What is the chance that it runs really hot <em>and</em> vibrates really hard? The model says <span class="math inline">\(\frac{1}{10} \times \frac{1}{20} = \frac{1}{200}\)</span>, it is really unlikely to get an engine with both problems at once.</p>
<p>Statistically minded readers may recognize that this multiplication assumes the features <span class="math inline">\(x_1, \dots, x_n\)</span> are <strong>statistically independent</strong>. It turns out the algorithm often works fine even when the features are <em>not</em> actually independent, and understanding statistical independence is not needed to use anomaly detection effectively.</p>
</div>
</div>
<p>A more compact way to write the product uses the symbol <span class="math inline">\(\prod\)</span>, which is a lot like the summation symbol <span class="math inline">\(\sum\)</span> except it means <strong>multiplying</strong> the terms rather than adding them:</p>
<p><span class="math display">\[
p(\vec{x}) = \prod_{j=1}^{n} p(x_j; \mu_j, \sigma_j^2)
\]</span></p>
<section id="the-full-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="the-full-algorithm">The Full Algorithm</h3>
<p>Putting it all together:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm summary
</div>
</div>
<div class="callout-body-container callout-body">
<ol type="1">
<li><strong>Choose features</strong> <span class="math inline">\(x_j\)</span> that you think might be indicative of anomalous examples.</li>
<li><strong>Fit the parameters</strong> <span class="math inline">\(\mu_1, \dots, \mu_n\)</span> and <span class="math inline">\(\sigma_1^2, \dots, \sigma_n^2\)</span>: <span class="math display">\[
\mu_j = \frac{1}{m} \sum_{i=1}^{m} x_j^{(i)}
\qquad\qquad
\sigma_j^2 = \frac{1}{m} \sum_{i=1}^{m} \left(x_j^{(i)} - \mu_j\right)^2
\]</span> (In a vectorized implementation, <span class="math inline">\(\vec{\mu} = \frac{1}{m}\sum_{i=1}^{m} \vec{x}^{(i)}\)</span> computes all the means at once.)</li>
<li><strong>Given a new example</strong> <span class="math inline">\(\vec{x}\)</span>, compute <span class="math display">\[
p(\vec{x}) = \prod_{j=1}^{n} p(x_j; \mu_j, \sigma_j^2) = \prod_{j=1}^{n} \frac{1}{\sqrt{2\pi}\,\sigma_j} \exp\!\left(-\frac{(x_j - \mu_j)^2}{2\sigma_j^2}\right)
\]</span></li>
<li><strong>Flag as an anomaly</strong> if <span class="math inline">\(p(\vec{x}) &lt; \varepsilon\)</span>.</li>
</ol>
</div>
</div>
<p>Note that fitting happens on the <em>unlabeled</em> training set, estimating these parameters is all the “training” there is.</p>
<p>The intuition behind what this algorithm does: it tends to flag an example as anomalous if <strong>one or more of its features is either very large or very small</strong> relative to what the training set showed. Each feature <span class="math inline">\(x_j\)</span> gets its own fitted Gaussian, and if even one feature of the new example lands way out in the tail of its Gaussian, that factor <span class="math inline">\(p(x_j; \mu_j, \sigma_j^2)\)</span> is very small, and one very small term in the product drags the whole product down, making <span class="math inline">\(p(\vec{x})\)</span> small. The algorithm is a systematic way of quantifying whether a new example <span class="math inline">\(\vec{x}\)</span> has any features that are unusually large or unusually small.</p>
</section>
<section id="a-worked-example" class="level3">
<h3 class="anchored" data-anchor-id="a-worked-example">A Worked Example</h3>
<p>Back to the engine dataset, where feature <span class="math inline">\(x_1\)</span> takes on a much larger range of values than feature <span class="math inline">\(x_2\)</span>. Fitting the parameters on this data gives approximately <span class="math inline">\(\mu_1 \approx 4.9\)</span> and <span class="math inline">\(\sigma_1 \approx 2.0\)</span> for the heat feature, and <span class="math inline">\(\mu_2 \approx 3.0\)</span> and <span class="math inline">\(\sigma_2 \approx 1.0\)</span> for the vibration feature, one wider Gaussian and one narrower one.</p>
<div id="5d254f84" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-6-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Multiplying <span class="math inline">\(p(x_1)\)</span> and <span class="math inline">\(p(x_2)\)</span> gives a 3D surface for <span class="math inline">\(p(\vec{x})\)</span>, where at any point the height of the surface is the product of the two Gaussian values for the corresponding <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>. The surface is high near the middle of the training data, values there are more likely, and falls toward zero far away, values out there have a much lower chance.</p>
<div id="14a31288" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-7-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Now pick the threshold <span class="math inline">\(\varepsilon = 0.02\)</span> and check two test examples. The first, <span class="math inline">\(\vec{x}_{test}^{(1)} = (4, 2)\)</span>, sits inside the cloud of training points, and computing the product of the two Gaussians gives <span class="math inline">\(p \approx 0.046\)</span>, much bigger than <span class="math inline">\(\varepsilon\)</span>, so the algorithm says this looks okay, not an anomaly. The second, <span class="math inline">\(\vec{x}_{test}^{(2)} = (8, 0.5)\)</span>, has an unusually low vibration value for its heat, and <span class="math inline">\(p\)</span> comes out around <span class="math inline">\(0.0009\)</span>, much smaller than <span class="math inline">\(\varepsilon\)</span>, so the algorithm flags it as a likely anomaly. Pretty much as you would hope: the point that looks normal passes, and the point much further from anything in the training set gets flagged.</p>
<p>That is the process of building an anomaly detection system. But how do you choose the parameter <span class="math inline">\(\varepsilon\)</span>? And how do you know whether the system is working well? That is next.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. Write the model <span class="math inline">\(p(\vec{x})\)</span> for an example with <span class="math inline">\(n\)</span> features. What assumption does the formula correspond to, and does the assumption have to hold?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[p(\vec{x}) = \prod_{j=1}^{n} p(x_j; \mu_j, \sigma_j^2)\]</span> the product of a separate Gaussian for each feature, each with its own mean <span class="math inline">\(\mu_j\)</span> and variance <span class="math inline">\(\sigma_j^2\)</span>. Multiplying the per-feature probabilities corresponds to assuming the features are statistically independent, but in practice the algorithm often works fine even when they are not.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. An engine has a <span class="math inline">\(\frac{1}{10}\)</span> chance of running unusually hot and a <span class="math inline">\(\frac{1}{20}\)</span> chance of vibrating really hard. Under the model, what is the chance of both at once, and what does this illustrate?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(\frac{1}{10} \times \frac{1}{20} = \frac{1}{200}\)</span>. It illustrates why the model multiplies per-feature probabilities: an example that is unusual in several features simultaneously is far less likely than one unusual in any single feature, so its <span class="math inline">\(p(\vec{x})\)</span> ends up very small.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does having just one feature far out in the tail of its Gaussian cause the whole example to be flagged?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because <span class="math inline">\(p(\vec{x})\)</span> is a product of the per-feature probabilities. A feature way out in the tail contributes a factor <span class="math inline">\(p(x_j; \mu_j, \sigma_j^2)\)</span> that is very close to zero, and multiplying anything by a near-zero factor makes the whole product near zero, so <span class="math inline">\(p(\vec{x}) &lt; \varepsilon\)</span> and the example is flagged. This is exactly the intended behavior: flag examples with any unusually large or unusually small feature.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the worked example with <span class="math inline">\(\varepsilon = 0.02\)</span>, the two test points had <span class="math inline">\(p \approx 0.046\)</span> and <span class="math inline">\(p \approx 0.0009\)</span>. What does the algorithm conclude for each?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The first, with <span class="math inline">\(0.046 \geq \varepsilon\)</span>, is judged okay, its features look similar to the training engines. The second, with <span class="math inline">\(0.0009 &lt; \varepsilon\)</span>, gets flagged as a likely anomaly, its combination of high heat and very low vibration is far from anything in the training set.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Anomaly detection flags a new input <span class="math inline">\(\vec{x}\)</span> as an anomaly if <span class="math inline">\(p(\vec{x}) &lt; \varepsilon\)</span>. If we reduce the value of <span class="math inline">\(\varepsilon\)</span>, what happens?</strong></p>
<ol type="a">
<li><p>The algorithm is more likely to classify new examples as an anomaly.</p></li>
<li><p>The algorithm is less likely to classify new examples as an anomaly.</p></li>
<li><p>The algorithm is more likely to classify some examples as an anomaly, and less likely to classify some examples as an anomaly. It depends on the example <span class="math inline">\(\vec{x}\)</span>.</p></li>
<li><p>The algorithm will automatically choose parameters <span class="math inline">\(\mu\)</span> and <span class="math inline">\(\sigma\)</span> to decrease <span class="math inline">\(p(\vec{x})\)</span> and compensate.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b.</strong> Shrinking <span class="math inline">\(\varepsilon\)</span> shrinks the region “<span class="math inline">\(p(\vec{x}) &lt; \varepsilon\)</span>” that counts as anomalous, a probability now has to be even smaller to clear the bar, so fewer examples qualify. Every example’s <span class="math inline">\(p(\vec{x})\)</span> stays exactly what it was, <span class="math inline">\(\varepsilon\)</span> is a threshold the algorithm compares against, not a parameter that reshapes the fitted Gaussians (ruling out d), and the direction of the effect, more anomalies flagged or fewer, is the same for every example, not example-dependent (ruling out c).</p>
</div>
</div>
</div>
<hr>
<p><strong>1. You fit Gaussians to 100 aircraft engines’ temperature and vibration measurements, and read off <span class="math inline">\(p(x_1) = 0.0738\)</span> for a new engine’s temperature (<span class="math inline">\(x_1 = 17.5\)</span>) and <span class="math inline">\(p(x_2) = 0.02288\)</span> for its vibration (<span class="math inline">\(x_2 = 48\)</span>). What is <span class="math inline">\(p(\vec{x})\)</span> for this engine?</strong></p>
<ol type="a">
<li><p><span class="math inline">\(0.0738 \times 0.02288 = 0.00169\)</span></p></li>
<li><p><span class="math inline">\(17.5 + 48 = 65.5\)</span></p></li>
<li><p><span class="math inline">\(0.0738 + 0.02288 = 0.0966\)</span></p></li>
<li><p><span class="math inline">\(17.5 \times 48 = 840\)</span></p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a.</strong> The model is <span class="math inline">\(p(\vec{x}) = p(x_1) \times p(x_2)\)</span>, the product of the two per-feature densities, so <span class="math inline">\(0.0738 \times 0.02288 \approx 0.00169\)</span>. The other options either operate on the raw feature values <span class="math inline">\(17.5\)</span> and <span class="math inline">\(48\)</span> instead of their probabilities, or add the two densities instead of multiplying them, neither of which is what the model computes.</p>
</div>
</div>
</div>
</section>
</section>
<section id="developing-and-evaluating-an-anomaly-detection-system" class="level2">
<h2 class="anchored" data-anchor-id="developing-and-evaluating-an-anomaly-detection-system">Developing and Evaluating an Anomaly Detection System</h2>
<p>Here are some practical tips for building one of these systems. A key idea: if you can <strong>evaluate the system as it is being developed</strong>, you can make decisions and improve it much more quickly. This is sometimes called <strong>real number evaluation</strong>: when you change the algorithm in some way, say change a feature or the value of <span class="math inline">\(\varepsilon\)</span>, having a way to compute a <em>number</em> that says whether it got better or worse makes it much easier to decide whether to keep the change. The same philosophy drove the <a href="../../machine-learning/advanced-learning-algorithms/model-evaluation-and-selection.html">model selection procedure with training, cross validation, and test sets</a> in the supervised setting.</p>
<p>For anomaly detection this requires a small twist. Even though the discussion so far has been about unlabeled data, assume there is a small amount of <strong>labeled data</strong> available: a small number of previously observed anomalies. Maybe after making aircraft engines for a few years, a few anomalous engines have turned up. Label known anomalies <span class="math inline">\(y = 1\)</span> and examples believed normal <span class="math inline">\(y = 0\)</span>. Then:</p>
<ul>
<li><strong>Training set</strong> <span class="math inline">\(\vec{x}^{(1)}, \dots, \vec{x}^{(m)}\)</span>: still unlabeled, all examples <em>assumed</em> normal (<span class="math inline">\(y = 0\)</span>). If a couple of anomalous examples accidentally slip in, the algorithm will still usually do okay.</li>
<li><strong>Cross validation set</strong> and <strong>test set</strong>: each holds mostly normal examples along with a <strong>few known anomalies</strong>, that is, lots of <span class="math inline">\(y = 0\)</span> and a few <span class="math inline">\(y = 1\)</span>. (Again, a mislabeled anomaly or two hiding among the <span class="math inline">\(y=0\)</span> examples is tolerable in practice.)</li>
</ul>
<section id="example-split-for-the-aircraft-engines" class="level3">
<h3 class="anchored" data-anchor-id="example-split-for-the-aircraft-engines">Example Split for the Aircraft Engines</h3>
<p>Say the factory has collected data from <strong>10,000 good engines</strong> over the years, plus <strong>20 flawed, anomalous engines</strong>. That tiny number of positives is typical; anomaly detection applications commonly work with anywhere from 2 to 50 known anomalies. One reasonable split:</p>
<ul>
<li><strong>Training set:</strong> 6,000 good engines. Fit the Gaussians, that is, compute all the <span class="math inline">\(\mu_j, \sigma_j^2\)</span>, from these.</li>
<li><strong>Cross validation set:</strong> 2,000 good engines + 10 known anomalies. Check how many of the anomalies the algorithm correctly flags, and how many good engines it wrongly flags, and use that to <strong>tune <span class="math inline">\(\varepsilon\)</span></strong> (and to add, subtract, or tune features <span class="math inline">\(x_j\)</span>).</li>
<li><strong>Test set:</strong> 2,000 good engines + 10 known anomalies. After all tuning is done, evaluate here for an honest measure of how the tuned system performs.</li>
</ul>
<p>Notice that this is still primarily an <strong>unsupervised</strong> learning algorithm: the training set has no labels (or all labels assumed <span class="math inline">\(y = 0\)</span>), and fitting the Gaussians uses only that unlabeled data. The handful of labeled anomalies is used <em>only</em> for cross validation and testing, and it turns out to be very helpful for tuning.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>The no-test-set alternative
</div>
</div>
<div class="callout-body-container callout-body">
<p>When the number of known anomalies is very small, say only two flawed engines ever observed, a common alternative is to skip the test set: train on 6,000 good engines, and put the remaining 4,000 good engines plus <em>all</em> the anomalies into the cross validation set, tuning <span class="math inline">\(\varepsilon\)</span> and the features against that. The downside is that with no test set, there is no fair way to tell how the system will do on future examples, and a higher risk that the choices of <span class="math inline">\(\varepsilon\)</span> and features have <strong>overfit</strong> the cross validation set, so real-world performance may disappoint. But when the data is this scarce, it may be the best available option, and it is done quite often.</p>
</div>
</div>
</section>
<section id="evaluating-on-the-cross-validation-or-test-set" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-on-the-cross-validation-or-test-set">Evaluating on the Cross Validation or Test Set</h3>
<p>Concretely, first fit the model <span class="math inline">\(p(\vec{x})\)</span> on the training set. Then, for each cross validation or test example <span class="math inline">\(\vec{x}\)</span>, predict a label and compare it against the true label, and use that comparison to tune <span class="math inline">\(\varepsilon\)</span>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm evaluation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Fit model <span class="math inline">\(p(\vec{x})\)</span> on training set <span class="math inline">\(\vec{x}^{(1)}, \vec{x}^{(2)}, \dots, \vec{x}^{(m)}\)</span>.</p>
<p>On a cross validation/test example <span class="math inline">\(\vec{x}\)</span>, predict</p>
<p><span class="math display">\[
y = \begin{cases} 1 &amp; \text{if } p(\vec{x}) &lt; \varepsilon \quad (\text{anomaly}) \\ 0 &amp; \text{if } p(\vec{x}) \geq \varepsilon \quad (\text{normal}) \end{cases}
\]</span></p>
<p>Possible evaluation metrics:</p>
<ul>
<li>True positive, false positive, false negative, true negative</li>
<li>Precision/Recall</li>
<li>F₁-score</li>
</ul>
<p>Use the cross validation set to choose the parameter <span class="math inline">\(\varepsilon\)</span>.</p>
</div>
</div>
<p>Using counts and rates instead of plain accuracy matters here because these datasets are highly <strong>skewed</strong>, maybe 10 positive examples against 2,000 negative ones (matching the 10-anomaly, 2,000-good-engine cross validation set from the split above), so plain classification accuracy is misleading, always predicting “normal” would score 99.5% and look great while catching zero anomalies. The <a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html">section on skewed datasets</a> covered the better tools for exactly this situation: true/false positive and negative counts, <strong>precision</strong>, <strong>recall</strong>, and the <strong>F₁ score</strong>. Those metrics apply directly here to measure how well the algorithm finds the small handful of anomalies amid the much larger set of normal examples, and trying a few different values of <span class="math inline">\(\varepsilon\)</span> and picking whichever gives the best F₁ score (or whichever trade-off of precision and recall fits the application) on the cross validation set is exactly how <span class="math inline">\(\varepsilon\)</span> gets tuned in practice. Even without computing the formal metrics, the essential intuition is to look at how many anomalies the algorithm catches and how many good engines it wrongly flags, and use that trade-off to pick a good <span class="math inline">\(\varepsilon\)</span>.</p>
<p>This does raise a question. If a few labeled examples are available anyway, why keep using an unsupervised algorithm at all, why not use those labels with a supervised learning algorithm instead? The comparison is next.</p>
</section>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. What is real number evaluation, and why does it speed up development?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It means having a way to compute a single number that measures how well the current system performs, so that after any change, a tweaked feature, a different <span class="math inline">\(\varepsilon\)</span>, you can immediately see whether the change made things better or worse. Decisions about keeping or reverting changes then become quick comparisons instead of guesswork.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the 10,000-good / 20-flawed engine example, describe the recommended three-way split and what each subset is used for.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Training set: 6,000 good engines, used to fit the Gaussian parameters <span class="math inline">\(\mu_j, \sigma_j^2\)</span> (no labels needed). Cross validation set: 2,000 good + 10 known anomalies, used to tune <span class="math inline">\(\varepsilon\)</span> and the choice of features by checking which anomalies get flagged and how many good engines get falsely flagged. Test set: the other 2,000 good + 10 anomalies, used once at the end for a fair estimate of real-world performance.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is the system still considered primarily unsupervised even though labeled anomalies appear in the evaluation sets?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the actual learning, fitting <span class="math inline">\(p(\vec{x})\)</span> by estimating the Gaussian parameters, happens on the unlabeled training set alone, where every example is just assumed normal. The labeled anomalies never enter the model fitting; they are used only to <em>evaluate</em> the model on the cross validation and test sets and to tune <span class="math inline">\(\varepsilon\)</span> and the features.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. When is it reasonable to drop the test set entirely, and what risk does that create?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When there are extremely few known anomalies (say, two), too few to populate both a cross validation and a test set, so all of them go into a single cross validation set used for tuning. The risk is overfitting the tuning decisions (<span class="math inline">\(\varepsilon\)</span>, feature choices) to that one set, with no fair way left to estimate performance on future data, so real-world results may be worse than expected.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Say you have 5,000 examples of normal airplane engines, and 15 examples of anomalous engines. How would you use the 15 examples of anomalous engines to evaluate your anomaly detection algorithm?</strong></p>
<ol type="a">
<li><p>You cannot evaluate an anomaly detection algorithm because it is an unsupervised learning algorithm.</p></li>
<li><p>Put the data of anomalous engines (together with some normal engines) in the cross-validation and/or test sets to measure if the learned model can correctly detect anomalous engines.</p></li>
<li><p>Because you have data of both normal and anomalous engines, don’t use anomaly detection. Use supervised learning instead.</p></li>
<li><p>Use it during training by fitting one Gaussian model to the normal engines, and a different Gaussian model to the anomalous engines.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b.</strong> This is exactly the aircraft-engine split worked through above: the bulk of the normal engines go into the unlabeled training set to fit <span class="math inline">\(p(\vec{x})\)</span>, while the small number of known anomalies, together with a slice of normal engines, go into the cross validation and test sets, where the labels get used to tune <span class="math inline">\(\varepsilon\)</span> and to measure how well the algorithm actually catches anomalies. (a) is wrong because unsupervised training does not preclude a labeled evaluation step; (c) throws away good data, 15 positives is exactly the small-count regime where anomaly detection is favored <a href="#anomaly-detection-versus-supervised-learning">over supervised learning</a>; and (d) misunderstands the algorithm, only <em>one</em> Gaussian model, fit to the normal data, is ever used, anomalies are never fitted to a distribution of their own.</p>
</div>
</div>
</div>
</section>
</section>
<section id="anomaly-detection-versus-supervised-learning" class="level2">
<h2 class="anchored" data-anchor-id="anomaly-detection-versus-supervised-learning">Anomaly Detection versus Supervised Learning</h2>
<p>With a few positive examples (<span class="math inline">\(y = 1\)</span>) and a large number of negative examples (<span class="math inline">\(y = 0\)</span>) in hand, when should you use anomaly detection, and when supervised learning? The decision is actually quite subtle in some applications, but there are useful rules of thumb.</p>
<p><strong>Anomaly detection</strong> is typically the more appropriate choice when there is a <strong>very small number of positive examples</strong>, 0 to 20 is not uncommon, alongside a relatively large number of negative examples. Recall that the parameters of <span class="math inline">\(p(\vec{x})\)</span> are learned <em>only from the negative examples</em>, and the precious positives are spent on the cross validation and test sets for tuning and evaluation. <strong>Supervised learning</strong>, in contrast, becomes more applicable with a larger number of both positive and negative examples.</p>
<p>But the deeper difference is in what each approach <em>assumes about future positives</em>:</p>
<ul>
<li><strong>Anomaly detection</strong> fits a model of what <em>normal</em> examples look like and flags anything that deviates a lot from normal. That works even if tomorrow brings a <strong>brand new way</strong> for something to go wrong that looks nothing like any anomaly seen so far. When there are many different types of anomalies, 20 positive examples cannot cover all the ways an aircraft engine could fail, this is the right mindset.</li>
<li><strong>Supervised learning</strong> looks at the positive examples it has and tries to decide whether a future example is <strong>similar to those</strong>. It assumes future positives will resemble the ones in the training set, and with enough positives, that assumption pays off.</li>
</ul>
<p>A pair of contrasting examples makes it concrete. <strong>Financial fraud</strong> keeps evolving, new and unique forms of fraud appear every few months, so anomaly detection is often used to catch anything different from transactions seen in the past. <strong>Email spam</strong>, on the other hand, stays thematically similar over the years, spam keeps trying to sell similar things and send people to similar websites, so the spam arriving in the next few days looks a lot like past spam, and supervised learning works well.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Anomaly detection</th>
<th>Supervised learning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Positive examples</strong></td>
<td>Very small number (often 0–20), used only for cross validation and testing</td>
<td>Large enough number for the algorithm to learn what positives look like</td>
</tr>
<tr class="even">
<td><strong>Assumption about future positives</strong></td>
<td>May look nothing like any positive seen so far</td>
<td>Likely to be similar to positives in the training set</td>
</tr>
<tr class="odd">
<td><strong>Typical applications</strong></td>
<td>New, previously unseen forms of fraud; unseen manufacturing defects; monitoring machines in a data center; security applications</td>
<td>Email spam; known, recurring defects (e.g.&nbsp;scratched phone cases); weather prediction; disease diagnosis from symptoms</td>
</tr>
</tbody>
</table>
<p>A few notes on the applications row. Manufacturing uses <em>both</em>: anomaly detection to find <strong>new, previously unseen defects</strong> (a brand new failure mode in an aircraft engine), and supervised learning to find <strong>known, previously seen defects</strong>, for instance a smartphone maker whose case-making machine occasionally scratches covers can collect plenty of labeled scratched-phone examples and train a supervised system to spot more scratches. Security-related applications lean heavily toward anomaly detection, because hackers keep finding brand new ways into systems, a hacked machine in a data center can behave differently in a way never seen before. Weather prediction is supervised because the same handful of output labels (sunny, rainy, snow) recur over and over, and likewise diagnosing a <em>known</em> disease from patient symptoms is a supervised task.</p>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Give the rule of thumb, based on counts of positive and negative examples, for choosing between the two approaches.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>With a very small number of positive examples, often between 0 and 20, and a comparatively large number of negatives, lean toward anomaly detection, which learns <span class="math inline">\(p(\vec{x})\)</span> from the negatives and reserves the positives for tuning and evaluation. With a large number of both positives and negatives, supervised learning becomes the more applicable choice.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Beyond the counts, what is the key conceptual difference in how the two approaches treat future positive examples?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Anomaly detection models what normal looks like and flags large deviations, so it can catch failure modes that have never been seen before. Supervised learning learns what past positives look like and asks whether a new example resembles them, so it excels when future positives repeat the patterns of past ones and struggles with genuinely novel ones.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is fraud detection commonly handled with anomaly detection while email spam is handled with supervised learning?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>New and unique forms of financial fraud keep appearing every few months, so a system must flag behavior unlike anything seen before, which is what anomaly detection does. Spam, by contrast, remains similar over the years, selling similar things and linking to similar sites, so tomorrow’s spam resembles yesterday’s labeled spam and a supervised classifier trained on past examples works well.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A smartphone factory wants to catch (i) scratched cases, a defect it sees every week, and (ii) whatever brand-new malfunction might appear next. Which tool fits each task?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-30-contents" aria-controls="callout-30" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-30" class="callout-30-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ol type="i">
<li>Supervised learning: scratches recur constantly, so plenty of labeled positive examples exist and future scratches look like past ones. (ii) Anomaly detection: a never-before-seen malfunction has no training examples by definition, so the system must instead notice that a unit deviates from normal behavior.</li>
</ol>
</div>
</div>
</div>
<hr>
<p><strong>1. You are building a system to detect if computers in a data center are malfunctioning. You have 10,000 data points of computers functioning well, and no data from computers malfunctioning. What type of algorithm should you use?</strong></p>
<ol type="a">
<li><p>Anomaly detection</p></li>
<li><p>Supervised learning</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a. Anomaly detection.</strong> With zero examples of a malfunctioning computer, there is nothing for a supervised algorithm to learn positives from. Anomaly detection fits <span class="math inline">\(p(\vec{x})\)</span> to the 10,000 normal machines alone and flags anything that deviates enough from that, exactly the very-small-positive-count regime (here, zero) where anomaly detection is the appropriate tool.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Same setup, but now you have 10,000 data points of computers functioning well, <em>and</em> 10,000 data points of computers malfunctioning. What type of algorithm should you use?</strong></p>
<ol type="a">
<li><p>Anomaly detection</p></li>
<li><p>Supervised learning</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b. Supervised learning.</strong> Now there is a large, roughly balanced set of both classes, plenty of malfunctioning examples for a supervised algorithm to learn what a malfunction actually looks like directly, rather than only having examples of normal behavior to model. This is the large-positive-count regime described above, where supervised learning becomes the more applicable choice.</p>
</div>
</div>
</div>
</section>
</section>
<section id="choosing-what-features-to-use" class="level2">
<h2 class="anchored" data-anchor-id="choosing-what-features-to-use">Choosing What Features to Use</h2>
<p>When building an anomaly detection algorithm, choosing a good set of features turns out to be <strong>really important</strong>, more so than in supervised learning. In supervised learning, imperfect features are often tolerable: the labels <span class="math inline">\(y\)</span> give the algorithm enough signal to figure out which features to ignore or how to rescale them. Anomaly detection learns from <em>unlabeled</em> data only, so it has no such help, features that don’t behave make it genuinely harder for the algorithm. Two practices help a lot: making the features more Gaussian, and error analysis.</p>
<section id="make-the-features-more-gaussian" class="level3">
<h3 class="anchored" data-anchor-id="make-the-features-more-gaussian">Make the Features More Gaussian</h3>
<p>Since each feature gets modeled by a Gaussian, the model fits best when the feature’s values actually look roughly Gaussian. So plot a <strong>histogram</strong> of each feature (<code>plt.hist(x, bins=50)</code>). If it looks like a symmetric bell, good, keep the feature as is. If it looks strongly skewed, not at all bell-shaped, consider <strong>transforming</strong> the feature into something more Gaussian. Common transformations:</p>
<ul>
<li><span class="math inline">\(\log(x)\)</span>, or <span class="math inline">\(\log(x + c)\)</span> for some constant <span class="math inline">\(c\)</span></li>
<li><span class="math inline">\(\sqrt{x}\)</span>, which is <span class="math inline">\(x^{0.5}\)</span>, or other powers like <span class="math inline">\(x^{0.4}\)</span> or <span class="math inline">\(x^{1/3}\)</span></li>
</ul>
<div id="8b601e93" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-8-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This exploration is fast to do in a Jupyter notebook: plot the histogram, try an exponent, look, adjust, in the demo above, <span class="math inline">\(x^{0.5}\)</span> helps and <span class="math inline">\(x^{0.4}\)</span> looks pretty Gaussian, so you would set <code>x = x**0.4</code> and use that transformed value in training. Two practical details from doing this live:</p>
<ul>
<li><span class="math inline">\(\log(0)\)</span> is <strong>negative infinity</strong>, so if a feature has zero values, <code>np.log(x)</code> errors; the common trick is <span class="math inline">\(\log(x + c)\)</span> with a tiny <span class="math inline">\(c\)</span> like 0.001, and <span class="math inline">\(c\)</span> itself is worth playing with, a larger <span class="math inline">\(c\)</span> transforms the distribution less.</li>
<li>The machine learning literature has ways to automatically measure how close a distribution is to Gaussian, but in practice trying a few values by eye and picking what looks right works well for all practical purposes.</li>
</ul>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Transform every set the same way
</div>
</div>
<div class="callout-body-container callout-body">
<p>Whatever transformation gets applied to the training set must also be applied to the <strong>cross validation and test set</strong> data. Otherwise the tuned threshold and parameters are being evaluated against differently scaled features.</p>
</div>
</div>
</section>
<section id="error-analysis-for-anomaly-detection" class="level3">
<h3 class="anchored" data-anchor-id="error-analysis-for-anomaly-detection">Error Analysis for Anomaly Detection</h3>
<p>If the trained algorithm does not work well on the cross validation set, look at <em>where</em> it makes mistakes and let that inspire improvements. Recall the goal: <span class="math inline">\(p(\vec{x})\)</span> <strong>large</strong> (at least <span class="math inline">\(\varepsilon\)</span>) for normal examples and <strong>small</strong> (below <span class="math inline">\(\varepsilon\)</span>) for anomalies. The <strong>most common problem</strong> in practice is that <span class="math inline">\(p(\vec{x})\)</span> is comparable for both, typically, large for an anomaly that happens to look similar to the normal examples in the features it has.</p>
<p>Concretely, suppose a fraud-detection system uses <span class="math inline">\(x_1\)</span> = number of transactions a user makes. A fraudulent user in the cross validation set might make a perfectly typical number of transactions, so their <span class="math inline">\(p(x_1)\)</span> is high and the algorithm fails to flag them. What to do: <strong>look at that example</strong> and try to figure out what made a person notice it is an anomaly, and if some <strong>new feature</strong> <span class="math inline">\(x_2\)</span> can capture that, say the account’s typing speed, which for this user is insanely fast, adding the feature lets the algorithm spot it.</p>
<div id="cefcd507" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-9-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>On the left, the anomalous user’s <span class="math inline">\(x_1\)</span> value sits comfortably under the fitted Gaussian, so <span class="math inline">\(p(x_1)\)</span> is high and nothing gets flagged. On the right, the new feature reveals a wildly anomalous typing speed, and with both features the fitted model assigns this point a very low probability, easy to detect. The development loop, then: <strong>train the model, see which cross validation anomalies it fails to detect, examine those examples, and let them inspire new features</strong> on which the anomaly takes unusually large or small values.</p>
</section>
<section id="combining-features" class="level3">
<h3 class="anchored" data-anchor-id="combining-features">Combining Features</h3>
<p>It is also not unusual to create new features by <strong>combining old ones</strong>. Take the data center monitoring example, starting with features like <span class="math inline">\(x_1\)</span> = memory use, <span class="math inline">\(x_2\)</span> = disk accesses per second, <span class="math inline">\(x_3\)</span> = CPU load, and <span class="math inline">\(x_4\)</span> = network traffic volume. Suppose one machine behaves very strangely, yet neither its CPU load nor its network traffic is unusual on its own, what is unusual is a really <strong>high CPU load combined with a very low network traffic volume</strong>. For a data center that streams videos, machines normally show high CPU with high traffic or low CPU with low traffic, but not that combination. Creating</p>
<p><span class="math display">\[
x_5 = \frac{\text{CPU load}}{\text{network traffic}}
\]</span></p>
<p>gives a feature that takes an unusually large value on exactly that machine, so the algorithm can flag future examples like it. Variations like <span class="math inline">\(x_6 = \frac{(\text{CPU load})^2}{\text{network traffic}}\)</span> are also fair game; play with different choices until <span class="math inline">\(p(\vec{x})\)</span> stays large for the normal examples but becomes small for the anomalies in the cross validation set.</p>
<p>That completes anomaly detection, and with clustering, both unsupervised learning topics of the course: algorithms that many companies use today in important commercial applications, learned from unlabeled data. The next part of these notes turns to <strong>recommender systems</strong>, the algorithms behind websites that recommend products or movies. They are among the most commercially important algorithms in machine learning, moving enormous value around while getting talked about surprisingly little.</p>
</section>
<section id="review-questions-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-5">Review Questions</h3>
<p><strong>1. Why does the choice of features matter more for anomaly detection than for supervised learning?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Supervised learning has labels <span class="math inline">\(y\)</span>, a supervisory signal that lets the algorithm learn to ignore irrelevant features or rescale them to best advantage. Anomaly detection learns from unlabeled data only, so it cannot figure out on its own which features to discount, and a poorly behaved feature directly distorts the model <span class="math inline">\(p(\vec{x})\)</span>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A feature’s histogram is heavily skewed with a long right tail. Name three transformations worth trying, and one rule that must be respected afterward.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Try <span class="math inline">\(\log(x + c)\)</span> for some constant <span class="math inline">\(c\)</span> (with <span class="math inline">\(c\)</span> small like 0.001 if <span class="math inline">\(x\)</span> can be zero, since <span class="math inline">\(\log(0)\)</span> is undefined), <span class="math inline">\(\sqrt{x} = x^{0.5}\)</span>, or other fractional powers such as <span class="math inline">\(x^{0.4}\)</span> or <span class="math inline">\(x^{1/3}\)</span>, adjusting the exponent or <span class="math inline">\(c\)</span> until the histogram looks roughly bell-shaped. The rule: whatever transformation is applied to the training set must be applied identically to the cross validation and test sets.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is the most common failure mode found during error analysis, and what is the standard remedy?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-36-contents" aria-controls="callout-36" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-36" class="callout-36-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The most common problem is that <span class="math inline">\(p(\vec{x})\)</span> is large for an anomaly, comparable to the normal examples, because the anomaly looks typical on the existing features. The remedy is to examine that missed anomaly, identify what actually makes it unusual, and add a new feature that captures it, like typing speed for a fraudster whose transaction count looked normal, so the example takes an unusually large or small value on the new feature.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the data center example, why does the ratio <span class="math inline">\(x_5 = \text{CPU load} / \text{network traffic}\)</span> catch a machine that neither feature catches alone?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-37-contents" aria-controls="callout-37" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-37" class="callout-37-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The suspicious machine’s CPU load and network traffic are each individually within normal range, so their separate Gaussians assign them healthy probabilities. What is anomalous is the <em>combination</em>, high CPU while serving almost no traffic, and the ratio encodes that combination as a single number that becomes unusually large exactly in that case, letting the per-feature Gaussian model flag it.</p>
</div>
</div>
</div>
</section>
</section>
<section id="lab-anomaly-detection" class="level2">
<h2 class="anchored" data-anchor-id="lab-anomaly-detection">Lab: Anomaly Detection</h2>
<p>This lab implements the anomaly detection algorithm and applies it to detect failing servers on a network. It starts with a small, two-feature dataset to build intuition and check the fit visually, then reruns the exact same code on a harder, eleven-feature dataset where a scatter plot is no longer possible. The two graded functions are exactly the two steps of the <a href="#the-anomaly-detection-algorithm">algorithm</a>, fitting the Gaussian parameters and choosing <span class="math inline">\(\varepsilon\)</span>.</p>
<div id="f08c8733" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="problem-statement-and-dataset" class="level3">
<h3 class="anchored" data-anchor-id="problem-statement-and-dataset">Problem Statement and Dataset</h3>
<p>The dataset holds two features for each compute server, <strong>throughput</strong> (mb/s) and <strong>latency</strong> (ms) of its response. Training data <span class="math inline">\(X_{train}\)</span> is unlabeled, mostly normal servers with a handful of anomalies mixed in, exactly the setup the <a href="#the-anomaly-detection-algorithm">main algorithm</a> assumes. Alongside it are a small cross validation set <span class="math inline">\(X_{val}\)</span> and its labels <span class="math inline">\(y_{val}\)</span>, where <span class="math inline">\(y = 1\)</span> marks a known anomalous server, used for choosing <span class="math inline">\(\varepsilon\)</span> exactly as the <a href="#developing-and-evaluating-an-anomaly-detection-system">evaluation section</a> described.</p>
<div id="cce7ae89" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>X_train <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/X_part1.npy"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>X_val <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/X_val_part1.npy"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>y_val <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/y_val_part1.npy"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First 5 elements of X_train:</span><span class="ch">\n</span><span class="st">"</span>, X_train[:<span class="dv">5</span>])</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First 5 elements of X_val:</span><span class="ch">\n</span><span class="st">"</span>, X_val[:<span class="dv">5</span>])</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First 5 elements of y_val:"</span>, y_val[:<span class="dv">5</span>])</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapes:"</span>, X_train.shape, X_val.shape, y_val.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>First 5 elements of X_train:
 [[13.04681517 14.74115241]
 [13.40852019 13.7632696 ]
 [14.19591481 15.85318113]
 [14.91470077 16.17425987]
 [13.57669961 14.04284944]]
First 5 elements of X_val:
 [[15.79025979 14.9210243 ]
 [13.63961877 15.32995521]
 [14.86589943 16.47386514]
 [13.58467605 13.98930611]
 [13.46404167 15.63533011]]
First 5 elements of y_val: [0 0 0 0 0]
Shapes: (307, 2) (307, 2) (307,)</code></pre>
</div>
</div>
<p>With only two features, the training set can be viewed directly as a scatter plot before doing anything else.</p>
<div id="dd77581a" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>plt.scatter(X_train[:, <span class="dv">0</span>], X_train[:, <span class="dv">1</span>], marker<span class="op">=</span><span class="st">"x"</span>, s<span class="op">=</span><span class="dv">32</span>, color<span class="op">=</span><span class="st">"#0096FF"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"the first dataset"</span>, fontsize<span class="op">=</span><span class="fl">10.5</span>, color<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"latency (ms)"</span>)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"throughput (mb/s)"</span>)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-12-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most points cluster in one dense region, with a few points scattered further out, plausible anomaly candidates once a model of <span class="math inline">\(p(\vec{x})\)</span> is in hand.</p>
</section>
<section id="exercise-1-estimating-the-gaussian-parameters" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1-estimating-the-gaussian-parameters">Exercise 1: Estimating the Gaussian Parameters</h3>
<p>The first graded function, <code>estimate_gaussian</code>, computes <code>mu</code> and <code>var</code>, the mean and variance of every feature in <code>X</code>, exactly the <a href="#estimating-the-parameters-from-data">two formulas</a> already derived,</p>
<p><span class="math display">\[
\mu_i = \frac{1}{m}\sum_{j=1}^{m} x_i^{(j)} \qquad\qquad \sigma_i^2 = \frac{1}{m}\sum_{j=1}^{m}\left(x_i^{(j)} - \mu_i\right)^2
\]</span></p>
<p>applied here to each column <span class="math inline">\(i\)</span> of the data matrix <code>X</code> at once with <code>axis=0</code>, instead of one feature at a time.</p>
<div id="00b6a174" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> estimate_gaussian(X):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Calculates mean and variance of all features</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">    in the dataset</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray): (m, n) Data matrix</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">        mu (ndarray): (n,) Mean of all features</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">        var (ndarray): (n,) Variance of all features</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    m, n <span class="op">=</span> X.shape</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    mu <span class="op">=</span> np.mean(X, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    var <span class="op">=</span> np.mean((X <span class="op">-</span> mu) <span class="op">**</span> <span class="dv">2</span>, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> mu, var</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="2cf0e902" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>mu, var <span class="op">=</span> estimate_gaussian(X_train)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Mean of each feature:"</span>, mu)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variance of each feature:"</span>, var)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean of each feature: [14.11222578 14.99771051]
Variance of each feature: [1.83263141 1.70974533]</code></pre>
</div>
</div>
<p>The expected output is a mean of <code>[14.11222578 14.99771051]</code> and a variance of <code>[1.83263141 1.70974533]</code>, and that is exactly what comes out.</p>
<p>With <code>mu</code> and <code>var</code> in hand, <code>multivariate_gaussian</code> below computes <span class="math inline">\(p(\vec{x})\)</span> for every example at once. It is written in a more general matrix form that also supports <em>correlated</em> features (an off-diagonal covariance matrix), useful for datasets beyond this lab, but when <code>var</code> is a plain vector, as it is here, it gets turned into a diagonal covariance matrix on the first line, which makes it compute exactly the same product of independent per-feature Gaussians, <span class="math inline">\(p(\vec{x}) = \prod_{j=1}^{n} p(x_j; \mu_j, \sigma_j^2)\)</span>, seen <a href="#the-anomaly-detection-algorithm">earlier</a>, just packaged as a single matrix expression instead of a loop.</p>
<div id="bcbafd1e" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> multivariate_gaussian(X, mu, var):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Computes the probability density function of the examples X</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co">    under the multivariate Gaussian distribution with parameters</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">    mu and var. If var is a matrix, it is treated as the covariance</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co">    matrix. If var is a vector, it is treated as the variances of</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co">    the features (a diagonal covariance matrix).</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> <span class="bu">len</span>(mu)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> var.ndim <span class="op">==</span> <span class="dv">1</span>:</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>        var <span class="op">=</span> np.diag(var)</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> X <span class="op">-</span> mu</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> (<span class="dv">2</span> <span class="op">*</span> np.pi) <span class="op">**</span> (<span class="op">-</span>k <span class="op">/</span> <span class="dv">2</span>) <span class="op">*</span> np.linalg.det(var) <span class="op">**</span> (<span class="op">-</span><span class="fl">0.5</span>) <span class="op">*</span> <span class="op">\</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        np.exp(<span class="op">-</span><span class="fl">0.5</span> <span class="op">*</span> np.<span class="bu">sum</span>(np.matmul(X, np.linalg.pinv(var)) <span class="op">*</span> X, axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> p</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Plotting the contours of this fitted distribution over the training data shows what the model actually learned.</p>
<div id="d571ff9e" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> visualize_fit(X, mu, var):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Plots the training data with contour lines of the fitted Gaussian."""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>    x1, x2 <span class="op">=</span> np.meshgrid(np.arange(<span class="dv">0</span>, <span class="fl">35.5</span>, <span class="fl">0.5</span>), np.arange(<span class="dv">0</span>, <span class="fl">35.5</span>, <span class="fl">0.5</span>))</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>    Z <span class="op">=</span> multivariate_gaussian(np.stack([x1.ravel(), x2.ravel()], axis<span class="op">=</span><span class="dv">1</span>), mu, var)</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    Z <span class="op">=</span> Z.reshape(x1.shape)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    plt.scatter(X[:, <span class="dv">0</span>], X[:, <span class="dv">1</span>], marker<span class="op">=</span><span class="st">"x"</span>, s<span class="op">=</span><span class="dv">32</span>, color<span class="op">=</span><span class="st">"#0096FF"</span>)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> np.<span class="bu">sum</span>(np.isinf(Z)) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>        plt.contour(x1, x2, Z, levels<span class="op">=</span><span class="fl">10.0</span> <span class="op">**</span> np.arange(<span class="op">-</span><span class="dv">20</span>, <span class="dv">1</span>, <span class="dv">3</span>),</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>                     colors<span class="op">=</span><span class="st">"#7030A0"</span>, linewidths<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"the Gaussian contours of the fitted distribution"</span>, fontsize<span class="op">=</span><span class="fl">10.5</span>, color<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"latency (ms)"</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"throughput (mb/s)"</span>)</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> multivariate_gaussian(X_train, mu, var)</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>visualize_fit(X_train, mu, var)</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-16-output-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The innermost contour marks where <span class="math inline">\(p(\vec{x})\)</span> is highest, and each ring further out marks a probability an order of magnitude lower, dropping all the way to <span class="math inline">\(10^{-20}\)</span> at the outermost ring. Most training examples sit inside the first couple of contours, exactly the dense, high-probability region the model expects, while the handful of scattered points from the earlier plot now sit far outside every ring.</p>
</section>
<section id="exercise-2-selecting-the-threshold-varepsilon" class="level3">
<h3 class="anchored" data-anchor-id="exercise-2-selecting-the-threshold-varepsilon">Exercise 2: Selecting the Threshold <span class="math inline">\(\varepsilon\)</span></h3>
<p>Having the probabilities is not enough on its own, a threshold <span class="math inline">\(\varepsilon\)</span> is still needed to decide low from high. The second graded function, <code>select_threshold</code>, finds a good <span class="math inline">\(\varepsilon\)</span> using the cross validation set: it tries many candidate thresholds and keeps whichever gives the best <span class="math inline">\(F_1\)</span> score, exactly the <a href="#evaluating-on-the-cross-validation-or-test-set">tuning procedure</a> described earlier, now made concrete in code. Recall precision and recall,</p>
<p><span class="math display">\[
prec = \frac{tp}{tp + fp} \qquad\qquad rec = \frac{tp}{tp + fn}
\]</span></p>
<p>where <span class="math inline">\(tp\)</span>, <span class="math inline">\(fp\)</span>, <span class="math inline">\(fn\)</span> are the true positive, false positive, and false negative counts from comparing the predictions <span class="math inline">\(p(\vec{x}) &lt; \varepsilon\)</span> against the ground-truth labels <span class="math inline">\(y_{val}\)</span>, <a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html">as covered for skewed datasets</a>, and the <span class="math inline">\(F_1\)</span> score combines them,</p>
<p><span class="math display">\[
F_1 = \frac{2 \cdot prec \cdot rec}{prec + rec}
\]</span></p>
<p>The loop that sweeps over candidate values of <span class="math inline">\(\varepsilon\)</span> is already provided; the graded part is computing <code>predictions</code>, <code>tp</code>, <code>fp</code>, <code>fn</code>, <code>prec</code>, <code>rec</code>, and <code>F1</code> inside it.</p>
<div id="711d7360" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> select_threshold(y_val, p_val):</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Finds the best threshold to use for selecting outliers</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co">    based on the results from a validation set (p_val)</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a><span class="co">    and the ground truth (y_val)</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a><span class="co">        y_val (ndarray): Ground truth on validation set</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="co">        p_val (ndarray): Results on validation set</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="co">        epsilon (float): Threshold chosen</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="co">        F1 (float):      F1 score by choosing epsilon as threshold</span></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    best_epsilon <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    best_F1 <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    F1 <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    step_size <span class="op">=</span> (<span class="bu">max</span>(p_val) <span class="op">-</span> <span class="bu">min</span>(p_val)) <span class="op">/</span> <span class="dv">1000</span></span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> epsilon <span class="kw">in</span> np.arange(<span class="bu">min</span>(p_val), <span class="bu">max</span>(p_val), step_size):</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        predictions <span class="op">=</span> (p_val <span class="op">&lt;</span> epsilon)</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a>        tp <span class="op">=</span> np.<span class="bu">sum</span>((predictions <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (y_val <span class="op">==</span> <span class="dv">1</span>))</span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        fp <span class="op">=</span> np.<span class="bu">sum</span>((predictions <span class="op">==</span> <span class="dv">1</span>) <span class="op">&amp;</span> (y_val <span class="op">==</span> <span class="dv">0</span>))</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        fn <span class="op">=</span> np.<span class="bu">sum</span>((predictions <span class="op">==</span> <span class="dv">0</span>) <span class="op">&amp;</span> (y_val <span class="op">==</span> <span class="dv">1</span>))</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>        prec <span class="op">=</span> tp <span class="op">/</span> (tp <span class="op">+</span> fp)</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>        rec <span class="op">=</span> tp <span class="op">/</span> (tp <span class="op">+</span> fn)</span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>        F1 <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> prec <span class="op">*</span> rec <span class="op">/</span> (prec <span class="op">+</span> rec)</span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> F1 <span class="op">&gt;</span> best_F1:</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>            best_F1 <span class="op">=</span> F1</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>            best_epsilon <span class="op">=</span> epsilon</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> best_epsilon, best_F1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="66ff162c" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>p_val <span class="op">=</span> multivariate_gaussian(X_val, mu, var)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>epsilon, F1 <span class="op">=</span> select_threshold(y_val, p_val)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best epsilon found using cross-validation: </span><span class="sc">%e</span><span class="st">"</span> <span class="op">%</span> epsilon)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best F1 on Cross Validation Set: </span><span class="sc">%f</span><span class="st">"</span> <span class="op">%</span> F1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best epsilon found using cross-validation: 8.990853e-05
Best F1 on Cross Validation Set: 0.875000</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_908917/3389176543.py:27: RuntimeWarning: invalid value encountered in scalar divide
  prec = tp / (tp + fp)</code></pre>
</div>
</div>
<p>The expected output is an epsilon of about <code>8.99e-05</code> and an <span class="math inline">\(F_1\)</span> score of <code>0.875</code>, matching what runs here. Applying that threshold back to the training set and circling whichever points fall below it shows the anomalies the algorithm actually caught.</p>
<div id="d91b3235" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>outliers <span class="op">=</span> p <span class="op">&lt;</span> epsilon</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Number of outliers found:"</span>, outliers.<span class="bu">sum</span>())</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">6</span>, <span class="dv">5</span>))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>visualize_fit(X_train, mu, var)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>plt.plot(X_train[outliers, <span class="dv">0</span>], X_train[outliers, <span class="dv">1</span>], <span class="st">"o"</span>, markersize<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>         markerfacecolor<span class="op">=</span><span class="st">"none"</span>, markeredgewidth<span class="op">=</span><span class="dv">2</span>, color<span class="op">=</span><span class="st">"#C00000"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"anomalies (red circles) flagged at the tuned $</span><span class="ch">\\</span><span class="st">varepsilon$"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>          fontsize<span class="op">=</span><span class="fl">10.5</span>, color<span class="op">=</span><span class="st">"gray"</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of outliers found: 6</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="anomaly-detection_files/figure-html/cell-19-output-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Six points get circled, all of them sitting out in the sparse, low-probability region well past the outermost contour, exactly the servers worth a closer look.</p>
</section>
<section id="a-harder-high-dimensional-dataset" class="level3">
<h3 class="anchored" data-anchor-id="a-harder-high-dimensional-dataset">A Harder, High-Dimensional Dataset</h3>
<p>The two-feature example makes the contours easy to see, but real servers expose far more than two measurements. The next dataset describes each server with <strong>11 features</strong> instead of 2, capturing many more properties of the machine, at which point a scatter plot is no longer an option, yet nothing about the algorithm has to change. The same <code>estimate_gaussian</code>, the same <code>multivariate_gaussian</code>, and the same <code>select_threshold</code> apply unmodified.</p>
<div id="11a4a072" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>X_train_high <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/X_part2.npy"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>X_val_high <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/X_val_part2.npy"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>y_val_high <span class="op">=</span> np.load(<span class="st">"../../media/anomaly-detection/y_val_part2.npy"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of X_train_high:"</span>, X_train_high.shape)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of X_val_high:"</span>, X_val_high.shape)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of y_val_high:"</span>, y_val_high.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of X_train_high: (1000, 11)
Shape of X_val_high: (100, 11)
Shape of y_val_high: (100,)</code></pre>
</div>
</div>
<div id="d7d902ff" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate the Gaussian parameters</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>mu_high, var_high <span class="op">=</span> estimate_gaussian(X_train_high)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the probabilities for the training set</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>p_high <span class="op">=</span> multivariate_gaussian(X_train_high, mu_high, var_high)</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the probabilities for the cross validation set</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>p_val_high <span class="op">=</span> multivariate_gaussian(X_val_high, mu_high, var_high)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the best threshold</span></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>epsilon_high, F1_high <span class="op">=</span> select_threshold(y_val_high, p_val_high)</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best epsilon found using cross-validation: </span><span class="sc">%e</span><span class="st">"</span> <span class="op">%</span> epsilon_high)</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Best F1 on Cross Validation Set: </span><span class="sc">%f</span><span class="st">"</span> <span class="op">%</span> F1_high)</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"# Anomalies found: </span><span class="sc">%d</span><span class="st">"</span> <span class="op">%</span> <span class="bu">sum</span>(p_high <span class="op">&lt;</span> epsilon_high))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Best epsilon found using cross-validation: 1.377229e-18
Best F1 on Cross Validation Set: 0.615385
# Anomalies found: 117</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>/tmp/ipykernel_908917/3389176543.py:27: RuntimeWarning: invalid value encountered in scalar divide
  prec = tp / (tp + fp)</code></pre>
</div>
</div>
<p>The expected output is an epsilon of about <code>1.38e-18</code>, an <span class="math inline">\(F_1\)</span> score of about <code>0.615</code>, and <code>117</code> anomalies found among the 1,000 training servers, and that is exactly what this run produces too. The <span class="math inline">\(F_1\)</span> score is noticeably lower than the two-feature case, harder, higher-dimensional data is a harder detection problem, but the same handful of lines of code, fitting one Gaussian per feature and sweeping <span class="math inline">\(\varepsilon\)</span> against a small labeled validation set, scales up to it without any changes.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-38-contents" aria-controls="callout-38" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Download the lab data
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-38" class="callout-38-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The six arrays used in this lab: <a href="../../media/anomaly-detection/X_part1.npy">X_part1.npy</a>, <a href="../../media/anomaly-detection/X_val_part1.npy">X_val_part1.npy</a>, <a href="../../media/anomaly-detection/y_val_part1.npy">y_val_part1.npy</a> for the two-feature server dataset, and <a href="../../media/anomaly-detection/X_part2.npy">X_part2.npy</a>, <a href="../../media/anomaly-detection/X_val_part2.npy">X_val_part2.npy</a>, <a href="../../media/anomaly-detection/y_val_part2.npy">y_val_part2.npy</a> for the eleven-feature one.</p>
</div>
</div>
</div>
</section>
<section id="review-questions-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-6">Review Questions</h3>
<p><strong>1. <code>estimate_gaussian</code> computes <code>mu</code> and <code>var</code> with <code>np.mean(X, axis=0)</code> rather than looping over features one at a time. What does <code>axis=0</code> buy here?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-39-contents" aria-controls="callout-39" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-39" class="callout-39-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>X</code> is an <span class="math inline">\((m, n)\)</span> matrix, examples down the rows and features across the columns. Averaging with <code>axis=0</code> collapses the row dimension, producing one mean per column, that is, one <span class="math inline">\(\mu_i\)</span> per feature, in a single vectorized call instead of an explicit loop over the <span class="math inline">\(n\)</span> features.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. <code>multivariate_gaussian</code> starts by checking <code>if var.ndim == 1</code> and converting <code>var</code> to <code>np.diag(var)</code>. Why, and what does that have to do with the per-feature product formula from earlier in this page?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-40-contents" aria-controls="callout-40" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-40" class="callout-40-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><code>estimate_gaussian</code> returns <code>var</code> as a plain vector of <span class="math inline">\(n\)</span> per-feature variances, but the general multivariate Gaussian formula expects a full <span class="math inline">\(n \times n\)</span> covariance matrix. Placing those variances on the diagonal of an otherwise-zero matrix encodes “each feature has its own variance and no feature is correlated with any other,” which is precisely the independence assumption behind <span class="math inline">\(p(\vec{x}) = \prod_{j=1}^n p(x_j; \mu_j, \sigma_j^2)\)</span>. The matrix form computes that same product, just as one linear-algebra expression instead of a loop over features.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In <code>select_threshold</code>, why does the search try <code>np.arange(min(p_val), max(p_val), step_size)</code> rather than, say, trying every power of ten?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-41-contents" aria-controls="callout-41" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-41" class="callout-41-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A useful <span class="math inline">\(\varepsilon\)</span> has to fall somewhere between the smallest and largest probability actually seen on the cross validation set, values outside that range would flag either everything or nothing as anomalous. Stepping evenly through that exact range in 1,000 increments is a simple, exhaustive way to sweep every meaningfully different threshold and score each one by <span class="math inline">\(F_1\)</span>, without having to guess the right scale in advance.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Moving from the 2-feature dataset to the 11-feature one, the best <span class="math inline">\(F_1\)</span> score drops from 0.875 to about 0.615. Does that mean the code is buggy?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-42-contents" aria-controls="callout-42" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-42" class="callout-42-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Not necessarily. <code>estimate_gaussian</code>, <code>multivariate_gaussian</code>, and <code>select_threshold</code> are unchanged between the two runs, and the shapes and outputs match the expected values in both cases. A lower <span class="math inline">\(F_1\)</span> on a harder, higher-dimensional, more realistic dataset is expected: with more features there are more ways for a normal example to look slightly unusual on some dimension, which makes drawing a clean line between normal and anomalous with a single Gaussian-per-feature model genuinely harder, not necessarily a sign of a bug.</p>
</div>
</div>
</div>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 38%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">38% completed (336 of 884 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../machine-learning/unsupervised-learning/clustering.html" class="pagination-link" aria-label="Clustering">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Clustering</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="pagination-link" aria-label="Collaborative Filtering">
        <span class="nav-page-text">Collaborative Filtering</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>