<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-17">
<meta name="description" content="What clustering is, plus the full k-means algorithm, its distortion cost function, random initialization against local optima, and how to choose K.">

<title>Clustering – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../machine-learning/unsupervised-learning/anomaly-detection.html" rel="next">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Clustering – Hossein’s Notes">
<meta property="og:description" content="What clustering is, plus the full k-means algorithm, its distortion cost function, random initialization against local optima, and how to choose K.">
<meta property="og:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/clustering_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="Hossein’s Notes">
<meta name="twitter:title" content="Clustering – Hossein’s Notes">
<meta name="twitter:description" content="What clustering is, plus the full k-means algorithm, its distortion cost function, random initialization against local optima, and how to choose K.">
<meta name="twitter:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/clustering_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-agentic-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Agentic AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-agentic-ai">    
        <li>
    <a class="dropdown-item" href="../../agentic/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/frameworks.html">
 <span class="dropdown-text">Frameworks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/agent-architecture.html">
 <span class="dropdown-text">Agent Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/async-io.html">
 <span class="dropdown-text">Async I/O</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/unsupervised-learning/clustering.html">Clustering</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/clustering.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anomaly Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering-in-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering in Practice</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/content-based-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Content-Based Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/principal-components-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Principal Components Analysis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#supervised-versus-unsupervised-learning" id="toc-supervised-versus-unsupervised-learning" class="nav-link active" data-scroll-target="#supervised-versus-unsupervised-learning">Supervised versus Unsupervised Learning</a></li>
  <li><a href="#finding-clusters" id="toc-finding-clusters" class="nav-link" data-scroll-target="#finding-clusters">Finding Clusters</a></li>
  <li><a href="#applications-of-clustering" id="toc-applications-of-clustering" class="nav-link" data-scroll-target="#applications-of-clustering">Applications of Clustering</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#k-means-intuition" id="toc-k-means-intuition" class="nav-link" data-scroll-target="#k-means-intuition">K-means Intuition</a>
  <ul class="collapse">
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#k-means-algorithm" id="toc-k-means-algorithm" class="nav-link" data-scroll-target="#k-means-algorithm">K-means Algorithm</a>
  <ul class="collapse">
  <li><a href="#corner-case-an-empty-cluster" id="toc-corner-case-an-empty-cluster" class="nav-link" data-scroll-target="#corner-case-an-empty-cluster">Corner Case: An Empty Cluster</a></li>
  <li><a href="#k-means-on-data-that-is-not-well-separated" id="toc-k-means-on-data-that-is-not-well-separated" class="nav-link" data-scroll-target="#k-means-on-data-that-is-not-well-separated">K-means on Data That Is Not Well Separated</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#cost-function-for-k-means" id="toc-cost-function-for-k-means" class="nav-link" data-scroll-target="#cost-function-for-k-means">Cost Function for K-means</a>
  <ul class="collapse">
  <li><a href="#why-each-step-reduces-the-cost" id="toc-why-each-step-reduces-the-cost" class="nav-link" data-scroll-target="#why-each-step-reduces-the-cost">Why Each Step Reduces the Cost</a></li>
  <li><a href="#convergence-guarantee" id="toc-convergence-guarantee" class="nav-link" data-scroll-target="#convergence-guarantee">Convergence Guarantee</a></li>
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#random-initialization" id="toc-random-initialization" class="nav-link" data-scroll-target="#random-initialization">Random Initialization</a>
  <ul class="collapse">
  <li><a href="#local-optima" id="toc-local-optima" class="nav-link" data-scroll-target="#local-optima">Local Optima</a></li>
  <li><a href="#trying-multiple-initializations" id="toc-trying-multiple-initializations" class="nav-link" data-scroll-target="#trying-multiple-initializations">Trying Multiple Initializations</a></li>
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#choosing-the-number-of-clusters" id="toc-choosing-the-number-of-clusters" class="nav-link" data-scroll-target="#choosing-the-number-of-clusters">Choosing the Number of Clusters</a>
  <ul class="collapse">
  <li><a href="#elbow-method" id="toc-elbow-method" class="nav-link" data-scroll-target="#elbow-method">Elbow Method</a></li>
  <li><a href="#evaluating-k-means-by-its-downstream-purpose" id="toc-evaluating-k-means-by-its-downstream-purpose" class="nav-link" data-scroll-target="#evaluating-k-means-by-its-downstream-purpose">Evaluating K-means by Its Downstream Purpose</a></li>
  <li><a href="#review-questions-5" id="toc-review-questions-5" class="nav-link" data-scroll-target="#review-questions-5">Review Questions</a></li>
  </ul></li>
  <li><a href="#lab-k-means-and-image-compression" id="toc-lab-k-means-and-image-compression" class="nav-link" data-scroll-target="#lab-k-means-and-image-compression">Lab: K-means and Image Compression</a>
  <ul class="collapse">
  <li><a href="#exercise-1-finding-closest-centroids" id="toc-exercise-1-finding-closest-centroids" class="nav-link" data-scroll-target="#exercise-1-finding-closest-centroids">Exercise 1: Finding Closest Centroids</a></li>
  <li><a href="#exercise-2-computing-centroid-means" id="toc-exercise-2-computing-centroid-means" class="nav-link" data-scroll-target="#exercise-2-computing-centroid-means">Exercise 2: Computing Centroid Means</a></li>
  <li><a href="#k-means-on-a-sample-dataset" id="toc-k-means-on-a-sample-dataset" class="nav-link" data-scroll-target="#k-means-on-a-sample-dataset">K-means on a Sample Dataset</a></li>
  <li><a href="#random-initialization-in-code" id="toc-random-initialization-in-code" class="nav-link" data-scroll-target="#random-initialization-in-code">Random Initialization in Code</a></li>
  <li><a href="#image-compression-with-k-means" id="toc-image-compression-with-k-means" class="nav-link" data-scroll-target="#image-compression-with-k-means">Image Compression with K-means</a></li>
  <li><a href="#compressing-the-image" id="toc-compressing-the-image" class="nav-link" data-scroll-target="#compressing-the-image">Compressing the Image</a></li>
  <li><a href="#review-questions-6" id="toc-review-questions-6" class="nav-link" data-scroll-target="#review-questions-6">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Clustering</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">unsupervised-learning</div>
  </div>
  </div>

<div>
  <div class="description">
    What clustering is, plus the full k-means algorithm, its distortion cost function, random initialization against local optima, and how to choose K.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~160 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level and capped at 3 hours.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~6,400 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>What is clustering? A <strong>clustering algorithm</strong> looks at a number of data points and automatically finds data points that are related or similar to each other. It is the first unsupervised learning algorithm of this course. This page pins down what clustering means, then builds up the complete <strong>k-means</strong> algorithm, the cost function it optimizes, the random initialization strategy that avoids bad clusterings, and how to choose the number of clusters <span class="math inline">\(K\)</span>.</p>
<section id="supervised-versus-unsupervised-learning" class="level2">
<h2 class="anchored" data-anchor-id="supervised-versus-unsupervised-learning">Supervised versus Unsupervised Learning</h2>
<p>To see what makes clustering different, contrast it with the supervised learning seen throughout the earlier courses, say, <a href="../../machine-learning/supervised-machine-learning/logistic-regression.html">binary classification</a>. Given a dataset with features <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span>, supervised learning had a training set with both the <strong>input features <span class="math inline">\(x\)</span></strong> and the <strong>labels <span class="math inline">\(y\)</span></strong>. Plotting such a dataset shows two classes, marked here as crosses and circles, and fitting a logistic regression algorithm or a <a href="../../machine-learning/advanced-learning-algorithms/neural-network-model.html">neural network</a> learns a <strong>decision boundary</strong> between them.</p>
<p>In <strong>unsupervised learning</strong>, the dataset comes with just <span class="math inline">\(x\)</span> and <em>not</em> the target labels <span class="math inline">\(y\)</span>. Plotting it shows only dots, no crosses and circles, because there are no labels to distinguish them.</p>
<div id="b9ae1916" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-2-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Because there are no target labels <span class="math inline">\(y\)</span>, it is not possible to tell the algorithm what the “right answer <span class="math inline">\(y\)</span>” is that it should predict. Instead, the algorithm gets asked to find <strong>something interesting about the data</strong>, that is, some interesting <em>structure</em> in it.</p>
</section>
<section id="finding-clusters" class="level2">
<h2 class="anchored" data-anchor-id="finding-clusters">Finding Clusters</h2>
<p>A clustering algorithm looks for one particular type of structure. Given a dataset like the one on the right above, it tries to see whether the data can be <strong>grouped into clusters</strong>, meaning groups of points that are similar to each other. In this case, a clustering algorithm might find that the dataset is made up of data from <strong>two clusters</strong>.</p>
<div id="4b6bdbb3" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="applications-of-clustering" class="level2">
<h2 class="anchored" data-anchor-id="applications-of-clustering">Applications of Clustering</h2>
<p>Clustering shows up in a wide range of applications, several of which appeared briefly back in <a href="../../machine-learning/supervised-machine-learning/unsupervised-learning.html">course 1’s introduction to unsupervised learning</a>.</p>
<ul>
<li><strong>Grouping similar news articles.</strong> Given many articles, group together the ones about the same story, like the panda story from course 1.</li>
<li><strong>Market segmentation.</strong> At deeplearning.ai, clustering learner data revealed that many learners come to grow their skills, or to develop their careers, or to stay updated on AI and understand how it affects their field of work. Discovering those groups helps serve each of them better, and anyone who does not fall into one of the clusters is welcome too.</li>
<li><strong>Analyzing DNA data.</strong> Looking at genetic expression data from different individuals and grouping together people who exhibit similar traits.</li>
<li><strong>Astronomical data analysis.</strong> Astronomers use clustering to group bodies in space for their analysis of what is going on out there, for example figuring out which bodies form one galaxy or which form coherent structures in space.</li>
</ul>
<p>The next section looks at the most commonly used clustering algorithm, the <strong>k-means</strong> algorithm, and how it works.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. What is the key difference between the training data for supervised learning and for unsupervised learning?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Supervised learning gets both the input features <span class="math inline">\(x\)</span> and the target labels <span class="math inline">\(y\)</span>, so the algorithm can be told the right answer to predict for each example. Unsupervised learning gets only <span class="math inline">\(x\)</span>, with no labels, so instead of predicting a known target, the algorithm is asked to find interesting structure in the data on its own.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In one sentence, what kind of structure does a clustering algorithm look for?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It looks for groups of data points that are similar to each other, called clusters, so that the dataset can be organized into a small number of coherent groups.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is there no “decision boundary” in the unsupervised version of the plot?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A decision boundary separates known classes, and learning one requires labels <span class="math inline">\(y\)</span> to say which side each training example belongs on. With no labels, there are no classes to separate, and the algorithm’s job changes from separating given categories to <em>discovering</em> groupings in the first place.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of the following are applications of clustering mentioned here? (Choose all that apply.)</strong></p>
<ol type="a">
<li><p>Grouping similar news articles together</p></li>
<li><p>Predicting house prices from square footage</p></li>
<li><p>Market segmentation of learners by their motivation</p></li>
<li><p>Grouping bodies in space to identify coherent structures such as galaxies</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a, c, and d</strong>, along with grouping people by genetic expression data. Predicting house prices (b) is a supervised regression problem, it needs labeled examples of prices, the target <span class="math inline">\(y\)</span>, which is exactly what unsupervised learning does without.</p>
</div>
</div>
</div>
</section>
</section>
<section id="k-means-intuition" class="level2">
<h2 class="anchored" data-anchor-id="k-means-intuition">K-means Intuition</h2>
<p>Here is what the <strong>k-means</strong> clustering algorithm does, illustrated on a dataset of 30 unlabeled training examples with the algorithm asked to find <strong>two clusters</strong>. (How to decide the number of clusters is covered in a <a href="#choosing-the-number-of-clusters">later section</a>.)</p>
<p>The first thing k-means does is take a <strong>random guess</strong> at where the centers of the two clusters might be. The centers of the clusters are called <strong>cluster centroids</strong>, drawn below as a red cross and a blue cross. The initial guesses are not particularly good, but they are a start. From there, k-means repeatedly does two different things.</p>
<ol type="1">
<li><strong>Assign points to cluster centroids.</strong> Go through every example, <span class="math inline">\(x^{(1)}\)</span> through <span class="math inline">\(x^{(30)}\)</span>, and check whether it is closer to the red or the blue cluster centroid, then assign it, illustrated by painting each dot red or blue, to whichever centroid is closer.</li>
<li><strong>Move cluster centroids.</strong> Look at all the red points and take their average, and move the red cross to that average location. Do the same for the blue points and the blue cross.</li>
</ol>
<p>With the new, hopefully slightly improved, centroid locations, the algorithm loops back to step 1, and because the centroids have moved, <strong>some points change color</strong>, a dot that used to be closer to the red cross may now be closer to the blue one. Then the centroids move again, and so on.</p>
<div id="1dbaa3c2" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Keeping on repeating the two steps, look at each point and assign it to the nearest cluster centroid, then move each cluster centroid to the mean of all the points with the same color, eventually there are <strong>no more changes</strong> to the colors of the points nor to the locations of the cluster centroids. At that point the k-means algorithm has <strong>converged</strong>. These two conditions always arrive together, because they are locked to each other. If no point changes color, then each centroid keeps the same set of points and so its mean does not move, and conversely if no centroid moves, then every point keeps the same nearest centroid and so no color changes. That is why the final panel above can declare convergence just from a reassignment in which nothing changes color. In this example, k-means has done a pretty good job, it found that the points up top correspond to one cluster and the points at the bottom to a second cluster.</p>
<p>The next section formalizes this into the algorithm, with the mathematical formulas for both steps.</p>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. What are the two steps k-means repeats, and in what order?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First, assign every point to its nearest cluster centroid (paint each dot the color of the closer cross). Second, move each cluster centroid to the average (mean) location of the points assigned to it. The algorithm alternates these two steps until nothing changes.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is a cluster centroid, and where do the first centroids come from?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A cluster centroid is the algorithm’s current guess for the center of a cluster. The first centroids come from a random guess, and they are usually not good guesses, the repeated assign-and-move steps are what improve them.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. How does k-means know when to stop?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It has converged when running the two steps produces no further changes, no point switches to a different centroid, and no centroid moves, because each centroid already sits at the mean of its assigned points.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A point was assigned to the red centroid on the first iteration but to the blue centroid on the second. How is that possible if the point never moved?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The centroids moved. After the first averaging step, the red and blue crosses are in new locations, and distances get re-measured against those new locations. A point near the middle can be closer to red under the old positions and closer to blue under the new ones.</p>
</div>
</div>
</div>
</section>
</section>
<section id="k-means-algorithm" class="level2">
<h2 class="anchored" data-anchor-id="k-means-algorithm">K-means Algorithm</h2>
<p>Here is the k-means algorithm written out in detail, enough to implement it. It begins by <strong>randomly initializing <span class="math inline">\(K\)</span> cluster centroids</strong> <span class="math inline">\(\vec{\mu}_1, \vec{\mu}_2, \dots, \vec{\mu}_K\)</span>. In the running example with <span class="math inline">\(K = 2\)</span>, this is the random placement of the red cross (centroid 1, so <span class="math inline">\(\vec{\mu}_1\)</span>) and the blue cross (centroid 2, so <span class="math inline">\(\vec{\mu}_2\)</span>).</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Vector notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>Each centroid <span class="math inline">\(\vec{\mu}_k\)</span> is a <strong>vector</strong> with the same dimension as the training examples. If each <span class="math inline">\(\vec{x}^{(i)}\)</span> has <span class="math inline">\(n = 2\)</span> features, then each <span class="math inline">\(\vec{\mu}_k\)</span> is also a list of two numbers. The arrow marks a vector; the corresponding Python variables have no arrow. This follows the <a href="../../machine-learning/supervised-machine-learning/multiple-linear-regression.html">machine learning notation convention</a> from earlier courses.</p>
</div>
</div>
<p>Having initialized the centroids, k-means then repeats the two steps from the <a href="#k-means-intuition">intuition section</a>.</p>
<p><strong>Step 1: assign points to cluster centroids.</strong> For <span class="math inline">\(i = 1\)</span> to <span class="math inline">\(m\)</span> (every training example), set <span class="math inline">\(c^{(i)}\)</span> to the index (from <span class="math inline">\(1\)</span> to <span class="math inline">\(K\)</span>) of the cluster centroid closest to <span class="math inline">\(\vec{x}^{(i)}\)</span>. “Closest” is measured by distance, written with the double-bar <strong>norm</strong> notation (also called the <strong>L2 norm</strong>), and it is more convenient to minimize the <em>squared</em> distance, which gives the same answer.</p>
<p><span class="math display">\[
c^{(i)} = \arg\min_{k} \; \lVert \vec{x}^{(i)} - \vec{\mu}_k \rVert^2
\]</span></p>
<p>For instance, if example <span class="math inline">\(\vec{x}^{(1)}\)</span> is closest to the red centroid, set <span class="math inline">\(c^{(1)} = 1\)</span>, and if example <span class="math inline">\(\vec{x}^{(12)}\)</span> is closest to the blue one, set <span class="math inline">\(c^{(12)} = 2\)</span>.</p>
<p><strong>Step 2: move the cluster centroids.</strong> For <span class="math inline">\(k = 1\)</span> to <span class="math inline">\(K\)</span>, set <span class="math inline">\(\vec{\mu}_k\)</span> to the <strong>average (mean)</strong> of the points assigned to cluster <span class="math inline">\(k\)</span>. Averaging the assigned points’ first feature gives the new horizontal position, averaging the second feature gives the new vertical position, and so on for each feature.</p>
<p><span class="math display">\[
\vec{\mu}_k = \frac{1}{n_k} \sum_{i \,:\, c^{(i)} = k} \vec{x}^{(i)}
\]</span></p>
<p>where <span class="math inline">\(n_k\)</span> is the number of points assigned to cluster <span class="math inline">\(k\)</span>. For example, if cluster 1 has training examples <span class="math inline">\(1, 5, 6, 10\)</span> assigned to it, then</p>
<p><span class="math display">\[
\vec{\mu}_1 = \frac{1}{4}\left( \vec{x}^{(1)} + \vec{x}^{(5)} + \vec{x}^{(6)} + \vec{x}^{(10)} \right)
\]</span></p>
<p>and since each <span class="math inline">\(\vec{x}\)</span> is a vector of <span class="math inline">\(n\)</span> numbers, <span class="math inline">\(\vec{\mu}_1\)</span> comes out as a vector of <span class="math inline">\(n\)</span> numbers too.</p>
<p>Written together, the algorithm is:</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Algorithm summary
</div>
</div>
<div class="callout-body-container callout-body">
<p>Randomly initialize <span class="math inline">\(K\)</span> cluster centroids <span class="math inline">\(\vec{\mu}_1, \vec{\mu}_2, \dots, \vec{\mu}_K\)</span>.</p>
<p>Repeat until convergence:</p>
<ul>
<li><strong>Assign points.</strong> For <span class="math inline">\(i = 1\)</span> to <span class="math inline">\(m\)</span>: set <span class="math inline">\(c^{(i)} = \arg\min_k \lVert \vec{x}^{(i)} - \vec{\mu}_k \rVert^2\)</span></li>
<li><strong>Move centroids.</strong> For <span class="math inline">\(k = 1\)</span> to <span class="math inline">\(K\)</span>: set <span class="math inline">\(\vec{\mu}_k\)</span> = mean of the points assigned to cluster <span class="math inline">\(k\)</span></li>
</ul>
</div>
</div>
<section id="corner-case-an-empty-cluster" class="level3">
<h3 class="anchored" data-anchor-id="corner-case-an-empty-cluster">Corner Case: An Empty Cluster</h3>
<p>There is one corner case. What happens if a cluster has <strong>zero training examples</strong> assigned to it? Then the move step would try to average zero points, which is not well defined. The most common response is to <strong>eliminate that cluster</strong>, ending up with <span class="math inline">\(K - 1\)</span> clusters. If you really do need all <span class="math inline">\(K\)</span> clusters, an alternative is to randomly reinitialize that centroid and hope it picks up some points on the next round, but eliminating the empty cluster is more common.</p>
</section>
<section id="k-means-on-data-that-is-not-well-separated" class="level3">
<h3 class="anchored" data-anchor-id="k-means-on-data-that-is-not-well-separated">K-means on Data That Is Not Well Separated</h3>
<p>The examples so far had <strong>well-separated</strong> clusters, three visibly distinct blobs, say. But k-means is frequently applied to data where the clusters are <em>not</em> well separated. Suppose you design and manufacture t-shirts and want to decide how to size <strong>small, medium, and large</strong>. You collect data on the heights and weights of likely buyers, which vary continuously with no clear clusters. Running k-means with three centroids anyway groups the people into three groups, and the centroids suggest the most representative height and weight for each size.</p>
<div id="5b25946b" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is an example of k-means giving a useful result even though the data does not lie in well-separated groups. You would then size the small t-shirt to fit the people in one cluster, the medium for the next, and the large for the third.</p>
<p>That is the k-means clustering algorithm, initialize the centroids randomly, then repeatedly assign points to centroids and move the centroids. But what is the algorithm really doing, and will it converge or run forever? The next section shows that k-means is actually optimizing a specific <strong>cost function</strong>, which explains why it converges.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. Write the two update rules of k-means. What does <span class="math inline">\(c^{(i)}\)</span> store, and what does <span class="math inline">\(\vec{\mu}_k\)</span> store?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The assignment step sets <span class="math inline">\(c^{(i)} = \arg\min_k \lVert \vec{x}^{(i)} - \vec{\mu}_k \rVert^2\)</span>, so <span class="math inline">\(c^{(i)}\)</span> stores the <em>index</em> of the centroid closest to example <span class="math inline">\(i\)</span> (a number from 1 to <span class="math inline">\(K\)</span>). The move step sets <span class="math inline">\(\vec{\mu}_k\)</span> to the mean of all points with <span class="math inline">\(c^{(i)} = k\)</span>, so <span class="math inline">\(\vec{\mu}_k\)</span> stores the <em>location</em> (a vector) of cluster <span class="math inline">\(k\)</span>’s centroid.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does the algorithm minimize the <em>squared</em> distance <span class="math inline">\(\lVert \vec{x}^{(i)} - \vec{\mu}_k \rVert^2\)</span> rather than the plain distance?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Purely for convenience. The centroid with the smallest squared distance is always the same as the centroid with the smallest distance (squaring is monotonic for non-negative values), so the assignment is identical, and squared distance avoids computing a square root.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. During the move step, one of the <span class="math inline">\(K\)</span> clusters has no points assigned to it. What goes wrong, and what is the usual fix?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The move step would average zero points, which is undefined. The most common fix is to eliminate that cluster and continue with <span class="math inline">\(K - 1\)</span> clusters. If all <span class="math inline">\(K\)</span> are required, the centroid can instead be randomly reinitialized in the hope of attracting points next round.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the t-shirt example, the height and weight data has no clear separated clusters. Does that make k-means the wrong tool?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;k-means still partitions the continuous data into three groups and returns a representative centroid for each, which is exactly what is needed to choose small, medium, and large dimensions. k-means often gives useful results even when the data does not fall into visibly distinct clusters.</p>
</div>
</div>
</div>
</section>
</section>
<section id="cost-function-for-k-means" class="level2">
<h2 class="anchored" data-anchor-id="cost-function-for-k-means">Cost Function for K-means</h2>
<p>In the earlier courses, supervised learning algorithms took a training set, posed a <strong>cost function</strong>, and used gradient descent or some other algorithm to optimize it. The k-means algorithm also optimizes a specific cost function, although the optimization algorithm is not gradient descent, it is the two-step procedure already seen.</p>
<p>Recall the notation. <span class="math inline">\(c^{(i)}\)</span> is the index (from <span class="math inline">\(1\)</span> to <span class="math inline">\(K\)</span>) of the cluster to which example <span class="math inline">\(\vec{x}^{(i)}\)</span> is currently assigned, and <span class="math inline">\(\vec{\mu}_k\)</span> is the location of cluster centroid <span class="math inline">\(k\)</span>. One more piece of notation ties them together: <span class="math inline">\(\vec{\mu}_{c^{(i)}}\)</span> is the centroid of the cluster to which <span class="math inline">\(\vec{x}^{(i)}\)</span> has been assigned. For example, <span class="math inline">\(\vec{\mu}_{c^{(10)}}\)</span> means “look up <span class="math inline">\(c^{(10)}\)</span> to see which cluster example 10 went to, then take that centroid’s location.”</p>
<p>The cost function that k-means minimizes is</p>
<p><span class="math display">\[
J\!\left(c^{(1)}, \dots, c^{(m)}, \vec{\mu}_1, \dots, \vec{\mu}_K\right) = \frac{1}{m} \sum_{i=1}^{m} \left\lVert \vec{x}^{(i)} - \vec{\mu}_{c^{(i)}} \right\rVert^2
\]</span></p>
<p>In words, <span class="math inline">\(J\)</span> is the <strong>average squared distance</strong> between every training example <span class="math inline">\(\vec{x}^{(i)}\)</span> and the location of the cluster centroid to which that example has been assigned. Written as an optimization objective, what k-means is solving is</p>
<p><span class="math display">\[
\min_{\substack{c^{(1)}, \dots, c^{(m)} \\ \vec{\mu}_1, \dots, \vec{\mu}_K}} \; J\!\left(c^{(1)}, \dots, c^{(m)}, \vec{\mu}_1, \dots, \vec{\mu}_K\right)
\]</span></p>
<p>a minimization over <em>both</em> sets of variables at once, the assignments of points to centroids and the locations of the centroids, to make the average squared distance as small as possible.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How to read the min notation
</div>
</div>
<div class="callout-body-container callout-body">
<p>This expression looks scarier than it is. The symbols stacked <em>underneath</em> <span class="math inline">\(\min\)</span> are simply the list of knobs the algorithm is allowed to turn, all <span class="math inline">\(m\)</span> assignments and all <span class="math inline">\(K\)</span> centroid positions. The whole line reads, “out of every possible way to assign the points and place the centroids, find the combination that makes <span class="math inline">\(J\)</span> smallest.” It is a statement of the goal, not a computation, and the two-step k-means procedure is one strategy for pursuing that goal.</p>
</div>
</div>
<p>This cost function has a name in the literature, the <strong>distortion function</strong>. If you hear someone talk about the distortion or the distortion cost function for k-means, this formula <span class="math inline">\(J\)</span> is what they mean.</p>
<section id="why-each-step-reduces-the-cost" class="level3">
<h3 class="anchored" data-anchor-id="why-each-step-reduces-the-cost">Why Each Step Reduces the Cost</h3>
<p>Here is the key insight, the two steps of k-means are each minimizing <span class="math inline">\(J\)</span>, just with respect to different variables.</p>
<ul>
<li><strong>The assign step minimizes <span class="math inline">\(J\)</span> over the assignments <span class="math inline">\(c^{(1)}, \dots, c^{(m)}\)</span>, holding the centroids <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span> fixed.</strong> For a single example, the term <span class="math inline">\(\lVert \vec{x}^{(i)} - \vec{\mu}_{c^{(i)}} \rVert^2\)</span> is made as small as possible by assigning <span class="math inline">\(\vec{x}^{(i)}\)</span> to the <strong>closest</strong> centroid, which is exactly what the assign step does. If a point could go to centroid 1 (far) or centroid 2 (near), picking the near one gives the smaller squared distance.</li>
<li><strong>The move step minimizes <span class="math inline">\(J\)</span> over the centroids <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span>, holding the assignments fixed.</strong> For a given cluster, the location that minimizes the average squared distance to its points is exactly their <strong>mean</strong>, which is what the move step computes.</li>
</ul>
<p>The second claim is worth seeing concretely. Take a cluster with just two points, at positions 1 and 11 on a line. Put the centroid at position 2, and the two squared distances are <span class="math inline">\(1^2\)</span> and <span class="math inline">\(9^2\)</span>, averaging <span class="math inline">\(\frac{1}{2}(1 + 81) = 41\)</span>. Now move the centroid to the mean of the two points, <span class="math inline">\(\frac{1 + 11}{2} = 6\)</span>, and the squared distances become <span class="math inline">\(5^2\)</span> and <span class="math inline">\(5^2\)</span>, averaging <span class="math inline">\(\frac{1}{2}(25 + 25) = 25\)</span>, much smaller. Playing with the centroid’s position confirms that the mean is the location that minimizes the average squared distance.</p>
<div id="dfc1dadb" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="convergence-guarantee" class="level3">
<h3 class="anchored" data-anchor-id="convergence-guarantee">Convergence Guarantee</h3>
<p>Because k-means is optimizing a cost function, and every step sets <span class="math inline">\(c^{(i)}\)</span> and <span class="math inline">\(\vec{\mu}_k\)</span> so as to reduce it, the algorithm is <strong>guaranteed to converge</strong>. On every iteration, the distortion should go <strong>down or stay the same</strong>. It should never go up, so if it ever does, that means there is a <strong>bug in the code</strong>.</p>
<p>This also gives a practical way to check for convergence. Once the cost function stops going down, once there is a single iteration where it stays the same, k-means has usually converged and can be stopped. In rare cases k-means runs a long time with the distortion decreasing very, very slowly, a bit like gradient descent, and then it is reasonable to decide the algorithm is close enough to convergence and stop rather than spend more compute.</p>
<p>The next section uses the cost function in another way, running k-means from <strong>multiple random initializations</strong> to find better clusters.</p>
</section>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. Write the k-means cost function and say what <span class="math inline">\(\vec{\mu}_{c^{(i)}}\)</span> refers to. What is this cost function also called?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[J = \frac{1}{m} \sum_{i=1}^{m} \left\lVert \vec{x}^{(i)} - \vec{\mu}_{c^{(i)}} \right\rVert^2\]</span> Here <span class="math inline">\(\vec{\mu}_{c^{(i)}}\)</span> is the location of the centroid of the cluster that example <span class="math inline">\(i\)</span> is assigned to, found by looking up <span class="math inline">\(c^{(i)}\)</span>. The cost is the average squared distance from each example to its own centroid, and it is also called the <strong>distortion function</strong>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The assign step and the move step each minimize <span class="math inline">\(J\)</span>, but over different variables. Which variables does each hold fixed, and which does it optimize?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The assign step holds the centroids <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span> fixed and optimizes the assignments <span class="math inline">\(c^{(1)}, \dots, c^{(m)}\)</span>, sending each point to its nearest centroid. The move step holds the assignments fixed and optimizes the centroids, setting each to the mean of its assigned points.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Two points sit at positions 1 and 11. Show that a centroid at their mean gives a smaller average squared distance than a centroid at position 2.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>At position 2, the distances are 1 and 9, so the average squared distance is <span class="math inline">\(\frac{1}{2}(1^2 + 9^2) = \frac{1}{2}(1 + 81) = 41\)</span>. At the mean, position 6, the distances are 5 and 5, giving <span class="math inline">\(\frac{1}{2}(5^2 + 5^2) = \frac{1}{2}(50) = 25\)</span>. Since <span class="math inline">\(25 &lt; 41\)</span>, the mean is better, and in fact the mean minimizes the average squared distance, which is why the move step uses it.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. While running your k-means code, you notice the distortion <span class="math inline">\(J\)</span> increased from one iteration to the next. What does this tell you?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There is a bug. Every step of k-means, both assigning points and moving centroids, can only decrease <span class="math inline">\(J\)</span> or leave it unchanged, so a genuine implementation never lets the distortion rise. An increase is a reliable signal that something in the code is wrong.</p>
</div>
</div>
</div>
</section>
</section>
<section id="random-initialization" class="level2">
<h2 class="anchored" data-anchor-id="random-initialization">Random Initialization</h2>
<p>The very first step of k-means is to choose random locations as the initial guesses for the cluster centroids <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span>. How is that random guess actually made, and how can taking several attempts lead to a better set of clusters?</p>
<p>First, when running k-means you should pretty much always choose the number of centroids <span class="math inline">\(K\)</span> to be <strong>less than the number of training examples <span class="math inline">\(m\)</span></strong>. Having <span class="math inline">\(K &gt; m\)</span> does not make sense, there would not even be enough training examples to have at least one per centroid. In the earlier example, <span class="math inline">\(K = 2\)</span> and <span class="math inline">\(m = 30\)</span>.</p>
<p>The most common way to initialize is to <strong>randomly pick <span class="math inline">\(K\)</span> training examples</strong> and set <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span> equal to those examples. So for <span class="math inline">\(K = 2\)</span>, pick two training examples at random and place the red and blue centroids right on top of them. (The earlier illustrations put the initial centroids at arbitrary random points rather than on training examples, purely to make the pictures clearer. Initializing on actual training examples is the method used in practice.)</p>
<section id="local-optima" class="level3">
<h3 class="anchored" data-anchor-id="local-optima">Local Optima</h3>
<p>Depending on which random examples get chosen, k-means can end up with <strong>different clusterings</strong>. Consider a dataset with three visible groups and <span class="math inline">\(K = 3\)</span>. One random initialization might produce a clean clustering, one centroid per group. But an unlucky initialization, say two centroids landing inside one group and one centroid inside another, can leave k-means stuck in a worse clustering. This is a <strong>local optimum</strong>: k-means is still minimizing the distortion <span class="math inline">\(J\)</span>, but this initialization happened to get trapped at a local minimum rather than the best one.</p>
<div id="5ff78b1f" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-7-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>All three of these are results k-means can reach on the <em>same</em> data, just from different random initializations. The good clustering (left) has small squared distances from each centroid to its points, so its distortion <span class="math inline">\(J\)</span> is small. In the two local optima, one centroid sits far from many of its assigned points, so <span class="math inline">\(J\)</span> is larger.</p>
</section>
<section id="trying-multiple-initializations" class="level3">
<h3 class="anchored" data-anchor-id="trying-multiple-initializations">Trying Multiple Initializations</h3>
<p>This suggests a fix. To give k-means a better chance of finding the good clustering, <strong>run it multiple times</strong> with different random initializations, then pick the run with the <strong>lowest cost function <span class="math inline">\(J\)</span></strong>. Because the good clustering has the smallest distortion, selecting by lowest <span class="math inline">\(J\)</span> selects it.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Multiple random initializations
</div>
</div>
<div class="callout-body-container callout-body">
<p>For <span class="math inline">\(i = 1\)</span> to <span class="math inline">\(100\)</span> (say):</p>
<ul>
<li>Randomly initialize k-means (pick <span class="math inline">\(K\)</span> training examples as the initial centroids).</li>
<li>Run k-means to convergence, giving assignments <span class="math inline">\(c^{(1)}, \dots, c^{(m)}\)</span> and centroids <span class="math inline">\(\vec{\mu}_1, \dots, \vec{\mu}_K\)</span>.</li>
<li>Compute the distortion (cost function) <span class="math inline">\(J\)</span>.</li>
</ul>
<p>Pick the set of clusters that gave the <strong>lowest</strong> <span class="math inline">\(J\)</span>.</p>
</div>
</div>
<p>Running this often gives a much better set of clusters, with a much lower distortion, than running k-means only once. A common number of initializations is somewhere between <strong>50 and 1000</strong>. Running many more than 1000 times tends to get computationally expensive with diminishing returns, but trying at least 50 or 100 will often give a much better result than a single shot. In practice it is almost always worth using more than one random initialization.</p>
<p>The last piece of the k-means story is how to choose the number of clusters <span class="math inline">\(K\)</span>, covered next.</p>
</section>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. What is the recommended way to initialize the cluster centroids, and why must <span class="math inline">\(K &lt; m\)</span>?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Randomly pick <span class="math inline">\(K\)</span> distinct training examples and set the initial centroids to their locations. <span class="math inline">\(K\)</span> must be less than the number of examples <span class="math inline">\(m\)</span>, otherwise there are not enough training examples to place at least one on each centroid.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is a local optimum in the context of k-means, and how does it arise?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A local optimum is a clustering where k-means has converged, no point changes and no centroid moves, but the distortion <span class="math inline">\(J\)</span> is higher than the best achievable. It arises from an unlucky random initialization, for example two centroids landing in one group and none in another, which traps the algorithm at a suboptimal local minimum of <span class="math inline">\(J\)</span>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Describe the multiple-random-initializations procedure. How do you choose among the runs?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Run k-means many times (commonly 50 to 1000), each with a fresh random initialization, running each to convergence and computing its distortion <span class="math inline">\(J\)</span>. Then keep the run with the lowest <span class="math inline">\(J\)</span>. Since lower distortion means tighter clusters, this selects the best clustering found across all the attempts.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. You run k-means once and get a clustering that looks poor. Your colleague says “k-means is broken.” What is the more likely explanation and fix?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>k-means is not broken, it most likely converged to a local optimum from an unlucky initialization. The fix is to run it several times (say 50 to 100) with different random initializations and keep the result with the lowest distortion <span class="math inline">\(J\)</span>, which usually recovers a much better clustering.</p>
</div>
</div>
</div>
</section>
</section>
<section id="choosing-the-number-of-clusters" class="level2">
<h2 class="anchored" data-anchor-id="choosing-the-number-of-clusters">Choosing the Number of Clusters</h2>
<p>The k-means algorithm requires, as one of its inputs, <span class="math inline">\(K\)</span>, the number of clusters to find. How do you decide whether you want two clusters, three, five, or ten?</p>
<p>For a lot of clustering problems, the right value of <span class="math inline">\(K\)</span> is <strong>truly ambiguous</strong>. Show different people the same dataset and ask how many clusters they see, and some will say two distinct clusters, and they will be right, while others will see four distinct clusters, and they will also be right, and a case can even be made for three. Because clustering is unsupervised, there are no “right answers” in the form of labels to replicate, and the data itself often does not give a clear indicator of how many clusters it contains.</p>
<div id="82657097" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-8-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="elbow-method" class="level3">
<h3 class="anchored" data-anchor-id="elbow-method">Elbow Method</h3>
<p>The academic literature has a few techniques for automatically choosing the number of clusters, and one worth recognizing (because others refer to it) is the <strong>elbow method</strong>. Run k-means with a variety of values of <span class="math inline">\(K\)</span> and plot the cost function <span class="math inline">\(J\)</span>, the distortion, as a function of the number of clusters. With very few clusters the distortion is high, and it decreases as <span class="math inline">\(K\)</span> grows. If the curve decreases rapidly until, say, <span class="math inline">\(K = 3\)</span> and more slowly after that, the bend is called the <strong>elbow</strong>, think of the curve as an arm, with the bend as its elbow, and the method says to pick the <span class="math inline">\(K\)</span> at the elbow.</p>
<div id="e36e13d1" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-9-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Plotting the cost as a function of <span class="math inline">\(K\)</span> can help gain some insight, but in practice the method is less useful than it sounds. For a lot of applications the right number of clusters is truly ambiguous, and many cost curves look like the one on the right, decreasing smoothly with <strong>no clear elbow</strong> to point at. (The left curve above comes from the well-separated three-blob data of the previous section, where the elbow at 3 is real; the right curve comes from the continuous t-shirt data, where there is no bend to find.)</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Technique that does not work
</div>
</div>
<div class="callout-body-container callout-body">
<p>Do not choose <span class="math inline">\(K\)</span> to <strong>minimize</strong> the cost function <span class="math inline">\(J\)</span>. More clusters pretty much always reduces <span class="math inline">\(J\)</span>, the more centroids there are, the closer each point sits to one of them, so this rule would almost always just pick the largest possible <span class="math inline">\(K\)</span>.</p>
</div>
</div>
</section>
<section id="evaluating-k-means-by-its-downstream-purpose" class="level3">
<h3 class="anchored" data-anchor-id="evaluating-k-means-by-its-downstream-purpose">Evaluating K-means by Its Downstream Purpose</h3>
<p>How is <span class="math inline">\(K\)</span> chosen in practice? Often k-means runs in order to produce clusters for some <strong>later, downstream purpose</strong>, and the recommendation is to evaluate k-means by how well it serves that purpose. In the t-shirt example, running k-means with <span class="math inline">\(K = 3\)</span> gives clusters for sizing small, medium, and large, and running it with <span class="math inline">\(K = 5\)</span> gives extra small through extra large. <strong>Both are completely valid groupings.</strong> The choice between three or five sizes is a business decision, better fit with five sizes, versus the extra manufacturing and shipping costs of five t-shirt types instead of three, so run both, look at the two solutions, and decide based on that trade-off.</p>
<div id="70a17251" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-10-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The upcoming k-means lab applies the algorithm to <strong>image compression</strong>, one of the most fun visual examples of k-means, where the same reasoning appears as a trade-off between the quality of the compressed image and how much space it saves, and the best <span class="math inline">\(K\)</span> can be decided manually from that trade-off.</p>
<p>That completes the k-means clustering algorithm, and with it, your first unsupervised learning algorithm. The next topic is the second unsupervised learning algorithm of the course, <strong>anomaly detection</strong>, looking at a dataset and finding unusual or anomalous things in it, another commercially important application of unsupervised learning.</p>
</section>
<section id="review-questions-5" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-5">Review Questions</h3>
<p><strong>1. Why is the “right” number of clusters often genuinely ambiguous?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because clustering is unsupervised, there are no labels providing a right answer to replicate, and the data itself frequently supports multiple readings, the same dataset can reasonably be seen as two clusters or as four. Different people looking at the same points can disagree and both be right.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Describe the elbow method and its main limitation.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-27-contents" aria-controls="callout-27" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-27" class="callout-27-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Run k-means for a range of <span class="math inline">\(K\)</span> values, plot the distortion <span class="math inline">\(J\)</span> against <span class="math inline">\(K\)</span>, and pick the <span class="math inline">\(K\)</span> at the “elbow,” where the curve stops decreasing rapidly and starts decreasing slowly. The limitation is that many real cost curves decrease smoothly with no clear elbow, leaving nothing to point at, which is why the method often does not settle the question in practice.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is choosing <span class="math inline">\(K\)</span> to minimize the cost function <span class="math inline">\(J\)</span> not a good technique?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-28-contents" aria-controls="callout-28" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-28" class="callout-28-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because increasing <span class="math inline">\(K\)</span> almost always decreases <span class="math inline">\(J\)</span>, with more centroids, every point ends up closer to some centroid. Minimizing <span class="math inline">\(J\)</span> over <span class="math inline">\(K\)</span> would therefore nearly always select the largest possible <span class="math inline">\(K\)</span>, regardless of what grouping actually makes sense for the data or the application.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the t-shirt example, both <span class="math inline">\(K = 3\)</span> and <span class="math inline">\(K = 5\)</span> produce valid clusterings. What is the recommended way to choose between them?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-29-contents" aria-controls="callout-29" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-29" class="callout-29-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Evaluate k-means by its downstream purpose. Run both, then weigh the trade-off that matters to the business, five sizes fit customers better, but manufacturing and shipping five t-shirt types costs more than three. The right <span class="math inline">\(K\)</span> is the one that best serves what the clusters will actually be used for, not a property of the data alone.</p>
</div>
</div>
</div>
</section>
</section>
<section id="lab-k-means-and-image-compression" class="level2">
<h2 class="anchored" data-anchor-id="lab-k-means-and-image-compression">Lab: K-means and Image Compression</h2>
<p>This lab implements the k-means algorithm and then uses it for <strong>image compression</strong>. It starts with a sample 2D dataset to build intuition, and then reduces the number of colors in an image to only the 16 that best represent it. The two graded functions are exactly the two steps of the <a href="#k-means-algorithm">algorithm</a>, finding the closest centroids and recomputing the centroid means.</p>
<div id="ab696d2b" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="exercise-1-finding-closest-centroids" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1-finding-closest-centroids">Exercise 1: Finding Closest Centroids</h3>
<p>In the cluster assignment phase, the algorithm assigns every example <span class="math inline">\(\vec{x}^{(i)}\)</span> to its closest centroid, given the current centroid positions. The function takes the data matrix <code>X</code> and the centroid locations <code>centroids</code>, and outputs a one-dimensional array <code>idx</code> holding the index of the closest centroid for every example.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Indexing note
</div>
</div>
<div class="callout-body-container callout-body">
<p>In code, the centroid index runs from <span class="math inline">\(0\)</span> to <span class="math inline">\(K-1\)</span> rather than the <span class="math inline">\(1\)</span> to <span class="math inline">\(K\)</span> of the lectures, because Python list indices start at 0.</p>
</div>
</div>
<p>For every example, <span class="math inline">\(c^{(i)} := j\)</span> that minimizes <span class="math inline">\(\lVert \vec{x}^{(i)} - \vec{\mu}_j \rVert^2\)</span>, where <span class="math inline">\(\vec{\mu}_j\)</span> is the position of the <span class="math inline">\(j\)</span>’th centroid ( <code>centroids[j]</code> in the code) and the double bars are the L2 norm, computed with <code>np.linalg.norm</code>.</p>
<div id="022979c2" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> find_closest_centroids(X, centroids):</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Computes the centroid memberships for every example.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray): (m, n) Input values</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co">        centroids (ndarray): (K, n) centroids</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co">        idx (array_like): (m,) closest centroids</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    K <span class="op">=</span> centroids.shape[<span class="dv">0</span>]</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> np.zeros(X.shape[<span class="dv">0</span>], dtype<span class="op">=</span><span class="bu">int</span>)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(X.shape[<span class="dv">0</span>]):</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>        distance <span class="op">=</span> []</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(K):</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>            norm_ij <span class="op">=</span> np.linalg.norm(X[i] <span class="op">-</span> centroids[j])</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>            distance.append(norm_ij)</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>        idx[i] <span class="op">=</span> np.argmin(distance)</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> idx</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Check the implementation on an example dataset (<a href="../../media/ex7_X.npy">download</a>) with three hand-placed centroids.</p>
<div id="b6537536" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.load(<span class="st">"../../media/ex7_X.npy"</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First five elements of X are:</span><span class="ch">\n</span><span class="st">"</span>, X[:<span class="dv">5</span>])</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The shape of X is:"</span>, X.shape)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Select an initial set of centroids (3 Centroids)</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>initial_centroids <span class="op">=</span> np.array([[<span class="dv">3</span>, <span class="dv">3</span>], [<span class="dv">6</span>, <span class="dv">2</span>], [<span class="dv">8</span>, <span class="dv">5</span>]])</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Find closest centroids using initial_centroids</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> find_closest_centroids(X, initial_centroids)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Print closest centroids for the first three elements</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"First three elements in idx are:"</span>, idx[:<span class="dv">3</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>First five elements of X are:
 [[1.84207953 4.6075716 ]
 [5.65858312 4.79996405]
 [6.35257892 3.2908545 ]
 [2.90401653 4.61220411]
 [3.23197916 4.93989405]]
The shape of X is: (300, 2)
First three elements in idx are: [0 2 1]</code></pre>
</div>
</div>
<p>The expected output is <code>[0 2 1]</code>, the first example is closest to centroid 0, the second to centroid 2, and the third to centroid 1.</p>
</section>
<section id="exercise-2-computing-centroid-means" class="level3">
<h3 class="anchored" data-anchor-id="exercise-2-computing-centroid-means">Exercise 2: Computing Centroid Means</h3>
<p>Given the assignments, the second phase recomputes, for each centroid, the mean of the points assigned to it,</p>
<p><span class="math display">\[
\vec{\mu}_k = \frac{1}{|C_k|} \sum_{i \in C_k} \vec{x}^{(i)}
\]</span></p>
<p>where <span class="math inline">\(C_k\)</span> is the set of examples assigned to centroid <span class="math inline">\(k\)</span> and <span class="math inline">\(|C_k|\)</span> is how many there are. Concretely, if examples <span class="math inline">\(\vec{x}^{(3)}\)</span> and <span class="math inline">\(\vec{x}^{(5)}\)</span> are assigned to centroid <span class="math inline">\(k = 2\)</span>, then <span class="math inline">\(\vec{\mu}_2 = \frac{1}{2}\left(\vec{x}^{(3)} + \vec{x}^{(5)}\right)\)</span>.</p>
<div id="92bd7208" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_centroids(X, idx, K):</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns the new centroids by computing the means of the</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">    data points assigned to each centroid.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray):   (m, n) Data points</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">        idx (ndarray): (m,) Array containing index of the closest centroid</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co">                       for each example in X</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co">        K (int):       number of centroids</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co">        centroids (ndarray): (K, n) New centroids computed</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    m, n <span class="op">=</span> X.shape</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    centroids <span class="op">=</span> np.zeros((K, n))</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(K):</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        points <span class="op">=</span> X[idx <span class="op">==</span> k]</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>        centroids[k] <span class="op">=</span> np.mean(points, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> centroids</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>centroids <span class="op">=</span> compute_centroids(X, idx, K)</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The centroids are:"</span>, centroids)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>The centroids are: [[2.42830111 3.15792418]
 [5.81350331 2.63365645]
 [7.11938687 3.6166844 ]]</code></pre>
</div>
</div>
<p>The handy trick here is <code>X[idx == k]</code>, which selects exactly the rows of <code>X</code> whose assignment equals <code>k</code>, and <code>np.mean(..., axis=0)</code> averages them feature by feature.</p>
</section>
<section id="k-means-on-a-sample-dataset" class="level3">
<h3 class="anchored" data-anchor-id="k-means-on-a-sample-dataset">K-means on a Sample Dataset</h3>
<p>With the two functions complete, <code>run_kMeans</code> calls them in a loop, exactly the pseudocode of the algorithm. The visualization helpers below draw each iteration’s assignments and the centroids’ movement trails; they are presentation code only.</p>
<div id="e9336f64" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> run_kMeans(X, initial_centroids, max_iters<span class="op">=</span><span class="dv">10</span>, plot_progress<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Runs the K-Means algorithm on data matrix X, where each row of X</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">    is a single example.</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    m, n <span class="op">=</span> X.shape</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>    K <span class="op">=</span> initial_centroids.shape[<span class="dv">0</span>]</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>    centroids <span class="op">=</span> initial_centroids</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    previous_centroids <span class="op">=</span> centroids</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> np.zeros(m)</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> plot_progress:</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        plt.figure(figsize<span class="op">=</span>(<span class="dv">8</span>, <span class="dv">6</span>))</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(max_iters):</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="st">"K-Means iteration </span><span class="sc">%d</span><span class="st">/</span><span class="sc">%d</span><span class="st">"</span> <span class="op">%</span> (i, max_iters <span class="op">-</span> <span class="dv">1</span>))</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>        <span class="co"># For each example in X, assign it to the closest centroid</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>        idx <span class="op">=</span> find_closest_centroids(X, centroids)</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> plot_progress:</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>            plot_progress_kMeans(X, centroids, previous_centroids, idx, K, i)</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>            previous_centroids <span class="op">=</span> centroids</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Given the memberships, compute new centroids</span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>        centroids <span class="op">=</span> compute_centroids(X, idx, K)</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> plot_progress:</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>        plt.show()</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> centroids, idx</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-31-contents" aria-controls="callout-31" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Plotting helpers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-31" class="callout-31-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div id="2be8a9ff" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.colors <span class="im">import</span> ListedColormap</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> draw_line(p1, p2, style<span class="op">=</span><span class="st">"-k"</span>, linewidth<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    plt.plot([p1[<span class="dv">0</span>], p2[<span class="dv">0</span>]], [p1[<span class="dv">1</span>], p2[<span class="dv">1</span>]], style, linewidth<span class="op">=</span>linewidth)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_data_points(X, idx):</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    cmap <span class="op">=</span> ListedColormap([<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"blue"</span>])</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    c <span class="op">=</span> cmap(idx)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    plt.scatter(X[:, <span class="dv">0</span>], X[:, <span class="dv">1</span>], facecolors<span class="op">=</span><span class="st">"none"</span>, edgecolors<span class="op">=</span>c,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>                linewidth<span class="op">=</span><span class="fl">0.5</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_progress_kMeans(X, centroids, previous_centroids, idx, K, i):</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    plot_data_points(X, idx)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    plt.scatter(centroids[:, <span class="dv">0</span>], centroids[:, <span class="dv">1</span>], marker<span class="op">=</span><span class="st">"x"</span>, c<span class="op">=</span><span class="st">"k"</span>, linewidths<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(centroids.shape[<span class="dv">0</span>]):</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>        draw_line(centroids[j, :], previous_centroids[j, :])</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="st">"Iteration number </span><span class="sc">%d</span><span class="st">"</span> <span class="op">%</span> i)</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_kMeans_RGB(X, centroids, idx, K):</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>    fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">7</span>, <span class="dv">7</span>))</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> fig.add_subplot(<span class="dv">111</span>, projection<span class="op">=</span><span class="st">"3d"</span>)</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="op">*</span>X.T <span class="op">*</span> <span class="dv">255</span>, zdir<span class="op">=</span><span class="st">"z"</span>, depthshade<span class="op">=</span><span class="va">False</span>, s<span class="op">=</span><span class="fl">0.3</span>, c<span class="op">=</span>X)</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    ax.scatter(<span class="op">*</span>centroids.T <span class="op">*</span> <span class="dv">255</span>, zdir<span class="op">=</span><span class="st">"z"</span>, depthshade<span class="op">=</span><span class="va">False</span>, s<span class="op">=</span><span class="dv">500</span>,</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>               c<span class="op">=</span><span class="st">"red"</span>, marker<span class="op">=</span><span class="st">"x"</span>, lw<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>    ax.set_xlabel(<span class="st">"R value - Redness"</span>)</span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a>    ax.set_ylabel(<span class="st">"G value - Greenness"</span>)</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    ax.set_zlabel(<span class="st">"B value - Blueness"</span>)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    ax.set_title(<span class="st">"Original colors and their color clusters' centroids"</span>)</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> show_centroid_colors(centroids):</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    palette <span class="op">=</span> np.expand_dims(centroids, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    num <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="bu">len</span>(centroids))</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="fl">1.6</span>))</span>
<span id="cb8-35"><a href="#cb8-35" aria-hidden="true" tabindex="-1"></a>    plt.xticks(num)</span>
<span id="cb8-36"><a href="#cb8-36" aria-hidden="true" tabindex="-1"></a>    plt.yticks([])</span>
<span id="cb8-37"><a href="#cb8-37" aria-hidden="true" tabindex="-1"></a>    plt.imshow(palette)</span>
<span id="cb8-38"><a href="#cb8-38" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</div>
<div id="2484c201" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set initial centroids and number of iterations</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>initial_centroids <span class="op">=</span> np.array([[<span class="dv">3</span>, <span class="dv">3</span>], [<span class="dv">6</span>, <span class="dv">2</span>], [<span class="dv">8</span>, <span class="dv">5</span>]])</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>max_iters <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Run K-Means</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>centroids, idx <span class="op">=</span> run_kMeans(X, initial_centroids, max_iters, plot_progress<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-Means iteration 0/9
K-Means iteration 1/9
K-Means iteration 2/9
K-Means iteration 3/9
K-Means iteration 4/9
K-Means iteration 5/9
K-Means iteration 6/9
K-Means iteration 7/9
K-Means iteration 8/9
K-Means iteration 9/9</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-17-output-2.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The final centroids are the black X marks in the middle of the colored clusters, and the connected X marks trace how each centroid traveled to get there, the <a href="#k-means-intuition">assign-and-move dance</a> drawn all at once.</p>
</section>
<section id="random-initialization-in-code" class="level3">
<h3 class="anchored" data-anchor-id="random-initialization-in-code">Random Initialization in Code</h3>
<p>The initial centroids above were hand-placed so the figure comes out the same every time. In practice, the strategy from the <a href="#random-initialization">random initialization section</a> applies, select random examples from the training set. The function below first shuffles the indices of the examples with <code>np.random.permutation()</code>, then takes the first <span class="math inline">\(K\)</span>, which selects examples at random without any risk of picking the same one twice.</p>
<div id="17dd89da" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> kMeans_init_centroids(X, K):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">    This function initializes K centroids to be used with</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co">    K-Means on the dataset X.</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray): Data points</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="co">        K (int):     number of centroids/clusters</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co">        centroids (ndarray): Initialized centroids</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Randomly reorder the indices of examples</span></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    randidx <span class="op">=</span> np.random.permutation(X.shape[<span class="dv">0</span>])</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take the first K examples as centroids</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>    centroids <span class="op">=</span> X[randidx[:K]]</span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> centroids</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">7</span>)</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>initial_centroids <span class="op">=</span> kMeans_init_centroids(X, K)</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>centroids, idx <span class="op">=</span> run_kMeans(X, initial_centroids, max_iters, plot_progress<span class="op">=</span><span class="va">True</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-Means iteration 0/9
K-Means iteration 1/9
K-Means iteration 2/9
K-Means iteration 3/9
K-Means iteration 4/9
K-Means iteration 5/9
K-Means iteration 6/9
K-Means iteration 7/9
K-Means iteration 8/9
K-Means iteration 9/9</code></pre>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-18-output-2.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Running this cell repeatedly (with different seeds) produces different clusterings depending on the initial points chosen, exactly the local-optima behavior discussed earlier.</p>
</section>
<section id="image-compression-with-k-means" class="level3">
<h3 class="anchored" data-anchor-id="image-compression-with-k-means">Image Compression with K-means</h3>
<p>Now the payoff. In a straightforward 24-bit color representation of an image, each pixel is three 8-bit unsigned integers (0 to 255) specifying the red, green, and blue intensity values, the <strong>RGB encoding</strong>. The image here (<a href="../../media/bird_small.png">download</a>) contains thousands of colors, and k-means will reduce them to just <strong>16</strong>, by treating every pixel as a data example in 3-dimensional RGB space and finding the 16 colors that best cluster the pixels.</p>
<div id="2ba791e8" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>original_img <span class="op">=</span> plt.imread(<span class="st">"../../media/bird_small.png"</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>plt.imshow(original_img)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>plt.axis(<span class="st">"off"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of original_img is:"</span>, original_img.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-19-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of original_img is: (128, 128, 3)</code></pre>
</div>
</div>
<p>The image is a three-dimensional matrix, the first two indices identify a pixel position and the third is red, green, or blue, so <code>original_img[50, 33, 2]</code> is the blue intensity of the pixel at row 50, column 33. To run k-means, reshape it into an <span class="math inline">\(m \times 3\)</span> matrix of pixel colors, where <span class="math inline">\(m = 128 \times 128 = 16384\)</span>. (PNG files load with values already in the 0 to 1 range; a JPG would need dividing by 255 first.)</p>
<div id="2f2c0eb6" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape the image into an m x 3 matrix where m = number of pixels</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Each row contains the Red, Green and Blue pixel values</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>X_img <span class="op">=</span> np.reshape(original_img, (original_img.shape[<span class="dv">0</span>] <span class="op">*</span> original_img.shape[<span class="dv">1</span>], <span class="dv">3</span>))</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of X_img:"</span>, X_img.shape)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Shape of X_img: (16384, 3)</code></pre>
</div>
</div>
<p>Run k-means on the pixel data with <span class="math inline">\(K = 16\)</span>. This is the same <code>run_kMeans</code> as before, just with 16,384 examples in 3 dimensions instead of 300 examples in 2.</p>
<div id="ce334f9d" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>K <span class="op">=</span> <span class="dv">16</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>max_iters <span class="op">=</span> <span class="dv">10</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>np.random.seed(<span class="dv">3</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>initial_centroids <span class="op">=</span> kMeans_init_centroids(X_img, K)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>centroids, idx <span class="op">=</span> run_kMeans(X_img, initial_centroids, max_iters)</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shape of idx:"</span>, idx.shape)</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Closest centroid for the first five elements:"</span>, idx[:<span class="dv">5</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-Means iteration 0/9
K-Means iteration 1/9
K-Means iteration 2/9
K-Means iteration 3/9
K-Means iteration 4/9
K-Means iteration 5/9
K-Means iteration 6/9
K-Means iteration 7/9
K-Means iteration 8/9
K-Means iteration 9/9
Shape of idx: (16384,)
Closest centroid for the first five elements: [11  9  9  9 11]</code></pre>
</div>
</div>
<p>Every color in the original image is a dot in 3D RGB space, and the red X marks are the 16 centroids k-means found, the 16 colors that will represent the compressed image.</p>
<div id="783dddf9" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>plot_kMeans_RGB(X_img, centroids, idx, K)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>show_centroid_colors(centroids)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-22-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-22-output-2.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="compressing-the-image" class="level3">
<h3 class="anchored" data-anchor-id="compressing-the-image">Compressing the Image</h3>
<p>With the 16 colors chosen, assign each pixel to its closest centroid and replace it with that centroid’s color. This is where the compression happens.</p>
<ul>
<li>The original image needs 24 bits (8 bits for each of the three channels) per pixel, <span class="math inline">\(128 \times 128 \times 24 = 393{,}216\)</span> bits in total.</li>
<li>The compressed representation stores a small dictionary of 16 colors at 24 bits each, and then only <strong>4 bits per pixel</strong> (enough to index 16 possibilities), <span class="math inline">\(16 \times 24 + 128 \times 128 \times 4 = 65{,}920\)</span> bits.</li>
</ul>
<p>That compresses the image by about a <strong>factor of 6</strong>.</p>
<div id="0a09e3cc" class="cell" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Find the closest centroid of each pixel</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>idx <span class="op">=</span> find_closest_centroids(X_img, centroids)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace each pixel with the color of the closest centroid</span></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>X_recovered <span class="op">=</span> centroids[idx, :]</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reshape image into proper dimensions</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>X_recovered <span class="op">=</span> np.reshape(X_recovered, original_img.shape)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">9</span>, <span class="dv">5</span>))</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].imshow(original_img)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">"Original"</span>)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_axis_off()</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].imshow(X_recovered)</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">"Compressed with </span><span class="sc">%d</span><span class="st"> colours"</span> <span class="op">%</span> K)</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_axis_off()</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="clustering_files/figure-html/cell-23-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The reconstruction retains most of the characteristics of the original, with some visible compression artifacts from using fewer colors. This is also where the <a href="#choosing-the-number-of-clusters">choosing <span class="math inline">\(K\)</span> discussion</a> becomes concrete, a larger <span class="math inline">\(K\)</span> gives a better-looking image but a bigger file, and the right trade-off is a judgment call, not something the data decides for you.</p>
</section>
<section id="review-questions-6" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-6">Review Questions</h3>
<p><strong>1. In the code, <code>idx[i]</code> ranges from 0 to <span class="math inline">\(K-1\)</span>, but the lectures wrote <span class="math inline">\(c^{(i)}\)</span> as ranging from 1 to <span class="math inline">\(K\)</span>. Why the difference?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-32-contents" aria-controls="callout-32" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-32" class="callout-32-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Python list and array indices start at 0, so the code labels the centroids 0 through <span class="math inline">\(K-1\)</span>. It is purely a bookkeeping convention, the algorithm is identical, and <code>idx[i]</code> plays exactly the role of <span class="math inline">\(c^{(i)}\)</span>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. <code>kMeans_init_centroids</code> shuffles the example indices with a permutation and takes the first <span class="math inline">\(K\)</span>. How does this differ from sampling with replacement, and why is that the right choice here?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-33-contents" aria-controls="callout-33" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-33" class="callout-33-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A permutation cannot repeat an index, so the <span class="math inline">\(K\)</span> chosen examples are guaranteed distinct, whereas sampling with replacement could pick the same example twice. For centroid initialization, duplicates would be harmful, two centroids starting at the identical point, so selecting without replacement is exactly what is wanted. (Sampling <em>with</em> replacement has its own separate role, generating training sets for tree ensembles.)</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Walk through the compression arithmetic. Where does the factor of about 6 come from?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-34-contents" aria-controls="callout-34" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-34" class="callout-34-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The original stores 24 bits per pixel: <span class="math inline">\(128 \times 128 \times 24 = 393{,}216\)</span> bits. The compressed version stores a 16-color dictionary (<span class="math inline">\(16 \times 24 = 384\)</span> bits) plus a 4-bit color index per pixel (<span class="math inline">\(128 \times 128 \times 4 = 65{,}536\)</span> bits), totaling <span class="math inline">\(65{,}920\)</span> bits. The ratio <span class="math inline">\(393{,}216 / 65{,}920 \approx 6\)</span> is the compression factor.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the image compression setting, what plays the role of a “training example,” and what do the 16 cluster centroids represent?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-35-contents" aria-controls="callout-35" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-35" class="callout-35-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Each pixel is a training example, a point in 3-dimensional RGB space with its red, green, and blue values as features. The 16 centroids are the 16 representative colors that best cluster all the pixel colors, and compression replaces every pixel with its cluster’s centroid color.</p>
</div>
</div>
</div>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 18%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">18% completed (160 of 884 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../machine-learning/unsupervised-learning/anomaly-detection.html" class="pagination-link" aria-label="Anomaly Detection">
        <span class="nav-page-text">Anomaly Detection</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>