<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-20">
<meta name="description" content="Making collaborative filtering work: mean normalization for brand-new users, implementing the algorithm in TensorFlow with Auto Diff and the Adam optimizer, finding related items from learned features, the limitations that motivate content-based filtering, and a practice lab building a movie recommender on the MovieLens dataset.">

<title>Collaborative Filtering in Practice – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Collaborative Filtering in Practice – Hossein’s Notes">
<meta property="og:description" content="Making collaborative filtering work: mean normalization for brand-new users, implementing the algorithm in TensorFlow with Auto Diff and the Adam optimizer, finding related items from learned features, the limitations that motivate content-based filtering, and a practice lab building a movie recommender on the MovieLens dataset.">
<meta property="og:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/collaborative-filtering-in-practice_files/figure-html/cell-3-output-1.svg">
<meta property="og:site_name" content="Hossein’s Notes">
<meta name="twitter:title" content="Collaborative Filtering in Practice – Hossein’s Notes">
<meta name="twitter:description" content="Making collaborative filtering work: mean normalization for brand-new users, implementing the algorithm in TensorFlow with Auto Diff and the Adam optimizer, finding related items from learned features, the limitations that motivate content-based filtering, and a practice lab building a movie recommender on the MovieLens dataset.">
<meta name="twitter:image" content="https://h.oliabak.com/machine-learning/unsupervised-learning/collaborative-filtering-in-practice_files/figure-html/cell-3-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-agentic-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Agentic AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-agentic-ai">    
        <li>
    <a class="dropdown-item" href="../../agentic/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/frameworks.html">
 <span class="dropdown-text">Frameworks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/agent-architecture.html">
 <span class="dropdown-text">Agent Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/async-io.html">
 <span class="dropdown-text">Async I/O</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Trainer</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/unsupervised-learning/collaborative-filtering-in-practice.html">Collaborative Filtering in Practice</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anomaly Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering-in-practice.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Collaborative Filtering in Practice</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#mean-normalization" id="toc-mean-normalization" class="nav-link active" data-scroll-target="#mean-normalization">Mean Normalization</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#implementing-it-in-tensorflow" id="toc-implementing-it-in-tensorflow" class="nav-link" data-scroll-target="#implementing-it-in-tensorflow">Implementing It in TensorFlow</a>
  <ul class="collapse">
  <li><a href="#adam-and-the-full-algorithm" id="toc-adam-and-the-full-algorithm" class="nav-link" data-scroll-target="#adam-and-the-full-algorithm">Adam and the Full Algorithm</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#finding-related-items" id="toc-finding-related-items" class="nav-link" data-scroll-target="#finding-related-items">Finding Related Items</a>
  <ul class="collapse">
  <li><a href="#limitations-of-collaborative-filtering" id="toc-limitations-of-collaborative-filtering" class="nav-link" data-scroll-target="#limitations-of-collaborative-filtering">Limitations of Collaborative Filtering</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#lab-movie-recommendations-with-collaborative-filtering" id="toc-lab-movie-recommendations-with-collaborative-filtering" class="nav-link" data-scroll-target="#lab-movie-recommendations-with-collaborative-filtering">Lab: Movie Recommendations with Collaborative Filtering</a>
  <ul class="collapse">
  <li><a href="#dataset" id="toc-dataset" class="nav-link" data-scroll-target="#dataset">Dataset</a></li>
  <li><a href="#exercise-1-cost-function-with-loops" id="toc-exercise-1-cost-function-with-loops" class="nav-link" data-scroll-target="#exercise-1-cost-function-with-loops">Exercise 1: Cost Function with Loops</a></li>
  <li><a href="#vectorized-cost-function" id="toc-vectorized-cost-function" class="nav-link" data-scroll-target="#vectorized-cost-function">Vectorized Cost Function</a></li>
  <li><a href="#adding-your-own-ratings" id="toc-adding-your-own-ratings" class="nav-link" data-scroll-target="#adding-your-own-ratings">Adding Your Own Ratings</a></li>
  <li><a href="#training" id="toc-training" class="nav-link" data-scroll-target="#training">Training</a></li>
  <li><a href="#recommendations" id="toc-recommendations" class="nav-link" data-scroll-target="#recommendations">Recommendations</a></li>
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Collaborative Filtering in Practice</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">unsupervised-learning</div>
  </div>
  </div>

<div>
  <div class="description">
    Making collaborative filtering work: mean normalization for brand-new users, implementing the algorithm in TensorFlow with Auto Diff and the Adam optimizer, finding related items from learned features, the limitations that motivate content-based filtering, and a practice lab building a movie recommender on the MovieLens dataset.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 20, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~168 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level and capped at 3 hours.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~4,800 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>The <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html">previous page</a> built the collaborative filtering algorithm: a cost function <span class="math inline">\(J(\vec{w}, b, \vec{x})\)</span> over the observed movie ratings, minimized over the per-user parameters <span class="math inline">\(\vec{w}^{(j)}, b^{(j)}\)</span> and the per-movie features <span class="math inline">\(\vec{x}^{(i)}\)</span> all at once. This page is about making it work well in practice: a normalization trick that fixes the algorithm’s embarrassing behavior on brand-new users, an actual TensorFlow implementation, and a bonus use of the learned features, finding related items, before closing with the limitations that motivate the next algorithm.</p>
<section id="mean-normalization" class="level2">
<h2 class="anchored" data-anchor-id="mean-normalization">Mean Normalization</h2>
<p>Back in the first course, <a href="../../machine-learning/supervised-machine-learning/feature-scaling.html">feature scaling</a> helped linear regression run faster by putting all the features on a comparable scale. Collaborative filtering has its own version of this trick. With ratings that range over numbers like 0 to 5 stars, the algorithm runs a bit more efficiently, and, more importantly, makes much more sensible predictions for brand-new users, if the ratings are first <strong>mean normalized</strong> so that each movie’s ratings average out to zero.</p>
<p>To see why this matters, take the ratings table from the previous page and add a fifth user, <strong>Eve</strong>, who has not rated any movies yet:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Movie</th>
<th style="text-align: center;">Alice (1)</th>
<th style="text-align: center;">Bob (2)</th>
<th style="text-align: center;">Carol (3)</th>
<th style="text-align: center;">Dave (4)</th>
<th style="text-align: center;">Eve (5)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Love at Last</td>
<td style="text-align: center;"><span class="star-filled">★★★★★</span> <span class="star-num">5</span></td>
<td style="text-align: center;"><span class="star-filled">★★★★★</span> <span class="star-num">5</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td>Romance Forever</td>
<td style="text-align: center;"><span class="star-filled">★★★★★</span> <span class="star-num">5</span></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;">?</td>
</tr>
<tr class="odd">
<td>Cute Puppies of Love</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;"><span class="star-filled">★★★★</span><span class="star-empty">☆</span> <span class="star-num">4</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td>Nonstop Car Chases</td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;"><span class="star-filled">★★★★★</span> <span class="star-num">5</span></td>
<td style="text-align: center;"><span class="star-filled">★★★★</span><span class="star-empty">☆</span> <span class="star-num">4</span></td>
<td style="text-align: center;">?</td>
</tr>
<tr class="odd">
<td>Swords vs.&nbsp;Karate</td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;"><span class="star-filled">★★★★★</span> <span class="star-num">5</span></td>
<td style="text-align: center;"><span class="star-empty">☆☆☆☆☆</span> <span class="star-num">0</span></td>
<td style="text-align: center;">?</td>
</tr>
</tbody>
</table>
<p>What would the algorithm, as built so far, predict for Eve? Something unhelpful. Because Eve has rated nothing, none of the squared-error terms in the cost function involve her parameters <span class="math inline">\(\vec{w}^{(5)}, b^{(5)}\)</span> at all, the only place they appear is the regularization term, which pulls <span class="math inline">\(\vec{w}^{(5)}\)</span> toward zero. So minimizing the cost gives <span class="math inline">\(\vec{w}^{(5)} = (0, 0)\)</span>, and since <span class="math inline">\(b\)</span> is not regularized but is initialized to 0 by default, most likely <span class="math inline">\(b^{(5)} = 0\)</span> too. The prediction for every movie <span class="math inline">\(i\)</span> is then</p>
<p><span class="math display">\[
\hat{y}(i, 5) = \vec{w}^{(5)} \cdot \vec{x}^{(i)} + b^{(5)} = 0
\]</span></p>
<p>The algorithm predicts Eve will rate <em>every single movie</em> zero stars, which is not a reasonable guess about a person just because they have not rated anything yet.</p>
<p>Mean normalization fixes this. First, take all of the values in the table, question marks included, and write them out as a two-dimensional matrix, one row per movie and one column per user, just a more compact way of holding exactly the same ratings:</p>
<p><span class="math display">\[
Y = \begin{bmatrix}
5 &amp; 5 &amp; 0 &amp; 0 &amp; ? \\
5 &amp; ? &amp; ? &amp; 0 &amp; ? \\
? &amp; 4 &amp; 0 &amp; ? &amp; ? \\
0 &amp; 0 &amp; 5 &amp; 4 &amp; ? \\
0 &amp; 0 &amp; 5 &amp; 0 &amp; ?
\end{bmatrix}
\]</span></p>
<p>To carry out mean normalization, go through this matrix row by row and, for each movie, compute the average of the ratings it actually received. Movie 1 got two 5s and two 0s, so its average is 2.5; movie 2 got a 5 and a 0, also 2.5; movie 3 averages 2; movie 4 averages 2.25; and movie 5, not that popular, got 0, 0, 5, and 0, averaging <span class="math inline">\(5/4 = 1.25\)</span>. Stack these averages into a vector</p>
<p><span class="math display">\[
\vec{\mu} = \begin{pmatrix} 2.5 \\ 2.5 \\ 2 \\ 2.25 \\ 1.25 \end{pmatrix}
\]</span></p>
<p>and subtract each movie’s mean <span class="math inline">\(\mu_i\)</span> from every rating of that movie. The question marks stay question marks, only real ratings get shifted:</p>
<div class="nowrap-first-col">
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Movie (<span class="math inline">\(\mu_i\)</span>)</th>
<th style="text-align: center;">Alice (1)</th>
<th style="text-align: center;">Bob (2)</th>
<th style="text-align: center;">Carol (3)</th>
<th style="text-align: center;">Dave (4)</th>
<th style="text-align: center;">Eve (5)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Love at Last (2.5)</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;"><span class="math inline">\(-2.5\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-2.5\)</span></td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td>Romance Forever (2.5)</td>
<td style="text-align: center;">2.5</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;"><span class="math inline">\(-2.5\)</span></td>
<td style="text-align: center;">?</td>
</tr>
<tr class="odd">
<td>Cute Puppies of Love (2)</td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;"><span class="math inline">\(-2\)</span></td>
<td style="text-align: center;">?</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td>Nonstop Car Chases (2.25)</td>
<td style="text-align: center;"><span class="math inline">\(-2.25\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-2.25\)</span></td>
<td style="text-align: center;">2.75</td>
<td style="text-align: center;">1.75</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="odd">
<td>Swords vs.&nbsp;Karate (1.25)</td>
<td style="text-align: center;"><span class="math inline">\(-1.25\)</span></td>
<td style="text-align: center;"><span class="math inline">\(-1.25\)</span></td>
<td style="text-align: center;">3.75</td>
<td style="text-align: center;"><span class="math inline">\(-1.25\)</span></td>
<td style="text-align: center;">?</td>
</tr>
</tbody>
</table>
</div>
<p>These shifted values become the new <span class="math inline">\(y(i,j)\)</span> that the algorithm trains on, as if Alice had given movie 1 a 2.5 and movie 4 a <span class="math inline">\(-2.25\)</span>. Learning <span class="math inline">\(\vec{w}^{(j)}, b^{(j)}, \vec{x}^{(i)}\)</span> proceeds exactly as before. The only other change comes at prediction time: since <span class="math inline">\(\mu_i\)</span> was subtracted out of movie <span class="math inline">\(i\)</span>’s ratings before training, it has to be added back to get an actual star rating (otherwise the model could predict negative stars, which is impossible on a 0-to-5 scale):</p>
<p><span class="math display">\[
\hat{y}(i, j) = \vec{w}^{(j)} \cdot \vec{x}^{(i)} + b^{(j)} + \mu_i
\]</span></p>
<p>Now look at what this does for Eve. Her parameters still come out as <span class="math inline">\(\vec{w}^{(5)} = (0,0)\)</span> and <span class="math inline">\(b^{(5)} = 0\)</span>, but the prediction for movie 1 becomes <span class="math inline">\(0 + \mu_1 = 2.5\)</span>. In fact, every one of Eve’s predicted ratings is simply <span class="math inline">\(\mu_i\)</span>, the average of what other users gave that movie, which is a far more reasonable starting guess for someone the system knows nothing about than a wall of zeros.</p>
<div id="ad3f46b3" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="collaborative-filtering-in-practice_files/figure-html/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>One design choice worth noting: this normalized the <strong>rows</strong> of the matrix (per movie), which helps with a <em>new user</em>. The alternative, normalizing the <strong>columns</strong> (per user), would instead help with a <em>brand-new movie</em> that nobody has rated. Row normalization is the more important of the two here: a reasonable default guess for a new user is genuinely useful, whereas a movie nobody has rated probably should not be shown to many users yet anyway. Normalizing just the rows works fine in practice, and it is what the practice lab uses.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Without mean normalization, why does the algorithm predict a new user will rate every movie 0 stars?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A user with no ratings contributes nothing to the squared-error part of the cost function, so their parameters only appear in the regularization term, which pushes <span class="math inline">\(\vec{w}^{(j)}\)</span> to <span class="math inline">\((0, \dots, 0)\)</span>; with <span class="math inline">\(b^{(j)}\)</span> initialized to 0 and never pulled anywhere else, it stays 0 too. The prediction <span class="math inline">\(\vec{w}^{(j)} \cdot \vec{x}^{(i)} + b^{(j)}\)</span> is then 0 for every movie.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Describe the two changes mean normalization makes to the algorithm, one before training and one at prediction time.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Before training, compute each movie’s average rating <span class="math inline">\(\mu_i\)</span> (over only the users who rated it) and subtract it from that movie’s ratings, then train on the shifted values. At prediction time, add <span class="math inline">\(\mu_i\)</span> back: <span class="math inline">\(\hat{y}(i,j) = \vec{w}^{(j)} \cdot \vec{x}^{(i)} + b^{(j)} + \mu_i\)</span>, so predictions land back on the real 0-to-5 star scale.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Rows or columns: which does this section normalize, and what would normalizing the other one help with instead?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It normalizes the rows, one mean per movie, which gives sensible default predictions for a new user who has rated nothing (they get each movie’s average). Normalizing the columns, one mean per user, would instead help with a brand-new movie nobody has rated, a less important case since an unrated movie probably should not be pushed to many users yet anyway.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The lecture described using “mean normalization” to do feature scaling of the ratings. Which equation below best describes this algorithm?</strong></p>
<p><strong>A.</strong> <span class="math display">\[
y_{\text{norm}}(i,j) = \frac{y(i,j) - \mu_i}{\max_i - \min_i}
\quad \text{where} \quad
\mu_i = \frac{1}{\sum_j r(i,j)} \sum_{j\,:\,r(i,j)=1} y(i,j)
\]</span></p>
<p><strong>B.</strong> <span class="math display">\[
y_{\text{norm}}(i,j) = \frac{y(i,j) - \mu_i}{\sigma_i}
\quad \text{where} \quad
\mu_i = \frac{1}{\sum_j r(i,j)} \sum_{j\,:\,r(i,j)=1} y(i,j), \quad
\sigma_i^2 = \frac{1}{\sum_j r(i,j)} \sum_{j\,:\,r(i,j)=1} \big(y(i,j) - \mu_i\big)^2
\]</span></p>
<p><strong>C.</strong> <span class="math display">\[
y_{\text{norm}}(i,j) = y(i,j) - \mu_i
\quad \text{where} \quad
\mu_i = \frac{1}{\sum_j r(i,j)} \sum_{j\,:\,r(i,j)=1} y(i,j)
\]</span></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>C.</strong> Mean normalization as used here only <em>subtracts</em> each movie’s mean <span class="math inline">\(\mu_i\)</span> (computed over just the users who rated it, that is the <span class="math inline">\(\frac{1}{\sum_j r(i,j)}\)</span> factor), producing a zero average value on a per-row basis, with nothing in the denominator. Option A is min-max scaling and option B is z-score standardization, both real <a href="../../machine-learning/supervised-machine-learning/feature-scaling.html">feature scaling</a> techniques from the first course, but not what the lecture described for ratings.</p>
</div>
</div>
</div>
</section>
</section>
<section id="implementing-it-in-tensorflow" class="level2">
<h2 class="anchored" data-anchor-id="implementing-it-in-tensorflow">Implementing It in TensorFlow</h2>
<p>TensorFlow is usually thought of as a tool for building neural networks, and it is, but it is also very useful for implementing other learning algorithms, collaborative filtering included. The reason is a feature called <strong>automatic differentiation</strong> (<strong>Auto Diff</strong> for short, and sometimes informally called Auto Grad, though technically Autograd is the name of one specific software package for it). Gradient descent needs the derivatives of the cost function, and deriving them by hand takes calculus. With Auto Diff, the only thing that needs writing is the <em>cost function itself</em>, and TensorFlow works out all the derivatives automatically.</p>
<p>Here is the idea on a tiny example first. Take a single parameter <span class="math inline">\(w\)</span>, a model <span class="math inline">\(f(x) = wx\)</span> with <span class="math inline">\(b = 0\)</span>, one training example <span class="math inline">\(x = 1, y = 1\)</span>, and the cost <span class="math inline">\(J = (wx - y)^2\)</span>. The gradient descent update is the familiar</p>
<p><span class="math display">\[
w \leftarrow w - \alpha \frac{\partial}{\partial w} J(w)
\]</span></p>
<p>and the TensorFlow version of it looks like this, with the new functions doing all the work marked on the numbered lines:</p>
<div id="c8d4a523" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-1"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-1-1"><a href="#annotated-cell-1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="annotated-cell-1-2"><a href="#annotated-cell-1-2" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-1-3" class="code-annotation-target"><a href="#annotated-cell-1-3" aria-hidden="true" tabindex="-1"></a>w <span class="op">=</span> tf.Variable(<span class="fl">3.0</span>)</span>
<span id="annotated-cell-1-4"><a href="#annotated-cell-1-4" aria-hidden="true" tabindex="-1"></a>x, y, alpha <span class="op">=</span> <span class="fl">1.0</span>, <span class="fl">1.0</span>, <span class="fl">0.01</span></span>
<span id="annotated-cell-1-5"><a href="#annotated-cell-1-5" aria-hidden="true" tabindex="-1"></a>iterations <span class="op">=</span> <span class="dv">500</span></span>
<span id="annotated-cell-1-6"><a href="#annotated-cell-1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-7"><a href="#annotated-cell-1-7" aria-hidden="true" tabindex="-1"></a>w_history <span class="op">=</span> [w.numpy()]</span>
<span id="annotated-cell-1-8"><a href="#annotated-cell-1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> <span class="bu">iter</span> <span class="kw">in</span> <span class="bu">range</span>(iterations):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-1-9" class="code-annotation-target"><a href="#annotated-cell-1-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> tf.GradientTape() <span class="im">as</span> tape:</span>
<span id="annotated-cell-1-10"><a href="#annotated-cell-1-10" aria-hidden="true" tabindex="-1"></a>        fwb <span class="op">=</span> w <span class="op">*</span> x</span>
<span id="annotated-cell-1-11"><a href="#annotated-cell-1-11" aria-hidden="true" tabindex="-1"></a>        costJ <span class="op">=</span> (fwb <span class="op">-</span> y) <span class="op">**</span> <span class="dv">2</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-1-12" class="code-annotation-target"><a href="#annotated-cell-1-12" aria-hidden="true" tabindex="-1"></a>    [dJdw] <span class="op">=</span> tape.gradient(costJ, [w])</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-1" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-1-13" class="code-annotation-target"><a href="#annotated-cell-1-13" aria-hidden="true" tabindex="-1"></a>    w.assign_add(<span class="op">-</span>alpha <span class="op">*</span> dJdw)</span>
<span id="annotated-cell-1-14"><a href="#annotated-cell-1-14" aria-hidden="true" tabindex="-1"></a>    w_history.append(w.numpy())</span>
<span id="annotated-cell-1-15"><a href="#annotated-cell-1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-1-16"><a href="#annotated-cell-1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"w after </span><span class="sc">{</span>iterations<span class="sc">}</span><span class="ss"> iterations: </span><span class="sc">{</span>w<span class="sc">.</span>numpy()<span class="sc">:.3f}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-1" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="3" data-code-annotation="1"><strong><code>tf.Variable</code></strong> creates the parameter <span class="math inline">\(w\)</span>, initialized to 3.0. Declaring it a <em>variable</em> is how TensorFlow is told this is a parameter to optimize.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="9" data-code-annotation="2"><strong><code>tf.GradientTape</code></strong> is the key piece: inside this block, TensorFlow records the sequence of operations used to compute <code>costJ</code> onto the “tape,” which is what makes automatic differentiation possible.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="12" data-code-annotation="3"><strong><code>tape.gradient</code></strong> plays the tape back to compute the derivative <span class="math inline">\(\frac{\partial J}{\partial w}\)</span> automatically, no calculus required.</span>
</dd>
<dt data-target-cell="annotated-cell-1" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-1" data-code-lines="13" data-code-annotation="4"><strong><code>assign_add</code></strong> performs the update <span class="math inline">\(w \leftarrow w - \alpha \frac{\partial J}{\partial w}\)</span>. TensorFlow variables need slightly special handling, which is why it is not written as plain <code>w = w - ...</code>.</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>w after 500 iterations: 1.000</code></pre>
</div>
</div>
<div id="38e386ef" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="collaborative-filtering-in-practice_files/figure-html/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Each red dot is one update, sliding down the cost curve from <span class="math inline">\(w = 3\)</span> to the minimum at <span class="math inline">\(w = 1\)</span>: big steps at first where the curve is steep, smaller and smaller ones as the slope flattens near the bottom. (The course slide runs only 30 iterations, but with this small learning rate that stops around <span class="math inline">\(w \approx 2.1\)</span>, so the loop here runs 500 to actually converge.) And all of it without ever writing down the derivative <span class="math inline">\(\frac{\partial J}{\partial w}\)</span> by hand.</p>
<section id="adam-and-the-full-algorithm" class="level3">
<h3 class="anchored" data-anchor-id="adam-and-the-full-algorithm">Adam and the Full Algorithm</h3>
<p>Once derivatives come for free, there is no need to stop at plain gradient descent. A more powerful optimizer like <a href="../../machine-learning/advanced-learning-algorithms/advanced-optimization.html">Adam</a> works with the exact same gradient tape. For collaborative filtering, the recipe is: write the <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html#the-full-collaborative-filtering-cost-function">combined cost function</a> <span class="math inline">\(J\)</span> from the previous page as code, taking the parameters <span class="math inline">\(\mathbf{X}, \mathbf{W}, \vec{b}\)</span>, the mean-normalized ratings, the matrix <span class="math inline">\(R\)</span> of which pairs are rated, and <span class="math inline">\(\lambda\)</span>, then let TensorFlow differentiate it and let Adam apply the updates. Here it is running end to end on the toy ratings table, Eve included:</p>
<div id="febc2b35" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="annotated-cell-2"><pre class="sourceCode python code-annotation-code code-with-copy code-annotated"><code class="sourceCode python"><span id="annotated-cell-2-1"><a href="#annotated-cell-2-1" aria-hidden="true" tabindex="-1"></a>movie_names <span class="op">=</span> [<span class="st">"Love at Last"</span>, <span class="st">"Romance Forever"</span>, <span class="st">"Cute Puppies of Love"</span>,</span>
<span id="annotated-cell-2-2"><a href="#annotated-cell-2-2" aria-hidden="true" tabindex="-1"></a>               <span class="st">"Nonstop Car Chases"</span>, <span class="st">"Swords vs. Karate"</span>]</span>
<span id="annotated-cell-2-3"><a href="#annotated-cell-2-3" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.array([</span>
<span id="annotated-cell-2-4"><a href="#annotated-cell-2-4" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">0</span>, <span class="dv">0</span>, np.nan],</span>
<span id="annotated-cell-2-5"><a href="#annotated-cell-2-5" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">5</span>, np.nan, np.nan, <span class="dv">0</span>, np.nan],</span>
<span id="annotated-cell-2-6"><a href="#annotated-cell-2-6" aria-hidden="true" tabindex="-1"></a>    [np.nan, <span class="dv">4</span>, <span class="dv">0</span>, np.nan, np.nan],</span>
<span id="annotated-cell-2-7"><a href="#annotated-cell-2-7" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">4</span>, np.nan],</span>
<span id="annotated-cell-2-8"><a href="#annotated-cell-2-8" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">5</span>, <span class="dv">0</span>, np.nan],</span>
<span id="annotated-cell-2-9"><a href="#annotated-cell-2-9" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="annotated-cell-2-10"><a href="#annotated-cell-2-10" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> (<span class="op">~</span>np.isnan(Y)).astype(<span class="bu">float</span>)                <span class="co"># r(i,j): 1 where a rating exists</span></span>
<span id="annotated-cell-2-11"><a href="#annotated-cell-2-11" aria-hidden="true" tabindex="-1"></a>mu <span class="op">=</span> np.nanmean(Y, axis<span class="op">=</span><span class="dv">1</span>, keepdims<span class="op">=</span><span class="va">True</span>)      <span class="co"># per-movie means, the vector mu</span></span>
<span id="annotated-cell-2-12"><a href="#annotated-cell-2-12" aria-hidden="true" tabindex="-1"></a>Ynorm <span class="op">=</span> np.where(R <span class="op">==</span> <span class="dv">1</span>, Y <span class="op">-</span> mu, <span class="dv">0</span>)            <span class="co"># mean-normalized ratings</span></span>
<span id="annotated-cell-2-13"><a href="#annotated-cell-2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-14"><a href="#annotated-cell-2-14" aria-hidden="true" tabindex="-1"></a>num_movies, num_users <span class="op">=</span> Y.shape</span>
<span id="annotated-cell-2-15"><a href="#annotated-cell-2-15" aria-hidden="true" tabindex="-1"></a>num_features <span class="op">=</span> <span class="dv">2</span></span>
<span id="annotated-cell-2-16"><a href="#annotated-cell-2-16" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-2-17" class="code-annotation-target"><a href="#annotated-cell-2-17" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cofi_cost_func(X, W, b, Ynorm, R, lambda_):</span>
<span id="annotated-cell-2-18"><a href="#annotated-cell-2-18" aria-hidden="true" tabindex="-1"></a>    err <span class="op">=</span> (tf.linalg.matmul(X, tf.transpose(W)) <span class="op">+</span> b <span class="op">-</span> Ynorm) <span class="op">*</span> R</span>
<span id="annotated-cell-2-19"><a href="#annotated-cell-2-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (<span class="fl">0.5</span> <span class="op">*</span> tf.reduce_sum(err <span class="op">**</span> <span class="dv">2</span>)</span>
<span id="annotated-cell-2-20"><a href="#annotated-cell-2-20" aria-hidden="true" tabindex="-1"></a>            <span class="op">+</span> (lambda_ <span class="op">/</span> <span class="dv">2</span>) <span class="op">*</span> (tf.reduce_sum(X <span class="op">**</span> <span class="dv">2</span>) <span class="op">+</span> tf.reduce_sum(W <span class="op">**</span> <span class="dv">2</span>)))</span>
<span id="annotated-cell-2-21"><a href="#annotated-cell-2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-22"><a href="#annotated-cell-2-22" aria-hidden="true" tabindex="-1"></a>tf.random.set_seed(<span class="dv">1234</span>)</span>
<span id="annotated-cell-2-23"><a href="#annotated-cell-2-23" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> tf.Variable(tf.random.normal((num_users, num_features), stddev<span class="op">=</span><span class="fl">0.1</span>))</span>
<span id="annotated-cell-2-24"><a href="#annotated-cell-2-24" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> tf.Variable(tf.random.normal((num_movies, num_features), stddev<span class="op">=</span><span class="fl">0.1</span>))</span>
<span id="annotated-cell-2-25"><a href="#annotated-cell-2-25" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> tf.Variable(tf.zeros((<span class="dv">1</span>, num_users)))</span>
<span id="annotated-cell-2-26"><a href="#annotated-cell-2-26" aria-hidden="true" tabindex="-1"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-2-27" class="code-annotation-target"><a href="#annotated-cell-2-27" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> tf.keras.optimizers.Adam(learning_rate<span class="op">=</span><span class="fl">1e-1</span>)</span>
<span id="annotated-cell-2-28"><a href="#annotated-cell-2-28" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="fl">0.1</span></span>
<span id="annotated-cell-2-29"><a href="#annotated-cell-2-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-30"><a href="#annotated-cell-2-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> <span class="bu">iter</span> <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">200</span>):</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-2-31" class="code-annotation-target"><a href="#annotated-cell-2-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> tf.GradientTape() <span class="im">as</span> tape:</span>
<span id="annotated-cell-2-32"><a href="#annotated-cell-2-32" aria-hidden="true" tabindex="-1"></a>        cost_value <span class="op">=</span> cofi_cost_func(X, W, b, Ynorm, R, lambda_)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-2-33" class="code-annotation-target"><a href="#annotated-cell-2-33" aria-hidden="true" tabindex="-1"></a>    grads <span class="op">=</span> tape.gradient(cost_value, [X, W, b])</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-2" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-2-34" class="code-annotation-target"><a href="#annotated-cell-2-34" aria-hidden="true" tabindex="-1"></a>    optimizer.apply_gradients(<span class="bu">zip</span>(grads, [X, W, b]))</span>
<span id="annotated-cell-2-35"><a href="#annotated-cell-2-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="annotated-cell-2-36"><a href="#annotated-cell-2-36" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"final cost: </span><span class="sc">{</span>cost_value<span class="sc">.</span>numpy()<span class="sc">:.4f}</span><span class="ss">"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-2" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="17" data-code-annotation="1"><strong><code>cofi_cost_func</code></strong> is the collaborative filtering cost function <span class="math inline">\(J\)</span> written as code, the one piece the programmer has to supply. Everything else is TensorFlow machinery.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="27" data-code-annotation="2"><strong><code>tf.keras.optimizers.Adam</code></strong> creates the optimizer object, with its learning rate. From here on it manages every parameter update.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="31" data-code-annotation="3"><strong><code>tf.GradientTape</code></strong> records the operations used to compute the cost, exactly as in the tiny example, just with a bigger cost function.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="33" data-code-annotation="4"><strong><code>tape.gradient</code></strong> returns the gradients of the cost with respect to <span class="math inline">\(\mathbf{X}\)</span>, <span class="math inline">\(\mathbf{W}\)</span>, and <span class="math inline">\(\vec{b}\)</span>, all three at once.</span>
</dd>
<dt data-target-cell="annotated-cell-2" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-2" data-code-lines="34" data-code-annotation="5"><strong><code>optimizer.apply_gradients</code></strong> hands the gradients to Adam to update the variables (<code>zip</code> is just plain Python, rearranging the gradients and variables into the pairs <code>apply_gradients</code> expects).</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>final cost: 1.1480</code></pre>
</div>
</div>
<p>The training loop has the same three beats as the tiny example: compute the cost inside a gradient tape, ask the tape for the gradients, and hand them to the optimizer. After training, predictions are <span class="math inline">\(\vec{w}^{(j)} \cdot \vec{x}^{(i)} + b^{(j)} + \mu_i\)</span>:</p>
<div id="b4e3ca30" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> (tf.linalg.matmul(X, tf.transpose(W)) <span class="op">+</span> b).numpy() <span class="op">+</span> mu</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>pd.DataFrame(np.<span class="bu">round</span>(pred, <span class="dv">1</span>) <span class="op">+</span> <span class="fl">0.0</span>, index<span class="op">=</span>movie_names,   <span class="co"># + 0.0 turns -0.0 into 0.0</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>             columns<span class="op">=</span>[<span class="st">"Alice"</span>, <span class="st">"Bob"</span>, <span class="st">"Carol"</span>, <span class="st">"Dave"</span>, <span class="st">"Eve"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Alice</th>
<th data-quarto-table-cell-role="th">Bob</th>
<th data-quarto-table-cell-role="th">Carol</th>
<th data-quarto-table-cell-role="th">Dave</th>
<th data-quarto-table-cell-role="th">Eve</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">Love at Last</th>
<td>5.0</td>
<td>5.0</td>
<td>0.0</td>
<td>0.0</td>
<td>2.5</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Romance Forever</th>
<td>4.9</td>
<td>4.9</td>
<td>0.3</td>
<td>0.0</td>
<td>2.5</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Cute Puppies of Love</th>
<td>4.0</td>
<td>4.0</td>
<td>0.0</td>
<td>0.1</td>
<td>2.0</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Nonstop Car Chases</th>
<td>0.0</td>
<td>0.0</td>
<td>5.0</td>
<td>3.9</td>
<td>2.3</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Swords vs. Karate</th>
<td>0.0</td>
<td>0.0</td>
<td>4.9</td>
<td>0.0</td>
<td>1.3</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>Three things worth reading off this table. The rated entries are reproduced almost exactly. The question marks from the original table have been filled in with sensible predictions, Bob’s unrated Romance Forever comes out around 4.9 and Alice’s unrated Cute Puppies of Love around 4.0, matching the guesses made by eye when the ratings table was <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html#framing-the-problem">first introduced</a>, and that filling-in is exactly what a recommender system is for. And Eve’s column lands on the per-movie means <span class="math inline">\(\vec{\mu}\)</span>, the mean-normalization behavior worked out above, now confirmed by running code.</p>
<p>Why not the usual <code>Sequential</code> / <code>model.compile</code> / <code>model.fit</code> recipe from the <a href="../../machine-learning/advanced-learning-algorithms/tensorflow-implementation.html">neural network pages</a>? Because collaborative filtering does not fit it: its cost function is not a stack of dense layers or any other standard layer type, so there is no model to compile. The gradient tape approach is the general-purpose fallback, implement the cost function yourself, and TensorFlow still supplies the derivatives and the optimizer. The practice lab for this section uses exactly this pattern on the <strong>MovieLens dataset</strong> (due to Harper and Konstan), real movies rated by real people. (PyTorch, among other packages, offers the same Auto Diff capability.)</p>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. What does TensorFlow’s gradient tape do, and what is the one piece of code the programmer still has to supply?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Inside a <code>with tf.GradientTape() as tape:</code> block, TensorFlow records the sequence of operations used to compute the cost, and <code>tape.gradient</code> then uses that recording to compute the derivatives of the cost with respect to any variables automatically (Auto Diff). The programmer only has to supply the cost function itself, no derivatives, no calculus.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which three sets of variables does <code>tape.gradient</code> differentiate the collaborative filtering cost with respect to, and what happens to those gradients next?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The features <span class="math inline">\(\mathbf{X}\)</span>, the user weights <span class="math inline">\(\mathbf{W}\)</span>, and the biases <span class="math inline">\(\vec{b}\)</span>, the same three sets of parameters the combined cost function is minimized over. The gradients are handed to the optimizer via <code>optimizer.apply_gradients(zip(grads, [X, W, b]))</code>, which applies the update, here using Adam rather than plain gradient descent.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why can’t collaborative filtering be trained with the standard <code>model.compile</code> and <code>model.fit</code> workflow?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>That workflow assumes the model is built from TensorFlow’s standard layer types, like a sequence of dense layers. The collaborative filtering model and cost function do not fit any of those layer types, so instead the cost function is implemented directly, and TensorFlow’s Auto Diff plus an optimizer like Adam do the rest.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The implementation of collaborative filtering utilized a custom training loop in TensorFlow. Is it true that TensorFlow always requires a custom training loop?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No: TensorFlow provides simplified training operations for some applications. The <code>model</code>, <code>compile</code>, <code>fit</code> sequence from the <a href="../../machine-learning/advanced-learning-algorithms/training-neural-networks.html">neural network pages</a> manages training automatically whenever the model fits TensorFlow’s standard layer paradigm. A custom training loop was used <em>here</em> because training <span class="math inline">\(\vec{w}\)</span>, <span class="math inline">\(b\)</span>, and <span class="math inline">\(\vec{x}\)</span> together does not fit that paradigm (there are alternate solutions, such as custom layers, but the custom loop is a useful general-purpose tool to know).</p>
</div>
</div>
</div>
</section>
</section>
<section id="finding-related-items" class="level2">
<h2 class="anchored" data-anchor-id="finding-related-items">Finding Related Items</h2>
<p>When an online store shows “customers also viewed these items,” or a streaming site lists movies similar to the one being browsed, how does it decide what counts as <em>similar</em>? Collaborative filtering gives a natural answer, almost for free.</p>
<p>The learned features <span class="math inline">\(\vec{x}^{(i)}\)</span> are the key. The previous page started with a hypothetical example of interpretable features, how much a movie is a romance versus an action movie, but when the algorithm learns features automatically, the individual numbers <span class="math inline">\(x_1, x_2, x_3, \dots\)</span> turn out to be quite hard to interpret; there is no clean reading like “<span class="math inline">\(x_1\)</span> means action movie” or “<span class="math inline">\(x_2\)</span> means foreign film.” Collectively, though, the feature vector <span class="math inline">\(\vec{x}^{(i)}\)</span> really does capture what movie <span class="math inline">\(i\)</span> is like: movies that users rate similarly end up with similar feature vectors. So to find items related to item <span class="math inline">\(i\)</span>, look for the items <span class="math inline">\(k\)</span> whose features <span class="math inline">\(\vec{x}^{(k)}\)</span> are closest to <span class="math inline">\(\vec{x}^{(i)}\)</span>, measured by the squared distance</p>
<p><span class="math display">\[
\sum_{l=1}^{n} \left( x_l^{(k)} - x_l^{(i)} \right)^2 = \left\lVert \vec{x}^{(k)} - \vec{x}^{(i)} \right\rVert^2
\]</span></p>
<p>the same squared-distance idea, written with the same <span class="math inline">\(\lVert \cdot \rVert^2\)</span> notation, as elsewhere in math. Find the 5 or 10 items with the smallest distance to <span class="math inline">\(\vec{x}^{(i)}\)</span>, and those are the related items to display. This idea of finding related items also becomes a small building block in a more powerful recommender system on a later page.</p>
<section id="limitations-of-collaborative-filtering" class="level3">
<h3 class="anchored" data-anchor-id="limitations-of-collaborative-filtering">Limitations of Collaborative Filtering</h3>
<p>Powerful as it is, collaborative filtering has two notable weaknesses.</p>
<p><strong>The cold start problem.</strong> How do you rank a brand-new movie that very few users have rated? And how do you show something sensible to a new user who has rated almost nothing? Mean normalization helps a lot with the second case, as shown above, but the predictions for barely-rated items and barely-active users are still not very accurate, and there ought to be better ways to serve them than “the average of everyone else.”</p>
<p><strong>No natural way to use side information.</strong> Collaborative filtering learns purely from the ratings matrix, and has no slot for the extra information that often exists about items and users. For a movie: its genre, its stars, the studio, the budget. For a user: demographics like age, gender, and location, expressed preferences like favorite genres, or even indirect signals, the user’s IP address hints at their location, and whether they browse on mobile or desktop, or which web browser they use, all correlate surprisingly well with preferences (users of Chrome, Firefox, Safari, and Edge measurably behave differently). All of these are little cues that collaborative filtering simply has no way to take in.</p>
<p>The next page develops <strong>content-based filtering</strong>, a state-of-the-art technique used in many commercial applications today, which addresses exactly these limitations.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. How does collaborative filtering find items related to a given item <span class="math inline">\(i\)</span>?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>By comparing learned feature vectors: for each candidate item <span class="math inline">\(k\)</span>, compute the squared distance <span class="math inline">\(\lVert \vec{x}^{(k)} - \vec{x}^{(i)} \rVert^2 = \sum_{l=1}^n (x_l^{(k)} - x_l^{(i)})^2\)</span>, and take the 5 or 10 items with the smallest distances. Items with similar learned features tend to genuinely be similar, even though the individual feature values are hard to interpret.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The learned features are described as “hard to interpret individually but meaningful collectively.” What does that mean?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No single learned feature reliably means something human-readable like “action movie” or “foreign film,” so reading <span class="math inline">\(x_1\)</span> or <span class="math inline">\(x_2\)</span> on its own tells you little. But the whole vector <span class="math inline">\(\vec{x}^{(i)}\)</span> still encodes what the movie is like, in the sense that movies rated similarly by users end up with nearby feature vectors, which is exactly what makes distance-based “related items” work.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Name the two main limitations of collaborative filtering, with an example of each.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>First, the cold start problem: it struggles with new items almost nobody has rated, and with new users who have rated almost nothing (mean normalization helps the new-user case but only so much). Second, it has no natural way to use side information, like a movie’s genre, cast, or budget, or a user’s age, location, expressed preferences, or even browsing signals like device or web browser, all of which can carry real predictive signal.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Once a model is trained, the “distance” between feature vectors gives an indication of how similar items are. Using the learned features below (three features, <span class="math inline">\(x_0\)</span> through <span class="math inline">\(x_2\)</span>), find the closest item to the movie “Pies, Pies, Pies”.</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Movie</th>
<th style="text-align: center;"><span class="math inline">\(x_0\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(x_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pastries for Supper</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">1.0</td>
</tr>
<tr class="even">
<td>Pies, Pies, Pies</td>
<td style="text-align: center;">2.0</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">4.0</td>
</tr>
<tr class="odd">
<td>Pies and You</td>
<td style="text-align: center;">5.0</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: center;">4.0</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Pies and You.</strong> Computing <span class="math inline">\(\lVert \vec{x}^{(k)} - \vec{x}^{(i)} \rVert^2\)</span> against Pies, Pies, Pies for each candidate: Pastries for Supper gives <span class="math inline">\((2-2)^2 + (2-3)^2 + (1-4)^2 = 0 + 1 + 9 = 10\)</span>, while Pies and You gives <span class="math inline">\((5-2)^2 + (3-3)^2 + (4-4)^2 = 9 + 0 + 0 = 9\)</span>. The smaller squared distance, 9, wins.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of these is an example of the cold start problem? (Check all that apply.)</strong></p>
<ul>
<li>A recommendation system takes so long to train that users get bored and leave.</li>
<li>A recommendation system is so computationally expensive that it causes your computer CPU to heat up, causing your computer to need to be cooled down and restarted.</li>
<li>A recommendation system is unable to give accurate rating predictions for a new product that no users have rated.</li>
<li>A recommendation system is unable to give accurate rating predictions for a new user that has rated few products.</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The last two. The cold start problem is about <em>data</em>, not computation: a recommendation system learns from product feedback, so a new product no users have rated, or a new user who has rated few products, gives it almost nothing to fit a prediction on. Training time and computational expense are real engineering concerns, but they are not what “cold start” refers to.</p>
</div>
</div>
</div>
</section>
</section>
<section id="lab-movie-recommendations-with-collaborative-filtering" class="level2">
<h2 class="anchored" data-anchor-id="lab-movie-recommendations-with-collaborative-filtering">Lab: Movie Recommendations with Collaborative Filtering</h2>
<p>This lab builds a working movie recommender on real data: the <strong>MovieLens “ml-latest-small” dataset</strong> (due to Harper and Konstan, 2015), reduced here to <span class="math inline">\(n_m = 4778\)</span> movies rated by <span class="math inline">\(n_u = 443\)</span> users, with ratings from 0.5 to 5 in half-star steps. The two graded pieces are the collaborative filtering <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html#the-full-collaborative-filtering-cost-function">cost function</a>, first with loops and then vectorized, after which the model trains with exactly the <a href="#adam-and-the-full-algorithm">custom training loop</a> from this page, learns 100 features per movie, and produces personal recommendations from ratings you enter yourself.</p>
<div id="86492324" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow <span class="im">import</span> keras</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> numpy <span class="im">import</span> loadtxt</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="dataset" class="level3">
<h3 class="anchored" data-anchor-id="dataset">Dataset</h3>
<p>The ratings live in the same two matrices used throughout this page, <span class="math inline">\(Y\)</span> (<span class="math inline">\(n_m \times n_u\)</span>, with 0 standing in for “not rated”) and <span class="math inline">\(R\)</span> (1 where a rating exists), just much bigger than the toy 5-movie version. The dataset also ships a set of <strong>pre-computed parameters</strong> <span class="math inline">\(\mathbf{X}\)</span>, <span class="math inline">\(\mathbf{W}\)</span>, <span class="math inline">\(\vec{b}\)</span>, trained values provided so the cost function can be tested against known numbers before any training happens.</p>
<div id="7831fad2" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>data_dir <span class="op">=</span> <span class="st">"../../media/collaborative-filtering"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> loadtxt(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movies_X.csv"</span>, delimiter<span class="op">=</span><span class="st">","</span>)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> loadtxt(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movies_W.csv"</span>, delimiter<span class="op">=</span><span class="st">","</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> loadtxt(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movies_b.csv"</span>, delimiter<span class="op">=</span><span class="st">","</span>).reshape(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> loadtxt(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movies_Y.csv"</span>, delimiter<span class="op">=</span><span class="st">","</span>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> loadtxt(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movies_R.csv"</span>, delimiter<span class="op">=</span><span class="st">","</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>num_movies, num_features <span class="op">=</span> X.shape</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>num_users <span class="op">=</span> W.shape[<span class="dv">0</span>]</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Y"</span>, Y.shape, <span class="st">"R"</span>, R.shape)</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"X"</span>, X.shape)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"W"</span>, W.shape)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"b"</span>, b.shape)</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"num_features"</span>, num_features)</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"num_movies"</span>, num_movies)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"num_users"</span>, num_users)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Y (4778, 443) R (4778, 443)
X (4778, 10)
W (443, 10)
b (1, 443)
num_features 10
num_movies 4778
num_users 443</code></pre>
</div>
</div>
<p>A quick statistic straight off the matrix, using <span class="math inline">\(R\)</span> as a mask so unrated entries do not drag the average down:</p>
<div id="149ebd51" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>tsmean <span class="op">=</span> np.mean(Y[<span class="dv">0</span>, R[<span class="dv">0</span>, :].astype(<span class="bu">bool</span>)])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Average rating for movie 1 : </span><span class="sc">{</span>tsmean<span class="sc">:0.3f}</span><span class="ss"> / 5"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Average rating for movie 1 : 3.400 / 5</code></pre>
</div>
</div>
<p>The expected average is 3.400, and that is what comes out.</p>
</section>
<section id="exercise-1-cost-function-with-loops" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1-cost-function-with-loops">Exercise 1: Cost Function with Loops</h3>
<p>The graded function <code>cofi_cost_func</code> computes</p>
<p><span class="math display">\[
J = \frac{1}{2} \sum_{(i,j)\,:\,r(i,j)=1} \left( \vec{w}^{(j)} \cdot \vec{x}^{(i)} + b^{(j)} - y(i,j) \right)^2 + \frac{\lambda}{2} \sum_{j} \sum_{k} \left(w_k^{(j)}\right)^2 + \frac{\lambda}{2} \sum_{i} \sum_{k} \left(x_k^{(i)}\right)^2
\]</span></p>
<p>written first with explicit loops over users and movies, so the code lines up one-to-one with the summation signs, multiplying each squared error by <span class="math inline">\(r(i,j)\)</span> instead of skipping unrated pairs:</p>
<div id="3a0b60e3" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cofi_cost_func(X, W, b, Y, R, lambda_):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns the cost for the collaborative filtering model</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">      X (ndarray (num_movies, num_features)): matrix of item features</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">      W (ndarray (num_users, num_features)) : matrix of user parameters</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">      b (ndarray (1, num_users))            : vector of user parameters</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co">      Y (ndarray (num_movies, num_users))   : matrix of user ratings of movies</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="co">      R (ndarray (num_movies, num_users))   : matrix, where R(i,j) = 1 if movie i was rated by user j</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="co">      lambda_ (float): regularization parameter</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co">      J (float) : Cost</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    nm, nu <span class="op">=</span> Y.shape</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    J <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> j <span class="kw">in</span> <span class="bu">range</span>(nu):</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>        w <span class="op">=</span> W[j, :]</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>        b_j <span class="op">=</span> b[<span class="dv">0</span>, j]</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(nm):</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>            x <span class="op">=</span> X[i, :]</span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>            y <span class="op">=</span> Y[i, j]</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a>            r <span class="op">=</span> R[i, j]</span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a>            J <span class="op">+=</span> r <span class="op">*</span> np.square(np.dot(w, x) <span class="op">+</span> b_j <span class="op">-</span> y)</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a>    J <span class="op">=</span> J <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a>    J <span class="op">+=</span> (lambda_ <span class="op">/</span> <span class="dv">2</span>) <span class="op">*</span> (np.<span class="bu">sum</span>(np.square(W)) <span class="op">+</span> np.<span class="bu">sum</span>(np.square(X)))</span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> J</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Because the double loop is slow, the check runs on a small slice of the data, 5 movies, 4 users, 3 features, first without regularization and then with <span class="math inline">\(\lambda = 1.5\)</span>:</p>
<div id="17891e8b" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>num_users_r <span class="op">=</span> <span class="dv">4</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>num_movies_r <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>num_features_r <span class="op">=</span> <span class="dv">3</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>X_r <span class="op">=</span> X[:num_movies_r, :num_features_r]</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>W_r <span class="op">=</span> W[:num_users_r, :num_features_r]</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>b_r <span class="op">=</span> b[<span class="dv">0</span>, :num_users_r].reshape(<span class="dv">1</span>, <span class="op">-</span><span class="dv">1</span>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>Y_r <span class="op">=</span> Y[:num_movies_r, :num_users_r]</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>R_r <span class="op">=</span> R[:num_movies_r, :num_users_r]</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> cofi_cost_func(X_r, W_r, b_r, Y_r, R_r, <span class="dv">0</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cost: </span><span class="sc">{</span>J<span class="sc">:0.2f}</span><span class="ss">"</span>)</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> cofi_cost_func(X_r, W_r, b_r, Y_r, R_r, <span class="fl">1.5</span>)</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cost (with regularization): </span><span class="sc">{</span>J<span class="sc">:0.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cost: 13.67
Cost (with regularization): 28.09</code></pre>
</div>
</div>
<p>The expected values are 13.67 without regularization and 28.09 with it, both matched. The lab’s public tests probe the same function with hand-constructed matrices of ones and zeros, where the correct cost can be worked out on paper:</p>
<div id="7220ef80" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>X_t <span class="op">=</span> np.ones((<span class="dv">5</span>, <span class="dv">3</span>))<span class="op">;</span> W_t <span class="op">=</span> np.ones((<span class="dv">4</span>, <span class="dv">3</span>))<span class="op">;</span> b_t <span class="op">=</span> np.zeros((<span class="dv">1</span>, <span class="dv">4</span>))</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Y_t <span class="op">=</span> np.zeros((<span class="dv">5</span>, <span class="dv">4</span>))<span class="op">;</span> R_t <span class="op">=</span> np.zeros((<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(cofi_cost_func(X_t, W_t, b_t, Y_t, R_t, <span class="dv">2</span>), <span class="dv">27</span>), <span class="op">\</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Check the regularization term (did you multiply by lambda_?)"</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>b_t <span class="op">=</span> np.ones((<span class="dv">1</span>, <span class="dv">4</span>))<span class="op">;</span> Y_t <span class="op">=</span> np.ones((<span class="dv">5</span>, <span class="dv">4</span>))<span class="op">;</span> R_t <span class="op">=</span> np.ones((<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(cofi_cost_func(X_t, W_t, b_t, Y_t, R_t, <span class="dv">0</span>), <span class="dv">90</span>), <span class="op">\</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Check the term without regularization"</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>Y_t <span class="op">=</span> np.zeros((<span class="dv">5</span>, <span class="dv">4</span>))</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a><span class="cf">assert</span> np.isclose(cofi_cost_func(X_t, W_t, b_t, Y_t, R_t, <span class="dv">0</span>), <span class="dv">160</span>), <span class="op">\</span></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Check the term without regularization"</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"All tests passed!"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>All tests passed!</code></pre>
</div>
</div>
</section>
<section id="vectorized-cost-function" class="level3">
<h3 class="anchored" data-anchor-id="vectorized-cost-function">Vectorized Cost Function</h3>
<p>The loop version is far too slow for training on the full dataset, and, written in plain NumPy loops, it also would not slot into TensorFlow’s gradient tape. The vectorized version below computes the identical cost as one matrix expression, all predictions at once via <span class="math inline">\(\mathbf{X}\mathbf{W}^T + \vec{b}\)</span>, masked by <span class="math inline">\(R\)</span>, using TensorFlow operations so <strong><code>tf.GradientTape</code></strong> can record it. It is the same <code>cofi_cost_func</code> used with the toy dataset <a href="#adam-and-the-full-algorithm">earlier on this page</a>.</p>
<div id="60ac51a5" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> cofi_cost_func_v(X, W, b, Y, R, lambda_):</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns the cost for the collaborative filtering model.</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Vectorized for speed. Uses tensorflow operations to be</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="co">    compatible with a custom training loop.</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    j <span class="op">=</span> (tf.linalg.matmul(X, tf.transpose(W)) <span class="op">+</span> b <span class="op">-</span> Y) <span class="op">*</span> R</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    J <span class="op">=</span> <span class="fl">0.5</span> <span class="op">*</span> tf.reduce_sum(j<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> (lambda_ <span class="op">/</span> <span class="dv">2</span>) <span class="op">*</span> (tf.reduce_sum(X<span class="op">**</span><span class="dv">2</span>) <span class="op">+</span> tf.reduce_sum(W<span class="op">**</span><span class="dv">2</span>))</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> J</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, <span class="dv">0</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cost: </span><span class="sc">{</span>J<span class="sc">:0.2f}</span><span class="ss">"</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>J <span class="op">=</span> cofi_cost_func_v(X_r, W_r, b_r, Y_r, R_r, <span class="fl">1.5</span>)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Cost (with regularization): </span><span class="sc">{</span>J<span class="sc">:0.2f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Cost: 13.67
Cost (with regularization): 28.09</code></pre>
</div>
</div>
<p>Same 13.67 and 28.09 as the loop version, so the two implementations agree.</p>
</section>
<section id="adding-your-own-ratings" class="level3">
<h3 class="anchored" data-anchor-id="adding-your-own-ratings">Adding Your Own Ratings</h3>
<p>Here is the part that makes the lab fun: enter ratings for movies <em>you</em> have opinions about, and the recommender will treat you as a new user. The file <code>small_movie_list.csv</code> maps each row index of <span class="math inline">\(Y\)</span> to a movie title. The ratings below are the lab’s example selections:</p>
<div id="be8610dc" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>movieList_df <span class="op">=</span> pd.read_csv(<span class="ss">f"</span><span class="sc">{</span>data_dir<span class="sc">}</span><span class="ss">/small_movie_list.csv"</span>,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                           header<span class="op">=</span><span class="dv">0</span>, index_col<span class="op">=</span><span class="dv">0</span>, delimiter<span class="op">=</span><span class="st">","</span>, quotechar<span class="op">=</span><span class="st">'"'</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>movieList <span class="op">=</span> movieList_df[<span class="st">"title"</span>].to_list()</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>my_ratings <span class="op">=</span> np.zeros(num_movies)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">2700</span>] <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Toy Story 3 (2010)</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">2609</span>] <span class="op">=</span> <span class="dv">2</span>   <span class="co"># Persuasion (2007)</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">929</span>]  <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Lord of the Rings: The Return of the King, The</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">246</span>]  <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Shrek (2001)</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">2716</span>] <span class="op">=</span> <span class="dv">3</span>   <span class="co"># Inception</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">1150</span>] <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Incredibles, The (2004)</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">382</span>]  <span class="op">=</span> <span class="dv">2</span>   <span class="co"># Amelie (Fabuleux destin d'Amélie Poulain, Le)</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">366</span>]  <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Harry Potter and the Sorcerer's Stone (2001)</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">622</span>]  <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Harry Potter and the Chamber of Secrets (2002)</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">988</span>]  <span class="op">=</span> <span class="dv">3</span>   <span class="co"># Eternal Sunshine of the Spotless Mind (2004)</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">2925</span>] <span class="op">=</span> <span class="dv">1</span>   <span class="co"># Louis Theroux: Law &amp; Disorder (2008)</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">2937</span>] <span class="op">=</span> <span class="dv">1</span>   <span class="co"># Nothing to Declare (Rien à déclarer)</span></span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>my_ratings[<span class="dv">793</span>]  <span class="op">=</span> <span class="dv">5</span>   <span class="co"># Pirates of the Caribbean: The Curse of the Black Pearl (2003)</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>my_rated <span class="op">=</span> [i <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(my_ratings)) <span class="cf">if</span> my_ratings[i] <span class="op">&gt;</span> <span class="dv">0</span>]</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"New user ratings:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(my_ratings)):</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> my_ratings[i] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Rated </span><span class="sc">{</span>my_ratings[i]<span class="sc">}</span><span class="ss"> for  </span><span class="sc">{</span>movieList_df<span class="sc">.</span>loc[i, <span class="st">'title'</span>]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>New user ratings:

Rated 5.0 for  Shrek (2001)
Rated 5.0 for  Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)
Rated 2.0 for  Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)
Rated 5.0 for  Harry Potter and the Chamber of Secrets (2002)
Rated 5.0 for  Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Rated 5.0 for  Lord of the Rings: The Return of the King, The (2003)
Rated 3.0 for  Eternal Sunshine of the Spotless Mind (2004)
Rated 5.0 for  Incredibles, The (2004)
Rated 2.0 for  Persuasion (2007)
Rated 5.0 for  Toy Story 3 (2010)
Rated 3.0 for  Inception (2010)
Rated 1.0 for  Louis Theroux: Law &amp; Disorder (2008)
Rated 1.0 for  Nothing to Declare (Rien à déclarer) (2010)</code></pre>
</div>
</div>
<p>These ratings get attached to the data as a brand-new first column of <span class="math inline">\(Y\)</span> (so the new user is user <span class="math inline">\(j = 0\)</span>), with a matching column of <span class="math inline">\(R\)</span> marking which movies were rated. Then the whole dataset is mean normalized, exactly the <a href="#mean-normalization">row-wise normalization</a> from earlier, implemented so that movies nobody rated end up with a mean of 0 rather than a divide-by-zero:</p>
<div id="a2cff548" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> normalizeRatings(Y, R):</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Preprocess data by subtracting mean rating for every movie (every row).</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Only include real ratings R(i,j)=1. Unrated movies get a mean of 0.</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns the mean rating in Ymean.</span></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    Ymean <span class="op">=</span> (np.<span class="bu">sum</span>(Y <span class="op">*</span> R, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">/</span> (np.<span class="bu">sum</span>(R, axis<span class="op">=</span><span class="dv">1</span>) <span class="op">+</span> <span class="fl">1e-12</span>)).reshape(<span class="op">-</span><span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    Ynorm <span class="op">=</span> Y <span class="op">-</span> np.multiply(Ymean, R)</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Ynorm, Ymean</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>Y <span class="op">=</span> np.c_[my_ratings, Y]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>R <span class="op">=</span> np.c_[(my_ratings <span class="op">!=</span> <span class="dv">0</span>).astype(<span class="bu">int</span>), R]</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>Ynorm, Ymean <span class="op">=</span> normalizeRatings(Y, R)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="training" class="level3">
<h3 class="anchored" data-anchor-id="training">Training</h3>
<p>Training is the custom loop from <a href="#adam-and-the-full-algorithm">this page’s TensorFlow section</a>, unchanged except for scale: <span class="math inline">\(n = 100\)</span> features per movie instead of 2, randomly initialized parameters for all <span class="math inline">\(4778\)</span> movies and <span class="math inline">\(444\)</span> users (the original 443 plus the new user), <span class="math inline">\(\lambda = 1\)</span>, and the Adam optimizer:</p>
<div id="51769885" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>num_movies, num_users <span class="op">=</span> Y.shape</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>num_features <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>tf.random.set_seed(<span class="dv">1234</span>)</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>W <span class="op">=</span> tf.Variable(tf.random.normal((num_users, num_features), dtype<span class="op">=</span>tf.float64), name<span class="op">=</span><span class="st">"W"</span>)</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> tf.Variable(tf.random.normal((num_movies, num_features), dtype<span class="op">=</span>tf.float64), name<span class="op">=</span><span class="st">"X"</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>b <span class="op">=</span> tf.Variable(tf.random.normal((<span class="dv">1</span>, num_users), dtype<span class="op">=</span>tf.float64), name<span class="op">=</span><span class="st">"b"</span>)</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> keras.optimizers.Adam(learning_rate<span class="op">=</span><span class="fl">1e-1</span>)</span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>iterations <span class="op">=</span> <span class="dv">200</span></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>lambda_ <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> <span class="bu">iter</span> <span class="kw">in</span> <span class="bu">range</span>(iterations):</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> tf.GradientTape() <span class="im">as</span> tape:</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>        cost_value <span class="op">=</span> cofi_cost_func_v(X, W, b, Ynorm, R, lambda_)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>    grads <span class="op">=</span> tape.gradient(cost_value, [X, W, b])</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>    optimizer.apply_gradients(<span class="bu">zip</span>(grads, [X, W, b]))</span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">iter</span> <span class="op">%</span> <span class="dv">20</span> <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb19-20"><a href="#cb19-20" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Training loss at iteration </span><span class="sc">{</span><span class="bu">iter</span><span class="sc">}</span><span class="ss">: </span><span class="sc">{</span>cost_value<span class="sc">:0.1f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Training loss at iteration 0: 2321191.3
Training loss at iteration 20: 136169.3
Training loss at iteration 40: 51863.7
Training loss at iteration 60: 24599.0
Training loss at iteration 80: 13630.6
Training loss at iteration 100: 8487.7
Training loss at iteration 120: 5807.8
Training loss at iteration 140: 4311.6
Training loss at iteration 160: 3435.3
Training loss at iteration 180: 2902.1</code></pre>
</div>
</div>
<p>The loss falls by more than an order of magnitude over 200 iterations. Note what is being learned here: <strong>no movie features were ever provided</strong>, the algorithm is inventing all 100 features per movie, plus every user’s parameters, from nothing but the ratings, exactly the point made when the <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html#the-full-collaborative-filtering-cost-function">combined cost function</a> was introduced.</p>
</section>
<section id="recommendations" class="level3">
<h3 class="anchored" data-anchor-id="recommendations">Recommendations</h3>
<p>Predictions come from the <a href="#mean-normalization">mean-normalized prediction formula</a>: compute <span class="math inline">\(\mathbf{X}\mathbf{W}^T + \vec{b}\)</span> for every movie-user pair, then add each movie’s mean <span class="math inline">\(\mu_i\)</span> back. Column 0 belongs to the new user, so sorting that column descending and skipping already-rated movies gives the personal recommendation list:</p>
<div id="09dc9af7" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> np.matmul(X.numpy(), np.transpose(W.numpy())) <span class="op">+</span> b.numpy()</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>pm <span class="op">=</span> p <span class="op">+</span> Ymean</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>my_predictions <span class="op">=</span> pm[:, <span class="dv">0</span>]</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>ix <span class="op">=</span> tf.argsort(my_predictions, direction<span class="op">=</span><span class="st">"DESCENDING"</span>)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">17</span>):</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>    j <span class="op">=</span> ix[i]</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> j <span class="kw">not</span> <span class="kw">in</span> my_rated:</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Predicting rating </span><span class="sc">{</span>my_predictions[j]<span class="sc">:0.2f}</span><span class="ss"> for movie </span><span class="sc">{</span>movieList[j]<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n\n</span><span class="st">Original vs Predicted ratings:</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="bu">len</span>(my_ratings)):</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> my_ratings[i] <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"Original </span><span class="sc">{</span>my_ratings[i]<span class="sc">}</span><span class="ss">, Predicted </span><span class="sc">{</span>my_predictions[i]<span class="sc">:0.2f}</span><span class="ss"> for </span><span class="sc">{</span>movieList[i]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Predicting rating 4.49 for movie My Sassy Girl (Yeopgijeogin geunyeo) (2001)
Predicting rating 4.48 for movie Martin Lawrence Live: Runteldat (2002)
Predicting rating 4.48 for movie Memento (2000)
Predicting rating 4.47 for movie Delirium (2014)
Predicting rating 4.47 for movie Laggies (2014)
Predicting rating 4.47 for movie One I Love, The (2014)
Predicting rating 4.46 for movie Particle Fever (2013)
Predicting rating 4.45 for movie Eichmann (2007)
Predicting rating 4.45 for movie Battle Royale 2: Requiem (Batoru rowaiaru II: Chinkonka) (2003)
Predicting rating 4.45 for movie Into the Abyss (2011)


Original vs Predicted ratings:

Original 5.0, Predicted 4.90 for Shrek (2001)
Original 5.0, Predicted 4.84 for Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone) (2001)
Original 2.0, Predicted 2.13 for Amelie (Fabuleux destin d'Amélie Poulain, Le) (2001)
Original 5.0, Predicted 4.88 for Harry Potter and the Chamber of Secrets (2002)
Original 5.0, Predicted 4.87 for Pirates of the Caribbean: The Curse of the Black Pearl (2003)
Original 5.0, Predicted 4.89 for Lord of the Rings: The Return of the King, The (2003)
Original 3.0, Predicted 3.00 for Eternal Sunshine of the Spotless Mind (2004)
Original 5.0, Predicted 4.90 for Incredibles, The (2004)
Original 2.0, Predicted 2.11 for Persuasion (2007)
Original 5.0, Predicted 4.80 for Toy Story 3 (2010)
Original 3.0, Predicted 3.00 for Inception (2010)
Original 1.0, Predicted 1.41 for Louis Theroux: Law &amp; Disorder (2008)
Original 1.0, Predicted 1.26 for Nothing to Declare (Rien à déclarer) (2010)</code></pre>
</div>
</div>
<p>Two things worth noticing. The predictions for the movies that <em>were</em> rated land close to the original ratings, the model fits the new user’s stated tastes. And the raw top-of-list recommendations skew toward obscure movies with very few ratings, a movie rated 5 stars by its only two raters can easily earn a huge predicted rating. A practical fix is to restrict attention to movies with a reasonable number of ratings and look at their average rating too:</p>
<div id="6be3e0da" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">filter</span> <span class="op">=</span> (movieList_df[<span class="st">"number of ratings"</span>] <span class="op">&gt;</span> <span class="dv">20</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>movieList_df[<span class="st">"pred"</span>] <span class="op">=</span> my_predictions</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>movieList_df <span class="op">=</span> movieList_df.reindex(columns<span class="op">=</span>[<span class="st">"pred"</span>, <span class="st">"mean rating"</span>, <span class="st">"number of ratings"</span>, <span class="st">"title"</span>])</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>movieList_df.loc[ix[:<span class="dv">300</span>]].loc[<span class="bu">filter</span>].sort_values(<span class="st">"mean rating"</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">15</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="18">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">pred</th>
<th data-quarto-table-cell-role="th">mean rating</th>
<th data-quarto-table-cell-role="th">number of ratings</th>
<th data-quarto-table-cell-role="th">title</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">1743</th>
<td>4.030961</td>
<td>4.252336</td>
<td>107</td>
<td>Departed, The (2006)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2112</th>
<td>3.985281</td>
<td>4.238255</td>
<td>149</td>
<td>Dark Knight, The (2008)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">211</th>
<td>4.477798</td>
<td>4.122642</td>
<td>159</td>
<td>Memento (2000)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">929</th>
<td>4.887054</td>
<td>4.118919</td>
<td>185</td>
<td>Lord of the Rings: The Return of the King, The...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2700</th>
<td>4.796531</td>
<td>4.109091</td>
<td>55</td>
<td>Toy Story 3 (2010)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">653</th>
<td>4.357304</td>
<td>4.021277</td>
<td>188</td>
<td>Lord of the Rings: The Two Towers, The (2002)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">1122</th>
<td>4.004471</td>
<td>4.006494</td>
<td>77</td>
<td>Shaun of the Dead (2004)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1841</th>
<td>3.980649</td>
<td>4.000000</td>
<td>61</td>
<td>Hot Fuzz (2007)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">3083</th>
<td>4.084643</td>
<td>3.993421</td>
<td>76</td>
<td>Dark Knight Rises, The (2012)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2804</th>
<td>4.434171</td>
<td>3.989362</td>
<td>47</td>
<td>Harry Potter and the Deathly Hallows: Part 1 (...</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">773</th>
<td>4.289676</td>
<td>3.960993</td>
<td>141</td>
<td>Finding Nemo (2003)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">1771</th>
<td>4.344999</td>
<td>3.944444</td>
<td>81</td>
<td>Casino Royale (2006)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">2649</th>
<td>4.133481</td>
<td>3.943396</td>
<td>53</td>
<td>How to Train Your Dragon (2010)</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">2455</th>
<td>4.175743</td>
<td>3.887931</td>
<td>58</td>
<td>Harry Potter and the Half-Blood Prince (2009)</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">361</th>
<td>4.135287</td>
<td>3.871212</td>
<td>132</td>
<td>Monsters, Inc. (2001)</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>This filtered view, the model’s top 300 picks for the new user, restricted to movies with more than 20 ratings and sorted by their overall mean rating (first 15 rows shown), is a much more plausible recommendation list, well-liked movies that also score highly for this specific user’s tastes. In a production system this kind of curation matters as much as the model itself, which is part of what the cold start discussion <a href="#limitations-of-collaborative-filtering">above</a> was pointing at.</p>
</section>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. The lab implements the cost function twice, once with loops and once vectorized. What is each version for?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The loop version exists for understanding and checking: it mirrors the summation formula symbol by symbol, one user at a time, one movie at a time, so it is easy to verify against the math, but it is far too slow for real data. The vectorized version computes the identical cost as one matrix expression, <span class="math inline">\(\mathbf{X}\mathbf{W}^T + \vec{b}\)</span> masked by <span class="math inline">\(R\)</span>, using TensorFlow operations, which makes it fast <em>and</em> recordable by <code>tf.GradientTape</code> for the custom training loop.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is the new user’s rating vector added as a column of <span class="math inline">\(Y\)</span> before training, rather than making predictions for them afterward?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Collaborative filtering only learns parameters <span class="math inline">\(\vec{w}^{(j)}, b^{(j)}\)</span> for users who are <em>in</em> the ratings matrix during training. Adding the new ratings as column 0 of <span class="math inline">\(Y\)</span> (with a matching column of <span class="math inline">\(R\)</span>) means the training loop fits parameters for the new user alongside everyone else, so their column of the prediction matrix is a genuine personalized prediction, informed by their 13 stated ratings and everything the other 443 users contributed about the movies.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In <code>normalizeRatings</code>, what is the <code>1e-12</code> in the denominator guarding against, and which earlier idea is this function implementing?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It implements the row-wise mean normalization from earlier on this page, subtract each movie’s average rating, computed over only the users who rated it. The <code>1e-12</code> guards against division by zero for a movie that nobody has rated, where <span class="math inline">\(\sum_j r(i,j) = 0\)</span>; such a movie simply gets a mean of 0 instead of crashing the computation.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The raw top-of-list recommendations are dominated by obscure movies with very few ratings. Why does that happen, and what does the lab do about it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A movie with only one or two ratings gives the model almost no constraint on its learned features, so its predicted ratings can come out extreme, a mild version of the cold start problem. The lab filters the top 300 predictions down to movies with more than 20 ratings and sorts by the overall mean rating, so the final list contains movies that are both broadly well-liked and predicted to suit this specific user.</p>
</div>
</div>
</div>
<p>That completes the practical side of collaborative filtering: mean normalization, a working TensorFlow implementation, related-item lookup, and a full recommender trained on real MovieLens data. The next page turns to <strong>content-based filtering</strong>, which brings side information about users and items into the model.</p>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 100%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">100% completed (585 of 585 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="pagination-link" aria-label="Collaborative Filtering">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Collaborative Filtering</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>