<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-27">
<meta name="description" content="Train a deep Q-network with experience replay, a target network, and an epsilon-greedy policy to land the lunar lander safely on the moon.">

<title>Lab: Deep Q-Learning, Lunar Lander – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../machine-learning/unsupervised-learning/continuous-state-spaces.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-622ec7ce41a9ca5e1e463d77623c85b1.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Lab: Deep Q-Learning, Lunar Lander – H’s Notes">
<meta property="og:description" content="Train a deep Q-network with experience replay, a target network, and an epsilon-greedy policy to land the lunar lander safely on the moon.">
<meta property="og:image" content="https://h.oliabak.com/media/reinforcement-learning/lunar-lander-lab/lunar_lander.gif">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Lab: Deep Q-Learning, Lunar Lander – H’s Notes">
<meta name="twitter:description" content="Train a deep Q-network with experience replay, a target network, and an epsilon-greedy policy to land the lunar lander safely on the moon.">
<meta name="twitter:image" content="https://h.oliabak.com/media/reinforcement-learning/lunar-lander-lab/lunar_lander.gif">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccie-data-center/index.html">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../networking/archive.html">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccnp-routing/index.html">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccnp-switching/index.html">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../cybersecurity/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../cybersecurity/archive.html">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../infrastructure/kali-linux/index.html">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../ai/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/federated-learning/index.html">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/improving-deep-neural-networks/index.html">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/structuring-machine-learning-projects/index.html">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/convolutional-neural-networks/index.html">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/sequence-models/index.html">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../tools/client-info.html">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/asn-conversion.html">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/subnet-calculator.html">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/network-toolkit.html">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/copy-paste-values.html">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../tools/function-graphs.html">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/markdown-preview.html">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../tools/eclipse-atlas.html">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/planetarium.html">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../tools/svg-preview.html">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/color-pallet.html">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/typography.html">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/tshirt-design.html">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/reassess-your-chess.html">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/daily-chess.html">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/roadmap.html">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/unsupervised-learning/lab-deep-q-learning-lunar-lander.html">Deep Q-Learning, Lunar Lander</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Clustering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/anomaly-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Anomaly Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/collaborative-filtering-in-practice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Collaborative Filtering in Practice</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/content-based-filtering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Content-Based Filtering</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/principal-components-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Principal Components Analysis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/reinforcement-learning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reinforcement Learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/state-action-value-function.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">State-Action Value Function</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/continuous-state-spaces.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Continuous State Spaces</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/unsupervised-learning/lab-deep-q-learning-lunar-lander.html" class="sidebar-item-text sidebar-link active"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Deep Q-Learning, Lunar Lander</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#import-packages" id="toc-import-packages" class="nav-link active" data-scroll-target="#import-packages">Import Packages</a></li>
  <li><a href="#hyperparameters" id="toc-hyperparameters" class="nav-link" data-scroll-target="#hyperparameters">Hyperparameters</a></li>
  <li><a href="#lunar-lander-environment" id="toc-lunar-lander-environment" class="nav-link" data-scroll-target="#lunar-lander-environment">Lunar Lander Environment</a>
  <ul class="collapse">
  <li><a href="#action-space" id="toc-action-space" class="nav-link" data-scroll-target="#action-space">Action Space</a></li>
  <li><a href="#observation-space" id="toc-observation-space" class="nav-link" data-scroll-target="#observation-space">Observation Space</a></li>
  <li><a href="#rewards" id="toc-rewards" class="nav-link" data-scroll-target="#rewards">Rewards</a></li>
  <li><a href="#episode-termination" id="toc-episode-termination" class="nav-link" data-scroll-target="#episode-termination">Episode Termination</a></li>
  </ul></li>
  <li><a href="#load-the-environment" id="toc-load-the-environment" class="nav-link" data-scroll-target="#load-the-environment">Load the Environment</a></li>
  <li><a href="#interacting-with-the-gym-environment" id="toc-interacting-with-the-gym-environment" class="nav-link" data-scroll-target="#interacting-with-the-gym-environment">Interacting with the Gym Environment</a>
  <ul class="collapse">
  <li><a href="#exploring-the-environment-dynamics" id="toc-exploring-the-environment-dynamics" class="nav-link" data-scroll-target="#exploring-the-environment-dynamics">Exploring the Environment Dynamics</a></li>
  </ul></li>
  <li><a href="#deep-q-learning" id="toc-deep-q-learning" class="nav-link" data-scroll-target="#deep-q-learning">Deep Q-Learning</a>
  <ul class="collapse">
  <li><a href="#target-network" id="toc-target-network" class="nav-link" data-scroll-target="#target-network">Target Network</a></li>
  <li><a href="#exercise-1-q-network-and-target-network" id="toc-exercise-1-q-network-and-target-network" class="nav-link" data-scroll-target="#exercise-1-q-network-and-target-network">Exercise 1: Q-Network and Target Network</a></li>
  <li><a href="#experience-replay" id="toc-experience-replay" class="nav-link" data-scroll-target="#experience-replay">Experience Replay</a></li>
  </ul></li>
  <li><a href="#deep-q-learning-algorithm-with-experience-replay" id="toc-deep-q-learning-algorithm-with-experience-replay" class="nav-link" data-scroll-target="#deep-q-learning-algorithm-with-experience-replay">Deep Q-Learning Algorithm with Experience Replay</a>
  <ul class="collapse">
  <li><a href="#exercise-2-computing-the-loss" id="toc-exercise-2-computing-the-loss" class="nav-link" data-scroll-target="#exercise-2-computing-the-loss">Exercise 2: Computing the Loss</a></li>
  </ul></li>
  <li><a href="#update-the-network-weights" id="toc-update-the-network-weights" class="nav-link" data-scroll-target="#update-the-network-weights">Update the Network Weights</a></li>
  <li><a href="#train-the-agent" id="toc-train-the-agent" class="nav-link" data-scroll-target="#train-the-agent">Train the Agent</a></li>
  <li><a href="#trained-agent-in-action" id="toc-trained-agent-in-action" class="nav-link" data-scroll-target="#trained-agent-in-action">Trained Agent in Action</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../auth.js"></script>
<script src="../../giscus-note.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../sidebar-active.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../nav-columns.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="bi bi-flask lab-title-icon" aria-hidden="true"></span><span class="visually-hidden">Lab:</span> Deep Q-Learning, Lunar Lander</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">unsupervised-learning</div>
  </div>
  </div>

<div>
  <div class="description">
    Train a deep Q-network with experience replay, a target network, and an epsilon-greedy policy to land the lunar lander safely on the moon.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 27, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~110 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~3,800 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";    }
    var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
    var dateCells = ["date", "date-modified"];
    dateCells.forEach(function (cls) {
      var el = meta.querySelector("." + cls);
      if (!el || el.dataset.weekdayified) return;
      var text = el.textContent.trim();
      var d = new Date(text);
      if (!isNaN(d.getTime())) {
        el.textContent = days[d.getDay()] + ", " + text;
      }
      el.dataset.weekdayified = "1";
    });
  }
});
</script>

<p>The <a href="../../machine-learning/unsupervised-learning/continuous-state-spaces.html">previous page</a> developed the DQN algorithm and its refinements, the target values from the Bellman equation, the ϵ-greedy policy, mini-batches, and soft updates. This lab, the practice lab that closes the course, puts all of it into practice. You train an agent to land a lunar lander safely on a landing pad on the surface of the moon.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../media/reinforcement-learning/lunar-lander-lab/lunar_lander.gif" class="img-fluid figure-img" style="width:55.0%"></p>
<figcaption>The lunar lander environment.</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>How this lab runs
</div>
</div>
<div class="callout-body-container callout-body">
<p>The lab runs in the course’s Jupyter environment, which provides <code>gym</code> version <code>0.24.0</code> with the Box2D <code>LunarLander-v2</code> environment, TensorFlow, and a virtual display for rendering. The code on this page is therefore shown rather than executed here, and every output, including the training log, the training plot, and the landing video, comes from an actual completed run of the notebook. To run it yourself you also need the helper file the code imports, <a href="../../media/reinforcement-learning/lunar-lander-lab/utils.py">utils.py</a>, placed next to the notebook.</p>
</div>
</div>
<section id="import-packages" class="level2">
<h2 class="anchored" data-anchor-id="import-packages">Import Packages</h2>
<p>The lab makes use of the following packages.</p>
<ul>
<li><code>numpy</code> is a package for scientific computing in Python.</li>
<li><code>deque</code> will be the data structure for the memory buffer. A deque (double-ended queue) works like a list with a fixed capacity that automatically discards its oldest entries as new ones arrive, which is exactly the behavior the replay buffer needs.</li>
<li><code>namedtuple</code> will be used to store the experience tuples. A named tuple is a tuple whose positions carry names, so a stored experience can be read as <code>e.state</code> or <code>e.reward</code> instead of a bare index.</li>
<li>The <code>gym</code> toolkit is a collection of environments that can be used to test reinforcement learning algorithms. Note that this lab uses <code>gym</code> version <code>0.24.0</code>.</li>
<li><code>PIL.Image</code> and <code>pyvirtualdisplay</code> are needed to render the lunar lander environment.</li>
<li>Several modules from the <code>tensorflow.keras</code> framework are used for building deep learning models.</li>
<li><code>utils</code> is a module that contains helper functions for this lab. You do not need to modify its code.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> time</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> deque, namedtuple</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> gym</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> PIL.Image</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> utils</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> pyvirtualdisplay <span class="im">import</span> Display</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras <span class="im">import</span> Sequential</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.layers <span class="im">import</span> Dense, Input</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.losses <span class="im">import</span> MSE</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.optimizers <span class="im">import</span> Adam</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The next cell sets up a virtual display for rendering and seeds the TensorFlow pseudo-random number generator, so that runs are reproducible.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set up a virtual display to render the Lunar Lander environment.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>Display(visible<span class="op">=</span><span class="dv">0</span>, size<span class="op">=</span>(<span class="dv">840</span>, <span class="dv">480</span>)).start()<span class="op">;</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the random seed for TensorFlow</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>tf.random.set_seed(utils.SEED)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="hyperparameters" class="level2">
<h2 class="anchored" data-anchor-id="hyperparameters">Hyperparameters</h2>
<p>These four hyperparameters are used throughout the lab. The memory buffer size <span class="math inline">\(N\)</span> is the capacity of the replay buffer, <span class="math inline">\(\gamma\)</span> is the discount factor, <span class="math inline">\(\alpha\)</span> is the learning rate, and the algorithm performs a learning update every <span class="math inline">\(C = 4\)</span> time steps rather than on every single step.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>MEMORY_SIZE <span class="op">=</span> <span class="dv">100_000</span>     <span class="co"># size of memory buffer</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>GAMMA <span class="op">=</span> <span class="fl">0.995</span>             <span class="co"># discount factor</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>ALPHA <span class="op">=</span> <span class="fl">1e-3</span>              <span class="co"># learning rate</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>NUM_STEPS_FOR_UPDATE <span class="op">=</span> <span class="dv">4</span>  <span class="co"># perform a learning update every C time steps</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="lunar-lander-environment" class="level2">
<h2 class="anchored" data-anchor-id="lunar-lander-environment">Lunar Lander Environment</h2>
<p>The lab uses OpenAI’s Gym library. The Gym library provides a wide variety of environments for reinforcement learning. Gym has since been handed over to the Farama Foundation, which maintains it today under the name <a href="https://gymnasium.farama.org/">Gymnasium</a>, so the Gymnasium documentation is the current reference for these environments, including the lunar lander. To put it simply, an environment represents a problem or task to be solved, and here that task is the lunar lander.</p>
<p>The goal is to land the lunar lander safely on the landing pad on the surface of the moon. The landing pad is designated by two flag poles and its center is at coordinates <span class="math inline">\((0, 0)\)</span>, but the lander is also allowed to land outside of the landing pad. The lander starts at the top center of the environment with a random initial force applied to its center of mass, and has infinite fuel. The environment is considered solved when the agent gets <span class="math inline">\(200\)</span> points.</p>
<section id="action-space" class="level3">
<h3 class="anchored" data-anchor-id="action-space">Action Space</h3>
<p>The agent has four discrete actions available, each with a corresponding numerical value.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Do nothing <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>Fire right engine <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>Fire main engine <span class="op">=</span> <span class="dv">2</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>Fire left engine <span class="op">=</span> <span class="dv">3</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="observation-space" class="level3">
<h3 class="anchored" data-anchor-id="observation-space">Observation Space</h3>
<p>The agent’s observation space consists of a state vector with 8 variables.</p>
<ul>
<li>Its <span class="math inline">\((x, y)\)</span> coordinates. The landing pad is always at coordinates <span class="math inline">\((0, 0)\)</span>.</li>
<li>Its linear velocities <span class="math inline">\((\dot{x}, \dot{y})\)</span>.</li>
<li>Its angle <span class="math inline">\(\theta\)</span>.</li>
<li>Its angular velocity <span class="math inline">\(\dot{\theta}\)</span>.</li>
<li>Two booleans, <span class="math inline">\(l\)</span> and <span class="math inline">\(r\)</span>, that represent whether each leg is in contact with the ground or not.</li>
</ul>
</section>
<section id="rewards" class="level3">
<h3 class="anchored" data-anchor-id="rewards">Rewards</h3>
<p>After every step, a reward is granted. The total reward of an episode is the sum of the rewards for all the steps within that episode. For each step, the reward</p>
<ul>
<li>is increased or decreased the closer or further the lander is to the landing pad,</li>
<li>is increased or decreased the slower or faster the lander is moving,</li>
<li>is decreased the more the lander is tilted (angle not horizontal),</li>
<li>is increased by 10 points for each leg that is in contact with the ground,</li>
<li>is decreased by 0.03 points each frame a side engine is firing, and</li>
<li>is decreased by 0.3 points each frame the main engine is firing.</li>
</ul>
<p>The episode receives an additional reward of <span class="math inline">\(-100\)</span> or <span class="math inline">\(+100\)</span> points for crashing or landing safely, respectively.</p>
</section>
<section id="episode-termination" class="level3">
<h3 class="anchored" data-anchor-id="episode-termination">Episode Termination</h3>
<p>An episode ends, meaning the environment enters a terminal state, if the lunar lander crashes (the body of the lander comes in contact with the surface of the moon), or if the absolute value of the lander’s <span class="math inline">\(x\)</span> coordinate becomes greater than 1 (it goes beyond the left or right border). The <a href="https://gymnasium.farama.org/environments/box2d/lunar_lander/">Gymnasium documentation</a> has a full description of the environment.</p>
</section>
</section>
<section id="load-the-environment" class="level2">
<h2 class="anchored" data-anchor-id="load-the-environment">Load the Environment</h2>
<p>The <code>.make()</code> method loads the <code>LunarLander-v2</code> environment, the latest version of the lunar lander environment.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>env <span class="op">=</span> gym.make(<span class="st">'LunarLander-v2'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Once the environment is loaded, the <code>.reset()</code> method resets it to the initial state. The lander starts at the top center of the environment, and the <code>.render()</code> method draws the first frame.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>env.reset()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>PIL.Image.fromarray(env.render(mode<span class="op">=</span><span class="st">'rgb_array'</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../media/reinforcement-learning/lunar-lander-lab/env_render.png" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>First frame of the reset environment, with the lander at the top center.</figcaption>
</figure>
</div>
<p>To build the neural network later on, we need to know the size of the state vector and the number of valid actions. The environment provides this information through <code>.observation_space.shape</code> and <code>.action_space.n</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>state_size <span class="op">=</span> env.observation_space.shape</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>num_actions <span class="op">=</span> env.action_space.n</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'State Shape:'</span>, state_size)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Number of actions:'</span>, num_actions)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<pre><code>State Shape: (8,)
Number of actions: 4</code></pre>
</section>
<section id="interacting-with-the-gym-environment" class="level2">
<h2 class="anchored" data-anchor-id="interacting-with-the-gym-environment">Interacting with the Gym Environment</h2>
<p>The Gym library implements the standard agent-environment loop formalism, shown in the clip below. An agent interacts with the environment in discrete time steps <span class="math inline">\(t = 0, 1, 2, \dots\)</span>. At each time step <span class="math inline">\(t\)</span>, the agent uses a policy <span class="math inline">\(\pi\)</span> to select an action <span class="math inline">\(A_t\)</span> based on its observation of the environment’s state <span class="math inline">\(S_t\)</span>. The agent receives a numerical reward <span class="math inline">\(R_t\)</span> and, on the next time step, moves to a new state <span class="math inline">\(S_{t+1}\)</span>.</p>
<div style="text-align:center;">
<video src="/media/reinforcement-learning/lunar-lander-lab/rl_formalism.m4v" width="720" controls="" loop="" muted="" poster="/media/reinforcement-learning/lunar-lander-lab/rl_formalism.png" style="max-width:100%;"></video>
</div>
<section id="exploring-the-environment-dynamics" class="level3">
<h3 class="anchored" data-anchor-id="exploring-the-environment-dynamics">Exploring the Environment Dynamics</h3>
<p>In Gym environments, the <code>.step()</code> method runs a single time step of the environment’s dynamics. In the version of <code>gym</code> used in this lab, <code>.step()</code> accepts an action and returns four values.</p>
<ul>
<li><code>observation</code> (<strong>object</strong>), an environment-specific object representing the observation of the environment. In the lunar lander this is a numpy array containing the positions and velocities described in the observation space section above.</li>
<li><code>reward</code> (<strong>float</strong>), the amount of reward returned as a result of taking the given action, a <code>numpy.float64</code> as described in the rewards section.</li>
<li><code>done</code> (<strong>boolean</strong>), which is <code>True</code> when the episode has terminated and the environment needs to be reset.</li>
<li><code>info</code> (<strong>dictionary</strong>), diagnostic information useful for debugging, not used in this lab.</li>
</ul>
<p>To begin an episode, reset the environment to an initial state with <code>.reset()</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reset the environment and get the initial state.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>current_state <span class="op">=</span> env.reset()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Once the environment is reset, the agent can start taking actions by calling <code>.step()</code>, one action per time step. The cell below takes action <code>0</code> (do nothing) and displays the returned values. You can select different actions by their numerical value and see how the returned values change.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Select an action</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>action <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Run a single time step of the environment's dynamics with the given action.</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>next_state, reward, done, _ <span class="op">=</span> env.step(action)</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Display table with values.</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>utils.display_table(current_state, action, next_state, reward, done)</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace the `current_state` with the state after the action is taken</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>current_state <span class="op">=</span> next_state</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The run recorded on this page produced the following transition for the do-nothing action.</p>
<table class="caption-top table">
<caption>Effect of a single do-nothing step on the state vector</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th style="text-align: right;"><span class="math inline">\(x\)</span></th>
<th style="text-align: right;"><span class="math inline">\(y\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\dot{x}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\dot{y}\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\theta\)</span></th>
<th style="text-align: right;"><span class="math inline">\(\dot{\theta}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(l\)</span></th>
<th style="text-align: center;"><span class="math inline">\(r\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Current state</td>
<td style="text-align: right;">0.001919</td>
<td style="text-align: right;">1.422301</td>
<td style="text-align: right;">0.194400</td>
<td style="text-align: right;">0.505814</td>
<td style="text-align: right;"><span class="math inline">\(-0.002217\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.044034\)</span></td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td>Next state</td>
<td style="text-align: right;">0.003839</td>
<td style="text-align: right;">1.433103</td>
<td style="text-align: right;">0.194137</td>
<td style="text-align: right;">0.480094</td>
<td style="text-align: right;"><span class="math inline">\(-0.004393\)</span></td>
<td style="text-align: right;"><span class="math inline">\(-0.043519\)</span></td>
<td style="text-align: center;">False</td>
<td style="text-align: center;">False</td>
</tr>
</tbody>
</table>
<p>The step returned a reward of <span class="math inline">\(1.104326\)</span> and <code>done</code> equal to <code>False</code>, so the episode continued. Even though the agent did nothing, the lander kept drifting upward slightly under its random initial force while gravity pulled the vertical velocity down, and both legs stayed off the ground. In practice, when the agent is trained, a loop lets it take many consecutive actions during an episode.</p>
</section>
</section>
<section id="deep-q-learning" class="level2">
<h2 class="anchored" data-anchor-id="deep-q-learning">Deep Q-Learning</h2>
<p>In cases where both the state and action space are discrete, the action-value function can be estimated iteratively by using the Bellman equation, <span class="math display">\[Q_{i+1}(s, a) = R + \gamma \max_{a'} Q_i(s', a')\]</span> This iterative method converges to the optimal action-value function <span class="math inline">\(Q^*(s, a)\)</span> as <span class="math inline">\(i \to \infty\)</span>. The agent just needs to gradually explore the state-action space and keep updating the estimate of <span class="math inline">\(Q(s, a)\)</span> until it converges. However, in cases where the state space is continuous, as with the lunar lander, it becomes practically impossible to explore the entire state-action space, which also makes it practically impossible to estimate <span class="math inline">\(Q(s, a)\)</span> this way until it converges to <span class="math inline">\(Q^*(s, a)\)</span>.</p>
<p>In deep Q-learning, we solve this problem by using a neural network to estimate the action-value function, <span class="math inline">\(Q(s, a) \approx Q^*(s, a)\)</span>. This neural network is the <strong>Q-network</strong>, and it can be trained by adjusting its weights at each iteration to minimize the mean squared error in the Bellman equation.</p>
<p>Unfortunately, using neural networks in reinforcement learning to estimate action-value functions has proven to be highly unstable. Luckily, a couple of techniques can be employed to avoid instabilities, a <strong>target network</strong> and <strong>experience replay</strong>. The following sections explore both.</p>
<section id="target-network" class="level3">
<h3 class="anchored" data-anchor-id="target-network">Target Network</h3>
<p>The Q-network can be trained by adjusting its weights at each iteration to minimize the mean squared error in the Bellman equation, where the target values are <span class="math display">\[y = R + \gamma \max_{a'} Q(s', a'; w)\]</span> and <span class="math inline">\(w\)</span> are the weights of the Q-network. The weights <span class="math inline">\(w\)</span> are adjusted at each iteration to minimize the error <span class="math display">\[\overbrace{\underbrace{R + \gamma \max_{a'} Q(s', a'; w)}_{y \text{ target}} - Q(s, a; w)}^{\text{Error}}\]</span></p>
<p>Notice the problem here. The <span class="math inline">\(y\)</span> target is changing on every iteration, because it is computed with the very weights being adjusted. Having a constantly moving target can lead to oscillations and instabilities. To avoid this, we create a separate neural network for generating the <span class="math inline">\(y\)</span> targets, called the <strong>target <span class="math inline">\(\hat{Q}\)</span>-network</strong>, with the same architecture as the original Q-network. The error becomes <span class="math display">\[\overbrace{\underbrace{R + \gamma \max_{a'} \hat{Q}(s', a'; w^-)}_{y \text{ target}} - Q(s, a; w)}^{\text{Error}}\]</span> where <span class="math inline">\(w^-\)</span> and <span class="math inline">\(w\)</span> are the weights of the target <span class="math inline">\(\hat{Q}\)</span>-network and Q-network, respectively.</p>
<p>In practice, every <span class="math inline">\(C\)</span> time steps the target <span class="math inline">\(\hat{Q}\)</span>-network generates the <span class="math inline">\(y\)</span> targets, and its weights get updated from the Q-network weights using a <strong>soft update</strong>, <span class="math display">\[w^- \leftarrow \tau w + (1 - \tau) w^-\]</span> where <span class="math inline">\(\tau \ll 1\)</span>. The soft update ensures the target values <span class="math inline">\(y\)</span> change slowly, which greatly improves the stability of the learning algorithm. In this lab, <span class="math inline">\(\tau\)</span> is set to <span class="math inline">\(0.001\)</span> in the <code>utils</code> module.</p>
</section>
<section id="exercise-1-q-network-and-target-network" class="level3">
<h3 class="anchored" data-anchor-id="exercise-1-q-network-and-target-network">Exercise 1: Q-Network and Target Network</h3>
<p>This exercise creates the Q-network and the target <span class="math inline">\(\hat{Q}\)</span>-network and sets the optimizer. The deep Q-network maps states to Q values, using the architecture developed on the previous page.</p>
<ul>
<li>An <code>Input</code> layer that takes <code>state_size</code> as input.</li>
<li>A <code>Dense</code> layer with <code>64</code> units and a <code>relu</code> activation function.</li>
<li>A <code>Dense</code> layer with <code>64</code> units and a <code>relu</code> activation function.</li>
<li>A <code>Dense</code> layer with <code>num_actions</code> units and a <code>linear</code> activation function. This is the output layer of the network.</li>
</ul>
<p>Both networks get the same architecture, and the optimizer is <code>Adam</code> with a learning rate equal to <code>ALPHA</code> from the hyperparameters section.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the Q-Network</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>q_network <span class="op">=</span> Sequential([</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    Input(shape<span class="op">=</span>state_size),</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span>num_actions, activation<span class="op">=</span><span class="st">'linear'</span>),</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the target Q^-Network</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>target_q_network <span class="op">=</span> Sequential([</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    Input(shape<span class="op">=</span>state_size),</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span><span class="dv">64</span>, activation<span class="op">=</span><span class="st">'relu'</span>),</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>    Dense(units<span class="op">=</span>num_actions, activation<span class="op">=</span><span class="st">'linear'</span>),</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>    ])</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> Adam(learning_rate<span class="op">=</span>ALPHA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Two details in that code are easy to skim past. The two networks are written out separately rather than one being copied from the other, so they start as independent objects with independently initialized weights. They will not stay identical, and that is the whole point of holding a target network. Only the output layer is <code>linear</code>. A Q value is an expected return, an unbounded quantity that can be negative when the lander crashes, so squashing it with a <code>relu</code> or a <code>sigmoid</code> would make the larger part of the value range unreachable.</p>
</section>
<section id="experience-replay" class="level3">
<h3 class="anchored" data-anchor-id="experience-replay">Experience Replay</h3>
<p>When an agent interacts with the environment, the states, actions, and rewards it experiences are sequential by nature. If the agent tries to learn from these consecutive experiences, it can run into problems due to the strong correlations between them. To avoid this, we employ <strong>experience replay</strong> to generate uncorrelated experiences for training. Experience replay consists of storing the agent’s experiences (the states, actions, and rewards it receives) in a memory buffer, and then sampling a random mini-batch of experiences from the buffer to do the learning. The experience tuples <span class="math inline">\((S_t, A_t, R_t, S_{t+1})\)</span> get added to the memory buffer at each time step as the agent interacts with the environment.</p>
<p>For convenience, experiences are stored as named tuples.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Store experiences as named tuples</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>experience <span class="op">=</span> namedtuple(<span class="st">"Experience"</span>, field_names<span class="op">=</span>[<span class="st">"state"</span>, <span class="st">"action"</span>, <span class="st">"reward"</span>, <span class="st">"next_state"</span>, <span class="st">"done"</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>By using experience replay, we avoid problematic correlations, oscillations, and instabilities. In addition, experience replay also allows the agent to potentially use the same experience in multiple weight updates, which increases data efficiency.</p>
</section>
</section>
<section id="deep-q-learning-algorithm-with-experience-replay" class="level2">
<h2 class="anchored" data-anchor-id="deep-q-learning-algorithm-with-experience-replay">Deep Q-Learning Algorithm with Experience Replay</h2>
<p>Putting the target network and experience replay together produces the full algorithm.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../media/reinforcement-learning/lunar-lander-lab/deep_q_algorithm.png" class="img-fluid figure-img" style="width:90.0%"></p>
<figcaption>Deep Q-learning with experience replay.</figcaption>
</figure>
</div>
<section id="exercise-2-computing-the-loss" class="level3">
<h3 class="anchored" data-anchor-id="exercise-2-computing-the-loss">Exercise 2: Computing the Loss</h3>
<p>This exercise implements line 12 of the algorithm above and computes the loss between the <span class="math inline">\(y\)</span> targets and the <span class="math inline">\(Q(s, a)\)</span> values. The <code>compute_loss</code> function sets the <span class="math inline">\(y\)</span> targets equal to <span class="math display">\[
y_j =
\begin{cases}
R_j &amp; \text{if episode terminates at step } j+1\\
R_j + \gamma \max\limits_{a'} \hat{Q}(s_{j+1}, a') &amp; \text{otherwise}
\end{cases}
\]</span></p>
<p>A couple of things worth noting about the implementation.</p>
<ul>
<li>The <code>compute_loss</code> function takes in a mini-batch of experience tuples, which is unpacked to extract <code>states</code>, <code>actions</code>, <code>rewards</code>, <code>next_states</code>, and <code>done_vals</code>. All of these are TensorFlow tensors whose size depends on the mini-batch size. For example, with a mini-batch size of <code>64</code>, both <code>rewards</code> and <code>done_vals</code> are tensors with <code>64</code> elements.</li>
<li>Using <code>if/else</code> statements to set the <span class="math inline">\(y\)</span> targets will not work when the variables are tensors with many elements. However, the <code>done_vals</code> tensor implements the case split in a single line. A Boolean <code>True</code> has the numerical value <code>1</code> and <code>False</code> has the value <code>0</code>, so the factor <code>(1 - done_vals)</code> equals <code>0</code> when an episode terminates at step <span class="math inline">\(j+1\)</span> and <code>1</code> otherwise, which switches the future term on and off exactly as the cases require.</li>
<li>The two lines with <code>tf.gather_nd</code> look intimidating, but their job is simple. The network outputs four Q values for every state in the mini-batch, and these lines pick out, for each experience, the single Q value of the action that was actually taken, so that it can be compared against its target.</li>
<li>The loss is the mean squared error (<code>MSE</code>) between the <code>y_targets</code> and the <code>q_values</code>.</li>
</ul>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_loss(experiences, gamma, q_network, target_q_network):</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Calculates the loss.</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a><span class="co">      experiences: (tuple) tuple of ["state", "action", "reward", "next_state", "done"] namedtuples</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co">      gamma: (float) The discount factor.</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="co">      q_network: (tf.keras.Sequential) Keras model for predicting the q_values</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">      target_q_network: (tf.keras.Sequential) Keras model for predicting the targets</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co">      loss: (TensorFlow Tensor(shape=(0,), dtype=int32)) the Mean-Squared Error between</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="co">            the y targets and the Q(s,a) values.</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Unpack the mini-batch of experience tuples</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    states, actions, rewards, next_states, done_vals <span class="op">=</span> experiences</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute max Q^(s,a)</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    max_qsa <span class="op">=</span> tf.reduce_max(target_q_network(next_states), axis<span class="op">=-</span><span class="dv">1</span>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Set y = R if episode terminates, otherwise set y = R + γ max Q^(s,a).</span></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>    y_targets <span class="op">=</span> rewards <span class="op">+</span> gamma <span class="op">*</span> max_qsa <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> done_vals)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the q_values and reshape to match y_targets</span></span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a>    q_values <span class="op">=</span> q_network(states)</span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    q_values <span class="op">=</span> tf.gather_nd(q_values, tf.stack([tf.<span class="bu">range</span>(q_values.shape[<span class="dv">0</span>]),</span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>                                                tf.cast(actions, tf.int32)], axis<span class="op">=</span><span class="dv">1</span>))</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Compute the loss</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>    loss <span class="op">=</span> MSE(y_targets, q_values)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> loss</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
</section>
<section id="update-the-network-weights" class="level2">
<h2 class="anchored" data-anchor-id="update-the-network-weights">Update the Network Weights</h2>
<p>The <code>agent_learn</code> function implements lines 12 to 14 of the algorithm, updating the weights of the Q and target <span class="math inline">\(\hat{Q}\)</span> networks using a custom training loop. Because it is a custom training loop, rather than the usual <code>model.fit()</code> call from the earlier courses, the gradients are retrieved via a <code>tf.GradientTape</code> instance, and <code>optimizer.apply_gradients()</code> then updates the weights of the Q-network. A gradient tape records the calculations performed inside its block, which lets TensorFlow work out the gradients of the loss with respect to the weights, exactly the derivatives that gradient descent needs. The <code>@tf.function</code> decorator increases performance, and without it training takes twice as long. The last line updates the weights of the target <span class="math inline">\(\hat{Q}\)</span>-network using the soft update from earlier, implemented in <code>utils.update_target_network</code>.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="at">@tf.function</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> agent_learn(experiences, gamma):</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Updates the weights of the Q networks.</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co">      experiences: (tuple) tuple of ["state", "action", "reward", "next_state", "done"] namedtuples</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="co">      gamma: (float) The discount factor.</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the loss</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">with</span> tf.GradientTape() <span class="im">as</span> tape:</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        loss <span class="op">=</span> compute_loss(experiences, gamma, q_network, target_q_network)</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the gradients of the loss with respect to the weights.</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    gradients <span class="op">=</span> tape.gradient(loss, q_network.trainable_variables)</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Update the weights of the q_network.</span></span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>    optimizer.apply_gradients(<span class="bu">zip</span>(gradients, q_network.trainable_variables))</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># update the weights of target q_network</span></span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    utils.update_target_network(q_network, target_q_network)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="train-the-agent" class="level2">
<h2 class="anchored" data-anchor-id="train-the-agent">Train the Agent</h2>
<p>Everything is now in place to train the agent. The training cell implements the algorithm figure line by line.</p>
<ul>
<li><strong>Line 1.</strong> Initialize the <code>memory_buffer</code> with a capacity of <span class="math inline">\(N =\)</span> <code>MEMORY_SIZE</code>. A <code>deque</code> serves as the data structure.</li>
<li><strong>Line 2.</strong> Skipped, since the <code>q_network</code> was already initialized in Exercise 1.</li>
<li><strong>Line 3.</strong> Initialize the <code>target_q_network</code> by setting its weights equal to those of the <code>q_network</code>.</li>
<li><strong>Line 4.</strong> Start the outer loop over <span class="math inline">\(M =\)</span> <code>num_episodes = 2000</code> episodes. This number is reasonable because the agent should be able to solve the environment in fewer than 2,000 episodes with this lab’s default parameters.</li>
<li><strong>Line 5.</strong> Use <code>.reset()</code> to get the initial state.</li>
<li><strong>Line 6.</strong> Start the inner loop over <span class="math inline">\(T =\)</span> <code>max_num_timesteps = 1000</code> time steps, so an episode terminates automatically if it has not ended after 1,000 steps.</li>
<li><strong>Line 7.</strong> The agent observes the current <code>state</code> and chooses an <code>action</code> using an ϵ-greedy policy. Training starts with <span class="math inline">\(\epsilon = 1\)</span>, equivalent to the equiprobable random policy (every one of the four actions is equally likely), so at the beginning the agent takes random actions regardless of the observed state. As training progresses, <span class="math inline">\(\epsilon\)</span> decreases slowly toward a minimum value using the decay rate <code>E_DECAY = 0.995</code>, so the agent leans more and more toward the actions it believes will maximize <span class="math inline">\(Q(s, a)\)</span>. The minimum is <code>E_MIN = 0.01</code> rather than exactly zero, to always keep a little bit of exploration during training. The implementation is in <code>utils.get_action</code>.</li>
<li><strong>Line 8.</strong> Use <code>.step()</code> to take the action and receive the <code>reward</code> and the <code>next_state</code>.</li>
<li><strong>Line 9.</strong> Store the <code>experience(state, action, reward, next_state, done)</code> tuple in the <code>memory_buffer</code>. The <code>done</code> variable is stored too, so that the <span class="math inline">\(y\)</span> targets in Exercise 2 know when an episode terminated.</li>
<li><strong>Line 10.</strong> Check whether the conditions are met to perform a learning update, via <code>utils.check_update_conditions</code>. The conditions are that <span class="math inline">\(C =\)</span> <code>NUM_STEPS_FOR_UPDATE = 4</code> time steps have occurred, and that the <code>memory_buffer</code> holds enough tuples to fill a mini-batch of 64.</li>
<li><strong>Lines 11 to 14.</strong> If an update is due, sample a random mini-batch of experience tuples from the buffer with <code>utils.get_experiences</code>, then set the <span class="math inline">\(y\)</span> targets, perform a gradient descent step, and update the network weights, all through the <code>agent_learn</code> function.</li>
<li><strong>Line 15.</strong> Set <code>next_state</code> as the new <code>state</code>, and break out of the inner loop if the episode has reached a terminal state.</li>
<li><strong>Line 16.</strong> Update the value of <span class="math inline">\(\epsilon\)</span> and check whether the environment is solved, defined as an average of 200 points over the last 100 episodes.</li>
</ul>
<p>The cell also tracks the total points per episode, to determine when the environment is solved and to see how the agent improved during training, and times the whole run.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>start <span class="op">=</span> time.time()</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>num_episodes <span class="op">=</span> <span class="dv">2000</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>max_num_timesteps <span class="op">=</span> <span class="dv">1000</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>total_point_history <span class="op">=</span> []</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>num_p_av <span class="op">=</span> <span class="dv">100</span>    <span class="co"># number of total points to use for averaging</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>epsilon <span class="op">=</span> <span class="fl">1.0</span>     <span class="co"># initial ε value for ε-greedy policy</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a memory buffer D with capacity N</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>memory_buffer <span class="op">=</span> deque(maxlen<span class="op">=</span>MEMORY_SIZE)</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the target network weights equal to the Q-Network weights</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>target_q_network.set_weights(q_network.get_weights())</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(num_episodes):</span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Reset the environment to the initial state and get the initial state</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    state <span class="op">=</span> env.reset()</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    total_points <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(max_num_timesteps):</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># From the current state S choose an action A using an ε-greedy policy</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>        state_qn <span class="op">=</span> np.expand_dims(state, axis<span class="op">=</span><span class="dv">0</span>)  <span class="co"># state needs to be the right shape for the q_network</span></span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>        q_values <span class="op">=</span> q_network(state_qn)</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>        action <span class="op">=</span> utils.get_action(q_values, epsilon)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Take action A and receive reward R and the next state S'</span></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>        next_state, reward, done, _ <span class="op">=</span> env.step(action)</span>
<span id="cb15-32"><a href="#cb15-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-33"><a href="#cb15-33" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Store experience tuple (S,A,R,S') in the memory buffer.</span></span>
<span id="cb15-34"><a href="#cb15-34" aria-hidden="true" tabindex="-1"></a>        <span class="co"># We store the done variable as well for convenience.</span></span>
<span id="cb15-35"><a href="#cb15-35" aria-hidden="true" tabindex="-1"></a>        memory_buffer.append(experience(state, action, reward, next_state, done))</span>
<span id="cb15-36"><a href="#cb15-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-37"><a href="#cb15-37" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Only update the network every NUM_STEPS_FOR_UPDATE time steps.</span></span>
<span id="cb15-38"><a href="#cb15-38" aria-hidden="true" tabindex="-1"></a>        update <span class="op">=</span> utils.check_update_conditions(t, NUM_STEPS_FOR_UPDATE, memory_buffer)</span>
<span id="cb15-39"><a href="#cb15-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-40"><a href="#cb15-40" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> update:</span>
<span id="cb15-41"><a href="#cb15-41" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Sample random mini-batch of experience tuples (S,A,R,S') from D</span></span>
<span id="cb15-42"><a href="#cb15-42" aria-hidden="true" tabindex="-1"></a>            experiences <span class="op">=</span> utils.get_experiences(memory_buffer)</span>
<span id="cb15-43"><a href="#cb15-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-44"><a href="#cb15-44" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Set the y targets, perform a gradient descent step,</span></span>
<span id="cb15-45"><a href="#cb15-45" aria-hidden="true" tabindex="-1"></a>            <span class="co"># and update the network weights.</span></span>
<span id="cb15-46"><a href="#cb15-46" aria-hidden="true" tabindex="-1"></a>            agent_learn(experiences, GAMMA)</span>
<span id="cb15-47"><a href="#cb15-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-48"><a href="#cb15-48" aria-hidden="true" tabindex="-1"></a>        state <span class="op">=</span> next_state.copy()</span>
<span id="cb15-49"><a href="#cb15-49" aria-hidden="true" tabindex="-1"></a>        total_points <span class="op">+=</span> reward</span>
<span id="cb15-50"><a href="#cb15-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-51"><a href="#cb15-51" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> done:</span>
<span id="cb15-52"><a href="#cb15-52" aria-hidden="true" tabindex="-1"></a>            <span class="cf">break</span></span>
<span id="cb15-53"><a href="#cb15-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-54"><a href="#cb15-54" aria-hidden="true" tabindex="-1"></a>    total_point_history.append(total_points)</span>
<span id="cb15-55"><a href="#cb15-55" aria-hidden="true" tabindex="-1"></a>    av_latest_points <span class="op">=</span> np.mean(total_point_history[<span class="op">-</span>num_p_av:])</span>
<span id="cb15-56"><a href="#cb15-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-57"><a href="#cb15-57" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Update the ε value</span></span>
<span id="cb15-58"><a href="#cb15-58" aria-hidden="true" tabindex="-1"></a>    epsilon <span class="op">=</span> utils.get_new_eps(epsilon)</span>
<span id="cb15-59"><a href="#cb15-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-60"><a href="#cb15-60" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\r</span><span class="ss">Episode </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> | Total point average of the last </span><span class="sc">{</span>num_p_av<span class="sc">}</span><span class="ss"> episodes: </span><span class="sc">{</span>av_latest_points<span class="sc">:.2f}</span><span class="ss">"</span>, end<span class="op">=</span><span class="st">""</span>)</span>
<span id="cb15-61"><a href="#cb15-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-62"><a href="#cb15-62" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (i<span class="op">+</span><span class="dv">1</span>) <span class="op">%</span> num_p_av <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb15-63"><a href="#cb15-63" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\r</span><span class="ss">Episode </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> | Total point average of the last </span><span class="sc">{</span>num_p_av<span class="sc">}</span><span class="ss"> episodes: </span><span class="sc">{</span>av_latest_points<span class="sc">:.2f}</span><span class="ss">"</span>)</span>
<span id="cb15-64"><a href="#cb15-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-65"><a href="#cb15-65" aria-hidden="true" tabindex="-1"></a>    <span class="co"># We will consider that the environment is solved if we get an</span></span>
<span id="cb15-66"><a href="#cb15-66" aria-hidden="true" tabindex="-1"></a>    <span class="co"># average of 200 points in the last 100 episodes.</span></span>
<span id="cb15-67"><a href="#cb15-67" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> av_latest_points <span class="op">&gt;=</span> <span class="fl">200.0</span>:</span>
<span id="cb15-68"><a href="#cb15-68" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n\n</span><span class="ss">Environment solved in </span><span class="sc">{</span>i<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss"> episodes!"</span>)</span>
<span id="cb15-69"><a href="#cb15-69" aria-hidden="true" tabindex="-1"></a>        q_network.save(<span class="st">'lunar_lander_model.h5'</span>)</span>
<span id="cb15-70"><a href="#cb15-70" aria-hidden="true" tabindex="-1"></a>        <span class="cf">break</span></span>
<span id="cb15-71"><a href="#cb15-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-72"><a href="#cb15-72" aria-hidden="true" tabindex="-1"></a>tot_time <span class="op">=</span> time.time() <span class="op">-</span> start</span>
<span id="cb15-73"><a href="#cb15-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-74"><a href="#cb15-74" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">Total Runtime: </span><span class="sc">{</span>tot_time<span class="sc">:.2f}</span><span class="ss"> s (</span><span class="sc">{</span>(tot_time<span class="op">/</span><span class="dv">60</span>)<span class="sc">:.2f}</span><span class="ss"> min)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>With the default parameters, this cell takes between 10 and 15 minutes to run. The recorded run produced the following log.</p>
<pre><code>Episode 100 | Total point average of the last 100 episodes: -150.85
Episode 200 | Total point average of the last 100 episodes: -106.11
Episode 300 | Total point average of the last 100 episodes: -77.256
Episode 400 | Total point average of the last 100 episodes: -25.01
Episode 500 | Total point average of the last 100 episodes: 159.91
Episode 534 | Total point average of the last 100 episodes: 201.37

Environment solved in 534 episodes!

Total Runtime: 753.70 s (12.56 min)</code></pre>
<p>Plotting the total point history along with the moving average shows how the agent improved during training. Early episodes score deeply negative totals, mostly crashes under the random policy, and the average climbs steadily as <span class="math inline">\(\epsilon\)</span> decays and the Q-network improves, crossing the 200-point threshold at episode 534.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the total point history along with the moving average</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>utils.plot_history(total_point_history)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../../media/reinforcement-learning/lunar-lander-lab/training_plot.png" class="img-fluid figure-img" style="width:75.0%"></p>
<figcaption>Total points per episode (light blue) and the 100-episode moving average (dark blue).</figcaption>
</figure>
</div>
</section>
<section id="trained-agent-in-action" class="level2">
<h2 class="anchored" data-anchor-id="trained-agent-in-action">Trained Agent in Action</h2>
<p>With the agent trained, the <code>utils.create_video</code> function creates a video of the agent interacting with the environment using the trained Q-network, and <code>utils.embed_mp4</code> embeds it in the notebook. Suppressing the <code>imageio</code> warnings first keeps the output clean.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Suppress warnings from imageio</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> logging</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>logging.getLogger().setLevel(logging.ERROR)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>filename <span class="op">=</span> <span class="st">"./videos/lunar_lander.mp4"</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>utils.create_video(filename, env, q_network)</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>utils.embed_mp4(filename)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Since the lander starts with a random initial force applied to its center of mass, every run of this cell produces a different video. If the agent was trained properly, it should land the lunar lander in the landing pad every time, regardless of the initial force. Here is the landing from the recorded run.</p>
<div style="text-align:center;">
<video src="/media/reinforcement-learning/lunar-lander-lab/lunar_lander_trained.mp4" width="720" controls="" loop="" style="max-width:100%;"></video>
</div>
<p>You have successfully used deep Q-learning with experience replay to train an agent to land a lunar lander safely on a landing pad on the surface of the moon.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Why does training a Q-network directly on the Bellman targets become unstable, and how does the target network help?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The target <span class="math inline">\(y = R + \gamma \max_{a'} Q(s', a'; w)\)</span> is computed with the same weights <span class="math inline">\(w\)</span> being trained, so the target moves on every iteration, which can cause oscillations and instabilities. The target <span class="math inline">\(\hat{Q}\)</span>-network is a separate copy whose weights <span class="math inline">\(w^-\)</span> change only through the slow soft update <span class="math inline">\(w^- \leftarrow \tau w + (1 - \tau) w^-\)</span> with <span class="math inline">\(\tau = 0.001\)</span>, so the targets change slowly and learning becomes much more stable.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What problem does experience replay solve, and what is the extra efficiency benefit?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Consecutive experiences are strongly correlated, and learning from them in order can cause problems. Storing experiences in a memory buffer and sampling a random mini-batch breaks those correlations. As a bonus, one experience can be reused in multiple weight updates, which increases data efficiency.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In <code>compute_loss</code>, why does the expression <code>rewards + gamma * max_qsa * (1 - done_vals)</code> implement the two-case definition of the targets?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The <code>done_vals</code> tensor holds <code>1</code> where the episode terminated at the next step and <code>0</code> where it did not. The factor <code>(1 - done_vals)</code> is therefore <code>0</code> at terminal transitions, reducing the target to <span class="math inline">\(R_j\)</span> alone, and <code>1</code> otherwise, keeping the full <span class="math inline">\(R_j + \gamma \max_{a'} \hat{Q}(s_{j+1}, a')\)</span>. One vectorized line replaces an <code>if/else</code> that would not work on tensors with many elements.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. How does the ϵ-greedy schedule in this lab move from exploration to exploitation?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Training starts with <span class="math inline">\(\epsilon = 1.0\)</span>, a completely random policy. After each episode, <span class="math inline">\(\epsilon\)</span> is multiplied by the decay rate <span class="math inline">\(0.995\)</span>, shrinking it gradually toward the minimum of <span class="math inline">\(0.01\)</span>, where it stays. The agent therefore explores heavily at first and acts greedily 99 percent of the time by the end, while always keeping a little exploration.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. When is the lunar lander environment considered solved, and when did the recorded run solve it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The environment is considered solved when the agent averages 200 points over the last 100 episodes. The recorded run reached an average of 201.37 at episode 534, after about 12.5 minutes of training.</p>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>To learn more about deep Q-learning, these are the papers behind the techniques used in this lab.</p>
<ul>
<li>Lillicrap, T. P., Hunt, J. J., Pritzel, A., Heess, N., Erez, T., Tassa, Y., et al.&nbsp;(2015). <em>Continuous control with deep reinforcement learning</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1509.02971" class="uri">https://doi.org/10.48550/arXiv.1509.02971</a></li>
<li>Mnih, V., Kavukcuoglu, K., Silver, D., Graves, A., Antonoglou, I., Wierstra, D., et al.&nbsp;(2013). <em>Playing Atari with deep reinforcement learning</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1312.5602" class="uri">https://doi.org/10.48550/arXiv.1312.5602</a></li>
<li>Mnih, V., Kavukcuoglu, K., Silver, D., Rusu, A. A., Veness, J., Bellemare, M. G., et al.&nbsp;(2015). Human-level control through deep reinforcement learning. <em>Nature, 518</em>(7540), 529-533. <a href="https://doi.org/10.1038/nature14236" class="uri">https://doi.org/10.1038/nature14236</a></li>
</ul>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 100%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">100% completed (1064 of 1064 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../machine-learning/unsupervised-learning/continuous-state-spaces.html" class="pagination-link" aria-label="Continuous State Spaces">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Continuous State Spaces</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>