<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Turn an ImageNet MobileNetV2 into an alpaca detector by training one new neuron on frozen features, then fine tuning the last 34 layers of the network.">

<title>Lab: Transfer Learning with MobileNetV2 – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../ai/deep-learning/convolutional-neural-networks/object-localization-and-landmark-detection" rel="next">
<link href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets" rel="prev">
<link href="../../../media/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-09af6f1c3ba400237d3ba77e487e1b25.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-43798084b7368a40096bd6648f6381c9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css?v=ba0d21cc">
<meta property="og:title" content="Lab: Transfer Learning with MobileNetV2 – H’s Notes">
<meta property="og:description" content="Turn an ImageNet MobileNetV2 into an alpaca detector by training one new neuron on frozen features, then fine tuning the last 34 layers of the network.">
<meta property="og:image" content="https://oliabak.com/ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet_files/figure-html/cell-4-output-1.png">
<meta property="og:site_name" content="H’s Notes">
<meta property="og:image:height" content="659">
<meta property="og:image:width" content="635">
<meta name="twitter:title" content="Lab: Transfer Learning with MobileNetV2 – H’s Notes">
<meta name="twitter:description" content="Turn an ImageNet MobileNetV2 into an alpaca detector by training one new neuron on frozen features, then fine tuning the last 34 layers of the network.">
<meta name="twitter:image" content="https://oliabak.com/ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet_files/figure-html/cell-4-output-1.png">
<meta name="twitter:image-height" content="659">
<meta name="twitter:image-width" content="635">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://oliabak.com/ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet">
<script type="application/ld+json" data-breadcrumbs="1">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Artificial Intelligence",
      "item": "https://oliabak.com/ai/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Deep Learning",
      "item": "https://oliabak.com/ai/deep-learning/"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Convolutional Neural Networks",
      "item": "https://oliabak.com/ai/deep-learning/convolutional-neural-networks/"
    },
    {
      "@type": "ListItem",
      "position": 4,
      "name": "Lab: Transfer Learning with MobileNetV2",
      "item": "https://oliabak.com/ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet"
    }
  ]
}
</script>
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../../networking/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccde-written/">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccie-data-center/">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../networking/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-routing/">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-switching/">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/kali-linux/">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../../ai/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/supervised-machine-learning/">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/advanced-learning-algorithms/">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/unsupervised-learning/">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/federated-learning/">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/neural-networks-and-deep-learning/">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/improving-deep-neural-networks/">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/structuring-machine-learning-projects/">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/convolutional-neural-networks/">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/sequence-models/">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../../math/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/linear-algebra/">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/calculus/">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/probability/">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/statistics/">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../../tools/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../../tools/client-info">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/asn-conversion">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/subnet-calculator">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/network-toolkit">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/pastebin">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/qr-code">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/fancy-text">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/copy-paste-values">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Classroom</li>
        <li>
    <a class="dropdown-item" href="../../../tools/randomizer">
 <span class="dropdown-text">Randomizer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../../tools/function-graphs">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/math-formula">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/latex-preview">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/markdown-preview">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/eclipse-atlas">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/planetarium">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../../tools/svg-preview">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/color-pallet">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/typography">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/tshirt-design">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../../tools/chess">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/reassess-your-chess">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/daily-chess">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../about">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/dashboard">
 <span class="dropdown-text">Dashboard</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../../about/roadmap">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/about-this-website">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet">Transfer Learning with MobileNetV2</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutional Neural Networks</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/convolutions-and-edge-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutions and Edge Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/strided-convolutions-and-volumes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Strided Convolutions and Convolutions Over Volume</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/one-layer-of-a-convolutional-network" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One Layer of a Convolutional Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/pooling-layers" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pooling Layers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full ConvNet Example and Why Convolutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-convolutional-model-step-by-step" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Convolutional Model Step by Step</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-convolutional-model-application" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Convolutional Model Application</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/classic-networks" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classic Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/modern-networks" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modern Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Residual Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MobileNet and EfficientNet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practical Advice for Using ConvNets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet" class="sidebar-item-text sidebar-link active"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Transfer Learning with MobileNetV2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/object-localization-and-landmark-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Object Localization and Landmark Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/sliding-windows-and-region-proposals" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sliding Windows and Region Proposals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/bounding-box-predictions-with-yolo" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bounding Box Predictions with YOLO</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/iou-non-max-suppression-and-anchor-boxes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IoU, Non-max Suppression, and Anchor Boxes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-car-detection-with-yolo" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Car Detection with YOLO</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/semantic-segmentation-with-u-net" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semantic Segmentation with U-Net</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-image-segmentation-with-u-net" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Image Segmentation with U-Net</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/face-recognition-and-one-shot-learning" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Face Recognition and One Shot Learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/siamese-networks-and-the-triplet-loss" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Siamese Networks and the Triplet Loss</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-face-recognition" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Face Recognition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/neural-style-transfer" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Style Transfer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-neural-style-transfer" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Art Generation with Neural Style Transfer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#packages" id="toc-packages" class="nav-link active" data-scroll-target="#packages">Packages</a></li>
  <li><a href="#dataset-from-a-directory" id="toc-dataset-from-a-directory" class="nav-link" data-scroll-target="#dataset-from-a-directory">Dataset From a Directory</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#data-augmentation" id="toc-data-augmentation" class="nav-link" data-scroll-target="#data-augmentation">Data Augmentation</a>
  <ul class="collapse">
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#what-the-pretrained-model-already-knows" id="toc-what-the-pretrained-model-already-knows" class="nav-link" data-scroll-target="#what-the-pretrained-model-already-knows">What the Pretrained Model Already Knows</a>
  <ul class="collapse">
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#new-head-on-frozen-features" id="toc-new-head-on-frozen-features" class="nav-link" data-scroll-target="#new-head-on-frozen-features">New Head on Frozen Features</a>
  <ul class="collapse">
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#fine-tuning-final-layers" id="toc-fine-tuning-final-layers" class="nav-link" data-scroll-target="#fine-tuning-final-layers">Fine-Tuning Final Layers</a>
  <ul class="collapse">
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<script src="../../../theme-toggle.js?v=3505170f"></script>
<script src="../../../auth.js?v=c90ca430"></script>
<script src="../../../site-metrics.js?v=9d1b4053"></script>
<script src="../../../giscus-note.js?v=b465dd22"></script>
<script src="../../../resume-reading.js?v=c40ebfea"></script>
<script src="../../../sidebar-active.js?v=62f05be2"></script>
<script src="../../../search-scope.js?v=13576411"></script>
<script src="../../../review-numbering.js?v=50100e67"></script>
<script src="../../../nav-columns.js?v=a9beef4d"></script>
<script src="../../../activation-colors.js?v=a9e5b12e"></script>
<script src="../../../visit-history.js?v=85edd45a"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="bi bi-flask lab-title-icon" aria-hidden="true"></span><span class="visually-hidden">Lab:</span> Transfer Learning with MobileNetV2</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">convolutional-neural-networks</div>
    <div class="quarto-category">computer-vision</div>
    <div class="quarto-category">transfer-learning</div>
    <div class="quarto-category">mobilenet</div>
    <div class="quarto-category">fine-tuning</div>
    <div class="quarto-category">data-augmentation</div>
    <div class="quarto-category">tensorflow</div>
    <div class="quarto-category">keras</div>
    <div class="quarto-category">lab</div>
  </div>
  </div>

<div>
  <div class="description">
    Turn an ImageNet MobileNetV2 into an alpaca detector by training one new neuron on frozen features, then fine tuning the last 34 layers of the network.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Aug 17, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (!meta) return;

  // Published, and Modified only where a page actually sets date-modified.
  // Two pages do, about-this-website and roadmap, and both carry it on
  // purpose because they describe a site that keeps changing.
  function readCell(sel) {
    var el = meta.querySelector(sel);
    if (!el) return "";
    var cell = el.closest("div");
    var body = cell && cell.querySelector(".quarto-title-meta-contents");
    return ((body || el).textContent || "").trim();
  }
  var published = readCell(".date");
  var modified = readCell(".date-modified");

  var html = '<span class="quarto-title-meta-item">136 min <span class="rt-info" tabindex="0" aria-describedby="reading-time-method"><span aria-hidden="true">&#9432;</span><span class="rt-tooltip" id="reading-time-method" role="tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></span><span class="quarto-title-meta-item">5,900 words</span><span class="quarto-title-meta-item">difficulty 3/5</span>';
  function esc(t) {
    return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  if (published) {
    html += '<span class="quarto-title-meta-item">published ' + esc(published) + '</span>';
  }
  if (modified && modified !== published) {
    html += '<span class="quarto-title-meta-item">updated ' + esc(modified) + '</span>';
  }

  var line = document.createElement("div");
  line.className = "quarto-title-meta-line site-meta";
  line.innerHTML = html;
  meta.insertBefore(line, meta.firstChild);
});
</script>

<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Six changes from the original notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>The assignment was written against TensorFlow 2.3 with Keras 2, and this page runs on TensorFlow 2.21 with Keras 3. Six things changed (updated 2026-08-31).</p>
<ul>
<li><strong>Global seeding was added</strong> with <code>tf.keras.utils.set_random_seed(1)</code>, so the run reproduces on every render.</li>
<li><strong>Several Keras APIs were migrated</strong>, including the preprocessing layer imports and the way the base model’s layers are looked up.</li>
<li><strong>The bundled MobileNetV2 weights and class JSON were replaced by Keras downloads</strong>, using <code>weights='imagenet'</code>, which caches under <code>~/.keras/models</code>.</li>
<li><strong>Fine-tuning runs five epochs rather than six.</strong> The notebook’s loop ran an extra epoch by accident; five is what its text describes.</li>
<li><strong>The accuracy metric was corrected.</strong> The head emits a logit, so the string <code>'accuracy'</code> would have thresholded at 0.5 on a logit, which is a probability of about 0.62. It is now <code>BinaryAccuracy(threshold=0.0)</code>.</li>
<li><strong>The validation results changed</strong> from the notebook’s 0.7385 before fine-tuning and 0.9692 after, to 0.9077 and 0.9846 here.</li>
</ul>
<p>The alpaca dataset, the two-stage transfer-learning recipe, the augmentation layers and the learning rates are the assignment’s own.</p>
</div>
</div>
<p><a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets#transfer-learning">Practical Advice for Using ConvNets</a> argued that downloading weights someone else trained beats starting from random initialization, and <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet">MobileNet and EfficientNet</a> took apart the architecture this lab borrows. Here the two meet in about forty lines of Keras.</p>
<p>MobileNetV2 is the network that page calls <strong>MobileNet v2</strong>, the 2018 generation that adds an expansion layer and a residual connection to the original design and repeats the resulting <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet#bottleneck-block">bottleneck block</a> 17 times. The 2 names the architecture, not a version of this lab, and it matters here because v1 and v2 are different networks with different weights.</p>
<p>The task is a binary classifier that answers one question about a photograph, whether or not it contains an alpaca. The dataset holds 327 images, of which 262 are used for training. That is nowhere near enough to fit a 2.3 million parameter network from scratch. MobileNetV2 has already been trained on the ILSVRC-2012 subset of ImageNet, about 1.28 million photographs across 1000 classes, so the expensive part of learning what images look like is already paid for. (Full ImageNet holds around 14 million images, but the weights Keras ships are the 1000-class ILSVRC ones.)</p>
<p>The work happens in two stages, and the difference between them is the point of the lab.</p>
<ul>
<li><strong>Feature extraction.</strong> Every borrowed layer is frozen and a single new output neuron is trained on top of them. 1281 trainable parameters out of 2.3 million.</li>
<li><strong>Fine-tuning.</strong> The last 34 of MobileNetV2’s 154 layers are unfrozen and training continues with a learning rate ten times smaller.</li>
</ul>
<p>Along the way you will build datasets straight from a directory of image files, augment them with random flips and rotations, and see why a pretrained network that has never heard of alpacas is still the right thing to start from.</p>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Three of these imports do the real work. <code>image_dataset_from_directory</code> reads image files off disk and hands back a batched dataset, <code>MobileNetV2</code> is the pretrained network, and <code>mobilenet_v2.preprocess_input</code> is the exact input scaling those pretrained weights expect.</p>
<p>Seeding covers the Python, NumPy, and TensorFlow generators in one call, which fixes the weight initialization, the train and validation shuffle, and the random augmentations, so the numbers on this page are stable across renders.</p>
<div id="03509b48" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>os.environ[<span class="st">"TF_CPP_MIN_LOG_LEVEL"</span>] <span class="op">=</span> <span class="st">"3"</span>      <span class="co"># quiet TensorFlow's startup logging</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> collections <span class="im">import</span> Counter</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tensorflow <span class="im">as</span> tf</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.utils <span class="im">import</span> image_dataset_from_directory</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> tensorflow.keras.layers <span class="im">import</span> (RandomFlip, RandomRotation, Dense, Dropout,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>                                     GlobalAveragePooling2D)</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>tf.keras.utils.set_random_seed(<span class="dv">1</span>)             <span class="co"># Python, NumPy and TensorFlow generators</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"TensorFlow"</span>, tf.__version__)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>TensorFlow 2.21.0</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Lab Files Download
</div>
</div>
<div class="callout-body-container callout-body">
<p>This lab needs the alpaca photographs and nothing else. The MobileNetV2 weights are fetched by Keras the first time the model is built and cached under <code>~/.keras/models</code>, so there is no weight file to hunt down.</p>
<p>The 327 photographs run to 117 MB at their original resolution, which is too large to host with the site, so they live on Google Drive as one folder per class.</p>
<ul>
<li><a href="https://drive.google.com/drive/folders/1v8-NpADjcu43Ct383nFfDb5H_33ft6y0?usp=sharing">alpaca</a>, 142 photographs</li>
<li><a href="https://drive.google.com/drive/folders/1jkKkf_aEzBdPTDdPr0OynjfslKhVo_bO?usp=sharing">not alpaca</a>, 185 photographs</li>
<li><a href="../../../media/deep-learning/transfer-learning-mobilenet/README.txt">README.txt</a> records where the images come from</li>
</ul>
<p>Download both folders and arrange them next to your notebook as <code>dataset/alpaca/</code> and <code>dataset/not alpaca/</code>, keeping the folder names exactly as they are. Those names are the class labels, and the space in <code>not alpaca</code> is part of one.</p>
</div>
</div>
</section>
<section id="dataset-from-a-directory" class="level2">
<h2 class="anchored" data-anchor-id="dataset-from-a-directory">Dataset From a Directory</h2>
<p>There is no CSV file and no HDF5 archive here. The labels are the folder names, one folder per class, and <code>image_dataset_from_directory</code> is the function that turns that layout into something trainable. It walks the directory, treats each subfolder as a class, decodes every image, resizes it to <code>image_size</code>, and groups the results into batches.</p>
<p>Four of its arguments deserve attention.</p>
<p><code>image_size=(160, 160)</code> is not a free choice. MobileNetV2 ships pretrained weights for a handful of input sizes, and 160 by 160 is one of them. Note that this resize does not crop, it squeezes, so the typical 1024 by 768 photograph in this dataset is compressed horizontally on its way into a square.</p>
<p><code>validation_split=0.2</code> with <code>subset='training'</code> and <code>subset='validation'</code> asks for the same split twice, once from each end. The function shuffles the file list, then hands back the first 80 percent or the last 20 percent depending on the subset.</p>
<p><code>seed=42</code> appears in both calls, and it has to be the same number in both. The split is computed from the shuffled file order, so two different seeds would produce two different orders, and the same photograph could easily land in both the training set and the validation set. The result would be a validation accuracy that flatters the model.</p>
<div id="951f74ab" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>BATCH_SIZE <span class="op">=</span> <span class="dv">32</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>IMG_SIZE <span class="op">=</span> (<span class="dv">160</span>, <span class="dv">160</span>)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>directory <span class="op">=</span> <span class="st">"../../../media/deep-learning/transfer-learning-mobilenet/dataset/"</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>train_dataset <span class="op">=</span> image_dataset_from_directory(directory,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>                                             shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                                             batch_size<span class="op">=</span>BATCH_SIZE,</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>                                             image_size<span class="op">=</span>IMG_SIZE,</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>                                             validation_split<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>                                             subset<span class="op">=</span><span class="st">'training'</span>,</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                                             seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>validation_dataset <span class="op">=</span> image_dataset_from_directory(directory,</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>                                                  shuffle<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>                                                  batch_size<span class="op">=</span>BATCH_SIZE,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                                                  image_size<span class="op">=</span>IMG_SIZE,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>                                                  validation_split<span class="op">=</span><span class="fl">0.2</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>                                                  subset<span class="op">=</span><span class="st">'validation'</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>                                                  seed<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>class_names <span class="op">=</span> train_dataset.class_names</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"class names:"</span>, class_names)</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"training batches:  "</span>, train_dataset.cardinality().numpy())</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"validation batches:"</span>, validation_dataset.cardinality().numpy())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Found 327 files belonging to 2 classes.
Using 262 files for training.
Found 327 files belonging to 2 classes.
Using 65 files for validation.
class names: ['alpaca', 'not alpaca']
training batches:   9
validation batches: 3</code></pre>
</div>
</div>
<p>The class names come back in alphabetical order, so <code>alpaca</code> is label 0 and <code>not alpaca</code> is label 1. Nine batches of 32 covers the 262 training images, with the last batch short.</p>
<p><code>class_names</code> is read straight after the dataset is created, and that ordering matters. Several of the transformations applied later return a plain dataset with no <code>class_names</code> attribute, so a copy has to be taken while it is still available.</p>
<p>Looking at a batch is worth doing before anything else. One <code>for</code> loop over <code>take(1)</code> pulls a single batch of 32 images and 32 labels, and the first nine of them go into a grid.</p>
<div id="39550e32" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="fl">5.6</span>, <span class="fl">5.6</span>))</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> images, labels <span class="kw">in</span> train_dataset.take(<span class="dv">1</span>):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">9</span>):</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>        plt.subplot(<span class="dv">3</span>, <span class="dv">3</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>        plt.imshow(images[i].numpy().astype(<span class="st">"uint8"</span>))     <span class="co"># pixels arrive as floats</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>        plt.title(class_names[labels[i]], fontsize<span class="op">=</span><span class="dv">11</span>, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>        plt.axis(<span class="st">"off"</span>)</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab-transfer-learning-with-mobilenet_files/figure-html/cell-4-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Dataset From a Directory.</figcaption>
</figure>
</div>
</div>
</div>
<p>The <code>.astype("uint8")</code> is not cosmetic. <code>image_dataset_from_directory</code> returns <code>float32</code> pixels in the range 0 to 255 rather than 0 to 1, and <code>imshow</code> interprets floats as if they were already scaled to 0 to 1, so without the cast every image would be a white rectangle. That 0 to 255 range comes back later, because the pretrained network expects to do its own scaling.</p>
<p>Notice what the negative class actually contains. It is not random photographs, it is other animals, several of them long necked and standing in grass. Giraffes, emus, and ostriches make a far harder negative class than street scenes would, because separating them from an alpaca takes more than noticing that the picture contains an animal outdoors.</p>
<div id="dd0f814e" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"image batch shape:"</span>, images.shape, images.dtype)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"label batch shape:"</span>, labels.shape, labels.dtype)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"pixel range:       </span><span class="sc">%.1f</span><span class="st"> to </span><span class="sc">%.1f</span><span class="st">"</span> <span class="op">%</span> (<span class="bu">float</span>(tf.reduce_min(images)),</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>                                           <span class="bu">float</span>(tf.reduce_max(images))))</span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"labels in batch:  "</span>, np.bincount(labels.numpy(), minlength<span class="op">=</span><span class="dv">2</span>),</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>      <span class="st">"(alpaca, not alpaca)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>image batch shape: (32, 160, 160, 3) &lt;dtype: 'float32'&gt;
label batch shape: (32,) &lt;dtype: 'int32'&gt;
pixel range:       0.0 to 255.0
labels in batch:   [19 13] (alpaca, not alpaca)</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Mislabeled Images
</div>
</div>
<div class="callout-body-container callout-body">
<p>The original dataset has a few mislabeled images in it, and they were left in place. A ceiling slightly below 100 percent accuracy is therefore expected, and chasing the last few percent on this dataset means fitting somebody else’s mistakes.</p>
</div>
</div>
<p>One more line prepares the training set for speed. Reading and decoding JPEG files is slow compared with the arithmetic of a forward pass, so without help the CPU would sit idle waiting for disk. <code>prefetch</code> overlaps the two, preparing the next batch while the current one is being trained on. Passing <code>AUTOTUNE</code> as the buffer size lets TensorFlow pick how many batches to keep ready, by timing each stage of the pipeline at runtime and adjusting.</p>
<div id="f5c3807c" class="cell" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>AUTOTUNE <span class="op">=</span> tf.data.AUTOTUNE</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>train_dataset <span class="op">=</span> train_dataset.prefetch(buffer_size<span class="op">=</span>AUTOTUNE)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Both calls to <code>image_dataset_from_directory</code> pass <code>seed=42</code>. What goes wrong if the second call uses a different seed?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The split is taken from a shuffled file list, so the seed determines which files land in the first 80 percent and which land in the last 20 percent. With two different seeds, the two calls shuffle differently, and a file that was in the training 80 percent of the first order can easily be in the validation 20 percent of the second. The two sets would overlap, and the validation accuracy would then be measuring performance on images the model has already trained on.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does the plotting code cast pixels with <code>.astype("uint8")</code> before calling <code>imshow</code>?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the dataset yields <code>float32</code> values between 0 and 255. Matplotlib treats a float image as already normalized to the range 0 to 1 and clips anything above, so every pixel brighter than 1.0 would be drawn as pure white. Casting to <code>uint8</code> tells <code>imshow</code> to use the 0 to 255 integer convention instead. Dividing by 255 would work equally well for display.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What does <code>prefetch(buffer_size=AUTOTUNE)</code> change about training, and what does it not change?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It changes when work happens, not what work happens. The input pipeline prepares batch <span class="math inline">\(n+1\)</span> while the model trains on batch <span class="math inline">\(n\)</span>, so decoding and resizing overlap with the forward and backward passes instead of blocking them. <code>AUTOTUNE</code> lets TensorFlow choose the buffer size by measuring the time spent in each stage. Gradients, weights, and accuracy are all unaffected, and the streaming design also means the dataset never has to fit in memory.</p>
</div>
</div>
</div>
</section>
</section>
<section id="data-augmentation" class="level2">
<h2 class="anchored" data-anchor-id="data-augmentation">Data Augmentation</h2>
<p>There are 262 training images. Every one of them is a fixed arrangement of pixels, and a network with millions of parameters will happily memorize all of them. <a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets#data-augmentation">Data augmentation</a> attacks that by manufacturing variety, showing the model a flipped or slightly turned version of a photograph instead of the original, so that no exact arrangement of pixels is ever seen twice.</p>
<p>Keras supplies augmentations as <strong>layers</strong>, and that is more than a stylistic detail. A layer becomes part of the model, so it is saved with the model and restored with it, and there is no separate preprocessing script to keep in sync. More importantly, augmentation layers are active only in training mode. During <code>fit</code> they randomize, and when the model later predicts they pass their input through untouched. Randomly rotating an image at prediction time would only add noise to the answer.</p>
<p>Two layers are enough here. <code>RandomFlip('horizontal')</code> mirrors the image left to right about half the time, which is safe because an alpaca facing left is still an alpaca. <code>RandomRotation(0.2)</code> turns it by a random fraction of a full circle, up to 0.2 of a turn in either direction, which is 72 degrees each way.</p>
<div id="ad1675a3" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> data_augmenter():</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Create a Sequential model composed of 2 augmentation layers.</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="co">        tf.keras.Sequential</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    data_augmentation <span class="op">=</span> tf.keras.Sequential()</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    data_augmentation.add(RandomFlip(<span class="st">'horizontal'</span>))</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>    data_augmentation.add(RandomRotation(<span class="fl">0.2</span>))</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> data_augmentation</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>data_augmentation <span class="op">=</span> data_augmenter()</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> data_augmentation.layers:</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="bu">type</span>(layer)<span class="sc">.</span><span class="va">__name__</span><span class="sc">:&lt;16}</span><span class="ss"> </span><span class="sc">{</span>layer<span class="sc">.</span>name<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>RandomFlip       random_flip
RandomRotation   random_rotation</code></pre>
</div>
</div>
<p>Running one image through it nine times gives nine different images. <code>tf.expand_dims(first_image, 0)</code> is there because the layers expect a batch, so a single image has to be given a batch dimension of one, and the display then indexes back into that batch with <code>[0]</code>.</p>
<p>Calling the augmenter directly like this puts it in training mode, which is why the nine outputs differ. Inside a model being used for prediction the same layers would return the image unchanged.</p>
<div id="c68853f2" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> image, _ <span class="kw">in</span> train_dataset.take(<span class="dv">1</span>):</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="fl">5.6</span>, <span class="fl">5.6</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    first_image <span class="op">=</span> image[<span class="dv">0</span>]</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">9</span>):</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>        plt.subplot(<span class="dv">3</span>, <span class="dv">3</span>, i <span class="op">+</span> <span class="dv">1</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>        augmented_image <span class="op">=</span> data_augmentation(tf.expand_dims(first_image, <span class="dv">0</span>))</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>        plt.imshow(augmented_image[<span class="dv">0</span>] <span class="op">/</span> <span class="dv">255</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>        plt.axis(<span class="st">'off'</span>)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab-transfer-learning-with-mobilenet_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Data Augmentation.</figcaption>
</figure>
</div>
</div>
</div>
<p>From one animal to nine variations of that animal, in two lines of configuration. Look at the corners of the rotated ones. Turning a square image leaves triangular gaps, and Keras fills them by reflecting the pixels just inside the edge rather than painting them a flat color, so a dark background reflects into a dark wedge and grass reflects into more grass. The statistics of the image stay roughly intact, which a block of pure black would not manage.</p>
<p>There is a limit to what this buys. Every variation still comes from the same 262 photographs, so augmentation stretches the data rather than adding to it. It cannot invent an alpaca in a setting none of the originals contain.</p>
<p>The last piece of preparation is the scaling the pretrained weights expect. MobileNetV2 was trained on inputs mapped to the range <span class="math inline">\(-1\)</span> to <span class="math inline">\(1\)</span>, not 0 to 1, and <code>preprocess_input</code> performs exactly that mapping, which for this network is <span class="math inline">\(x / 127.5 - 1\)</span>. Reusing the function rather than writing the arithmetic is the safer habit, since a different pretrained network may well have used a different convention, and every filter in the borrowed layers was tuned against whatever scaling its training used.</p>
<div id="3176c493" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>preprocess_input <span class="op">=</span> tf.keras.applications.mobilenet_v2.preprocess_input</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>sample <span class="op">=</span> tf.constant([[<span class="fl">0.0</span>, <span class="fl">127.5</span>, <span class="fl">255.0</span>]])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"0 to 255 in: "</span>, sample.numpy())</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"scaled out:  "</span>, preprocess_input(tf.identity(sample)).numpy())</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>0 to 255 in:  [[  0.  127.5 255. ]]
scaled out:   [[-1.  0.  1.]]</code></pre>
</div>
</div>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. Why are the augmentations built as layers inside the model rather than applied to the dataset before training?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because a layer travels with the model. It is saved and restored along with the weights, so there is no separate preprocessing step to reproduce later, and the augmentation cannot drift out of step with the network it was designed for. Keras also gives these layers the right behavior automatically, since they randomize during <code>fit</code> and pass their input straight through during <code>predict</code> and <code>evaluate</code>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. <code>RandomRotation(0.2)</code> is described as rotating by up to 72 degrees. Where does that number come from, and why is a large rotation reasonable here but a vertical flip is not offered?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The factor is measured in full turns, so 0.2 means 0.2 of 360 degrees, which is 72 degrees, applied in either direction. A photograph of an alpaca tilted 72 degrees still shows an alpaca, so the label survives the transformation. A vertical flip would produce an upside down animal, which no photograph in the dataset resembles, so it would teach the network to recognize inputs it will never be asked about. The test for any augmentation is whether the label still holds after it.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why call <code>preprocess_input</code> instead of dividing the pixels by 255?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the borrowed weights were fitted against a specific input scaling. MobileNetV2 was trained on inputs in the range <span class="math inline">\(-1\)</span> to <span class="math inline">\(1\)</span>, so feeding it values in 0 to 1 would shift and shrink everything the first convolution sees, and the features those filters produce would no longer be the features they were trained to produce. Calling the function that ships with the model means the scaling is correct without having to remember which network used which convention.</p>
</div>
</div>
</div>
</section>
</section>
<section id="what-the-pretrained-model-already-knows" class="level2">
<h2 class="anchored" data-anchor-id="what-the-pretrained-model-already-knows">What the Pretrained Model Already Knows</h2>
<p>Before deleting anything, it is worth loading MobileNetV2 exactly as it was trained, classifier and all, and seeing what it says about these photographs. <code>include_top=True</code> keeps the 1000-way ImageNet output layer, and <code>weights='imagenet'</code> downloads the trained weights and caches them. With the top attached, Keras applies a softmax by default, so those 1000 numbers are class probabilities rather than raw scores.</p>
<div id="38dfab51" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>IMG_SHAPE <span class="op">=</span> IMG_SIZE <span class="op">+</span> (<span class="dv">3</span>,)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>base_model <span class="op">=</span> tf.keras.applications.MobileNetV2(input_shape<span class="op">=</span>IMG_SHAPE,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                               include_top<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                                               weights<span class="op">=</span><span class="st">'imagenet'</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"layers:     </span><span class="sc">{</span><span class="bu">len</span>(base_model.layers)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"parameters: </span><span class="sc">{</span>base_model<span class="sc">.</span>count_params()<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"output:     </span><span class="sc">{</span>base_model<span class="sc">.</span>output<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>layers:     156
parameters: 3,538,984
output:     (None, 1000)</code></pre>
</div>
</div>
<p>A <code>summary()</code> of this model runs to several hundred lines, which is not a useful thing to read. Counting layers by type says more in nine lines, and every count in it can be traced back to the <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet#mobilenet-architecture">architecture</a>.</p>
<div id="e102d399" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer_type, count <span class="kw">in</span> Counter(<span class="bu">type</span>(l).<span class="va">__name__</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="cf">for</span> l <span class="kw">in</span> base_model.layers).most_common():</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>count<span class="sc">:&gt;4}</span><span class="ss">  </span><span class="sc">{</span>layer_type<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"last two layers:"</span>, [l.name <span class="cf">for</span> l <span class="kw">in</span> base_model.layers[<span class="op">-</span><span class="dv">2</span>:]])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  52  BatchNormalization
  35  Conv2D
  35  ReLU
  17  DepthwiseConv2D
  10  Add
   4  ZeroPadding2D
   1  InputLayer
   1  GlobalAveragePooling2D
   1  Dense

last two layers: ['global_average_pooling2d', 'predictions']</code></pre>
</div>
</div>
<p>Those numbers are the architecture, stated as a census.</p>
<p>The 17 <code>DepthwiseConv2D</code> layers are 17 bottleneck blocks, one depthwise convolution each, which is the <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet#depthwise-separable-convolution">depthwise separable convolution</a> that makes the network cheap. The 35 ordinary convolutions account for the rest of that structure, namely one stem convolution, a <span class="math inline">\(1 \times 1\)</span> projection in each of the 17 blocks, a <span class="math inline">\(1 \times 1\)</span> expansion in 16 of them, and one final <span class="math inline">\(1 \times 1\)</span> convolution that widens the volume to 1280 channels. The 10 <code>Add</code> layers are the residual connections, present only in the blocks where the shape allows the input to be added back, exactly as in the <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks#convolutional-block">convolutional block</a> argument from the previous lab. Every convolution is followed by BatchNorm, which is why there are 52 of those.</p>
<p>The two layers at the end are the <strong>top</strong>, a global average pooling followed by a dense layer named <code>predictions</code>. Together they turn features into the 1000 ImageNet class scores, and they hold 1,281,000 of the model’s parameters, over a third of the total.</p>
<p>Now push a real batch through it. The images need the <span class="math inline">\(-1\)</span> to <span class="math inline">\(1\)</span> scaling first, and <code>decode_predictions</code> turns the 1000 raw scores for each image into the top few class names.</p>
<div id="4c7d61f9" class="cell" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>base_model.trainable <span class="op">=</span> <span class="va">False</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>image_batch, label_batch <span class="op">=</span> <span class="bu">next</span>(<span class="bu">iter</span>(train_dataset))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>pred <span class="op">=</span> base_model(preprocess_input(tf.identity(image_batch)))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"prediction shape:"</span>, pred.shape, <span class="st">"(batch size, ImageNet classes)"</span>)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>decoded <span class="op">=</span> tf.keras.applications.mobilenet_v2.decode_predictions(pred.numpy(), top<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>):</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>    truth <span class="op">=</span> class_names[label_batch[i]]</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>    guesses <span class="op">=</span> <span class="st">"   "</span>.join(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> </span><span class="sc">{</span>score<span class="sc">:.0%}</span><span class="ss">"</span> <span class="cf">for</span> _, name, score <span class="kw">in</span> decoded[i])</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>truth<span class="sc">:&lt;12}</span><span class="ss"> </span><span class="sc">{</span>guesses<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>prediction shape: (32, 1000) (batch size, ImageNet classes)

alpaca       llama 62%   gazelle 13%
alpaca       llama 83%   gazelle 5%
alpaca       llama 28%   bighorn 6%
not alpaca   gazelle 69%   impala 14%
not alpaca   ostrich 95%   Arabian_camel 0%
not alpaca   lesser_panda 91%   polecat 1%
not alpaca   abaya 11%   fur_coat 8%
alpaca       bighorn 42%   llama 29%</code></pre>
</div>
</div>
<p>Some of those guesses are close and some are absurd, and none of them say alpaca. That is not a failure of the network. ImageNet’s 1000 classes simply do not include one, so the closest thing the classifier can reach for is llama, or a wild sheep, or whatever else the features happen to point at. The output layer can only ever name a class it was trained on.</p>
<p>The features underneath tell a different story. Guessing llama for an alpaca means the layers before the classifier have already measured wool, ears, a long neck, and a muzzle. That is the part worth keeping. Deleting the top and training a replacement is what the rest of this lab does.</p>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. The model outputs 1000 numbers per image. Why does that make the top layer useless here, while the layers below it stay valuable?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The 1000 outputs are the 1000 ImageNet classes, and alpaca is not one of them, so no output of that layer can express the answer this task needs. The layers below the classifier do not name classes at all, they produce a 1280 number description of the image, built from edges, textures, and shapes learned across those 1.28 million photographs. Nothing about that description is specific to the 1000 labels, which is why it transfers. Only the last layer needs replacing.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The network calls one alpaca a llama with high confidence. Is that evidence against using it as a starting point?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is evidence in favor. A llama is the nearest available label to an alpaca, so producing it means the features underneath have correctly picked up the wool, ears, and neck of the animal. A network whose features were useless would have guessed something with no visual relationship to the photograph. The classifier is constrained to the vocabulary it was taught, and it is choosing the best word in that vocabulary.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Counting layers by type shows 17 depthwise convolutions but only 10 <code>Add</code> layers. Why are there fewer additions than blocks?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because a residual connection needs the input and the output of the block to have the same shape. A block that downsamples, or that changes the channel count, cannot simply add its input back, so no <code>Add</code> layer appears there. MobileNetV2 leaves those blocks without a shortcut rather than paying for a projection, so only the 10 blocks whose stride is 1 and whose channel count is unchanged carry one.</p>
</div>
</div>
</div>
</section>
</section>
<section id="new-head-on-frozen-features" class="level2">
<h2 class="anchored" data-anchor-id="new-head-on-frozen-features">New Head on Frozen Features</h2>
<p>Three steps turn the pretrained network into an alpaca detector.</p>
<ol type="1">
<li><strong>Delete the top.</strong> Pass <code>include_top=False</code>, which drops the pooling and the 1000-way classifier and leaves the feature volume exposed.</li>
<li><strong>Add a new head.</strong> Pool the feature volume to a vector, apply dropout, and finish with a single neuron, since a binary decision needs exactly one number.</li>
<li><strong>Freeze the rest.</strong> Set <code>base_model.trainable = False</code> so gradient descent updates the new head and nothing else.</li>
</ol>
<p>The Functional API is what assembles this, because the augmentation and the scaling sit in the middle of the path from input to output rather than being separate preprocessing steps.</p>
<p>Four lines in the function below need justifying.</p>
<p><code>x = data_augmentation(inputs)</code> puts augmentation inside the model, so it runs during <code>fit</code> and is skipped during <code>predict</code>.</p>
<p><code>x = base_model(x, training=False)</code> is the subtlest line on this page. Setting <code>base_model.trainable = False</code> stops the weights from being updated, but BatchNorm layers hold something that is not a weight, namely a running mean and variance of the activations they have seen. Those statistics are updated in training mode, not by gradient descent, so a frozen network would still quietly overwrite them with statistics from 262 alpaca photographs. Passing <code>training=False</code> puts the borrowed layers in inference mode, so they keep the ImageNet statistics they were shipped with. Without it, the features drift while their weights sit still.</p>
<p><code>GlobalAveragePooling2D()</code> averages each of the 1280 channels over the 5 by 5 grid of positions, giving 1280 numbers. This is the same move that kept the classifier small in <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks#building-resnet-50">ResNet-50</a>. Flattening the volume instead would produce <span class="math inline">\(5 \times 5 \times 1280 = 32{,}000\)</span> inputs and a classifier 25 times larger, for a task with 262 training examples.</p>
<p><code>Dense(1)</code> has no activation function, so it outputs a raw score rather than a probability. The sigmoid is folded into the loss instead, through <code>BinaryCrossentropy(from_logits=True)</code>, which is more numerically stable than applying a sigmoid and then taking its logarithm.</p>
<div id="3f6506bf" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> alpaca_model(image_shape<span class="op">=</span>IMG_SIZE, data_augmentation<span class="op">=</span>data_augmenter()):</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Define a tf.keras model for binary classification out of the MobileNetV2 model.</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Arguments:</span></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a><span class="co">        image_shape -- image width and height</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co">        data_augmentation -- data augmentation function</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a><span class="co">        tf.keras.Model</span></span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>    input_shape <span class="op">=</span> image_shape <span class="op">+</span> (<span class="dv">3</span>,)</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>    base_model <span class="op">=</span> tf.keras.applications.MobileNetV2(input_shape<span class="op">=</span>input_shape,</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                                                   include_top<span class="op">=</span><span class="va">False</span>,  <span class="co"># drop the classifier</span></span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                                                   weights<span class="op">=</span><span class="st">'imagenet'</span>)</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Freeze the base model so that only the new head is trained</span></span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>    base_model.trainable <span class="op">=</span> <span class="va">False</span></span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a>    inputs <span class="op">=</span> tf.keras.Input(shape<span class="op">=</span>input_shape)</span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Augment first, then apply the scaling the pretrained weights expect</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> data_augmentation(inputs)</span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> preprocess_input(x)</span>
<span id="cb20-26"><a href="#cb20-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-27"><a href="#cb20-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># training=False keeps the borrowed BatchNorm layers on their ImageNet statistics</span></span>
<span id="cb20-28"><a href="#cb20-28" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> base_model(x, training<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb20-29"><a href="#cb20-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-30"><a href="#cb20-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># New binary classification head</span></span>
<span id="cb20-31"><a href="#cb20-31" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> GlobalAveragePooling2D()(x)</span>
<span id="cb20-32"><a href="#cb20-32" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> Dropout(<span class="fl">0.2</span>)(x)</span>
<span id="cb20-33"><a href="#cb20-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-34"><a href="#cb20-34" aria-hidden="true" tabindex="-1"></a>    <span class="co"># One neuron, no activation: the sigmoid lives in the loss function</span></span>
<span id="cb20-35"><a href="#cb20-35" aria-hidden="true" tabindex="-1"></a>    outputs <span class="op">=</span> Dense(<span class="dv">1</span>)(x)</span>
<span id="cb20-36"><a href="#cb20-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-37"><a href="#cb20-37" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> tf.keras.Model(inputs, outputs)</span>
<span id="cb20-38"><a href="#cb20-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-39"><a href="#cb20-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model</span>
<span id="cb20-40"><a href="#cb20-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-41"><a href="#cb20-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-42"><a href="#cb20-42" aria-hidden="true" tabindex="-1"></a>model2 <span class="op">=</span> alpaca_model(IMG_SIZE, data_augmentation)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The whole model is six layers, because the borrowed network counts as one of them. Printing them with their output shapes and their trainable flags shows the structure and the freezing in one table.</p>
<div id="66fde5c9" class="cell" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'#'</span><span class="sc">:&lt;3}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'layer'</span><span class="sc">:&lt;24}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'type'</span><span class="sc">:&lt;24}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'output shape'</span><span class="sc">:&gt;20}</span><span class="ss">  trainable"</span>)</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i, layer <span class="kw">in</span> <span class="bu">enumerate</span>(model2.layers):</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>i<span class="sc">:&lt;3}</span><span class="ss"> </span><span class="sc">{</span>layer<span class="sc">.</span>name<span class="sc">:&lt;24}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">type</span>(layer)<span class="sc">.</span><span class="va">__name__</span><span class="sc">:&lt;24}</span><span class="ss"> "</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span><span class="bu">str</span>(layer.output.shape)<span class="sc">:&gt;20}</span><span class="ss">  </span><span class="sc">{</span>layer<span class="sc">.</span>trainable<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>trainable <span class="op">=</span> <span class="bu">sum</span>(<span class="bu">int</span>(np.prod(w.shape)) <span class="cf">for</span> w <span class="kw">in</span> model2.trainable_weights)</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>()</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"total parameters:     </span><span class="sc">{</span>model2<span class="sc">.</span>count_params()<span class="sc">:,}</span><span class="ss">"</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"trainable parameters: </span><span class="sc">{</span>trainable<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>#   layer                    type                             output shape  trainable
0   input_layer_3            InputLayer                (None, 160, 160, 3)  True
1   sequential               Sequential                (None, 160, 160, 3)  True
2   mobilenetv2_1.00_160     Functional                 (None, 5, 5, 1280)  False
3   global_average_pooling2d_1 GlobalAveragePooling2D           (None, 1280)  True
4   dropout                  Dropout                          (None, 1280)  True
5   dense                    Dense                               (None, 1)  True

total parameters:     2,259,265
trainable parameters: 1,281</code></pre>
</div>
</div>
<p>The feature volume is 5 by 5 by 1280. A 160 pixel input reduced by five stride 2 stages gives <span class="math inline">\(160 / 32 = 5\)</span>, and the final <span class="math inline">\(1 \times 1\)</span> convolution of the borrowed network sets the 1280 channels.</p>
<p>The trainable count is worth staring at. It is 1281, which is <span class="math inline">\(1280\)</span> weights plus one bias, out of 2.26 million parameters in the model. Everything else is frozen. Training this is closer to fitting a logistic regression on 1280 features than to training a ConvNet, which is exactly why 262 images is enough.</p>
<p>Compiling needs the matching loss for a single logit output, and Adam at its usual learning rate of 0.001 is fine here, because the layer being trained starts from random values and has nothing worth preserving.</p>
<div id="047b9f6a" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>base_learning_rate <span class="op">=</span> <span class="fl">0.001</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The head is a single Dense(1) unit with no activation, so it emits a LOGIT.</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># A logit is positive when the model favors the positive class, so the decision</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># boundary sits at 0. The string 'accuracy' would resolve to BinaryAccuracy with</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co"># its default threshold of 0.5, which on a logit means a probability of about</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 0.62, not 0.5. Naming the metric explicitly puts the cut in the right place.</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>model2.<span class="bu">compile</span>(optimizer<span class="op">=</span>tf.keras.optimizers.Adam(learning_rate<span class="op">=</span>base_learning_rate),</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>               loss<span class="op">=</span>tf.keras.losses.BinaryCrossentropy(from_logits<span class="op">=</span><span class="va">True</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>               metrics<span class="op">=</span>[tf.keras.metrics.BinaryAccuracy(threshold<span class="op">=</span><span class="fl">0.0</span>, name<span class="op">=</span><span class="st">'accuracy'</span>)])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Five epochs over nine batches is 45 gradient steps in total. Passing <code>validation_data</code> makes Keras evaluate the held out 65 images after every epoch, which is what fills in the second half of the table.</p>
<div id="1455eaef" class="cell" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>initial_epochs <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>history <span class="op">=</span> model2.fit(train_dataset, validation_data<span class="op">=</span>validation_dataset,</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>                     epochs<span class="op">=</span>initial_epochs, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>h <span class="op">=</span> history.history</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'epoch'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'loss'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'accuracy'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'val_loss'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'val_accuracy'</span><span class="sc">:&gt;13}</span><span class="ss">"</span>)</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> e <span class="kw">in</span> <span class="bu">range</span>(initial_epochs):</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>e<span class="op">+</span><span class="dv">1</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span>h[<span class="st">'loss'</span>][e]<span class="sc">:&gt;9.4f}</span><span class="ss"> </span><span class="sc">{</span>h[<span class="st">'accuracy'</span>][e]<span class="sc">:&gt;10.4f}</span><span class="ss"> "</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>h[<span class="st">'val_loss'</span>][e]<span class="sc">:&gt;10.4f}</span><span class="ss"> </span><span class="sc">{</span>h[<span class="st">'val_accuracy'</span>][e]<span class="sc">:&gt;13.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> epoch      loss   accuracy   val_loss  val_accuracy
     1    0.6875     0.6183     0.5803        0.6462
     2    0.5864     0.6794     0.4516        0.8000
     3    0.5139     0.8053     0.3808        0.8923
     4    0.4192     0.8244     0.3357        0.9077
     5    0.3829     0.8435     0.3000        0.9077</code></pre>
</div>
</div>
<p>Both losses fall steadily and the validation accuracy climbs from roughly two thirds (0.6462) to about ninety percent (0.9077). For 45 gradient steps that touch 1281 parameters, that is a great deal of progress, and it comes almost entirely from features the model was handed rather than features it learned.</p>
<p>Plotting the four columns of that table is how the run is usually judged. The same plotting function is used again after fine-tuning, so it takes an optional epoch to mark.</p>
<div id="39d7619e" class="cell" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_curves(history_dict, fine_tune_epoch<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Loss and accuracy side by side, with an optional fine-tuning marker."""</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> pd.DataFrame(history_dict)</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a>    df.index <span class="op">=</span> <span class="bu">range</span>(<span class="dv">1</span>, <span class="bu">len</span>(df) <span class="op">+</span> <span class="dv">1</span>)          <span class="co"># epochs count from 1</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a>    fig, axes <span class="op">=</span> plt.subplots(<span class="dv">1</span>, <span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">13</span>, <span class="dv">5</span>))</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(df.index, df[<span class="st">'loss'</span>], color<span class="op">=</span><span class="st">'#4682B4'</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].plot(df.index, df[<span class="st">'val_loss'</span>], color<span class="op">=</span><span class="st">'#CC5500'</span>, label<span class="op">=</span><span class="st">'validation'</span>)</span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].set_title(<span class="st">'Model loss'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">0</span>].set_ylabel(<span class="st">'Cross entropy'</span>)</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].plot(df.index, df[<span class="st">'accuracy'</span>], color<span class="op">=</span><span class="st">'#4682B4'</span>, label<span class="op">=</span><span class="st">'train'</span>)</span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].plot(df.index, df[<span class="st">'val_accuracy'</span>], color<span class="op">=</span><span class="st">'#CC5500'</span>, label<span class="op">=</span><span class="st">'validation'</span>)</span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].set_title(<span class="st">'Model accuracy'</span>, fontsize<span class="op">=</span><span class="dv">12</span>, color<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a>    axes[<span class="dv">1</span>].set_ylabel(<span class="st">'Accuracy'</span>)</span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> ax <span class="kw">in</span> axes:</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> fine_tune_epoch <span class="kw">is</span> <span class="kw">not</span> <span class="va">None</span>:</span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>            ax.axvline(fine_tune_epoch, color<span class="op">=</span><span class="st">'#6A0DAD'</span>, linestyle<span class="op">=</span><span class="st">'--'</span>,</span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>                       linewidth<span class="op">=</span><span class="fl">1.2</span>, label<span class="op">=</span><span class="st">'start fine tuning'</span>)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>        ax.set_xlabel(<span class="st">'Epoch'</span>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a>        ax.set_xticks(df.index)</span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>        ax.set_ylim(<span class="dv">0</span>, <span class="dv">1</span>)                     <span class="co"># fixed axis, so later runs compare directly</span></span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>        ax.grid(linestyle<span class="op">=</span><span class="st">'--'</span>, alpha<span class="op">=</span><span class="fl">0.4</span>)</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>        ax.legend()</span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-28"><a href="#cb26-28" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb26-29"><a href="#cb26-29" aria-hidden="true" tabindex="-1"></a>    plt.show()</span>
<span id="cb26-30"><a href="#cb26-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-31"><a href="#cb26-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-32"><a href="#cb26-32" aria-hidden="true" tabindex="-1"></a>plot_curves(h)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab-transfer-learning-with-mobilenet_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Model accuracy.</figcaption>
</figure>
</div>
</div>
</div>
<p>Both panels use a fixed 0 to 1 axis. Letting matplotlib choose the range instead would stretch a five point accuracy difference across the whole height of the plot and make a plateau look like a climb, and it would also stop this figure from being comparable with the one after fine-tuning.</p>
<p>Wrong about one image in seven is better than guessing and short of finished. The next section closes most of that gap with the same data and five more epochs.</p>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. Where does the number 1281 come from?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is the <code>Dense(1)</code> layer, and nothing else. Global average pooling turns the 5 by 5 by 1280 feature volume into 1280 numbers, so the single output neuron has 1280 weights and one bias, giving 1281 parameters. The 2.26 million parameters of the borrowed network are frozen, and pooling and dropout have no parameters at all.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. <code>base_model.trainable = False</code> already freezes the borrowed layers. Why is <code>training=False</code> needed as well when the base model is called?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the two flags control different things. <code>trainable = False</code> stops gradient descent from updating weights. It does not stop a BatchNorm layer from updating its running mean and variance, which happens in training mode as a side effect of seeing data rather than through a gradient. Left in training mode, the frozen network would replace ImageNet statistics with statistics from 262 alpaca photographs, so the features would shift underneath a head that is being trained to interpret them. <code>training=False</code> puts those layers in inference mode and keeps the statistics fixed.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does the final layer have no sigmoid, and what makes <code>from_logits=True</code> the matching choice?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The layer outputs a raw score, and the loss applies the sigmoid itself. Doing it in one place is more numerically stable, because binary cross entropy needs <span class="math inline">\(\log \sigma(z)\)</span>, and computing the sigmoid first can round a confident prediction to exactly 0 or 1, at which point the logarithm is infinite. <code>from_logits=True</code> tells the loss that its input is <span class="math inline">\(z\)</span> rather than a probability, so it can use a formulation that never takes the logarithm of a rounded value. At prediction time the sigmoid has to be applied by hand, or the sign of the score read directly, since a positive score means a probability above one half.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Global average pooling reduces 5 by 5 by 1280 to 1280 numbers. What is the alternative, and why is it a poor fit for this dataset?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The alternative is <code>Flatten</code>, which would keep all <span class="math inline">\(5 \times 5 \times 1280 = 32{,}000\)</span> numbers and give the output neuron 32,001 parameters instead of 1281. With 262 training images, a head that large has far more freedom than the data can constrain, and it would also make the model sensitive to where in the frame a feature appeared. Averaging over the 25 positions asks whether a feature is present anywhere, which is the right question for a whole image label.</p>
</div>
</div>
</div>
</section>
</section>
<section id="fine-tuning-final-layers" class="level2">
<h2 class="anchored" data-anchor-id="fine-tuning-final-layers">Fine-Tuning Final Layers</h2>
<p>Feature extraction treated the borrowed network as a fixed function. Fine-tuning goes further and lets part of it adapt.</p>
<p>Which part follows from what the layers hold. Early layers respond to edges, corners, and simple textures, and those are common to nearly all photographs, so there is nothing about alpacas to gain by changing them. Later layers assemble high level structure, wispy hair against a background, a particular shape of ear, and those are the ones worth adapting to a new dataset. So the end of the network is unfrozen and the beginning stays as it is.</p>
<p>Two settings implement it. <code>fine_tune_at = 120</code> marks where unfreezing begins, which leaves 34 of MobileNetV2’s 154 layers trainable, about the last fifth of the network rather than a third. The learning rate drops to a tenth of the original, because these weights are already good and the aim is to nudge them rather than restart them. A full sized step would undo in a few batches what ImageNet training established.</p>
<p>Getting hold of the borrowed network inside <code>model2</code> deserves a note. Course material reaches for it by position, as <code>model2.layers[4]</code>, which depends on how many layer objects the preprocessing happens to create in a particular TensorFlow version. In the version used here, the scaling is folded into the graph without creating a layer, so the base model sits at index 2 rather than 4. Looking it up by name is stable across versions, and the name records the architecture’s own settings, a width multiplier of 1.00 and a 160 pixel input.</p>
<div id="c32c34d6" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>base_model <span class="op">=</span> model2.get_layer(<span class="st">'mobilenetv2_1.00_160'</span>)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>base_model.trainable <span class="op">=</span> <span class="va">True</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"layers in the base model:"</span>, <span class="bu">len</span>(base_model.layers))</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fine-tune from this layer onwards</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>fine_tune_at <span class="op">=</span> <span class="dv">120</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Freeze all the layers before the fine_tune_at layer</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> layer <span class="kw">in</span> base_model.layers[:fine_tune_at]:</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    layer.trainable <span class="op">=</span> <span class="va">False</span></span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>loss_function <span class="op">=</span> tf.keras.losses.BinaryCrossentropy(from_logits<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>optimizer <span class="op">=</span> tf.keras.optimizers.Adam(learning_rate<span class="op">=</span><span class="fl">0.1</span> <span class="op">*</span> base_learning_rate)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Same logit threshold correction as the first compile.</span></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a>metrics <span class="op">=</span> [tf.keras.metrics.BinaryAccuracy(threshold<span class="op">=</span><span class="fl">0.0</span>, name<span class="op">=</span><span class="st">'accuracy'</span>)]</span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>model2.<span class="bu">compile</span>(loss<span class="op">=</span>loss_function, optimizer<span class="op">=</span>optimizer, metrics<span class="op">=</span>metrics)</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a>trainable_now <span class="op">=</span> <span class="bu">sum</span>(<span class="bu">int</span>(np.prod(w.shape)) <span class="cf">for</span> w <span class="kw">in</span> model2.trainable_weights)</span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"trainable layers: </span><span class="sc">{</span><span class="bu">sum</span>(l.trainable <span class="cf">for</span> l <span class="kw">in</span> base_model.layers)<span class="sc">}</span><span class="ss"> of "</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="bu">len</span>(base_model.layers)<span class="sc">}</span><span class="ss">"</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"trainable parameters: </span><span class="sc">{</span>trainable_now<span class="sc">:,}</span><span class="ss"> of </span><span class="sc">{</span>model2<span class="sc">.</span>count_params()<span class="sc">:,}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>layers in the base model: 154
trainable layers: 34 of 154
trainable parameters: 1,626,177 of 2,259,265</code></pre>
</div>
</div>
<p>The trainable count goes from 1281 to over 1.6 million, which is most of the network’s parameters even though only the last 34 layers of 154 were released. Parameters cluster at the deep end, where the channel counts are largest, so unfreezing the last fifth of the layers unfreezes the majority of the weights.</p>
<p>Recompiling is mandatory, not tidiness. Keras works out which variables to optimize when the model is compiled, so changing <code>trainable</code> flags afterwards has no effect until <code>compile</code> is called again.</p>
<p>The BatchNorm question from the previous section has already been settled here, and quietly. The graph still calls <code>base_model(x, training=False)</code>, so even the unfrozen layers keep their ImageNet running statistics and use them for normalization. Their scale and shift parameters are trained, their statistics are not, which is the standard recipe for fine-tuning a small dataset.</p>
<p>Training continues from where it stopped. The weights carry over because it is the same model object, and <code>initial_epoch</code> only sets the epoch counter so the numbering continues at 6 instead of restarting at 1.</p>
<div id="eed69f2d" class="cell" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>fine_tune_epochs <span class="op">=</span> <span class="dv">5</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>total_epochs <span class="op">=</span> initial_epochs <span class="op">+</span> fine_tune_epochs</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>history_fine <span class="op">=</span> model2.fit(train_dataset,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>                          epochs<span class="op">=</span>total_epochs,</span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>                          initial_epoch<span class="op">=</span>initial_epochs,</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>                          validation_data<span class="op">=</span>validation_dataset,</span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>                          verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>hf <span class="op">=</span> history_fine.history</span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'epoch'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'loss'</span><span class="sc">:&gt;9}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'accuracy'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'val_loss'</span><span class="sc">:&gt;10}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'val_accuracy'</span><span class="sc">:&gt;13}</span><span class="ss">"</span>)</span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> e <span class="kw">in</span> <span class="bu">range</span>(fine_tune_epochs):</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>initial_epochs<span class="op">+</span>e<span class="op">+</span><span class="dv">1</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span>hf[<span class="st">'loss'</span>][e]<span class="sc">:&gt;9.4f}</span><span class="ss"> </span><span class="sc">{</span>hf[<span class="st">'accuracy'</span>][e]<span class="sc">:&gt;10.4f}</span><span class="ss"> "</span></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>hf[<span class="st">'val_loss'</span>][e]<span class="sc">:&gt;10.4f}</span><span class="ss"> </span><span class="sc">{</span>hf[<span class="st">'val_accuracy'</span>][e]<span class="sc">:&gt;13.4f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> epoch      loss   accuracy   val_loss  val_accuracy
     6    0.4043     0.8435     0.1920        0.9385
     7    0.2915     0.8969     0.1269        0.9846
     8    0.2212     0.9237     0.1011        0.9846
     9    0.1819     0.9389     0.0839        0.9846
    10    0.1209     0.9733     0.0727        0.9846</code></pre>
</div>
</div>
<p>Joining the two runs end to end shows what changed. Concatenating the two history dictionaries gives ten epochs on one axis, and the marker goes at the epoch where fine-tuning began.</p>
<div id="40dde84e" class="cell" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>plot_curves({key: h[key] <span class="op">+</span> hf[key] <span class="cf">for</span> key <span class="kw">in</span> h},</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>            fine_tune_epoch<span class="op">=</span>initial_epochs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="lab-transfer-learning-with-mobilenet_files/figure-html/cell-20-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Fine-Tuning Final Layers.</figcaption>
</figure>
</div>
</div>
</div>
<p>Both curves bend at the line. Validation accuracy climbs sharply in the five fine-tuning epochs, and the validation loss keeps falling, with a marked drop right after the bend. (It is not falling faster than at every earlier point. The single largest drop of the whole run happens before fine-tuning begins.) This is what happens when 1.6 million parameters are allowed to move instead of 1281, on features that were already close to right.</p>
<p>One feature of the accuracy panel looks wrong at first glance. The validation curve sits <strong>above</strong> the training curve for most of the run, which is the opposite of the usual picture. Both of the model’s regularizers explain it. Dropout switches off a fifth of the pooled features during training and none of them during evaluation, and the augmentation layers hand training flipped and rotated images while evaluation sees the originals. The training number is therefore measured on a handicapped model looking at harder inputs, so it is not directly comparable to the validation number.</p>
<div id="475fc1a5" class="cell" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>loss, accuracy <span class="op">=</span> model2.evaluate(validation_dataset, verbose<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Validation loss     = </span><span class="sc">{</span>loss<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Validation accuracy = </span><span class="sc">{</span>accuracy<span class="sc">:.4f}</span><span class="ss">"</span>)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"class order: </span><span class="sc">{</span>class_names<span class="sc">}</span><span class="ss">  (score above 0 means '</span><span class="sc">{</span>class_names[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">')"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Validation loss     = 0.0727
Validation accuracy = 0.9846
class order: ['alpaca', 'not alpaca']  (score above 0 means 'not alpaca')</code></pre>
</div>
</div>
<p>Predicting on a batch shows what the single output neuron actually produces. The raw score is a logit, so the sign alone is the decision, and a sigmoid turns it into the probability of the second class.</p>
<div id="c2f895ac" class="cell" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>images, labels <span class="op">=</span> <span class="bu">next</span>(<span class="bu">iter</span>(validation_dataset.take(<span class="dv">1</span>)))</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> model2.predict(images, verbose<span class="op">=</span><span class="dv">0</span>).flatten()</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>probs <span class="op">=</span> tf.sigmoid(logits).numpy()</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'true'</span><span class="sc">:&lt;12}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'logit'</span><span class="sc">:&gt;8}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'P(not alpaca)'</span><span class="sc">:&gt;15}</span><span class="ss">  </span><span class="sc">{</span><span class="st">'predicted'</span><span class="sc">:&lt;12}</span><span class="ss">"</span>)</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">8</span>):</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>    predicted <span class="op">=</span> class_names[<span class="bu">int</span>(logits[i] <span class="op">&gt;</span> <span class="dv">0</span>)]</span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a>    mark <span class="op">=</span> <span class="st">""</span> <span class="cf">if</span> predicted <span class="op">==</span> class_names[labels[i]] <span class="cf">else</span> <span class="st">"  &lt;- wrong"</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>class_names[labels[i]]<span class="sc">:&lt;12}</span><span class="ss"> </span><span class="sc">{</span>logits[i]<span class="sc">:&gt;8.2f}</span><span class="ss"> </span><span class="sc">{</span>probs[i]<span class="sc">:&gt;14.1%}</span><span class="ss">  "</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"</span><span class="sc">{</span>predicted<span class="sc">:&lt;12}{</span>mark<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>true            logit   P(not alpaca)  predicted   
not alpaca       1.27          78.1%  not alpaca  
alpaca          -6.18           0.2%  alpaca      
alpaca          -5.65           0.4%  alpaca      
alpaca          -1.06          25.6%  alpaca      
not alpaca       9.91         100.0%  not alpaca  
not alpaca       9.52         100.0%  not alpaca  
alpaca          -2.22           9.8%  alpaca      
not alpaca       8.23         100.0%  not alpaca  </code></pre>
</div>
</div>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Why is the fine-tuning learning rate a tenth of the original?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the weights being updated are already good. They encode features learned from 1.28 million ILSVRC images, and the goal is to adjust them slightly toward this dataset, not to search for them again. A full sized step, driven by gradients from 262 photographs, can move them far enough in the first few batches to destroy what ImageNet training produced, and with so little data there is not enough signal to rebuild it. A small learning rate keeps the update in the neighborhood of a solution that already works.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why unfreeze the last layers rather than the first ones?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because of what each end has learned. Early layers detect edges, corners, and simple textures, which look the same in a photograph of an alpaca as in any other photograph, so there is nothing to gain by retraining them and a great deal to lose. Later layers combine those primitives into high level structure that is specific to the classes they were trained on, and it is exactly that specialization that should be redirected toward wool, ears, and muzzles. This is the same rule of thumb as <a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets#more-data-fewer-frozen-layers">freezing fewer layers when you have more data</a>, applied from the deep end inwards.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Only 34 of the 154 layers were unfrozen, yet the trainable parameter count jumps from 1281 to more than 1.6 million. Why is the jump so large?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because parameters are not spread evenly through the network. Width grows with depth, so the last layers work with hundreds or over a thousand channels while the first ones work with tens, and the cost of a convolution scales with the product of its input and output channel counts. The deep end therefore holds most of the weights in a small number of layers, which is also why unfreezing a small tail is enough to give the model real freedom.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Validation accuracy ends up above training accuracy. Normally that ordering is a warning sign, so why is it expected here?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the two numbers are measured under different conditions. Training accuracy is computed while dropout is discarding a fifth of the pooled features and while the augmentation layers are flipping and rotating the inputs, so the model is handicapped and the images are harder than the originals. Validation accuracy is computed with dropout off, no augmentation, and the images as they are. The gap says the regularizers are doing their job, not that something is wrong. The comparison to worry about is a training accuracy that climbs while validation accuracy stalls or falls, which is overfitting.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why must <code>compile</code> be called again after changing the <code>trainable</code> flags?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because compiling is when Keras collects the list of variables the optimizer will update, along with the loss and the metrics. Flipping <code>trainable</code> on a layer afterwards changes the model but not that list, so training would carry on updating exactly what it updated before. Recompiling rebuilds it, and it also installs the new optimizer with the smaller learning rate.</p>
</div>
</div>
</div>
</section>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>The lab trained one neuron, then let a third of a borrowed network adjust, and reached a useful alpaca detector from 262 photographs.</p>
<p><strong>Datasets come from directories.</strong> <code>image_dataset_from_directory</code> turns folder names into labels and files into batches. Matching seeds across the two calls is what keeps the training and validation subsets from overlapping.</p>
<p><strong>Augmentation belongs in the model.</strong> <code>RandomFlip</code> and <code>RandomRotation</code> are layers, so they are saved with the model and they switch themselves off outside training. They stretch a small dataset without adding to it.</p>
<p><strong>Reuse the input scaling, not just the weights.</strong> <code>preprocess_input</code> applies the mapping the pretrained filters were fitted against.</p>
<p><strong>Freezing has two parts.</strong> <code>trainable = False</code> holds the weights still, and <code>training=False</code> holds the BatchNorm statistics still. Missing the second one lets the features drift under a head that is learning to read them.</p>
<p><strong>Fine-tuning is the same model with more freedom.</strong> Unfreeze the deep layers, drop the learning rate by a factor of ten, recompile, and continue. On this dataset that turned a fair classifier into a good one, which is the whole argument for transfer learning restated as a measurement.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Sandler, M., Howard, A., Zhu, M., Zhmoginov, A., &amp; Chen, L.-C. (2018). MobileNetV2: Inverted residuals and linear bottlenecks. In <em>2018 IEEE/CVF Conference on Computer Vision and Pattern Recognition</em> (pp.&nbsp;4510-4520). IEEE. <a href="https://doi.org/10.1109/CVPR.2018.00474" class="uri">https://doi.org/10.1109/CVPR.2018.00474</a></li>
</ul>


<div id="section-progress-widget" class="section-progress-widget" hidden="">
  <p class="section-progress-label">Progress through this page</p>
  <progress class="section-progress" value="53" max="100" aria-label="53 percent through this page"></progress>
  <p class="section-progress-detail">53% (1104 of 2070 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.hidden = false; sb.appendChild(w); }
});
</script>

</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://oliabak.com/giscus-theme-dark.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets" class="pagination-link" aria-label="Practical Advice for Using ConvNets">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Practical Advice for Using ConvNets</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../ai/deep-learning/convolutional-neural-networks/object-localization-and-landmark-detection" class="pagination-link" aria-label="Object Localization and Landmark Detection">
        <span class="nav-page-text">Object Localization and Landmark Detection</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>H’s Notes</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../about">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/dashboard">
<p>Dashboard</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/roadmap">
<p>Roadmap</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>