<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Skip connections and ResNets, why a one by one filter does more than multiply, and how bottlenecks make the inception module affordable enough to stack.">

<title>Modern Networks – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks" rel="next">
<link href="../../../ai/deep-learning/convolutional-neural-networks/classic-networks" rel="prev">
<link href="../../../media/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-09af6f1c3ba400237d3ba77e487e1b25.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-5d07f2f2a1dffb4a2e46c704181860bb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-b359a33defd986239048130c5c3f6bd3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-5d07f2f2a1dffb4a2e46c704181860bb.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../../styles.css">
<meta property="og:title" content="Modern Networks – H’s Notes">
<meta property="og:description" content="Skip connections and ResNets, why a one by one filter does more than multiply, and how bottlenecks make the inception module affordable enough to stack.">
<meta property="og:image" content="https://h.oliabak.com/ai/deep-learning/convolutional-neural-networks/modern-networks_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Modern Networks – H’s Notes">
<meta name="twitter:description" content="Skip connections and ResNets, why a one by one filter does more than multiply, and how bottlenecks make the inception module affordable enough to stack.">
<meta name="twitter:image" content="https://h.oliabak.com/ai/deep-learning/convolutional-neural-networks/modern-networks_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://h.oliabak.com/ai/deep-learning/convolutional-neural-networks/modern-networks">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../../networking/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccde-written/">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccie-data-center/">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../networking/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-routing/">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-switching/">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/kali-linux/">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../../ai/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/supervised-machine-learning/">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/advanced-learning-algorithms/">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/unsupervised-learning/">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/federated-learning/">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/neural-networks-and-deep-learning/">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/improving-deep-neural-networks/">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/structuring-machine-learning-projects/">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/convolutional-neural-networks/">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/sequence-models/">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../../math/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/linear-algebra/">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/calculus/">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/probability/">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/statistics/">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../../tools/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../../tools/client-info">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/asn-conversion">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/subnet-calculator">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/network-toolkit">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/pastebin">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/qr-code">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/fancy-text">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/copy-paste-values">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Classroom</li>
        <li>
    <a class="dropdown-item" href="../../../tools/randomizer">
 <span class="dropdown-text">Randomizer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../../tools/function-graphs">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/math-formula">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/latex-preview">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/markdown-preview">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/eclipse-atlas">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/planetarium">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../../tools/svg-preview">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/color-pallet">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/typography">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/tshirt-design">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../../tools/chess">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/reassess-your-chess">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/daily-chess">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../about">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/dashboard">
 <span class="dropdown-text">Dashboard</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../../about/roadmap">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/about-this-website">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/deep-learning/convolutional-neural-networks/modern-networks">Modern Networks</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutional Neural Networks</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/convolutions-and-edge-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutions and Edge Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/strided-convolutions-and-volumes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Strided Convolutions and Convolutions Over Volume</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/one-layer-of-a-convolutional-network" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One Layer of a Convolutional Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/pooling-layers" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pooling Layers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Full ConvNet Example and Why Convolutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-convolutional-model-step-by-step" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Convolutional Model Step by Step</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-convolutional-model-application" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Convolutional Model Application</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/classic-networks" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classic Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/modern-networks" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Modern Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Residual Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MobileNet and EfficientNet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/practical-advice-for-convnets" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practical Advice for Using ConvNets</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-transfer-learning-with-mobilenet" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Transfer Learning with MobileNetV2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/object-localization-and-landmark-detection" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Object Localization and Landmark Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/sliding-windows-and-region-proposals" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Sliding Windows and Region Proposals</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/bounding-box-predictions-with-yolo" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bounding Box Predictions with YOLO</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/iou-non-max-suppression-and-anchor-boxes" class="sidebar-item-text sidebar-link">
 <span class="menu-text">IoU, Non-max Suppression, and Anchor Boxes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-car-detection-with-yolo" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Car Detection with YOLO</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/semantic-segmentation-with-u-net" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Semantic Segmentation with U-Net</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-image-segmentation-with-u-net" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Image Segmentation with U-Net</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/face-recognition-and-one-shot-learning" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Face Recognition and One Shot Learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/siamese-networks-and-the-triplet-loss" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Siamese Networks and the Triplet Loss</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-face-recognition" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Face Recognition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/neural-style-transfer" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Style Transfer</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-neural-style-transfer" class="sidebar-item-text sidebar-link"><i class="bi bi-flask" role="img" aria-label="Lab">
</i> 
 <span class="menu-text">Art Generation with Neural Style Transfer</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#residual-networks" id="toc-residual-networks" class="nav-link active" data-scroll-target="#residual-networks">Residual Networks</a>
  <ul class="collapse">
  <li><a href="#residual-block" id="toc-residual-block" class="nav-link" data-scroll-target="#residual-block">Residual Block</a></li>
  <li><a href="#stacking-blocks-into-a-network" id="toc-stacking-blocks-into-a-network" class="nav-link" data-scroll-target="#stacking-blocks-into-a-network">Stacking Blocks Into a Network</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  <li><a href="#why-residual-networks-work" id="toc-why-residual-networks-work" class="nav-link" data-scroll-target="#why-residual-networks-work">Why Residual Networks Work</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#one-by-one-convolutions" id="toc-one-by-one-convolutions" class="nav-link" data-scroll-target="#one-by-one-convolutions">One by One Convolutions</a>
  <ul class="collapse">
  <li><a href="#why-it-looks-useless" id="toc-why-it-looks-useless" class="nav-link" data-scroll-target="#why-it-looks-useless">Why It Looks Useless</a></li>
  <li><a href="#why-it-is-actually-useful" id="toc-why-it-is-actually-useful" class="nav-link" data-scroll-target="#why-it-is-actually-useful">Why It Is Actually Useful</a></li>
  <li><a href="#shrinking-the-number-of-channels" id="toc-shrinking-the-number-of-channels" class="nav-link" data-scroll-target="#shrinking-the-number-of-channels">Shrinking the Number of Channels</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#inception-network" id="toc-inception-network" class="nav-link" data-scroll-target="#inception-network">Inception Network</a>
  <ul class="collapse">
  <li><a href="#inception-module" id="toc-inception-module" class="nav-link" data-scroll-target="#inception-module">Inception Module</a></li>
  <li><a href="#problem-of-computational-cost" id="toc-problem-of-computational-cost" class="nav-link" data-scroll-target="#problem-of-computational-cost">Problem of Computational Cost</a></li>
  <li><a href="#bottleneck-layer" id="toc-bottleneck-layer" class="nav-link" data-scroll-target="#bottleneck-layer">Bottleneck Layer</a></li>
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  <li><a href="#building-the-full-network" id="toc-building-the-full-network" class="nav-link" data-scroll-target="#building-the-full-network">Building the Full Network</a></li>
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<script src="../../../theme-toggle.js"></script>
<script src="../../../auth.js"></script>
<script src="../../../site-metrics.js"></script>
<script src="../../../giscus-note.js"></script>
<script src="../../../resume-reading.js"></script>
<script src="../../../sidebar-active.js"></script>
<script src="../../../search-scope.js"></script>
<script src="../../../review-numbering.js"></script>
<script src="../../../nav-columns.js"></script>
<script src="../../../activation-colors.js"></script>
<script src="../../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Modern Networks</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">convolutional-neural-networks</div>
    <div class="quarto-category">computer-vision</div>
    <div class="quarto-category">architecture</div>
    <div class="quarto-category">resnet</div>
    <div class="quarto-category">skip-connections</div>
    <div class="quarto-category">network-in-network</div>
    <div class="quarto-category">inception</div>
    <div class="quarto-category">googlenet</div>
  </div>
  </div>

<div>
  <div class="description">
    Skip connections and ResNets, why a one by one filter does more than multiply, and how bottlenecks make the inception module affordable enough to stack.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Aug 15, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (!meta) return;

  // Published only. Modified is dropped, and only two pages in the project
  // ever set date-modified.
  var published = "";
  var dateCell = meta.querySelector(".date");
  if (dateCell) {
    var cell = dateCell.closest("div");
    var body = cell && cell.querySelector(".quarto-title-meta-contents");
    published = ((body || dateCell).textContent || "").trim();
  }

  var html = '<span class="quarto-title-meta-item">107 min <span class="rt-info" tabindex="0" aria-describedby="reading-time-method"><span aria-hidden="true">&#9432;</span><span class="rt-tooltip" id="reading-time-method" role="tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level. About 6,800 words.</span></span></span><span class="quarto-title-meta-item">difficulty 3/5</span>';
  if (published) {
    html += '<span class="quarto-title-meta-item">published ' +
            published.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;") +
            '</span>';
  }

  var line = document.createElement("div");
  line.className = "quarto-title-meta-line site-meta";
  line.innerHTML = html;
  meta.insertBefore(line, meta.firstChild);
});
</script>

<p><a href="../../../ai/deep-learning/convolutional-neural-networks/classic-networks">Classic Networks</a> covered LeNet-5, AlexNet, and VGG-16, the architectures that established the basic patterns. This page covers the three ideas that came after them, the ones most modern convolutional architectures are built from. Residual networks make it possible to train networks over a hundred layers deep. One by one convolutions give a cheap way to change the number of channels in a volume. The inception module refuses to choose a filter size at all, and uses one by one convolutions to make that affordable.</p>
<section id="residual-networks" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="residual-networks">Residual Networks</h2>
<p>Very deep neural networks are difficult to train, because of <a href="../../../ai/deep-learning/improving-deep-neural-networks/setting-up-your-optimization-problem">vanishing and exploding gradient</a> problems. This section covers <strong>skip connections</strong>, which let you take the activation from one layer and feed it to another layer much deeper in the network. Using them you can build a <strong>ResNet</strong>, which makes it possible to train very deep networks, sometimes over a hundred layers.</p>
<section id="residual-block" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="residual-block">Residual Block</h3>
<p>ResNets are built out of something called a residual block, so it is worth describing that first.</p>
<p>Take two layers of a neural network. You start with the activation <span class="math inline">\(a^{[l]}\)</span>, then get <span class="math inline">\(a^{[l+1]}\)</span>, and two layers later you have <span class="math inline">\(a^{[l+2]}\)</span>. Going through the steps of that computation, you start from <span class="math inline">\(a^{[l]}\)</span> and apply a linear operation,</p>
<p><span class="math display">\[
z^{[l+1]} = W^{[l+1]} a^{[l]} + b^{[l+1]}
\]</span></p>
<p>then apply the ReLU non-linearity to get</p>
<p><span class="math display">\[
a^{[l+1]} = g(z^{[l+1]})
\]</span></p>
<p>In the next layer you apply the linear step again,</p>
<p><span class="math display">\[
z^{[l+2]} = W^{[l+2]} a^{[l+1]} + b^{[l+2]}
\]</span></p>
<p>and finally another ReLU, which gives <span class="math inline">\(a^{[l+2]} = g(z^{[l+2]})\)</span>.</p>
<p>In other words, for information to flow from <span class="math inline">\(a^{[l]}\)</span> to <span class="math inline">\(a^{[l+2]}\)</span> it has to go through all of those steps. That route is called the <strong>main path</strong> of this set of layers.</p>
<p>In a residual network you make one change. You take <span class="math inline">\(a^{[l]}\)</span>, copy it, and pass it much further into the network, adding it just before the ReLU non-linearity. That path is called the <strong>shortcut</strong>. The last equation goes away, and instead</p>
<p><span class="math display">\[
a^{[l+2]} = g\left(z^{[l+2]} + a^{[l]}\right)
\]</span></p>
<p>The addition of <span class="math inline">\(a^{[l]}\)</span> here is what makes this a residual block.</p>
<div id="7fa8c558" class="cell page-columns page-full" data-execution_count="1">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-2-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Residual block with a two-layer main path and an identity shortcut to the addition node.</figcaption>
</figure>
</div>
</div>
</div>
<p>The main path is drawn unrolled into the steps it performs, which is linear, ReLU, linear, ReLU. The shortcut carries <span class="math inline">\(a^{[l]}\)</span> forward and joins the main path at the addition, after the second linear step but before the final ReLU. That is why the last equation changes rather than a new one being added at the end.</p>
<p>Projected back onto a network, the block is nothing more than two of its layers. The activation <span class="math inline">\(a^{[l]}\)</span> feeds forward through both of them in the usual way, and a copy of it travels along the shortcut and rejoins the computation inside layer <span class="math inline">\(l+2\)</span>, where it is added to every unit before the ReLU is applied.</p>
<div id="1281aa7a" class="cell page-columns page-full" data-execution_count="2">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-3-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Two-layer residual block embedded inside a larger neural network.</figcaption>
</figure>
</div>
</div>
</div>
<p>Instead of the term shortcut you also hear <strong>skip connection</strong>, because <span class="math inline">\(a^{[l]}\)</span> skips over the two transformations in the residual branch in order to pass information deeper into the network. The inventors of ResNet are Kaiming He, Xiangyu Zhang, Shaoqing Ren, and Jian Sun, who introduced it in <a href="https://doi.org/10.1109/CVPR.2016.90">He, Zhang, Ren, and Sun (2016)</a>.</p>
</section>
<section id="stacking-blocks-into-a-network" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="stacking-blocks-into-a-network">Stacking Blocks Into a Network</h3>
<p>What they found is that using residual blocks lets you train much deeper networks. The way you build a ResNet is to take many of these blocks and stack them together.</p>
<p>Start from what the ResNet paper calls a <strong>plain network</strong>, which is just a stack of layers with no shortcuts. To turn it into a ResNet, you add the skip connections, so that every two layers gets the change described above and becomes a residual block.</p>
<div id="a8c5e340" class="cell page-columns page-full" data-execution_count="3">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-4-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Stacking Blocks Into a Network.</figcaption>
</figure>
</div>
</div>
</div>
<p>Now consider what happens if you train a plain network with a standard optimization algorithm such as gradient descent. In the ResNet experiments, increasing the depth of a plain network eventually made its <strong>training</strong> error go back up. This is the <em>degradation problem</em>. It is not overfitting, because the model is doing worse even on the data it was trained on.</p>
<p>That outcome is surprising. Provided the added layers preserve the activation shape and can represent the identity, a deeper network can represent everything its shallower counterpart can, since it could set the new layers to do nothing. So the <em>best attainable</em> training error should not increase with depth. That is a statement about what the architecture can represent, not a promise that gradient descent will find those identity-like parameters.</p>
<p>Skip connections make that easy-to-find identity path available. Consequently, a ResNet can continue lowering its training error at depths where an otherwise comparable plain network becomes difficult to optimize.</p>
<div id="9e3b3895" class="cell page-columns page-full" data-execution_count="4">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-5-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Training error as depth increases (schematic).</figcaption>
</figure>
</div>
</div>
</div>
<p>This is a schematic, not a plot of one dataset. The dashed line is the representational lower bound. If the new layers learned the identity, a deeper model could match the shallower one. The ResNet curve stays close to that bound, while the plain network peels away once the depth passes a certain point. The shape is the thing to take from the plot, rather than the unscaled values on its vertical axis.</p>
<p>By allowing activations to travel much deeper into the network, ResNets also give forward activations and backward gradients shorter routes through the model. That makes optimization much more manageable and lets you train networks well past the depth where comparable plain networks fail. Eventually the benefit of additional depth can plateau, but residual connections substantially push that limit outward.</p>
</section>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Where exactly in the two layer block is <span class="math inline">\(a^{[l]}\)</span> added, and why does the position matter?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is added to <span class="math inline">\(z^{[l+2]}\)</span>, after the linear step of the second layer but <strong>before</strong> its ReLU, giving <span class="math inline">\(a^{[l+2]} = g(z^{[l+2]} + a^{[l]})\)</span>. Thus the final ReLU acts on the combined main-path and shortcut signal. With the ReLU model used here, zeroing the residual branch gives <span class="math inline">\(g(a^{[l]}) = a^{[l]}\)</span> because <span class="math inline">\(a^{[l]}\)</span> is non-negative. Adding the shortcut after the ReLU would also allow the identity in this special case, so the identity argument alone does not determine the placement; the two arrangements are different block designs.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In theory a deeper network should never do worse on the training set than a shallower one. Why does a deep plain network do worse in practice?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The theoretical argument assumes the extra layers can be set to compute the identity, so the deeper network can always reproduce the shallower one. That is a statement about what the network <strong>can</strong> represent. In practice the optimization algorithm has to <strong>find</strong> those parameters by gradient descent, and in a very deep plain network learning even the identity turns out to be hard, so the extra layers make the result worse rather than better.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. True or false. The motivation for residual networks is that very deep networks are so good at fitting complex functions that training them almost always overfits the training data.</strong></p>
<ol type="a">
<li><p>True</p></li>
<li><p>False</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b.</strong> The problem is the opposite one. Very deep plain networks are hard to train, and past a certain depth their <strong>training</strong> error starts rising rather than falling, so extra depth does not even buy a better fit to the data the network was trained on. Residual connections attack that optimization difficulty, which is what makes networks of a hundred layers or more trainable at all. Overfitting is a different problem, addressed by regularization and more data.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The equation below captures the computation in a residual block, with two terms left out. What goes in the two blanks?</strong></p>
<p><span class="math display">\[
a^{[l+2]} = g\big(W^{[l+2]} g(W^{[l+1]} a^{[l]} + b^{[l+1]}) + b^{[l+2]} + \underline{\hspace{2em}}\big) + \underline{\hspace{2em}}
\]</span></p>
<ol type="a">
<li><p><span class="math inline">\(z^{[l]}\)</span> and <span class="math inline">\(a^{[l]}\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(0\)</span> and <span class="math inline">\(a^{[l]}\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(a^{[l]}\)</span> and <span class="math inline">\(0\)</span>, respectively.</p></li>
<li><p><span class="math inline">\(0\)</span> and <span class="math inline">\(z^{[l+1]}\)</span>, respectively.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>c.</strong> The inner <span class="math inline">\(g\)</span> produces <span class="math inline">\(a^{[l+1]}\)</span>, so the expression inside the outer <span class="math inline">\(g\)</span> is <span class="math inline">\(z^{[l+2]}\)</span>. The shortcut adds <span class="math inline">\(a^{[l]}\)</span> to that, before the ReLU of layer <span class="math inline">\(l+2\)</span> runs, which puts it in the first blank. Nothing at all is added after the activation, so the second blank is <span class="math inline">\(0\)</span>. Option b has the two the wrong way round, placing the shortcut after the outer activation instead of before it, which is a different block design.</p>
</div>
</div>
</div>
</section>
<section id="why-residual-networks-work" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="why-residual-networks-work">Why Residual Networks Work</h3>
<p>The reason skip connections help is worth working through, because it is a short argument and it explains the whole design.</p>
<p>Take an input <span class="math inline">\(x\)</span> feeding into some big network that outputs <span class="math inline">\(a^{[l]}\)</span>. Now make it deeper by adding two extra layers, and make those two layers a residual block with the shortcut. Assume the network uses ReLU activations throughout, so every activation is greater than or equal to zero, with the possible exception of the input <span class="math inline">\(x\)</span>.</p>
<div id="2827dcfc" class="cell page-columns page-full" data-execution_count="5">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-6-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Why Residual Networks Work.</figcaption>
</figure>
</div>
</div>
</div>
<p>The upper row is the original network. The lower row preserves that network and appends a residual block. The orange shortcut reaches the addition before the final ReLU, so the two new layers can be present without changing the activation when their residual branch is zero.</p>
<p>Look at what <span class="math inline">\(a^{[l+2]}\)</span> becomes. Copying the expression from above,</p>
<p><span class="math display">\[
a^{[l+2]} = g\left(z^{[l+2]} + a^{[l]}\right)
      = g\left(W^{[l+2]} a^{[l+1]} + b^{[l+2]} + a^{[l]}\right)
\]</span></p>
<p>Now notice something. Suppose the residual branch contributes nothing: set <span class="math inline">\(W^{[l+2]} = 0\)</span> and, for the sake of argument, <span class="math inline">\(b^{[l+2]} = 0\)</span>. Then those two terms go away and you are left with</p>
<p><span class="math display">\[
a^{[l+2]} = g\left(a^{[l]}\right) = a^{[l]}
\]</span></p>
<p>The last step holds because <span class="math inline">\(a^{[l]}\)</span> is itself the output of a ReLU, so it is non-negative, and applying ReLU to a non-negative quantity gives it back unchanged.</p>
<p>What this shows is that <strong>the identity function is easy for a residual block to represent</strong>. Getting <span class="math inline">\(a^{[l+2]} = a^{[l]}\)</span> costs nothing more than making the residual branch zero. The shortcut itself already carries the input forward.</p>
<p>That is the whole point. Adding these two layers retains an accessible identity parameterization, so the deeper network can match the simpler one in principle. It is not a guarantee that any optimizer will find that setting, but it is far easier to access than in a comparable plain stack.</p>
<p>Of course the goal is not merely to avoid hurting performance. If those hidden units actually learn something useful, the block does better than the identity. What goes wrong in very deep plain networks is that as they get deeper it becomes genuinely difficult to choose parameters that learn even the identity, which is why so many layers end up making the result worse instead of better.</p>
<p>So the main reason residual networks work is that their extra layers have a convenient identity parameterization. That makes them much easier to optimize than a comparable plain stack, while still allowing the residual branch to learn useful changes when they are needed.</p>
<section id="matching-the-dimensions" class="level4">
<h4 class="anchored" data-anchor-id="matching-the-dimensions">Matching the Dimensions</h4>
<p>One detail in the addition is worth spelling out. The expression <span class="math inline">\(z^{[l+2]} + a^{[l]}\)</span> assumes those two have the <strong>same dimension</strong>. This is why you see so many <a href="../../../ai/deep-learning/convolutional-neural-networks/convolutions-and-edge-detection#valid-and-same-convolutions">same convolutions</a> in ResNets, because a same convolution preserves the height and width, which makes the addition of two equal sized volumes straightforward.</p>
<p>When the input and output do have different dimensions, say <span class="math inline">\(a^{[l]}\)</span> is 128 dimensional while <span class="math inline">\(z^{[l+2]}\)</span> is 256 dimensional, you add an extra matrix <span class="math inline">\(W_s\)</span>, in this case 256 by 128, so that <span class="math inline">\(W_s a^{[l]}\)</span> is 256 dimensional and the addition is again between two vectors of matching size. <span class="math inline">\(W_s\)</span> can be a matrix of parameters that is learned, or a fixed matrix that simply zero pads <span class="math inline">\(a^{[l]}\)</span> out to 256 dimensions. Either version works.</p>
<p><span class="math display">\[
a^{[l+2]} = g\left(z^{[l+2]} + W_s a^{[l]}\right)
\]</span></p>
</section>
<section id="residual-networks-on-images" class="level4 page-columns page-full">
<h4 class="anchored" data-anchor-id="residual-networks-on-images">Residual Networks on Images</h4>
<p>Applied to images, the plain version is a network where you feed in an image and pass it through a number of convolutional layers until eventually you have a softmax output at the end. To turn it into a ResNet you add the skip connections.</p>
<p>A few details matter here. There are a lot of 3 by 3 convolutions, and most of them are 3 by 3 same convolutions, which is exactly why you are adding equal dimension volumes. These are convolutional layers rather than fully connected ones, but because they are same convolutions the dimensions are preserved and <span class="math inline">\(z^{[l+2]} + a^{[l]}\)</span> makes sense.</p>
<p>As in earlier convolutional networks, the spatial resolution is reduced as depth grows. In a standard ResNet this usually happens with a strided convolution at the start of a new stage, rather than with a pooling layer inside every block. Whenever a block changes the height, width, or channel count, its shortcut needs the <span class="math inline">\(W_s\)</span> adjustment; in image models this is commonly a learned <span class="math inline">\(1 \times 1\)</span> projection with the same stride. A typical ResNet has an initial convolution and pooling stem, groups of residual blocks made from <span class="math inline">\(3 \times 3\)</span> convolutions, then global average pooling and a final classifier.</p>
<p>The stage layout below makes that pattern concrete for the ImageNet version of ResNet-34. Each colored card represents a sequence of basic residual blocks, each containing two <span class="math inline">\(3 \times 3\)</span> convolutions.</p>
<div id="f699ad46" class="cell page-columns page-full" data-execution_count="6">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-7-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Residual Networks on Images.</figcaption>
</figure>
</div>
</div>
</div>
<p>The first stage preserves the pooled <span class="math inline">\(56 \times 56\)</span> resolution. The first block in every later stage halves the spatial size and increases the channel count, which is why it uses the projection <span class="math inline">\(W_s\)</span> on its shortcut. Counting the stem convolution, the two convolutions in each of the 16 basic blocks, and the final classifier gives 34 weighted layers.</p>
<p>The next section covers a different idea, namely what happens when you use a filter that is only one by one.</p>
</section>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. Walk through why setting <span class="math inline">\(W^{[l+2]} = 0\)</span> and <span class="math inline">\(b^{[l+2]} = 0\)</span> makes a residual block compute the identity.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Start from <span class="math inline">\(a^{[l+2]} = g(W^{[l+2]} a^{[l+1]} + b^{[l+2]} + a^{[l]})\)</span>. With both parameters zero, the first two terms vanish, leaving <span class="math inline">\(a^{[l+2]} = g(a^{[l]})\)</span>. Because <span class="math inline">\(a^{[l]}\)</span> is the output of an earlier ReLU it is non-negative, and ReLU leaves non-negative values unchanged, so <span class="math inline">\(g(a^{[l]}) = a^{[l]}\)</span>. The block passes its input straight through.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Does this identity argument require L2 regularization?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;L2 regularization, or weight decay, may encourage smaller weights, but it does not make them exactly zero and is not the reason ResNets work. The point of the argument is architectural. Once the residual branch is near zero, the shortcut already supplies an identity path. That path is available whether or not weight decay is used.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is <span class="math inline">\(W_s\)</span> for, and when do you need it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math inline">\(W_s\)</span> reshapes <span class="math inline">\(a^{[l]}\)</span> so it can be added to <span class="math inline">\(z^{[l+2]}\)</span> when the two have different dimensions, for example 128 against 256. It is a 256 by 128 matrix, either learned along with everything else or fixed to simply zero pad the shorter vector. You need it wherever the shortcut spans a layer that changes the dimensions, which in an image network means wherever a pooling layer or a stride greater than one sits inside the block.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why do residual networks for images use so many same convolutions?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the shortcut adds <span class="math inline">\(a^{[l]}\)</span> to <span class="math inline">\(z^{[l+2]}\)</span>, and addition needs both to have the same height, width, and channel count. A same convolution preserves the height and width by construction, so consecutive layers inside a block produce matching volumes and the addition works with no adjustment at all. Valid convolutions would shrink the volume at every layer and require a <span class="math inline">\(W_s\)</span> correction on every shortcut.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Does adding a residual block guarantee the network gets better?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;The guarantee is weaker and more useful than that. It guarantees the block can easily do no harm, because the identity is cheap to learn. Anything the two layers learn beyond the identity is an improvement on top of that floor. The contrast is with a plain network, where extra depth can actively make the training error worse because even the identity is hard to find.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Adding a residual block to the end of a network makes it deeper. Which of the following is true?</strong></p>
<ol type="a">
<li><p>The performance of the network does not get hurt, because the residual block can easily approximate the identity function.</p></li>
<li><p>The performance of the network is hurt, because the network is made harder to train.</p></li>
<li><p>It shifts the behavior of the whole network to be more like the identity function.</p></li>
<li><p>The number of parameters decreases, because of the shortcut connections.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>a.</strong> This is the argument worked through just above. In a residual block <span class="math inline">\(a^{[l+2]} = g(W^{[l+2]} a^{[l+1]} + b^{[l+2]} + a^{[l]})\)</span>, so setting <span class="math inline">\(W^{[l+2]}\)</span> and <span class="math inline">\(b^{[l+2]}\)</span> to zero leaves <span class="math inline">\(g(a^{[l]}) = a^{[l]}\)</span>, the identity. Gradient descent can reach that easily, which sets a floor under the performance. Option b describes what happens with a plain block. Option c confuses one block being able to act as the identity with the whole network doing so, and the rest of the network is untouched. Option d is wrong because the shortcut carries no weights of its own, so the parameter count goes up by whatever the two new layers hold.</p>
</div>
</div>
</div>
</section>
</section>
<section id="one-by-one-convolutions" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="one-by-one-convolutions">One by One Convolutions</h2>
<p>One of the ideas that really helps in designing convolutional architectures is the one by one convolution. At first glance that seems like a strange thing to do, since a one by one filter looks like it is just multiplying by a number. It turns out to be considerably more than that.</p>
<section id="why-it-looks-useless" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="why-it-looks-useless">Why It Looks Useless</h3>
<p>Start with the case where it really is trivial. Take a 6 by 6 image with a single channel, so 6 by 6 by 1, and convolve it with a one by one by one filter whose single entry is 2. Every output value is just the input value multiplied by 2.</p>
<div id="8d358da8" class="cell page-columns page-full" data-execution_count="7">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-8-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Why It Looks Useless.</figcaption>
</figure>
</div>
</div>
</div>
<p>So 1, 2, 3 ends up as 2, 4, 6, and so on. Convolving a single channel image with a one by one filter does not seem particularly useful.</p>
</section>
<section id="why-it-is-actually-useful" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="why-it-is-actually-useful">Why It Is Actually Useful</h3>
<p>The picture changes completely once the input has many channels. Take a 6 by 6 by 32 volume instead of 6 by 6 by 1, and convolve it with a one by one by 32 filter.</p>
<p>Now the filter has to match the channel count of its input, so it holds 32 numbers. At each of the 36 positions it takes the element-wise product between the 32 numbers running down the channel axis of the input and the 32 numbers in the filter, sums them, and applies a ReLU. That gives a single real number, which becomes one entry of the output.</p>
<p>One useful way to think about those 32 filter numbers is as a <strong>single neuron</strong> taking 32 inputs, multiplying them by 32 weights, applying a ReLU, and producing one output. The convolution just applies that same neuron at each of the 36 positions.</p>
<p>More generally, if you have not one filter but several, it is as though you have not one neuron but a small layer of them, each taking all 32 numbers of one position as input. So a one by one convolution is essentially a <strong>fully connected network applied at every position of the volume</strong>, taking <span class="math inline">\(n_C\)</span> numbers in and producing as many numbers out as there are filters.</p>
<div id="f6c4f842" class="cell page-columns page-full" data-execution_count="8">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-9-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Why It Is Actually Useful.</figcaption>
</figure>
</div>
</div>
</div>
<p>Doing that at each of the 6 by 6 positions gives an output that is 6 by 6 by the number of filters. So a one by one convolution really does carry out a non-trivial computation on the input volume. The idea is often called a one by one convolution, but it is also called <strong>network in network</strong>, from <a href="https://doi.org/10.48550/arXiv.1312.4400">Lin, Chen, and Yan (2013)</a>. Even though the details of the architecture in that paper are not widely used, the network in network idea has been very influential, including on the <a href="#inception-network">inception network</a>.</p>
</section>
<section id="shrinking-the-number-of-channels" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="shrinking-the-number-of-channels">Shrinking the Number of Channels</h3>
<p>Here is the use that matters most. Suppose you have a 28 by 28 by 192 volume.</p>
<p>If you want to shrink the height and width, you already know how, using a <a href="../../../ai/deep-learning/convolutional-neural-networks/pooling-layers">pooling layer</a>. But what if the number of channels has grown too large and it is the channel count you want to shrink? How do you get to 28 by 28 by 32?</p>
<p>Use 32 filters that are one by one. Technically each filter is one by one by 192, because the number of channels in a filter always has to match the number of channels in the input. With 32 such filters the output is 28 by 28 by 32.</p>
<div id="7c961591" class="cell page-columns page-full" data-execution_count="9">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-10-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Shrinking the Number of Channels.</figcaption>
</figure>
</div>
</div>
</div>
<p>This is the counterpart to pooling. A pooling layer shrinks <span class="math inline">\(n_H\)</span> and <span class="math inline">\(n_W\)</span>, the height and width. A one by one convolution shrinks <span class="math inline">\(n_C\)</span>, the number of channels. That distinction is what makes it so useful, and the <a href="#inception-network">inception network</a> uses exactly this trick to save a large amount of computation.</p>
<p>Of course you do not have to shrink. Keeping the number of filters at 192 is fine too, in which case the effect of the one by one convolution is simply to add a non-linearity. It lets the network learn a more complex function by adding another layer that takes 28 by 28 by 192 in and gives 28 by 28 by 192 out.</p>
<p>So a one by one convolution lets you shrink the number of channels in your volumes, keep it the same, or even increase it if you want.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. Why is a one by one convolution trivial on a single channel image but not on a 32 channel volume?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The filter always has to match the channel count of its input, so on a 6 by 6 by 1 input the filter is 1 by 1 by 1, a single number, and the convolution is scalar multiplication. On a 6 by 6 by 32 input the filter is 1 by 1 by 32, so at each position it combines all 32 channel values into one number through a weighted sum and a ReLU. The work happens along the channel axis, which barely exists in the single channel case.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. How many parameters does a one by one convolution with 32 filters on a 28 by 28 by 192 input have?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Each filter is <span class="math inline">\(1 \times 1 \times 192\)</span>, so 192 weights plus one bias, and there are 32 of them, giving <span class="math inline">\(32 \times (192 + 1) = 6{,}176\)</span>. Note that the 28 by 28 does not appear, because a convolution reuses the same filter at every position regardless of the image size.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is the difference in effect between a pooling layer and a one by one convolution?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A pooling layer shrinks the height and width, <span class="math inline">\(n_H\)</span> and <span class="math inline">\(n_W\)</span>, and leaves the number of channels alone, because it is applied to each channel independently. A one by one convolution leaves the height and width alone and changes the number of channels, <span class="math inline">\(n_C\)</span>, to whatever the filter count is. They act on different axes of the volume, which is why architectures use both.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. If a one by one convolution keeps the channel count the same, what has it accomplished?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It has added a non-linearity. Each position passes through a weighted sum and a ReLU, so the network gains another layer of representational power without changing the shape of the volume at all. That is the network in network idea, a small fully connected network applied at every spatial position.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. True or false. A one by one convolution is the same as multiplying by a single number.</strong></p>
<ol type="a">
<li><p>True</p></li>
<li><p>False</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b.</strong> That is true only in the degenerate case of a single channel input, where the filter really is one number. On a volume with <span class="math inline">\(n_C\)</span> channels the filter is <span class="math inline">\(1 \times 1 \times n_C\)</span>, so at each position it takes a weighted sum over the whole depth of the volume and passes the result through a ReLU. It is a small fully connected network applied at every spatial position, not a scalar multiplication.</p>
</div>
</div>
</div>
</section>
</section>
<section id="inception-network" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="inception-network">Inception Network</h2>
<p>When designing a convolutional layer you have to pick things. Do you want a 1 by 1 filter, or 3 by 3, or 5 by 5? Or do you want a pooling layer instead? What the inception network says is, why not do them all. It makes the architecture more complicated, but it also works remarkably well.</p>
<section id="inception-module" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="inception-module">Inception Module</h3>
<p>Say you have a 28 by 28 by 192 input volume. Instead of committing to one filter size, or even to whether you want a convolutional layer or a pooling layer, an inception layer does all of them.</p>
<p>This first version intentionally sends the input directly into the 3 by 3 and 5 by 5 convolutions. It is the expensive design used to motivate the bottleneck layers introduced later. The completed module under <a href="#building-the-full-network">Building the Full Network</a> adds one by one reductions before those costly branches.</p>
<p>You could use a 1 by 1 convolution and get 28 by 28 by 64 out. Maybe you also want to try a 3 by 3, giving 28 by 28 by 128. You then stack that second volume next to the first. To make the dimensions line up, the 3 by 3 is a same convolution, so its output height and width stay at 28 by 28. Perhaps a 5 by 5 filter works better, so do that too and have it output 28 by 28 by 32, again as a same convolution.</p>
<p>Finally, maybe you do not want a convolutional layer at all. Apply pooling with same padding and a stride of one, then use a one by one convolution to project that branch down to 32 channels. That gives a fourth 28 by 28 by 32 output to stack with the others.</p>
<div id="28cdd95b" class="cell page-columns page-full" data-execution_count="10">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-11-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Inception Module.</figcaption>
</figure>
</div>
</div>
</div>
<p>One detail about the pooling branch is unusual and easy to miss. To keep its height and width at 28 by 28, it uses same padding together with a <strong>stride of one</strong>. Pooling alone would still have 192 channels, because pooling works independently on every input channel. The following one by one convolution is what projects the pooled volume down to 32 channels, allowing it to concatenate with the other branches.</p>
<p>With an inception module like this you input one volume and output another. Adding up the branches, <span class="math inline">\(64 + 128 + 32 + 32 = 256\)</span>, so the module takes 28 by 28 by 192 in and gives 28 by 28 by 256 out.</p>
<p>That is the heart of the inception network, due to Christian Szegedy, Wei Liu, Yangqing Jia, Pierre Sermanet, Scott Reed, Dragomir Anguelov, Dumitru Erhan, Vincent Vanhoucke, and Andrew Rabinovich, published as <a href="https://doi.org/10.1109/CVPR.2015.7298594">Szegedy et al.&nbsp;(2015)</a>. The basic idea is that instead of picking one filter size or pooling and committing to it, you do them all, concatenate the outputs, and let the network learn whichever combination of filter sizes it wants to use.</p>
</section>
<section id="problem-of-computational-cost" class="level3">
<h3 class="anchored" data-anchor-id="problem-of-computational-cost">Problem of Computational Cost</h3>
<p>There is a problem with the inception module as described, namely computational cost. It is worth working out the cost of just the 5 by 5 branch.</p>
<p>That branch takes the 28 by 28 by 192 input and applies a 5 by 5 same convolution with 32 filters, producing 28 by 28 by 32. There are 32 filters because the output has 32 channels, and each filter is 5 by 5 by 192.</p>
<p>The total number of multiplications is the number of output values times the number of multiplications needed for each one. There are <span class="math inline">\(28 \times 28 \times 32\)</span> output values, and each one costs <span class="math inline">\(5 \times 5 \times 192\)</span> multiplications.</p>
<div id="c9954f01" class="cell" data-execution_count="11">
<div class="cell-output cell-output-stdout">
<pre><code>output values      28 x 28 x 32     =     25,088
cost per value     5 x 5 x 192      =      4,800
total multiplications               = 120,422,400   (120 million)</code></pre>
</div>
</div>
<p>You can do 120 million multiplications on a modern computer, but it is still an expensive operation, and this is one branch of one module.</p>
</section>
<section id="bottleneck-layer" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="bottleneck-layer">Bottleneck Layer</h3>
<p>Using the <a href="#one-by-one-convolutions">one by one convolution</a>, the cost can be cut by roughly a factor of ten.</p>
<p>Here is the alternative. Take the same 28 by 28 by 192 input, use a one by one convolution to reduce it to 16 channels instead of 192, and then run the 5 by 5 convolution on that much smaller volume to get the final output. The input and output dimensions are unchanged, still 28 by 28 by 192 in and 28 by 28 by 32 out. What has changed is that the huge volume on the left has been shrunk to a much smaller intermediate volume with 16 channels instead of 192.</p>
<div id="9d49644c" class="cell page-columns page-full" data-execution_count="12">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-13-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Bottleneck Layer.</figcaption>
</figure>
</div>
</div>
</div>
<p>This intermediate volume is sometimes called a <strong>bottleneck layer</strong>, because a bottleneck is the smallest part of something. If you picture a glass bottle, the bottleneck is where it narrows. In the same way this is the narrowest part of the network, where the representation is shrunk before being expanded again.</p>
<p>Now the cost. The one by one convolution has 16 filters, each of dimension 1 by 1 by 192, where that 192 matches the input channel count. Then the 5 by 5 convolution runs on the 16 channel volume.</p>
<div id="7acfdb29" class="cell" data-execution_count="13">
<div class="cell-output cell-output-stdout">
<pre><code>1x1 step   28x28x16 outputs, 192 each     =    2,408,448   (2.4M)
5x5 step   28x28x32 outputs, 5x5x16 each  =   10,035,200   (10.0M)
total                                     =   12,443,648   (12.4M)

against the direct version                =  120,422,400   (120.4M)
ratio                                     = 0.103, about one tenth</code></pre>
</div>
</div>
<p>So the computational cost drops from about 120 million multiplications to about 12.4 million, roughly a tenth. The number of additions needed is very similar to the number of multiplications, which is why only multiplications are counted.</p>
<p>You might reasonably worry that shrinking the representation so dramatically hurts performance. It turns out that so long as the bottleneck is implemented within reason, you can shrink the representation size significantly without seeming to hurt performance, while saving a great deal of computation.</p>
</section>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. Why does the max pooling branch need same padding and a stride of one, which is not how pooling is normally used?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the four branch outputs are concatenated along the channel axis, and concatenation requires them to agree on height and width. The other three branches are same convolutions producing 28 by 28, so the pooling has to produce 28 by 28 as well. Normal pooling with <span class="math inline">\(f=2\)</span>, <span class="math inline">\(s=2\)</span> would halve it to 14 by 14 and could not be stacked. Same padding with a stride of one is the only setting that leaves the spatial size untouched.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Where does the 120 million figure come from?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is the number of output values times the cost of each. The output is 28 by 28 by 32, which is 25,088 values, and each one requires an element-wise product over a <span class="math inline">\(5 \times 5 \times 192\)</span> window, which is 4,800 multiplications. Multiplying gives <span class="math inline">\(25{,}088 \times 4{,}800 = 120{,}422{,}400\)</span>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. The bottleneck version does two convolutions instead of one. Why is doing more layers cheaper?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because cost is driven by the depth of the volume the expensive filter has to look through. The 5 by 5 filter is the costly part, at <span class="math inline">\(5 \times 5 \times n_C\)</span> multiplications per output value. Running it against 192 channels costs 4,800 per value; running it against 16 costs 400. The extra 1 by 1 layer that performs the reduction is cheap, at 192 multiplications per value over a smaller output, so paying 2.4 million to avoid 110 million is a large net win.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of the following are true about the inception network? Check all that apply.</strong></p>
<ol type="a">
<li><p>Making an inception network deeper will not hurt the training set performance.</p></li>
<li><p>Inception blocks allow the use of a combination of 1 by 1, 3 by 3, and 5 by 5 convolutions and pooling, by applying one layer after the other.</p></li>
<li><p>Inception blocks allow the use of a combination of 1 by 1, 3 by 3, and 5 by 5 convolutions and pooling, by stacking up all the activations resulting from each type of layer.</p></li>
<li><p>One problem with simply stacking up several layers is the computational cost of it.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>c and d.</strong> Stacking the four branch outputs along the channel axis to get one volume, so the network does not have to commit to a single filter size, is the whole idea of the module, and the computational cost of doing so is exactly what the 1 by 1 bottleneck exists to control. Option b describes the branches running in series, which is not what happens, since they run in parallel on the same input and are concatenated. Option a is the mistake corrected by the <a href="#residual-networks">residual networks</a> section, where stacking more layers onto a plain network is shown to make the training error rise rather than fall.</p>
</div>
</div>
</div>
</section>
<section id="building-the-full-network" class="level3 page-columns page-full">
<h3 class="anchored" data-anchor-id="building-the-full-network">Building the Full Network</h3>
<p>With the bottleneck idea in hand, the complete inception module can be assembled. The module takes as input the activation from some previous layer, again 28 by 28 by 192.</p>
<p>The example worked through above was the 1 by 1 followed by the 5 by 5, where the 1 by 1 has 16 channels and the 5 by 5 outputs 28 by 28 by 32. To save computation on the 3 by 3 convolution you do the same thing there, putting a 1 by 1 reduction in front of it. In the concrete GoogLeNet inception(3a) configuration shown below, that reduction uses 96 filters and the following 3 by 3 convolution uses 128 filters.</p>
<p>The standalone 1 by 1 branch needs no bottleneck reduction. Its convolution is already inexpensive, so it directly produces the 28 by 28 by 64 branch output. A second 1 by 1 layer could add another learned transformation, but it would not serve the cost-saving purpose of reducing channels before a larger spatial filter.</p>
<p>Finally the pooling layer. To be able to concatenate everything, the pooling uses same padding so the output stays 28 by 28. But notice that max pooling, even with same padding and a 3 by 3 filter at stride 1, gives 28 by 28 by <strong>192</strong>. Pooling acts on each channel independently, so it has the same depth as its input, which is a lot of channels. So you add one more 1 by 1 convolutional layer after the pooling to shrink the number of channels, taking it down to 28 by 28 by 32 using 32 filters of dimension 1 by 1 by 192. Without that step the pooling branch would dominate the channels of the final output.</p>
<p>Then you take all of these blocks and do channel concatenation, giving <span class="math inline">\(64 + 128 + 32 + 32 = 256\)</span>, so 28 by 28 by 256.</p>
<div id="9308ce71" class="cell page-columns page-full" data-execution_count="14">
<div class="cell-output cell-output-display page-columns page-full">
<div class="quarto-figure quarto-figure-center page-columns page-full">
<figure class="figure page-columns page-full">
<p class="page-columns page-full"><img src="modern-networks_files/figure-html/cell-15-output-1.svg" class="img-fluid figure-img column-body-outset"></p>
<figcaption>Building the Full Network.</figcaption>
</figure>
</div>
</div>
</div>
<p>That is one inception module, and the inception network is more or less a lot of these modules put together. In the picture from the paper you notice many repeated blocks, and although the whole thing looks complicated, each block is just the module above. There are some extra max pooling layers between them to change the height and width, but essentially the network is these blocks repeated at different positions. If you understand the inception block, you understand the inception network.</p>
<section id="side-branches" class="level4">
<h4 class="anchored" data-anchor-id="side-branches">Side Branches</h4>
<p>There is one more detail if you read the paper, namely some additional side branches.</p>
<p>The last few layers of the network are a fully connected layer followed by a softmax that makes the prediction. What the side branches do is take a hidden layer from partway through the network, pass it through a few fully connected layers, and use <strong>that</strong> to make a prediction with its own softmax output.</p>
<p>What this accomplishes is to help ensure that the features computed in the intermediate layers, not just the final ones, are already good enough to predict the output class of an image. This appears to have a regularizing effect and helps prevent the network from overfitting.</p>
<p>This particular network was developed by authors at Google, who called it <strong>GoogLeNet</strong>, spelled that way to pay homage to LeNet.</p>
<p>As a closing detail, the name inception comes from the paper citing the “we need to go deeper” meme, with the URL as an actual reference, as motivation for building deeper networks. It is not often that research papers get to cite internet memes.</p>
<p>Since the original module, the authors and others have built newer versions, so you sometimes see inception v2, v3, and v4 in use. There is also a version that combines the inception module with the <a href="#residual-networks">residual network</a> idea of skip connections, which sometimes works even better. All of them are built on the basic idea of the inception module stacked many times over.</p>
<p>The <a href="../../../ai/deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet">next page</a> turns to architectures designed for devices where computation is scarce.</p>
</section>
</section>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Why does the pooling branch need a 1 by 1 convolution after it, when the other branches have theirs before?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Pooling has no learned filters and operates independently on each channel, so its output has the same depth as its input, 192 channels. In this branch the goal is to preserve pooled features first, then learn a 32-channel projection, so the 1 by 1 convolution comes after pooling. Moving it before pooling would define a different computation rather than an equivalent rearrangement. Without the projection, the pooling branch alone would contribute 192 channels and dominate the concatenated output.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why is there no 1 by 1 reduction in front of the 1 by 1 branch?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is not needed as a bottleneck. The reductions exist to make an expensive 3 by 3 or 5 by 5 filter process fewer channels, while a 1 by 1 filter is already inexpensive. Two 1 by 1 layers with a non-linearity between them could learn a richer transformation, but that is a different design goal from the computational reduction used in the other two convolution branches.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What do the side branches in GoogLeNet do, and why do they help?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>They take a hidden layer partway through the network, run it through a few fully connected layers, and attach their own softmax prediction. This forces the intermediate features to be good enough to classify the image on their own, rather than only being useful after every remaining layer has run. That acts as a regularizer and helps prevent overfitting.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. An inception module lets the network use every filter size at once. What is the cost of that flexibility, and how is it managed?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The cost is computation. Running a 5 by 5 convolution directly against a 192 channel volume takes about 120 million multiplications for one branch of one module, and the network stacks many modules. It is managed with 1 by 1 bottleneck layers that shrink the channel count before the expensive filters run, cutting that branch to about 12.4 million, roughly a tenth, with no measurable loss in performance.</p>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>He, K., Zhang, X., Ren, S., &amp; Sun, J. (2016). Deep residual learning for image recognition. In <em>2016 IEEE Conference on Computer Vision and Pattern Recognition (CVPR)</em> (pp.&nbsp;770-778). IEEE. <a href="https://doi.org/10.1109/CVPR.2016.90" class="uri">https://doi.org/10.1109/CVPR.2016.90</a></li>
<li>Lin, M., Chen, Q., &amp; Yan, S. (2013). <em>Network in network</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1312.4400" class="uri">https://doi.org/10.48550/arXiv.1312.4400</a></li>
<li>Szegedy, C., Liu, W., Jia, Y., Sermanet, P., Reed, S., Anguelov, D., et al.&nbsp;(2015). Going deeper with convolutions. In <em>2015 IEEE Conference on Computer Vision and Pattern Recognition (CVPR)</em> (pp.&nbsp;1-9). IEEE. <a href="https://doi.org/10.1109/CVPR.2015.7298594" class="uri">https://doi.org/10.1109/CVPR.2015.7298594</a></li>
</ul>


<div id="section-progress-widget" class="section-progress-widget" hidden="">
  <p class="section-progress-label">Progress through this section</p>
  <progress class="section-progress" value="34" max="100" aria-label="34 percent through this section"></progress>
  <p class="section-progress-detail">34% through this section (717 of 2067 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.hidden = false; sb.appendChild(w); }
});
</script>

</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme-dark.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../ai/deep-learning/convolutional-neural-networks/classic-networks" class="pagination-link" aria-label="Classic Networks">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Classic Networks</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../../ai/deep-learning/convolutional-neural-networks/lab-residual-networks" class="pagination-link" aria-label="Residual Networks">
        <span class="nav-page-text">Residual Networks</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>H’s Notes</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../about">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/dashboard">
<p>Dashboard</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/roadmap">
<p>Roadmap</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>