<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Why non-i.i.d. client data can disrupt federated averaging, what client drift is, a from-scratch FedAvg implementation that shows it, and the variants that address it.">

<title>Data Heterogeneity and Client Drift – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<link href="../../../ai/machine-learning/federated-learning/bandwidth-in-federated-learning" rel="prev">
<link href="../../../media/favicon.ico" rel="icon">
<script src="../../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-dark-09af6f1c3ba400237d3ba77e487e1b25.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting-2fbff13f3c01954db7c154d56b89b1ba.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../../site_libs/bootstrap/bootstrap-dark-43798084b7368a40096bd6648f6381c9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../../site_libs/bootstrap/bootstrap-7259a1b8aa62165dc6d664d43cf53c19.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": true,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": "tree",
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../../styles.css?v=10149509">
<meta property="og:title" content="Data Heterogeneity and Client Drift – H’s Notes">
<meta property="og:description" content="Why non-i.i.d. client data can disrupt federated averaging, what client drift is, a from-scratch FedAvg implementation that shows it, and the variants that address it.">
<meta property="og:image" content="https://oliabak.com/ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift_files/figure-html/cell-6-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Data Heterogeneity and Client Drift – H’s Notes">
<meta name="twitter:description" content="Why non-i.i.d. client data can disrupt federated averaging, what client drift is, a from-scratch FedAvg implementation that shows it, and the variants that address it.">
<meta name="twitter:image" content="https://oliabak.com/ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift_files/figure-html/cell-6-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
<link rel="canonical" href="https://oliabak.com/ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift">
<script type="application/ld+json" data-breadcrumbs="1">
{
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  "itemListElement": [
    {
      "@type": "ListItem",
      "position": 1,
      "name": "Artificial Intelligence",
      "item": "https://oliabak.com/ai/"
    },
    {
      "@type": "ListItem",
      "position": 2,
      "name": "Machine Learning",
      "item": "https://oliabak.com/ai/machine-learning/"
    },
    {
      "@type": "ListItem",
      "position": 3,
      "name": "Federated Learning",
      "item": "https://oliabak.com/ai/machine-learning/federated-learning/"
    },
    {
      "@type": "ListItem",
      "position": 4,
      "name": "Data Heterogeneity and Client Drift",
      "item": "https://oliabak.com/ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift"
    }
  ]
}
</script>
</head>

<body class="nav-sidebar docked nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../../">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../../networking/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccde-written/">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccie-data-center/">
 <span class="dropdown-text">CCIE Data Center</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../networking/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-routing/">
 <span class="dropdown-text">CCNP Routing</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../networking/ccnp-switching/">
 <span class="dropdown-text">CCNP Switching</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-cybersecurity" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Cybersecurity</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-cybersecurity">    
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Archive</li>
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/archive">
 <span class="dropdown-text">Archive Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../cybersecurity/kali-linux/">
 <span class="dropdown-text">Kali Linux</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="../../../ai/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Machine Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/">
 <span class="dropdown-text">Machine Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/supervised-machine-learning/">
 <span class="dropdown-text">Supervised Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/advanced-learning-algorithms/">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/unsupervised-learning/">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/machine-learning/federated-learning/">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Deep Learning</li>
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/">
 <span class="dropdown-text">Deep Learning Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/neural-networks-and-deep-learning/">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/improving-deep-neural-networks/">
 <span class="dropdown-text">Improving Deep Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/structuring-machine-learning-projects/">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/convolutional-neural-networks/">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../ai/deep-learning/sequence-models/">
 <span class="dropdown-text">Sequence Models</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../../math/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/linear-algebra/">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/calculus/">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/probability/">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../math/statistics/">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../../tools/">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../../tools/client-info">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/asn-conversion">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/subnet-calculator">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/network-toolkit">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/pastebin">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/short-links">
 <span class="dropdown-text">Short Links</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/qr-code">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/fancy-text">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/copy-paste-values">
 <span class="dropdown-text">Copy Paste Values</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Classroom</li>
        <li>
    <a class="dropdown-item" href="../../../tools/randomizer">
 <span class="dropdown-text">Randomizer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../../tools/function-graphs">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/math-formula">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/latex-preview">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/markdown-preview">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../../tools/eclipse-atlas">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/planetarium">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../../tools/diagrams">
 <span class="dropdown-text">Diagrams</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/svg-preview">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/color-pallet">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/typography">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/tshirt-design">
 <span class="dropdown-text">T-shirt Design</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../../tools/chess">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/reassess-your-chess">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../tools/daily-chess">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../../about">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/dashboard">
 <span class="dropdown-text">Dashboard</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../../about/roadmap">
 <span class="dropdown-text">Roadmap</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../../about/about-this-website">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/">Machine Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/federated-learning/">Federated Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift">Data Heterogeneity and Client Drift</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Artificial Intelligence</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/machine-learning/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../../../ai/machine-learning/federated-learning/" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Federated Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth3 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/why-federated-learning" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Why Federated Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/how-federated-learning-works" class="sidebar-item-text sidebar-link">
 <span class="menu-text">How Federated Learning Works</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/tuning-federated-learning-systems" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tuning Federated Learning Systems</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/data-privacy-in-federated-learning" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Privacy in Federated Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/bandwidth-in-federated-learning" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bandwidth in Federated Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../../ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Data Heterogeneity and Client Drift</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#independent-and-identically-distributed-data" id="toc-independent-and-identically-distributed-data" class="nav-link active" data-scroll-target="#independent-and-identically-distributed-data">Independent and Identically Distributed Data</a>
  <ul class="collapse">
  <li><a href="#ways-data-can-be-non-i.i.d." id="toc-ways-data-can-be-non-i.i.d." class="nav-link" data-scroll-target="#ways-data-can-be-non-i.i.d.">Ways Data Can Be Non-i.i.d.</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#client-drift" id="toc-client-drift" class="nav-link" data-scroll-target="#client-drift">Client Drift</a>
  <ul class="collapse">
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#lab-federated-averaging-from-scratch" id="toc-lab-federated-averaging-from-scratch" class="nav-link" data-scroll-target="#lab-federated-averaging-from-scratch">Lab: Federated Averaging from Scratch</a>
  <ul class="collapse">
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#splitting-the-data-three-ways" id="toc-splitting-the-data-three-ways" class="nav-link" data-scroll-target="#splitting-the-data-three-ways">Splitting the Data Three Ways</a></li>
  <li><a href="#model-and-the-local-client-loop" id="toc-model-and-the-local-client-loop" class="nav-link" data-scroll-target="#model-and-the-local-client-loop">Model and the Local Client Loop</a></li>
  <li><a href="#server-loop" id="toc-server-loop" class="nav-link" data-scroll-target="#server-loop">Server Loop</a></li>
  <li><a href="#watching-drift-happen" id="toc-watching-drift-happen" class="nav-link" data-scroll-target="#watching-drift-happen">Watching Drift Happen</a></li>
  <li><a href="#separating-drift-from-sampling-luck" id="toc-separating-drift-from-sampling-luck" class="nav-link" data-scroll-target="#separating-drift-from-sampling-luck">Separating Drift from Sampling Luck</a></li>
  <li><a href="#does-weighting-actually-matter" id="toc-does-weighting-actually-matter" class="nav-link" data-scroll-target="#does-weighting-actually-matter">Does Weighting Actually Matter?</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#variants-that-fix-it" id="toc-variants-that-fix-it" class="nav-link" data-scroll-target="#variants-that-fix-it">Variants That Fix It</a>
  <ul class="collapse">
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#other-challenges" id="toc-other-challenges" class="nav-link" data-scroll-target="#other-challenges">Other Challenges</a>
  <ul class="collapse">
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<script src="../../../theme-toggle.js?v=3505170f"></script>
<script src="../../../auth.js?v=37e2729f"></script>
<script src="../../../site-metrics.js?v=9d1b4053"></script>
<script src="../../../giscus-note.js?v=e94ec728"></script>
<script src="../../../resume-reading.js?v=c40ebfea"></script>
<script src="../../../sidebar-active.js?v=62f05be2"></script>
<script src="../../../search-scope.js?v=13576411"></script>
<script src="../../../review-numbering.js?v=50100e67"></script>
<script src="../../../nav-columns.js?v=a9beef4d"></script>
<script src="../../../activation-colors.js?v=a9e5b12e"></script>
<script src="../../../visit-history.js?v=85edd45a"></script>

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../../ai/">Artificial Intelligence</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/">Machine Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/federated-learning/">Federated Learning</a></li><li class="breadcrumb-item"><a href="../../../ai/machine-learning/federated-learning/data-heterogeneity-and-client-drift">Data Heterogeneity and Client Drift</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Data Heterogeneity and Client Drift</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">federated-learning</div>
    <div class="quarto-category">non-iid</div>
    <div class="quarto-category">client-drift</div>
    <div class="quarto-category">fedavg</div>
  </div>
  </div>

<div>
  <div class="description">
    Why non-i.i.d. client data can disrupt federated averaging, what client drift is, a from-scratch FedAvg implementation that shows it, and the variants that address it.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">Sep 1, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (!meta) return;

  // Published, and Modified only where a page actually sets date-modified.
  // Two pages do, about-this-website and roadmap, and both carry it on
  // purpose because they describe a site that keeps changing.
  function readCell(sel) {
    var el = meta.querySelector(sel);
    if (!el) return "";
    var cell = el.closest("div");
    var body = cell && cell.querySelector(".quarto-title-meta-contents");
    return ((body || el).textContent || "").trim();
  }
  var published = readCell(".date");
  var modified = readCell(".date-modified");

  var html = '<span class="quarto-title-meta-item">118 min <span class="rt-info" tabindex="0" aria-describedby="reading-time-method"><span aria-hidden="true">&#9432;</span><span class="rt-tooltip" id="reading-time-method" role="tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></span><span class="quarto-title-meta-item">6,000 words</span><span class="quarto-title-meta-item">difficulty 3/5</span>';
  function esc(t) {
    return t.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }
  if (published) {
    html += '<span class="quarto-title-meta-item">published ' + esc(published) + '</span>';
  }
  if (modified && modified !== published) {
    html += '<span class="quarto-title-meta-item">updated ' + esc(modified) + '</span>';
  }

  var line = document.createElement("div");
  line.className = "quarto-title-meta-line site-meta";
  line.innerHTML = html;
  meta.insertBefore(line, meta.firstChild);
});
</script>

<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Where this page comes from
</div>
</div>
<div class="callout-body-container callout-body">
<p>The rest of this section follows the Flower short course. This page draws on a separate university lecture in the reference library, which spends its closing third on the challenges of federated learning rather than on building a system that works. That is a useful counterweight, because a course that only shows the happy path leaves you unprepared for the first time a federated run does something strange.</p>
<p>The lab builds federated averaging from scratch in PyTorch, following a tutorial notebook from the same lecture. Every other lab in this section uses <a href="https://flower.ai/">Flower</a>, which is the right way to do this in practice. Writing the loop by hand once is worth it anyway, because when a run misbehaves you want to know what the framework is doing on your behalf.</p>
</div>
</div>
<p>Every page in this section so far has quietly assumed something that is almost never true. This page is about what happens when that assumption breaks, which in production is most of the time.</p>
<p>The assumption is about how data is spread across clients. When you <a href="../../../ai/machine-learning/federated-learning/why-federated-learning#lab-what-missing-data-does-to-a-model">split MNIST three ways</a> or <a href="../../../ai/machine-learning/federated-learning/how-federated-learning-works#lab-federating-the-mnist-experiment">federate it with Flower</a>, the arrangement is tidy. Real federations are not tidy, and the untidiness has a name, a mechanism, and a family of algorithms invented to deal with it.</p>
<section id="independent-and-identically-distributed-data" class="level2">
<h2 class="anchored" data-anchor-id="independent-and-identically-distributed-data">Independent and Identically Distributed Data</h2>
<p>Ordinary machine learning rests on an assumption so routine that most courses state it once and never mention it again. Training examples are assumed to be <strong>i.i.d.</strong>, meaning <strong>independent and identically distributed</strong>. Independent says that knowing one example tells you nothing about the next. Identically distributed says that every example is drawn from the same underlying population.</p>
<p>Centralized training gets close to this for free. You collect everything into one pile and draw batches from it at random. Random mixing does not conjure genuine independence out of biased or duplicated data, and it cannot make two different populations into one. What it does buy is the part stochastic gradient descent actually leans on. Each batch looks statistically like the pooled dataset, so the gradient computed on one batch is a reasonable estimate of the gradient on all of it.</p>
<p>Federated learning cannot pool, and so it cannot mix <strong>across clients</strong>. Note the precision there, because a federated client shuffles its own data perfectly happily, and the lab below does exactly that inside <code>local_update</code>. What no participant can do is shuffle examples across the boundary between one client and another, because that would mean moving raw data off the device, which was the entire point of not doing it. Whatever grouping the world imposed between clients is the grouping you are stuck with.</p>
<p>That grouping is usually not random, because data lands on a device for a reason. Your phone’s photo library reflects your life. A hospital’s scans reflect its specialty and the population it serves. A regional bank’s transactions reflect one country’s spending habits and one country’s fraud patterns. In the language of the field, the clients hold <strong>non-i.i.d.</strong> data, and the general condition is called <strong>data heterogeneity</strong>.</p>
<section id="ways-data-can-be-non-i.i.d." class="level3">
<h3 class="anchored" data-anchor-id="ways-data-can-be-non-i.i.d.">Ways Data Can Be Non-i.i.d.</h3>
<p>The single label “non-i.i.d.” covers several distinct problems that behave differently, and it is worth separating them.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Kind of skew</th>
<th style="text-align: left;">What differs between clients</th>
<th style="text-align: left;">Example</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Label skew</strong></td>
<td style="text-align: left;">Which classes appear, and in what proportion</td>
<td style="text-align: left;">One hospital sees mostly fractures, another mostly tumors</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Quantity skew</strong></td>
<td style="text-align: left;">How much data each client holds</td>
<td style="text-align: left;">One phone has 50 photos, another has 12,000</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Feature skew</strong></td>
<td style="text-align: left;">How the same class looks</td>
<td style="text-align: left;">The digit 7 written with and without a crossbar</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Concept shift</strong></td>
<td style="text-align: left;">What the label means for the same features</td>
<td style="text-align: left;">“Expensive” for a house in one city and another</td>
</tr>
</tbody>
</table>
<p>A note on the last row, because the terminology trips people up. <strong>Concept shift</strong> is what is described here, a disagreement between clients at the same moment about what a label means. <strong>Concept drift</strong> is a different thing, the same distribution changing over time, and the two get used interchangeably far more often than they should.</p>
<p>Label skew is the kind most heavily studied and the kind the lab below demonstrates, and it is the one that damages federated averaging most reliably. It is not automatically the worst in every setting. Which kind hurts most depends on the task, the model, and how clients are sampled, and severe feature or concept shift can do more harm than mild label skew.</p>
</section>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. What does random batching actually buy centralized training, and why can federated learning not get it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It does not manufacture genuine independence, and it cannot merge two different populations into one. What it buys is the one property stochastic gradient descent actually leans on. Drawing batches at random from a single pool makes each batch resemble the pooled dataset, so a gradient computed on one batch is a reasonable estimate of the gradient on all of it. Federated learning cannot pool, so it cannot mix examples <strong>across</strong> clients, although each client shuffles its own data freely. Whatever grouping exists between clients in the world is the grouping the algorithm is stuck with, and in a real federation it is rarely random. A simulation like the lab below can of course deal the data out at random, which is exactly what makes it a useful baseline rather than a realistic one.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Give an example of label skew and an example of feature skew in the same federation.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>In a federation of hospitals, <strong>label skew</strong> would be an orthopedic center holding mostly fracture cases while a cancer center holds mostly tumor cases, so the classes appear in very different proportions. <strong>Feature skew</strong> would be the same condition looking different across sites because the hospitals use scanners from different manufacturers with different resolutions and contrast.</p>
</div>
</div>
</div>
</section>
</section>
<section id="client-drift" class="level2">
<h2 class="anchored" data-anchor-id="client-drift">Client Drift</h2>
<p>Here is the mechanism, and it follows from one detail of federated averaging that looks harmless.</p>
<p>In each round, a client does not take one gradient step. It runs <strong>several local epochs</strong> of training before sending anything back, which is precisely what makes federated learning affordable, since a round trip over the network costs far more than a few passes over local data.</p>
<p>Now put those two facts together. Each client trains for a while on data drawn from its own skewed distribution. Training for a while means moving toward the minimum of <em>its</em> loss surface, not the global one. A client holding only 3s and 8s does not drift a little toward a model that prefers 3s and 8s. Given enough local steps, it walks a long way toward a model that predicts almost nothing else, because on its data that model is correct.</p>
<p>Every selected client does this at once, in a different direction. The server then averages the results. This divergence of the local models during a round, and the fact that their average is not where any of them was heading, is called <strong>client drift</strong>.</p>
<p>Two consequences follow. The second is directly visible in the lab below. The first is the standard explanation for it, and note that this lab does not evaluate the individual local models, so it does not demonstrate that part on its own.</p>
<ul>
<li><strong>Averaging parameters is not averaging behavior.</strong> The map from a network’s parameters to the function it computes is nonlinear, so the parameters halfway between two networks do not give you a model halfway between their behaviors. Add that the loss surface is not convex, which removes any guarantee that the midpoint is a low-loss point at all, and two networks that each solve their own task well can average into one that does neither. Note that this is a possibility rather than a rule. The midpoint <em>can</em> be bad, not that it generally is.</li>
<li><strong>Progress becomes non-monotonic.</strong> Accuracy stops climbing steadily and starts lurching, sometimes falling sharply from one round to the next. On an i.i.d. split the curve is smooth. On a badly skewed one it looks like it is being knocked around.</li>
</ul>
<p>There is a lever you already have. The <a href="../../../ai/machine-learning/federated-learning/tuning-federated-learning-systems#client-configuration">client configuration</a> sent by the server controls how many local epochs each client runs, and that number is the drift dial. More local epochs mean fewer expensive rounds and more drift per round. Fewer local epochs mean less drift and more communication. Under heterogeneity this trade stops being a pure efficiency question and becomes a correctness question.</p>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. Explain client drift in terms of local epochs.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A client runs several local epochs before reporting back, so it moves a long way toward the minimum of <strong>its own</strong> loss surface rather than taking one small step toward the global one. When each selected client does this on differently skewed data, the local models diverge, and their average is not where any of them was heading. More local epochs per round means more drift.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why can averaging two well-performing local models produce a worse global model?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the map from parameters to behavior is nonlinear, so parameters halfway between two models do not produce behavior halfway between them. On top of that the loss surface is not convex, which removes any guarantee that the midpoint is a low-loss point. Neither fact says the midpoint is <em>usually</em> bad, only that nothing prevents it from being bad, and under heavy skew it often is.</p>
</div>
</div>
</div>
</section>
</section>
<section id="lab-federated-averaging-from-scratch" class="level2">
<h2 class="anchored" data-anchor-id="lab-federated-averaging-from-scratch">Lab: Federated Averaging from Scratch</h2>
<p>Everything above is a claim. This lab builds federated averaging by hand, with no framework, and then runs it on three different splits so the claims can be checked against numbers.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>Six changes from the source notebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>This lab follows a PyTorch federated learning tutorial from the reference library. It runs on PyTorch 2.13.0 and torchvision 0.28.0, and six things changed (updated 2026-09-01).</p>
<ul>
<li><strong>The loss pairing was tidied, though it was not a bug.</strong> The notebook’s model ends in <code>F.log_softmax</code> and its criterion is <code>nn.CrossEntropyLoss</code>, which applies a log-softmax of its own. That looks like a double application, and it is worth knowing why it is harmless. Log-softmax is <strong>idempotent</strong>, meaning applying it to something already log-softmaxed returns the input unchanged, so the two losses agree to floating-point precision and produce identical gradients. This lab uses <code>nn.NLLLoss</code>, which is the honest partner for a model returning log probabilities, but the change is readability rather than correctness. The notebook trains exactly as fast either way.</li>
<li><strong>Shard apportionment is now exact.</strong> The notebook rounds each client’s share of the shards independently, so the total can drift off the 1,200 available. Depending on the seed that either strands shards or silently truncates the last clients. This lab uses largest-remainder apportionment and asserts that every split is a genuine partition of all 60,000 images.</li>
<li><strong>Averaging is now weighted by client dataset size.</strong> The notebook’s <code>average_weights</code> takes a plain unweighted mean, which does not match federated averaging as published, where each client’s contribution is weighted by how much data it holds. Since the notebook’s own non-i.i.d. splitter gives clients wildly unequal amounts, the difference is real. Both versions are implemented here and compared.</li>
<li><strong><code>dataset.train_labels</code> was replaced with <code>dataset.targets</code>.</strong> The old attribute was removed from torchvision.</li>
<li><strong>The device is chosen at runtime.</strong> The notebook hardcodes <code>cuda</code>. This page renders on a machine without a GPU.</li>
<li><strong>Test accuracy is measured every round.</strong> The notebook tracks only training loss, which cannot show client drift. Drift is a statement about the global model, so the global model has to be evaluated.</li>
</ul>
<p>The split functions, the CNN architecture, the local client update loop, and the structure of the server loop are the notebook’s own.</p>
</div>
</div>
<section id="setup" class="level3">
<h3 class="anchored" data-anchor-id="setup">Setup</h3>
<p>MNIST is loaded exactly as the earlier labs in this section load it, from a local <code>MNIST_data/</code> cache. The four raw archives are also <a href="../../../media/machine-learning/federated-learning/mnist/train-images-idx3-ubyte.gz">hosted on this site</a> if you would rather populate that cache by hand than let torchvision fetch them. The accuracies printed below came from a CPU run, and a different device or a different PyTorch build can move the exact figures even with the seeds fixed.</p>
<div id="2e2138cb" class="cell" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> copy</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn <span class="im">as</span> nn</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torch.utils.data <span class="im">import</span> DataLoader, Subset</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> torchvision <span class="im">import</span> datasets, transforms</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>device <span class="op">=</span> torch.device(<span class="st">"cuda"</span> <span class="cf">if</span> torch.cuda.is_available() <span class="cf">else</span> <span class="st">"cpu"</span>)</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>transform <span class="op">=</span> transforms.Compose([</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    transforms.ToTensor(),</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    transforms.Normalize((<span class="fl">0.1307</span>,), (<span class="fl">0.3081</span>,)),</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>])</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>trainset <span class="op">=</span> datasets.MNIST(<span class="st">"./MNIST_data/"</span>, train<span class="op">=</span><span class="va">True</span>, download<span class="op">=</span><span class="va">True</span>, transform<span class="op">=</span>transform)</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>testset <span class="op">=</span> datasets.MNIST(<span class="st">"./MNIST_data/"</span>, train<span class="op">=</span><span class="va">False</span>, download<span class="op">=</span><span class="va">True</span>, transform<span class="op">=</span>transform)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>LABELS <span class="op">=</span> trainset.targets.numpy()</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>NUM_CLIENTS <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"device: </span><span class="sc">{</span>device<span class="sc">}</span><span class="ss">, train: </span><span class="sc">{</span><span class="bu">len</span>(trainset)<span class="sc">}</span><span class="ss">, test: </span><span class="sc">{</span><span class="bu">len</span>(testset)<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>device: cpu, train: 60000, test: 10000</code></pre>
</div>
</div>
</section>
<section id="splitting-the-data-three-ways" class="level3">
<h3 class="anchored" data-anchor-id="splitting-the-data-three-ways">Splitting the Data Three Ways</h3>
<p>A federated experiment needs a rule for deciding which training examples belong to which client. That rule is the experiment. Three of them are built here.</p>
<p>The <strong>i.i.d.</strong> split is the easy case and the one to measure everything else against. Shuffle all 60,000 images and deal them out like cards, so every client gets 600 images covering all ten digits in roughly the proportions of the full dataset.</p>
<div id="ecb0888a" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> iid_split(n_clients, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Shuffle everything and deal it out. Every client looks like every other."""</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    idx <span class="op">=</span> rng.permutation(<span class="bu">len</span>(trainset))</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {i: idx[i::n_clients] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_clients)}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <strong>pathological</strong> split is the standard worst case from the federated learning literature. Sort the entire dataset by digit, cut the sorted run into 200 contiguous shards, and give each client 2 shards at random. Because the data was sorted first, a shard is nearly all one digit, so a client ends up holding one to three digits and nothing else.</p>
<div id="37ab75f2" class="cell" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> pathological_split(n_clients, shards_per_client<span class="op">=</span><span class="dv">2</span>, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Sort by label, cut into shards, give each client a couple of shards.</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Sorting first is what makes a shard nearly pure, and purity is the point."""</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    num_shards <span class="op">=</span> n_clients <span class="op">*</span> shards_per_client</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    shard_size <span class="op">=</span> <span class="bu">len</span>(trainset) <span class="op">//</span> num_shards</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(LABELS, kind<span class="op">=</span><span class="st">"stable"</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>    pool <span class="op">=</span> rng.permutation(num_shards)</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> {</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>        i: np.concatenate([</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>            order[s <span class="op">*</span> shard_size:(s <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> shard_size]</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>            <span class="cf">for</span> s <span class="kw">in</span> pool[i <span class="op">*</span> shards_per_client:(i <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> shards_per_client]</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>        ])</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_clients)</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    }</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The <strong>unequal</strong> split is the notebook’s own, and it adds quantity skew on top of label skew. The sorted data is cut into 1,200 small shards, and each client is given a random number of them between 1 and 30, so client sizes range from about 50 images to well over 1,000.</p>
<div id="0bc3be1c" class="cell" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> unequal_split(n_clients, seed<span class="op">=</span><span class="dv">0</span>, num_shards<span class="op">=</span><span class="dv">1200</span>, shard_size<span class="op">=</span><span class="dv">50</span>,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>                  min_shards<span class="op">=</span><span class="dv">1</span>, max_shards<span class="op">=</span><span class="dv">30</span>):</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Label skew with quantity skew on top, so clients differ in how much</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co">    data they hold as well as which digits."""</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> np.argsort(LABELS, kind<span class="op">=</span><span class="st">"stable"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Draw a rough size per client, then apportion the shards exactly.</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Rounding each share independently would let the total drift off 1200,</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># which either strands shards or silently starves the last clients.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> num_shards <span class="op">&gt;=</span> n_clients, <span class="st">"every client needs at least one shard"</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    raw <span class="op">=</span> rng.integers(min_shards, max_shards <span class="op">+</span> <span class="dv">1</span>, size<span class="op">=</span>n_clients).astype(<span class="bu">float</span>)</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    share <span class="op">=</span> raw <span class="op">/</span> raw.<span class="bu">sum</span>() <span class="op">*</span> num_shards</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    sizes <span class="op">=</span> np.maximum(<span class="dv">1</span>, np.floor(share).astype(<span class="bu">int</span>))</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    residual <span class="op">=</span> num_shards <span class="op">-</span> sizes.<span class="bu">sum</span>()</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> residual <span class="op">&gt;</span> <span class="dv">0</span>:</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Largest remainder: the leftover shards go to the biggest fractions.</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> i <span class="kw">in</span> np.argsort(<span class="op">-</span>(share <span class="op">-</span> np.floor(share)))[:residual]:</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>            sizes[i] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> residual <span class="op">&lt;</span> <span class="dv">0</span>:</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>        <span class="co"># The minimum-of-one floor overshot. Take the excess back from the</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># largest clients, never dropping anyone below one shard. Guarding the</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>        <span class="co"># sign matters: a negative count in a slice would silently index from</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>        <span class="co"># the end and increment almost everybody.</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(<span class="op">-</span>residual):</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>            eligible <span class="op">=</span> np.where(sizes <span class="op">&gt;</span> <span class="dv">1</span>)[<span class="dv">0</span>]</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a>            sizes[eligible[np.argmax(sizes[eligible])]] <span class="op">-=</span> <span class="dv">1</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> sizes.<span class="bu">sum</span>() <span class="op">==</span> num_shards <span class="kw">and</span> sizes.<span class="bu">min</span>() <span class="op">&gt;=</span> <span class="dv">1</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>    pool <span class="op">=</span> <span class="bu">list</span>(rng.permutation(num_shards))</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>    groups <span class="op">=</span> {}</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(n_clients):</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>        picked <span class="op">=</span> [pool.pop() <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(sizes[i])]</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a>        groups[i] <span class="op">=</span> np.concatenate([order[s <span class="op">*</span> shard_size:(s <span class="op">+</span> <span class="dv">1</span>) <span class="op">*</span> shard_size]</span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a>                                    <span class="cf">for</span> s <span class="kw">in</span> picked])</span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> <span class="kw">not</span> pool, <span class="st">"every shard must be assigned"</span></span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> groups</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>groups_iid <span class="op">=</span> iid_split(NUM_CLIENTS)</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>groups_path <span class="op">=</span> pathological_split(NUM_CLIENTS)</span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>groups_uneq <span class="op">=</span> unequal_split(NUM_CLIENTS)</span>
<span id="cb5-44"><a href="#cb5-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-45"><a href="#cb5-45" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, g <span class="kw">in</span> [(<span class="st">"i.i.d."</span>, groups_iid), (<span class="st">"pathological"</span>, groups_path),</span>
<span id="cb5-46"><a href="#cb5-46" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"unequal"</span>, groups_uneq)]:</span>
<span id="cb5-47"><a href="#cb5-47" aria-hidden="true" tabindex="-1"></a>    sizes <span class="op">=</span> [<span class="bu">len</span>(g[i]) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(NUM_CLIENTS)]</span>
<span id="cb5-48"><a href="#cb5-48" aria-hidden="true" tabindex="-1"></a>    digits <span class="op">=</span> [<span class="bu">len</span>(<span class="bu">set</span>(LABELS[g[i]].tolist())) <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(NUM_CLIENTS) <span class="cf">if</span> <span class="bu">len</span>(g[i])]</span>
<span id="cb5-49"><a href="#cb5-49" aria-hidden="true" tabindex="-1"></a>    assigned <span class="op">=</span> np.concatenate([g[i] <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(NUM_CLIENTS) <span class="cf">if</span> <span class="bu">len</span>(g[i])])</span>
<span id="cb5-50"><a href="#cb5-50" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Every split must be a genuine partition: all 60,000 images, none twice.</span></span>
<span id="cb5-51"><a href="#cb5-51" aria-hidden="true" tabindex="-1"></a>    <span class="cf">assert</span> <span class="bu">len</span>(assigned) <span class="op">==</span> <span class="bu">len</span>(np.unique(assigned)) <span class="op">==</span> <span class="bu">len</span>(trainset)</span>
<span id="cb5-52"><a href="#cb5-52" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&gt;13}</span><span class="ss">: sizes </span><span class="sc">{</span><span class="bu">min</span>(sizes)<span class="sc">:&gt;4}</span><span class="ss"> to </span><span class="sc">{</span><span class="bu">max</span>(sizes)<span class="sc">:&gt;5}</span><span class="ss">,  "</span></span>
<span id="cb5-53"><a href="#cb5-53" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"distinct digits per client </span><span class="sc">{</span><span class="bu">min</span>(digits)<span class="sc">:&gt;2}</span><span class="ss"> to </span><span class="sc">{</span><span class="bu">max</span>(digits)<span class="sc">:&gt;2}</span><span class="ss">,  "</span></span>
<span id="cb5-54"><a href="#cb5-54" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"total </span><span class="sc">{</span><span class="bu">len</span>(assigned)<span class="sc">}</span><span class="ss">, all distinct"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       i.i.d.: sizes  600 to   600,  distinct digits per client 10 to 10,  total 60000, all distinct
 pathological: sizes  600 to   600,  distinct digits per client  1 to  3,  total 60000, all distinct
      unequal: sizes   50 to  1150,  distinct digits per client  1 to 10,  total 60000, all distinct</code></pre>
</div>
</div>
<p>Read that output before going further, because it is the whole experiment in three lines. Under the i.i.d. split every client holds all ten digits. Under the pathological split a client holds one to three, and note that every client still holds exactly 600 images, which is deliberate. Holding the quantity fixed means any damage that split does is attributable to label skew alone. The unequal split then adds quantity skew on top, with client sizes running from 50 to 1,150, a factor of twenty-three.</p>
<p>Seeing it directly is more convincing than the summary.</p>
<div id="bf2c4c5c" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data-heterogeneity-and-client-drift_files/figure-html/cell-6-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>How many examples of each digit the first twenty clients hold, under each split</figcaption>
</figure>
</div>
</div>
</div>
<p>The left panel is a flat wash, since every client holds a bit of everything. The middle panel is almost entirely white with one to three dark cells per row, and each row is a client that has never seen most of the ten digits. The right panel adds rows of visibly different intensity, which is the quantity skew.</p>
</section>
<section id="model-and-the-local-client-loop" class="level3">
<h3 class="anchored" data-anchor-id="model-and-the-local-client-loop">Model and the Local Client Loop</h3>
<p>The model is the notebook’s small convolutional network. Nothing about it is special, and that is deliberate, since any effect seen here is a property of the federation rather than of the architecture.</p>
<div id="9f78c65b" class="cell" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">class</span> CNN(nn.Module):</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> <span class="fu">__init__</span>(<span class="va">self</span>):</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>        <span class="bu">super</span>().<span class="fu">__init__</span>()</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv1 <span class="op">=</span> nn.Conv2d(<span class="dv">1</span>, <span class="dv">10</span>, kernel_size<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.conv2 <span class="op">=</span> nn.Conv2d(<span class="dv">10</span>, <span class="dv">20</span>, kernel_size<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc1 <span class="op">=</span> nn.Linear(<span class="dv">320</span>, <span class="dv">50</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>        <span class="va">self</span>.fc2 <span class="op">=</span> nn.Linear(<span class="dv">50</span>, <span class="dv">10</span>)</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">def</span> forward(<span class="va">self</span>, x):</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(F.max_pool2d(<span class="va">self</span>.conv1(x), <span class="dv">2</span>))</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(F.max_pool2d(<span class="va">self</span>.conv2(x), <span class="dv">2</span>))</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> x.flatten(<span class="dv">1</span>)</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> F.relu(<span class="va">self</span>.fc1(x))</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span> F.log_softmax(<span class="va">self</span>.fc2(x), dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co"># The model returns log probabilities, so NLLLoss is the matching API.</span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co"># The notebook's CrossEntropyLoss pairing applies log-softmax a second time,</span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co"># which is harmless because the operation is idempotent. Same gradients,</span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co"># same speed. This is a readability change, not a fix.</span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>criterion <span class="op">=</span> nn.NLLLoss()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Now the client side. This function is what runs on a phone or inside a hospital. It receives a copy of the current global model, trains it on data the server will never see, and hands back the updated parameters together with a count of how many examples it used.</p>
<p>That count is not bookkeeping. It is what makes the server’s average correct.</p>
<div id="4b202899" class="cell" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> local_update(model, idxs, local_epochs<span class="op">=</span><span class="dv">5</span>, batch_size<span class="op">=</span><span class="dv">128</span>, lr<span class="op">=</span><span class="fl">0.01</span>):</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""One client's share of a round. Returns updated weights and the</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">    number of examples they were computed from."""</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>    loader <span class="op">=</span> DataLoader(Subset(trainset, idxs), batch_size<span class="op">=</span>batch_size, shuffle<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    optimizer <span class="op">=</span> torch.optim.SGD(model.parameters(), lr<span class="op">=</span>lr)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    model.train()</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(local_epochs):</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> images, labels <span class="kw">in</span> loader:</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>            images, labels <span class="op">=</span> images.to(device), labels.to(device)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>            optimizer.zero_grad()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>            loss <span class="op">=</span> criterion(model(images), labels)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>            loss.backward()</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>            optimizer.step()</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> model.state_dict(), <span class="bu">len</span>(idxs)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note the <code>local_epochs=5</code>. Five full passes over local data happen before anything is reported. That parameter is the drift dial from the previous section.</p>
</section>
<section id="server-loop" class="level3">
<h3 class="anchored" data-anchor-id="server-loop">Server Loop</h3>
<p>The server does three things. It picks clients, it waits, and it averages. The averaging is the only interesting part.</p>
<div id="07fce809" class="cell" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> average_weights(weights, counts<span class="op">=</span><span class="va">None</span>):</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Federated averaging. With counts, each client is weighted by how much</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co">    data it trained on, which is FedAvg as published. Without counts, every</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">    client counts equally, which is what the source notebook does."""</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> counts <span class="kw">is</span> <span class="va">None</span>:</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>        counts <span class="op">=</span> [<span class="dv">1</span>] <span class="op">*</span> <span class="bu">len</span>(weights)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> <span class="bu">sum</span>(counts)</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    avg <span class="op">=</span> copy.deepcopy(weights[<span class="dv">0</span>])</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> key <span class="kw">in</span> avg.keys():</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Every entry in this model's state dict is floating point. A model with</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>        <span class="co"># batch normalization also carries an integer `num_batches_tracked`</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>        <span class="co"># buffer, which must not be averaged this way; adapt with care.</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>        avg[key] <span class="op">=</span> <span class="bu">sum</span>(w[key].<span class="bu">float</span>() <span class="op">*</span> n <span class="cf">for</span> w, n <span class="kw">in</span> <span class="bu">zip</span>(weights, counts)) <span class="op">/</span> total</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> avg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The difference between those two branches is worth pausing on. Suppose a round selects one client holding 1,200 images and another holding 50. A plain mean gives the 50-image client equal say, so a model shaped by 50 examples carries the same weight as one shaped by twenty-four times as much evidence. Weighting by count restores the balance, and it is what makes the round optimize the sample-weighted objective that federated averaging is defined against, where every training example counts once regardless of which client holds it.</p>
<p>It is tempting to go one step further and say this makes a federated round equivalent to one large batch spread across machines. Resist that. The equivalence would hold if each client took a single weighted gradient step from the shared starting point. After five local epochs each client has followed its own nonlinear trajectory, and the gap between those trajectories is precisely the thing this page is about.</p>
<div id="a1bc0da7" class="cell" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="at">@torch.no_grad</span>()</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> evaluate(model):</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Accuracy of the global model on the full MNIST test set."""</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    model.<span class="bu">eval</span>()</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    correct <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> images, labels <span class="kw">in</span> DataLoader(testset, batch_size<span class="op">=</span><span class="dv">2000</span>):</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>        images, labels <span class="op">=</span> images.to(device), labels.to(device)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>        correct <span class="op">+=</span> (model(images).argmax(<span class="dv">1</span>) <span class="op">==</span> labels).<span class="bu">sum</span>().item()</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> correct <span class="op">/</span> <span class="bu">len</span>(testset)</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> run_federated(groups, rounds<span class="op">=</span><span class="dv">15</span>, fraction<span class="op">=</span><span class="fl">0.05</span>, weighted<span class="op">=</span><span class="va">True</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>                  local_epochs<span class="op">=</span><span class="dv">5</span>, seed<span class="op">=</span><span class="dv">1</span>):</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""The whole algorithm. Select, broadcast, train locally, aggregate, repeat."""</span></span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>    torch.manual_seed(seed)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>    rng <span class="op">=</span> np.random.default_rng(seed)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>    n_clients <span class="op">=</span> <span class="bu">len</span>(groups)</span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>    global_model <span class="op">=</span> CNN().to(device)</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>    history <span class="op">=</span> []</span>
<span id="cb10-20"><a href="#cb10-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-21"><a href="#cb10-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(rounds):</span>
<span id="cb10-22"><a href="#cb10-22" aria-hidden="true" tabindex="-1"></a>        n_selected <span class="op">=</span> <span class="bu">max</span>(<span class="dv">1</span>, <span class="bu">int</span>(fraction <span class="op">*</span> n_clients))</span>
<span id="cb10-23"><a href="#cb10-23" aria-hidden="true" tabindex="-1"></a>        selected <span class="op">=</span> rng.choice(n_clients, n_selected, replace<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb10-24"><a href="#cb10-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-25"><a href="#cb10-25" aria-hidden="true" tabindex="-1"></a>        local_weights, local_counts <span class="op">=</span> [], []</span>
<span id="cb10-26"><a href="#cb10-26" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> client <span class="kw">in</span> selected:</span>
<span id="cb10-27"><a href="#cb10-27" aria-hidden="true" tabindex="-1"></a>            <span class="cf">if</span> <span class="bu">len</span>(groups[client]) <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb10-28"><a href="#cb10-28" aria-hidden="true" tabindex="-1"></a>                <span class="cf">continue</span></span>
<span id="cb10-29"><a href="#cb10-29" aria-hidden="true" tabindex="-1"></a>            <span class="co"># Each client starts from a copy of the current global model.</span></span>
<span id="cb10-30"><a href="#cb10-30" aria-hidden="true" tabindex="-1"></a>            w, n <span class="op">=</span> local_update(copy.deepcopy(global_model), groups[client],</span>
<span id="cb10-31"><a href="#cb10-31" aria-hidden="true" tabindex="-1"></a>                                local_epochs<span class="op">=</span>local_epochs)</span>
<span id="cb10-32"><a href="#cb10-32" aria-hidden="true" tabindex="-1"></a>            local_weights.append(w)</span>
<span id="cb10-33"><a href="#cb10-33" aria-hidden="true" tabindex="-1"></a>            local_counts.append(n)</span>
<span id="cb10-34"><a href="#cb10-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-35"><a href="#cb10-35" aria-hidden="true" tabindex="-1"></a>        global_model.load_state_dict(</span>
<span id="cb10-36"><a href="#cb10-36" aria-hidden="true" tabindex="-1"></a>            average_weights(local_weights, local_counts <span class="cf">if</span> weighted <span class="cf">else</span> <span class="va">None</span>))</span>
<span id="cb10-37"><a href="#cb10-37" aria-hidden="true" tabindex="-1"></a>        history.append(evaluate(global_model))</span>
<span id="cb10-38"><a href="#cb10-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-39"><a href="#cb10-39" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> history</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>That is the core of federated learning in about twenty lines. What Flower adds in the other labs of this section is everything around it, including parameter serialization, network transport, orchestration of clients that come and go, failure handling, and metrics collection. That surrounding machinery is most of the engineering, which is exactly why you should use a framework in practice. The algorithm itself is what is above.</p>
</section>
<section id="watching-drift-happen" class="level3">
<h3 class="anchored" data-anchor-id="watching-drift-happen">Watching Drift Happen</h3>
<p>Three runs, identical in every respect except how the data was split.</p>
<div id="65c29239" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>history_iid <span class="op">=</span> run_federated(groups_iid)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>history_path <span class="op">=</span> run_federated(groups_path)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>history_uneq <span class="op">=</span> run_federated(groups_uneq)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'round'</span><span class="sc">:&gt;6}{</span><span class="st">'i.i.d.'</span><span class="sc">:&gt;10}{</span><span class="st">'pathological'</span><span class="sc">:&gt;14}{</span><span class="st">'unequal'</span><span class="sc">:&gt;10}</span><span class="ss">"</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r, (a, b, c) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(history_iid, history_path, history_uneq), <span class="dv">1</span>):</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:&gt;6}{</span>a<span class="sc">:&gt;10.3f}{</span>b<span class="sc">:&gt;14.3f}{</span>c<span class="sc">:&gt;10.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> round    i.i.d.  pathological   unequal
     1     0.119         0.101     0.137
     2     0.183         0.191     0.151
     3     0.371         0.235     0.294
     4     0.515         0.239     0.573
     5     0.521         0.339     0.658
     6     0.642         0.209     0.680
     7     0.750         0.237     0.772
     8     0.793         0.385     0.683
     9     0.830         0.350     0.799
    10     0.839         0.558     0.826
    11     0.860         0.325     0.803
    12     0.870         0.433     0.855
    13     0.878         0.476     0.859
    14     0.885         0.494     0.859
    15     0.883         0.641     0.845</code></pre>
</div>
</div>
<div id="867271ab" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data-heterogeneity-and-client-drift_files/figure-html/cell-12-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Global model accuracy per round under three data splits, with everything else held identical</figcaption>
</figure>
</div>
</div>
</div>
<p>The green i.i.d. curve is what a healthy federated run looks like. It climbs steadily, and the only time it moves backwards at all is two thousandths at the final round, which is noise rather than a trend.</p>
<p>The red pathological curve is the one to study. From round 3 onward it sits far below the others, and more tellingly it does not climb monotonically. Watch it gain ground and then lose it, most starkly from 0.558 at round 10 down to 0.325 at round 11. The likely story is that a round whose five selected clients hold complementary digits averages into something reasonable, and the next round, whose clients overlap or cover a narrow set, averages into something much worse.</p>
<p>That is an explanation rather than a measurement, and it is worth flagging as such. Two effects could produce this curve, and the next section separates them.</p>
<p>The orange unequal curve is the surprise, and it is worth not glossing over. It does not sit neatly between the other two. It tracks the i.i.d. run closely and at several rounds it is actually <strong>ahead</strong>, reaching 0.658 at round 5 where the i.i.d. run is at 0.521. It does finish behind, 0.845 against 0.883, a gap of about four percentage points. The point is the shape rather than the endpoint. This split wobbles, but it never collapses the way the red one does.</p>
<p>The honest reading is that this split is not skewed enough to hurt much. Its clients hold up to ten digits each, so the shards they were dealt happen to cover the label space reasonably well.</p>
<p>Be careful not to over-read it. This split varies label skew and quantity skew together, so it cannot tell you that quantity skew on its own is mild. Isolating that would need a split with equal label coverage and unequal sizes, which this experiment does not include. What the run does support is narrower and still useful. A split that looks visibly non-i.i.d. on a distribution plot trained almost as well as a clean one, at this seed and this configuration. Heterogeneity is a spectrum rather than a switch, the catastrophe in the red curve needs label skew taken to an extreme, and measuring where your own data sits between those two cases is worth doing before reaching for a fancier algorithm.</p>
</section>
<section id="separating-drift-from-sampling-luck" class="level3">
<h3 class="anchored" data-anchor-id="separating-drift-from-sampling-luck">Separating Drift from Sampling Luck</h3>
<p>The red curve is dramatic, but on its own it does not prove what caused it. Two different things could produce that lurching, and they are easy to confuse.</p>
<p>The first is <strong>client drift</strong>, the effect this page is about, which needs multiple local epochs to build up. The second is <strong>partial participation</strong>. Only five of the hundred clients take part in each round, and under the pathological split each holds one to three digits, so which five get drawn changes what the round can possibly learn. That would knock the curve around even if every client took a single tiny step.</p>
<p>The two are separable by experiment. Run the same pathological split again with <code>local_epochs=1</code> instead of 5. Partial participation is unchanged, since the selection is identical. Only the distance each client travels before reporting is reduced.</p>
<div id="dcabf916" class="cell" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>history_path_e1 <span class="op">=</span> run_federated(groups_path, local_epochs<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'round'</span><span class="sc">:&gt;6}{</span><span class="st">'E = 5'</span><span class="sc">:&gt;9}{</span><span class="st">'E = 1'</span><span class="sc">:&gt;9}</span><span class="ss">"</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r, (a, b) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(history_path, history_path_e1), <span class="dv">1</span>):</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:&gt;6}{</span>a<span class="sc">:&gt;9.3f}{</span>b<span class="sc">:&gt;9.3f}</span><span class="ss">"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> wobble(h):</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Mean size of a round-to-round change, and the worst single drop."""</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>    d <span class="op">=</span> np.diff(h)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">float</span>(np.<span class="bu">abs</span>(d).mean()), <span class="bu">float</span>(d.<span class="bu">min</span>())</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, h <span class="kw">in</span> [(<span class="st">"pathological, E = 5"</span>, history_path),</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"pathological, E = 1"</span>, history_path_e1),</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>                (<span class="st">"i.i.d., E = 5"</span>, history_iid)]:</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    m, worst <span class="op">=</span> wobble(h)</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">:&gt;22}</span><span class="ss">: mean absolute change </span><span class="sc">{</span>m<span class="sc">:.3f}</span><span class="ss">, worst single-round drop </span><span class="sc">{</span>worst<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> round    E = 5    E = 1
     1    0.101    0.114
     2    0.191    0.168
     3    0.235    0.119
     4    0.239    0.160
     5    0.339    0.170
     6    0.209    0.101
     7    0.237    0.142
     8    0.385    0.226
     9    0.350    0.118
    10    0.558    0.176
    11    0.325    0.188
    12    0.433    0.191
    13    0.476    0.172
    14    0.494    0.216
    15    0.641    0.295
   pathological, E = 5: mean absolute change 0.095, worst single-round drop -0.233
   pathological, E = 1: mean absolute change 0.048, worst single-round drop -0.108
         i.i.d., E = 5: mean absolute change 0.055, worst single-round drop -0.002</code></pre>
</div>
</div>
<div id="75286755" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="data-heterogeneity-and-client-drift_files/figure-html/cell-14-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>The pathological split run with five local epochs and with one, holding client selection identical</figcaption>
</figure>
</div>
</div>
</div>
<p>The result leans toward the drift explanation, and the useful number is the worst single-round drop rather than the average movement.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Run</th>
<th style="text-align: right;">Mean absolute change per round</th>
<th style="text-align: right;">Worst single-round drop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pathological, 5 local epochs</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;"><strong>-0.233</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Pathological, 1 local epoch</td>
<td style="text-align: right;">0.048</td>
<td style="text-align: right;">-0.108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">i.i.d., 5 local epochs</td>
<td style="text-align: right;">0.055</td>
<td style="text-align: right;">-0.002</td>
</tr>
</tbody>
</table>
<p>Holding client selection identical and cutting local epochs from five to one roughly halves the round-to-round movement and cuts the worst collapse from 23 percentage points to 11. More local training went with more volatility, which is what the drift story predicts.</p>
<p>Now the caveats, because this experiment is weaker than it first looks and it is worth being precise about why.</p>
<ul>
<li><strong>One epoch is not one step.</strong> A pathological client holds 600 examples at batch size 128, so even a single epoch is five sequential optimizer steps. The <code>E = 1</code> run still contains drift. It contains less of it, not none.</li>
<li><strong>Two things changed, not one.</strong> Cutting epochs reduces both how far a client travels and how much total optimization happens per round. The lower accuracy of the <code>E = 1</code> run is the second effect, and the two cannot be untangled from this comparison alone.</li>
<li><strong>Minibatch order is not matched.</strong> <code>DataLoader</code> shuffles from the global torch generator, so the two runs consume different numbers of random permutations and their per-client batch orders diverge after the first client. Client <em>selection</em> is identical, but the stochasticity inside local training is not.</li>
</ul>
<p>So the residual 11-point drop at <code>E = 1</code> is not cleanly “the sampling effect”. It is a mixture of partial participation, the drift that one epoch still produces, and ordinary SGD noise. Reading it as a decomposition would be over-claiming.</p>
<p>What the run does support is narrower. At this seed, with client selection held fixed, adding local training amplified volatility, and the i.i.d. run at the same five epochs never dropped more than two thousandths. That is consistent with drift and inconsistent with sampling being the whole story. A clean separation would need matched per-client randomness, a single-full-batch-step baseline, or a direct measurement of how far the local models diverge from each other within a round. None of those is done here.</p>
<p>The cost side is unambiguous. The one-epoch run ends at 0.295 against 0.641 for five epochs. Smoother, and far less learned, because it did a fifth of the local work across the same number of expensive rounds. That is the communication trade from the previous section, priced.</p>
</section>
<section id="does-weighting-actually-matter" class="level3">
<h3 class="anchored" data-anchor-id="does-weighting-actually-matter">Does Weighting Actually Matter?</h3>
<p>The unequal split is the one where weighting by dataset size should matter, since that is the split with clients of very different sizes. The weighted run above is already available, so only the plain-mean version needs computing.</p>
<div id="492c6d97" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>history_uneq_plain <span class="op">=</span> run_federated(groups_uneq, weighted<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'round'</span><span class="sc">:&gt;6}{</span><span class="st">'weighted'</span><span class="sc">:&gt;11}{</span><span class="st">'plain mean'</span><span class="sc">:&gt;13}</span><span class="ss">"</span>)</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> r, (a, b) <span class="kw">in</span> <span class="bu">enumerate</span>(<span class="bu">zip</span>(history_uneq, history_uneq_plain), <span class="dv">1</span>):</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>r<span class="sc">:&gt;6}{</span>a<span class="sc">:&gt;11.3f}{</span>b<span class="sc">:&gt;13.3f}</span><span class="ss">"</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="ch">\n</span><span class="ss">final weighted:   </span><span class="sc">{</span>history_uneq[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"final plain mean: </span><span class="sc">{</span>history_uneq_plain[<span class="op">-</span><span class="dv">1</span>]<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean over last 5 rounds, weighted:   </span><span class="sc">{</span>np<span class="sc">.</span>mean(history_uneq[<span class="op">-</span><span class="dv">5</span>:])<span class="sc">:.3f}</span><span class="ss">"</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"mean over last 5 rounds, plain mean: </span><span class="sc">{</span>np<span class="sc">.</span>mean(history_uneq_plain[<span class="op">-</span><span class="dv">5</span>:])<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> round   weighted   plain mean
     1      0.137        0.126
     2      0.151        0.278
     3      0.294        0.264
     4      0.573        0.498
     5      0.658        0.572
     6      0.680        0.641
     7      0.772        0.697
     8      0.683        0.668
     9      0.799        0.778
    10      0.826        0.813
    11      0.803        0.786
    12      0.855        0.822
    13      0.859        0.784
    14      0.859        0.859
    15      0.845        0.808

final weighted:   0.845
final plain mean: 0.808
mean over last 5 rounds, weighted:   0.844
mean over last 5 rounds, plain mean: 0.812</code></pre>
</div>
</div>
<p>Weighting wins, and the evidence is better than a single endpoint comparison would suggest. It is ahead in 13 of the 15 rounds, not just at the finish, and averaged over the last five rounds the gap is about three percentage points. A consistent lead across rounds is harder to explain by luck than one lucky final round would be.</p>
<p>It is still one seed. The 15 rounds are successive states of a single run rather than 15 independent trials, so a consistent lead across them is weaker evidence than 13 independent wins would be, and confirming the direction properly would mean repeating across several seeds.</p>
<p>The practical conclusion does not rest on the measurement. Weighting by example count is what federated averaging is defined to do, it makes the round optimize the objective in which every example counts once, and it costs one integer per client per round. Use it because it is the algorithm, and treat this run as an illustration rather than as the reason.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. In the pathological split, why does test accuracy sometimes fall from one round to the next?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because only five of the hundred clients are selected per round, and each holds one to three digits. Which five get picked decides what the round can learn. A draw of clients covering complementary digits averages into something reasonable, and the next draw, whose clients overlap or cover a narrow set, averages into something worse. The algorithm did not change between those rounds, only the sample of clients did, and under heavy skew that sample dominates the result.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why does the client return a count of examples along with its weights?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>So the server can weight each client’s contribution by how much data it was computed from, which is federated averaging as published. Without it, a model trained on 50 examples counts as much as one trained on 1,200, and under quantity skew that systematically distorts the global model.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. If you cut <code>local_epochs</code> from 5 to 1, what would you expect to happen to the pathological curve, and what would it cost?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Drift would fall, because each client would move a much shorter distance toward its own local optimum before reporting, so the models being averaged would be closer together and the curve would be smoother. The cost is communication. You would need many more rounds to reach the same accuracy, and each round is a full model broadcast and upload, which is exactly the <a href="../../../ai/machine-learning/federated-learning/bandwidth-in-federated-learning">bandwidth</a> the section spends a page on. The <a href="#separating-drift-from-sampling-luck">control experiment</a> above runs exactly this comparison and finds both halves of the prediction, a smoother curve and a much lower final accuracy, though it also explains why that comparison is not a clean decomposition.</p>
</div>
</div>
</div>
</section>
</section>
<section id="variants-that-fix-it" class="level2">
<h2 class="anchored" data-anchor-id="variants-that-fix-it">Variants That Fix It</h2>
<p>Client drift is not a fact you have to live with. It is the problem a whole line of research set out to solve, and understanding why each variant exists is more useful than memorizing what it does.</p>
<p>All of them keep the federated structure of the round that <a href="https://arxiv.org/abs/1602.05629">McMahan et al.&nbsp;(2016)</a> introduced. The client still trains locally, the server still aggregates. What changes is either what the client is allowed to optimize or what the server does with what comes back.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Algorithm</th>
<th style="text-align: left;">The fix</th>
<th style="text-align: left;">Where it acts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>FedProx</strong></td>
<td style="text-align: left;">Adds a penalty that discourages the local model from moving far from the global one</td>
<td style="text-align: left;">Client</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>SCAFFOLD</strong></td>
<td style="text-align: left;">Estimates each client’s drift direction and corrects local steps by it</td>
<td style="text-align: left;">Client and server</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>FedAvgM</strong></td>
<td style="text-align: left;">Applies momentum on the server, smoothing round-to-round lurching</td>
<td style="text-align: left;">Server</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>FedAdam, FedYogi, FedAdagrad</strong></td>
<td style="text-align: left;">Treats the aggregate update as a gradient and applies an adaptive optimizer</td>
<td style="text-align: left;">Server</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>FedGMA</strong></td>
<td style="text-align: left;">Masks coordinates of the aggregate update where clients disagree in sign</td>
<td style="text-align: left;">Server</td>
</tr>
</tbody>
</table>
<p>Two families are visible in that table. None of them eliminates drift, so read all of these as mitigations rather than cures.</p>
<p><strong>Client-side methods reduce how much drift is produced.</strong> <a href="https://arxiv.org/abs/1812.06127">Li et al.&nbsp;(2018)</a> proposed <strong>FedProx</strong>, which adds a proximal term to the local loss that grows with the distance between the local model and the global one it started from. It is a soft penalty, so it discourages wandering rather than preventing it, and the strength of the discouragement is a hyperparameter. <a href="https://arxiv.org/abs/1910.06378">Karimireddy et al.&nbsp;(2019)</a> proposed <strong>SCAFFOLD</strong>, which maintains <strong>control variates</strong>, running estimates of the direction in which a client’s gradients differ from the average, and subtracts that estimate from each local step. It is listed as client and server because it keeps control state in both places and ships it alongside the model, which is where its extra bandwidth and storage cost comes from.</p>
<p><strong>Server-side methods absorb drift after it arrives.</strong> <a href="https://arxiv.org/abs/1909.06335">Hsu et al.&nbsp;(2019)</a> proposed <strong>FedAvgM</strong>, on the observation that if the aggregated update lurches from round to round, momentum is the classic cure for a lurching update, so apply it at the server. <a href="https://arxiv.org/abs/2003.00295">Reddi et al.&nbsp;(2020)</a> generalized this into <strong>adaptive federated optimization</strong>, reinterpreting the difference between the old and new global model as a pseudo-gradient and feeding it to Adam, Yogi, or Adagrad. The reinterpretation is the clever part, because every adaptive optimizer ever written for centralized training becomes available for free. <a href="https://arxiv.org/abs/2201.11986">Tenison et al.&nbsp;(2022)</a> proposed <strong>FedGMA</strong>, which keeps a coordinate of the aggregated update only where a sufficient share of clients agree on its sign, on the theory that disagreement across clients signals client-specific noise rather than shared structure.</p>
<p>Whether any of them helps on a given federation is an empirical question. <a href="https://arxiv.org/abs/1806.00582">Zhao et al.&nbsp;(2018)</a> is the standard reference for how sharply accuracy degrades as skew increases, and it is worth reading before assuming a variant will rescue a badly skewed setup.</p>
<p>You do not implement these by hand. The <a href="../../../ai/machine-learning/federated-learning/tuning-federated-learning-systems#aggregation">tuning page</a> mentioned that aggregation is a swappable component, and this is what fills that slot. In Flower, moving from FedAvg to FedAdam means handing the server a different strategy object, and nothing else in the system moves.</p>
<p>That cheapness is specific to the server-side family, which is worth remembering when planning a change. FedProx and SCAFFOLD alter what the client computes, so adopting either means shipping new client code and, for SCAFFOLD, new state to store and transmit. On a federation of five hospitals that is a meeting. On a federation of ten million phones it is a release cycle, and it is why the server-side options get tried first far more often than their published results alone would justify.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Which one to reach for
</div>
</div>
<div class="callout-body-container callout-body">
<p>Try weighted FedAvg first and measure. Heterogeneity is a spectrum, and plenty of real federations are skewed enough to mention and not skewed enough to need anything fancy.</p>
<p>If the accuracy curve wobbles, a server-side fix is the cheaper experiment, because it changes one object on the server and requires nothing new from the clients. If the wobble persists and you control the client software, FedProx is the next step, since it adds one term to the local loss. Reach for SCAFFOLD when drift is severe and you can afford the extra per-client state and bandwidth.</p>
</div>
</div>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. What is the practical difference between a client-side fix such as FedProx and a server-side fix such as FedAdam?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A client-side fix changes what the client optimizes, so it reduces how much drift is produced, but it requires deploying new code to every participating device. A server-side fix changes only how the server combines what comes back, absorbing some of the drift after the fact, and can be swapped without touching the clients at all. That deployment asymmetry usually makes a server-side fix the cheaper thing to try first. Neither family eliminates drift.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What does it mean to call the difference between the old and new global model a “pseudo-gradient”, and why is that reframing useful?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It means treating the aggregated client update as if it were a gradient step the server is taking, even though it was produced by many clients running many local steps rather than by differentiating a loss. It is useful because it turns the server into an ordinary optimization loop, so any optimizer built for centralized training, including Adam, Yogi, and Adagrad, can be dropped straight in.</p>
</div>
</div>
</div>
</section>
</section>
<section id="other-challenges" class="level2">
<h2 class="anchored" data-anchor-id="other-challenges">Other Challenges</h2>
<p>Heterogeneity is the largest of the open problems but not the only one. Three others round out the picture, and each connects to a page elsewhere in this section.</p>
<p><strong>Communication overhead.</strong> Every round ships a full model down and a full update back. With frequent rounds and a large model this dominates the cost of the whole system, and high network latency slows every round to the speed of its slowest participant. This is what <a href="../../../ai/machine-learning/federated-learning/bandwidth-in-federated-learning">bandwidth in federated learning</a> is about, and it interacts directly with drift, since the obvious fix for drift is more rounds and the obvious fix for bandwidth is fewer.</p>
<p><strong>Privacy and security.</strong> Model updates still leak information about the data that produced them, which is why <a href="../../../ai/machine-learning/federated-learning/data-privacy-in-federated-learning">data privacy in federated learning</a> exists as a page. Beyond leakage there is active malice. Because the server cannot see client data, it cannot easily tell a client with unusual data from a client that is lying, and a <strong>poisoning attack</strong> exploits exactly that, submitting crafted updates to degrade the global model or plant a backdoor. Heterogeneity makes this harder to defend, since the natural defense is to reject updates that look like outliers, and under genuine heterogeneity honest clients produce outlying updates all the time.</p>
<p><strong>Regulatory compliance and accountability.</strong> Federated learning is often adopted because of data protection regulation such as the GDPR in Europe or PIPEDA in Canada, and keeping data on the device helps considerably. <a href="https://doi.org/10.1038/s41746-020-00323-1">Rieke et al.&nbsp;(2020)</a> survey what this looks like in healthcare specifically, where the regulatory pressure is heaviest and the incentive to collaborate across institutions is strongest. It does not settle everything on its own, because the model updates that do travel may still carry personal information, which is one reason differential privacy gets layered on top. Separately, in finance, healthcare, and autonomous driving, a model has to be explainable and auditable, and a model assembled from updates contributed by many parties that nobody can inspect is a harder thing to account for than one trained on a dataset you hold.</p>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Why does data heterogeneity make poisoning attacks harder to defend against?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The natural defense is to reject updates that look like statistical outliers. Under genuine heterogeneity, honest clients legitimately produce outlying updates all the time, because their data really is different. Any filter aggressive enough to catch attackers also discards the contributions of unusual but honest clients, which is the exact data the federation existed to reach.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Reducing local epochs helps with drift. Why is it not a free fix?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because it buys accuracy with communication. Fewer local epochs means less progress per round, so many more rounds are needed, and every round costs a full model broadcast and a full update upload. The two main costs of a federated system pull in opposite directions here.</p>
</div>
</div>
</div>
</section>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<ul>
<li>Hsu, T.-M. H., Qi, H., &amp; Brown, M. (2019). <em>Measuring the effects of non-identical data distribution for federated visual classification</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1909.06335" class="uri">https://doi.org/10.48550/arXiv.1909.06335</a></li>
<li>Karimireddy, S. P., Kale, S., Mohri, M., Reddi, S. J., Stich, S. U., &amp; Suresh, A. T. (2019). <em>SCAFFOLD: Stochastic controlled averaging for federated learning</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1910.06378" class="uri">https://doi.org/10.48550/arXiv.1910.06378</a></li>
<li>Li, T., Sahu, A. K., Zaheer, M., Sanjabi, M., Talwalkar, A., &amp; Smith, V. (2018). <em>Federated optimization in heterogeneous networks</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1812.06127" class="uri">https://doi.org/10.48550/arXiv.1812.06127</a></li>
<li>McMahan, H. B., Moore, E., Ramage, D., Hampson, S., &amp; Agüera y Arcas, B. (2016). <em>Communication-efficient learning of deep networks from decentralized data</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1602.05629" class="uri">https://doi.org/10.48550/arXiv.1602.05629</a></li>
<li>Reddi, S., Charles, Z., Zaheer, M., Garrett, Z., Rush, K., Konečný, J., et al.&nbsp;(2020). <em>Adaptive federated optimization</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.2003.00295" class="uri">https://doi.org/10.48550/arXiv.2003.00295</a></li>
<li>Rieke, N., Hancox, J., Li, W., Milletarì, F., Roth, H. R., Albarqouni, S., et al.&nbsp;(2020). The future of digital health with federated learning. <em>npj Digital Medicine, 3</em>, 119. <a href="https://doi.org/10.1038/s41746-020-00323-1" class="uri">https://doi.org/10.1038/s41746-020-00323-1</a></li>
<li>Tenison, I., Sreeramadas, S. A., Mugunthan, V., Oyallon, E., Rish, I., &amp; Belilovsky, E. (2022). <em>Gradient masked averaging for federated learning</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.2201.11986" class="uri">https://doi.org/10.48550/arXiv.2201.11986</a></li>
<li>Zhao, Y., Li, M., Lai, L., Suda, N., Civin, D., &amp; Chandra, V. (2018). <em>Federated learning with non-IID data</em>. arXiv. <a href="https://doi.org/10.48550/arXiv.1806.00582" class="uri">https://doi.org/10.48550/arXiv.1806.00582</a></li>
</ul>


<div id="section-progress-widget" class="section-progress-widget" hidden="">
  <p class="section-progress-label">Progress through this page</p>
  <progress class="section-progress" value="100" max="100" aria-label="100 percent through this page"></progress>
  <p class="section-progress-detail">100% (374 of 374 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.hidden = false; sb.appendChild(w); }
});
</script>

</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://oliabak.com/giscus-theme-dark.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      if (authorPrefersDark) {
          [baseTheme, altTheme] = [altTheme, baseTheme];
      }
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../../ai/machine-learning/federated-learning/bandwidth-in-federated-learning" class="pagination-link" aria-label="Bandwidth in Federated Learning">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Bandwidth in Federated Learning</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>H’s Notes</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../../../about">
<p>About</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/dashboard">
<p>Dashboard</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../../../about/roadmap">
<p>Roadmap</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>