<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Eigenvalues and Eigenvectors – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./media/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="./math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="./ai/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/machine-learning/index.html">
 <span class="dropdown-text">Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/deep-learning/index.html">
 <span class="dropdown-text">Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/agentic/index.html">
 <span class="dropdown-text">Agentic AI</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="./networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="./tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="./about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#important-note" id="toc-important-note" class="nav-link active" data-scroll-target="#important-note">Important Note</a></li>
  <li><a href="#table-of-contents" id="toc-table-of-contents" class="nav-link" data-scroll-target="#table-of-contents">Table of Contents</a>
  <ul class="collapse">
  <li><a href="#packages" id="toc-packages" class="nav-link" data-scroll-target="#packages">Packages</a>
  <ul class="collapse">
  <li><a href="#exercise-4" id="toc-exercise-4" class="nav-link" data-scroll-target="#exercise-4">Exercise 4</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Eigenvalues and Eigenvectors</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~26 min read</p></div>';
    meta.appendChild(div);
  }
});
</script>

<p>Welcome to the last assignment of this course and congratulations for making it this far. In this final assignment you will use your knowledge of linear algebra and your skills using Python and NumPy to address some real-world scenarios where linear algebra is actually used to solve and simplify problems.</p>
<p><strong>After this assignment you will be able to:</strong> - apply linear transformations, eigenvalues and eigenvectors in a webpage navigation model - apply PCA on a dataset to reduce its dimensions</p>
<section id="important-note" class="level2">
<h2 class="anchored" data-anchor-id="important-note">Important Note</h2>
<p>Please <strong>do not</strong> delete any exercise cells or add your solutions in different cells. <strong>Keep your solution in the original cell provided</strong>; failing to do so will disrupt the autograder.</p>
<p>Additionally, <strong>do not import any new libraries</strong>, and <strong>avoid importing libraries within any cell designated for grading</strong>, as this will also interfere with the autograder’s functionality.</p>
</section>
<section id="table-of-contents" class="level1">
<h1>Table of Contents</h1>
<ul>
<li><a href="#1">1 - Application of Eigenvalues and Eigenvectors: Navigating Webpages</a>
<ul>
<li><a href="#ex01">Exercise 1</a></li>
<li><a href="#ex02">Exercise 2</a></li>
</ul></li>
<li><a href="#2">2 - Application of Eigenvalues and Eigenvectors: Principal Component Analysis</a>
<ul>
<li><a href="#2.1">2.1 Load the data</a></li>
<li><a href="#2.2">2.2 Get the covariance matrix</a>
<ul>
<li><a href="#ex03">Exercise 3</a></li>
<li><a href="#ex04">Exercise 4</a></li>
</ul></li>
<li><a href="#2.3">2.3 - Compute the eigenvalues and eigenvectors</a></li>
<li><a href="#2.4">2.4 Transform the centered data with PCA</a>
<ul>
<li><a href="#ex05">Exercise 5</a></li>
</ul></li>
<li><a href="#2.5">2.5 Analyzing the dimensionality reduction in 2 dimensions</a></li>
<li><a href="#2.6">2.6 Reconstructing the images from the eigenvectors</a></li>
<li><a href="#2.7">2.7 Explained variance</a></li>
</ul></li>
</ul>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Run the following cell to load the packages you’ll need.</p>
<div id="cell-5" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> scipy.sparse.linalg</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Load the utils module and the unit tests defined for this notebook.</p>
<div id="cell-7" class="cell" data-tags="[]" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> utils</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> w4_unittest</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><a name="1"></a> ## 1 - Application of Eigenvalues and Eigenvectors: Navigating Webpages</p>
<p>As you learned in the lectures, eigenvalues and eigenvectors play a very important role in what’s called (discrete) dynamical systems. As you might recall, a <strong>discrete dynamical system</strong> describes a system where, as time goes by, the state changes according to some process. When defining this dynamical systems you could represent all the possible states, such as sunny, rainy or cloudy, in a vector called the <strong>state vector</strong>.</p>
<p>Each discrete dynamical system can be represented by a transition matrix <span class="math inline">\(P\)</span>, which indicates, given a particular state, what are the chances or probabilities of moving to each of the other states. This means the element <span class="math inline">\((2,1)\)</span> of the matrix represents the probability of transitioning from state <span class="math inline">\(1\)</span> to state <span class="math inline">\(2\)</span>.</p>
<p>Starting with an initial state <span class="math inline">\(X_0\)</span>, the transition to the next state <span class="math inline">\(X_1\)</span> is a linear transformation defined by the transition matrix <span class="math inline">\(P\)</span>: <span class="math inline">\(X_1=PX_0\)</span>. That leads to <span class="math inline">\(X_2=PX_1=P^2X_0\)</span>, <span class="math inline">\(X_3=P^3X_0\)</span>, and so on. This implies that <span class="math inline">\(X_t=PX_{t-1}\)</span> for <span class="math inline">\(t=0,1,2,3,\ldots\)</span>. In other words, we can keep multiplying by <code>P</code> to move from one state to the next.</p>
<p>One application of discrete dynamical systems is to model browsing web pages. Web pages often contain links to other pages, so the dynamical system would model how a user goes from one page to another by hopping from link to link. For simplicity, assume that the browser is only following links to a new page rather than navigating to an unlinked one.</p>
<p>In this case, the state vector <span class="math inline">\(X_t\)</span> will be the probabilities that the browser is on a particular page at time <span class="math inline">\(t\)</span>. Navigation from one page to another advances the model from one state vector <span class="math inline">\(X_{t-1}\)</span> to another state vector <span class="math inline">\(X_t\)</span>. A linear transformation, defined by a matrix <span class="math inline">\(P\)</span>, will have entries <span class="math inline">\(p_{ij}\)</span> with the probabilities that the browser navigates to page <span class="math inline">\(j\)</span> from page <span class="math inline">\(i\)</span>. For fixed column <span class="math inline">\(j\)</span>, the entries represent a probability distribution describing location of the browser at the next step, given that you are at state <span class="math inline">\(j\)</span>. Thus, the entries in each column must add to 1.</p>
<p><a name="ex01"></a> ### Exercise 1</p>
<p>For the sake of the example, consider there are only a small number of pages <span class="math inline">\(n=5\)</span>. This means that the transition matrix <span class="math inline">\(P\)</span> will be a <span class="math inline">\(5 \times 5\)</span> matrix. In this particular case, all elements on the main diagonal should be equal to <span class="math inline">\(0\)</span>, since we are making the reasonable assumption that there is no existing link to the current page. Also, as metioned before, all the entries in each column must add to one. Here is an example of such a matrix for <span class="math inline">\(n=5\)</span>:</p>
<p><span class="math display">\[P=
\begin{bmatrix}
0    &amp; 0.75 &amp; 0.35 &amp; 0.25 &amp; 0.85 \\
0.15 &amp; 0    &amp; 0.35 &amp; 0.25 &amp; 0.05 \\
0.15 &amp; 0.15 &amp; 0    &amp; 0.25 &amp; 0.05 \\
0.15 &amp; 0.05 &amp; 0.05 &amp; 0    &amp; 0.05 \\
0.55 &amp; 0.05 &amp; 0.25 &amp; 0.25 &amp; 0
\end{bmatrix}\tag{5}
\]</span></p>
<p>Define vector <span class="math inline">\(X_0\)</span>, so the browser starts navigation at page <span class="math inline">\(4\)</span> (<span class="math inline">\(X_0\)</span> is a vector with a single entry equal to one, and all other entries equal to zero). Apply the transformation once: <span class="math inline">\(X_1=PX_0\)</span> to find a vector of the probabilities that the browser is at each of four pages.</p>
<div id="cell-10" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>P <span class="op">=</span> np.array([ </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>    [<span class="dv">0</span>, <span class="fl">0.75</span>, <span class="fl">0.35</span>, <span class="fl">0.25</span>, <span class="fl">0.85</span>], </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.15</span>, <span class="dv">0</span>, <span class="fl">0.35</span>, <span class="fl">0.25</span>, <span class="fl">0.05</span>], </span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.15</span>, <span class="fl">0.15</span>, <span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.05</span>], </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.15</span>, <span class="fl">0.05</span>, <span class="fl">0.05</span>, <span class="dv">0</span>, <span class="fl">0.05</span>], </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    [<span class="fl">0.55</span>, <span class="fl">0.05</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>, <span class="dv">0</span>]  </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>]) </span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>X0 <span class="op">=</span> np.array([[<span class="dv">0</span>],[<span class="dv">0</span>],[<span class="dv">0</span>],[<span class="dv">1</span>],[<span class="dv">0</span>]])</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="co">### START CODE HERE </span><span class="al">###</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Multiply matrix P and X_0 (matrix multiplication).</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>X1 <span class="op">=</span> P <span class="op">@</span> X0</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a><span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Sum of columns of P: </span><span class="sc">{</span><span class="bu">sum</span>(P)<span class="sc">}</span><span class="ss">'</span>)</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'X1:</span><span class="ch">\n</span><span class="sc">{</span>X1<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Sum of columns of P: [1. 1. 1. 1. 1.]
X1:
[[0.25]
 [0.25]
 [0.25]
 [0.  ]
 [0.25]]</code></pre>
</div>
</div>
<section id="expected-output" class="level5">
<h5 class="anchored" data-anchor-id="expected-output"><strong>Expected Output</strong></h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Sum of columns of P: [<span class="fl">1.</span> <span class="fl">1.</span> <span class="fl">1.</span> <span class="fl">1.</span> <span class="fl">1.</span>]</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>X1:</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>[[<span class="fl">0.25</span>]</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a> [<span class="fl">0.25</span>]</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a> [<span class="fl">0.25</span>]</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a> [<span class="fl">0.</span>  ]</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a> [<span class="fl">0.25</span>]]</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="cell-12" class="cell" data-editable="false" data-tags="[]" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test your solution.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>w4_unittest.test_matrix(P, X0, X1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>Applying the transformation <span class="math inline">\(m\)</span> times you can find a vector <span class="math inline">\(X_m\)</span> with the probabilities of the browser being at each of the pages after <span class="math inline">\(m\)</span> steps of navigation.</p>
<div id="cell-14" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="7">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> np.array([[<span class="dv">0</span>],[<span class="dv">0</span>],[<span class="dv">0</span>],[<span class="dv">1</span>],[<span class="dv">0</span>]])</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>m <span class="op">=</span> <span class="dv">20</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> t <span class="kw">in</span> <span class="bu">range</span>(m):</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> P <span class="op">@</span> X</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(X)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[0.39392366]
 [0.13392366]
 [0.11407667]
 [0.0850993 ]
 [0.27297672]]</code></pre>
</div>
</div>
<p>It is useful to predict the probabilities in <span class="math inline">\(X_m\)</span> when <span class="math inline">\(m\)</span> is large, and thus determine what pages a browser is more likely to visit after a long period of browsing the web. In other words, we want to know which pages ultimately get the most traffic. One way to do that is just apply the transformation many times, and with this small <span class="math inline">\(5 \times 5\)</span> example you can do that just fine. In real life problems, however, you’ll have enormous matrices and doing so will be computationally expensive. Here is where eigenvalues and eigenvectors can help here significantly reducing the amount of calculations. Let’s see how!</p>
<p>Begin by finding eigenvalues and eigenvectors for the previously defined matrix <span class="math inline">\(P\)</span>:</p>
<div id="cell-17" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>eigenvals, eigenvecs <span class="op">=</span> np.linalg.eig(P)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Eigenvalues of P:</span><span class="ch">\n</span><span class="sc">{</span>eigenvals<span class="sc">}</span><span class="ch">\n\n</span><span class="ss">Eigenvectors of P</span><span class="ch">\n</span><span class="sc">{</span>eigenvecs<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Eigenvalues of P:
[ 1.         -0.70367062  0.00539505 -0.08267227 -0.21905217]

Eigenvectors of P
[[-0.76088562 -0.81362074  0.10935376  0.14270615 -0.39408574]
 [-0.25879453  0.050269   -0.6653158   0.67528802 -0.66465044]
 [-0.2204546   0.07869601 -0.29090665  0.17007443  0.35048734]
 [-0.1644783   0.12446953  0.19740707 -0.43678067  0.23311487]
 [-0.52766004  0.56018621  0.64946163 -0.55128793  0.47513398]]</code></pre>
</div>
</div>
<p>As you can see, there is one eigenvalue with value <span class="math inline">\(1\)</span>, and the other four have an aboslute values smaller than 1. It turns out this is a property of transition matrices. In fact, they have so many properties that these types of matrices fall into a category of matrices called <strong>Markov matrix</strong>.</p>
<p>In general, a square matrix whose entries are all nonnegative, and the sum of the elements for each column is equal to <span class="math inline">\(1\)</span> is called a <strong>Markov matrix</strong>. Markov matrices have a handy property - they always have an eigenvalue equal to 1. As you learned in the lectures, in the case of transition matrices, the eigenvector associated with the eigenvalue <span class="math inline">\(1\)</span> will determine the state of the model in the long run , after evolving for a long period of time.</p>
<p>You can easily verify that the matrix <span class="math inline">\(P\)</span> you defined earlier is in fact a Markov matrix. So, if <span class="math inline">\(m\)</span> is large enough, the equation <span class="math inline">\(X_m=PX_{m-1}\)</span> can be rewritten as <span class="math inline">\(X_m=PX_{m-1}=1\times X_m\)</span>. This means that predicting probabilities at time <span class="math inline">\(m\)</span>, when <span class="math inline">\(m\)</span> is large you can simply just look for an eigenvector corresponding to the eigenvalue <span class="math inline">\(1\)</span>.</p>
<p>So, let’s extract the eigenvector associated to the eigenvalue <span class="math inline">\(1\)</span>.</p>
<div id="cell-19" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>X_inf <span class="op">=</span> eigenvecs[:,<span class="dv">0</span>]</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Eigenvector corresponding to the eigenvalue 1:</span><span class="ch">\n</span><span class="sc">{</span>X_inf[:,np.newaxis]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Eigenvector corresponding to the eigenvalue 1:
[[-0.76088562]
 [-0.25879453]
 [-0.2204546 ]
 [-0.1644783 ]
 [-0.52766004]]</code></pre>
</div>
</div>
<p><a name="ex02"></a> ### Exercise 2</p>
<p>Just to verify the results, perform matrix multiplication <span class="math inline">\(PX\)</span> (multiply matrix <code>P</code> and vector <code>X_inf</code>) to check that the result will be equal to the vector <span class="math inline">\(X\)</span> (<code>X_inf</code>).</p>
<div id="cell-21" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is organised as a function only for grading purposes.</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> check_eigenvector(P, X_inf):</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">### START CODE HERE </span><span class="al">###</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>    X_check <span class="op">=</span> P <span class="op">@</span> X_inf</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X_check</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>X_check <span class="op">=</span> check_eigenvector(P, X_inf)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Original eigenvector corresponding to the eigenvalue 1:</span><span class="ch">\n</span><span class="st">"</span> <span class="op">+</span> <span class="bu">str</span>(X_inf))</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Result of multiplication:"</span> <span class="op">+</span> <span class="bu">str</span>(X_check))</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Function np.isclose compares two NumPy arrays element by element, allowing for error tolerance (rtol parameter).</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Check that PX=X element by element:"</span> <span class="op">+</span> <span class="bu">str</span>(np.isclose(X_inf, X_check, rtol<span class="op">=</span><span class="fl">1e-10</span>)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Original eigenvector corresponding to the eigenvalue 1:
[-0.76088562 -0.25879453 -0.2204546  -0.1644783  -0.52766004]
Result of multiplication:[-0.76088562 -0.25879453 -0.2204546  -0.1644783  -0.52766004]
Check that PX=X element by element:[ True  True  True  True  True]</code></pre>
</div>
</div>
<div id="cell-22" class="cell" data-editable="false" data-tags="[]" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test your solution.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>w4_unittest.test_check_eigenvector(check_eigenvector)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>This result gives the direction of the eigenvector, but as you can see the entries can’t be interpreted as probabilities since you have negative values, and they don’t add to 1. That’s no problem. Remember that by convention <code>np.eig</code> returns eigenvectors with norm 1, but actually any vector on the same line is also an eigenvector to the eigenvalue 1, so you can simply scale the vector so that all entries are positive and add to one.This will give you the long-run probabilities of landing on a given web page.</p>
<div id="cell-24" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>X_inf <span class="op">=</span> X_inf<span class="op">/</span><span class="bu">sum</span>(X_inf)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"Long-run probabilities of being at each webpage:</span><span class="ch">\n</span><span class="sc">{</span>X_inf[:,np.newaxis]<span class="sc">}</span><span class="ss">"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Long-run probabilities of being at each webpage:
[[0.39377747]
 [0.13393269]
 [0.11409081]
 [0.08512166]
 [0.27307736]]</code></pre>
</div>
</div>
<p>This means that after navigating the web for a long time, the probability that the browser is at page 1 is 0.394, of being on page 2 is 0.134, on page 3 0.114, on page 4 0.085, and finally page 5 has a probability of 0.273.</p>
<p>Looking at this result you can conclude that page 1 is the most likely for the browser to be at, while page 4 is the least probable one.</p>
<p>If you compare the result of <code>X_inf</code> with the one you got after evolving the systems 20 times, they are the same up to the third decimal!</p>
<p>Here is a fun fact: this type of a model was the foundation of the PageRank algorithm, which is the basis of Google’s very successful search engine.</p>
<p><a name="2"></a> ## 2 - Application of Eigenvalues and Eigenvectors: Principal Component Analysis</p>
<p>As you learned in the lectures, one of the useful applications of eigenvalues and eigenvectors is the dimensionality reduction algorithm called Principal Component Analyisis, or PCA for short.</p>
<p>In this second section of the assignment you will be applying PCA on an image dataset to perform image compression.</p>
<p>You will be using a portion of the <a href="https://www.kaggle.com/datasets/alessiosanna/cat-dog-64x64-pixel/data">Cat and dog face</a> dataset from Kaggle. In particular, you will be using the cat images.</p>
<p>Remember that to apply PCA on any dataset you will begin by defining the covariance matrix. After that you will compute the eigenvalues and eigenvectors of this covariance matrix. Each of these eigenvectors will be a <strong>principal component</strong>. To perform the dimensionality reduction, you will take the <span class="math inline">\(k\)</span> principal components associated to the <span class="math inline">\(k\)</span> biggest eigenvalues, and transform the original data by projecting it onto the direction of these principal components (eigenvectors).</p>
<p><a name="2.1"></a> ### 2.1 - Load the data Begin by loading the images and transforming them to black and white using <code>load_images</code> function from utils.</p>
<div id="cell-27" class="cell" data-tags="[]" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>imgs <span class="op">=</span> utils.load_images(<span class="st">'./data/'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><code>imgs</code> should be a list, where each element of the list is an array (matrix). Let’s check it out</p>
<div id="cell-29" class="cell" data-tags="[]" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>height, width <span class="op">=</span> imgs[<span class="dv">0</span>].shape</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'</span><span class="ch">\n</span><span class="ss">Your dataset has </span><span class="sc">{</span><span class="bu">len</span>(imgs)<span class="sc">}</span><span class="ss"> images of size </span><span class="sc">{</span>height<span class="sc">}</span><span class="ss">x</span><span class="sc">{</span>width<span class="sc">}</span><span class="ss"> pixels</span><span class="ch">\n</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Your dataset has 55 images of size 64x64 pixels
</code></pre>
</div>
</div>
<p>Go ahead and plot one image to see what they look like. You can use the colormap ‘gray’ to plot in black and white. Feel free to look into as many pictures as you want.</p>
<div id="cell-31" class="cell" data-tags="[]" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>plt.imshow(imgs[<span class="dv">0</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>When working with images, you can consider each pixel as a variable. Having each image in matrix form is good for visualizing the image, but not so much for operating on each variable.</p>
<p>In order to apply PCA for dimensionality reduction you will need to flatten each image into a single row vector. You can do this using the <code>reshape</code> function from NumPy.</p>
<p>The resulting array will have 55 rows, one for each image, and 64x64=4096 columns.</p>
<div id="cell-33" class="cell" data-tags="[]" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>imgs_flatten <span class="op">=</span> np.array([im.reshape(<span class="op">-</span><span class="dv">1</span>) <span class="cf">for</span> im <span class="kw">in</span> imgs])</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'imgs_flatten shape: </span><span class="sc">{</span>imgs_flatten<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>imgs_flatten shape: (55, 4096)</code></pre>
</div>
</div>
<p><a name="2.2"></a> ## 2.2 - Get the covariance matrix</p>
<p>Now that you have the images in the correct shape you are ready to apply PCA on the flattened dataset.</p>
<p>If you consider each pixel (column) as a variable, and each image (rows) as an obervation you will have 55 observations of 4096 variables, <span class="math inline">\(X_1, X_2, \ldots, X_{4096}\)</span> so that <span class="math display">\[\mathrm{imgs\_flatten} = \begin{bmatrix} x_{1,1} &amp; x_{1,2} &amp; \ldots &amp; x_{1,4096}\\
                                           x_{2,1} &amp; x_{2,2} &amp; \ldots &amp; x_{2,4096} \\
                                           \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
                                           x_{55,1} &amp; x_{55,2} &amp; \ldots &amp; x_{55,4096}\end{bmatrix}\]</span></p>
<p>As you might remember from the lectures, to compute PCA you first need to find the covariance matrix</p>
<p><span class="math display">\[\Sigma = \begin{bmatrix}Var(X_1) &amp; Cov(X_1, X_2) &amp; \ldots &amp; Cov(X_1, X_{4096}) \\
                          Cov(X_1, X_2) &amp; Var(X_2) &amp; \ldots &amp; Cov(X_2, X_{4096})\\
                          \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
                          Cov(X_1,X_{4096}) &amp; Cov(X_2, X_{4096}) &amp;\ldots &amp; Var(X_{4096})\end{bmatrix}\]</span></p>
<p><a name="ex03"></a> ### Exercise 3</p>
<p>In order to get the covariance matrix you first need to center the data by subtracting the mean for each variable (column).</p>
<p>As you’ve seen in the lectures, the centered data matrix looks something like this:</p>
<p><span class="math display">\[X = \begin{bmatrix} (x_{1,1}- \mu_1) &amp; (x_{1,2}- \mu_2) &amp; \ldots &amp; (x_{1,4096}- \mu_{4096})\\
                                           (x_{2,1}- \mu_1) &amp; (x_{2,2}- \mu_2) &amp; \ldots &amp; (x_{2,4096}- \mu_{4096}) \\
                                           \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\
                                           (x_{55,1}- \mu_1) &amp; (x_{55,2}- \mu_2) &amp; \ldots &amp; (x_{55,4096}- \mu_{4096})\end{bmatrix}\]</span></p>
<p>From the lectures you know that, for example, the mean of the first variable (pixel) can be found as the mean of all the observations: <span class="math inline">\(\mu_1 = \frac{1}{55} \sum_{i=1}^{55} x_{i,1}\)</span>.</p>
<p>For the following exercise you will implement a function that takes an array of shape <span class="math inline">\(\mathrm{Num. observations}\times\mathrm{Num. variables}\)</span>, and returns the centered data.</p>
<p>To perform the centering you will need three numpy functions. Click on their names if you want to read the official documentation for each in more detail: - <a href="https://numpy.org/doc/stable/reference/generated/numpy.mean.html"><code>np.mean</code></a>: use this function to compute the mean of each variable, just remember to pass the correct <code>axis</code> argument. - <a href="https://numpy.org/doc/stable/reference/generated/numpy.repeat.html#numpy-repeat"><code>np.repeat</code></a>: This will allow for you to repeat the values of each <span class="math inline">\(\mu_i\)</span> . - <a href="https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape"><code>np.reshape</code></a>: Use this function to reshape the repeated values into a matrix of shape the same size as your input data. To get the correct matrix after the reshape, remember to use the parameter <code>order='F'</code>.</p>
<div id="cell-35" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="19">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graded cell</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> center_data(Y):</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Center your original data</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a><span class="co">         Y (ndarray): input data. Shape (n_observations x n_pixels)</span></span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a><span class="co">    Outputs:</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray): centered data</span></span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>    <span class="co">### START CODE HERE </span><span class="al">###</span></span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>    mean_vector <span class="op">=</span> np.mean(Y, axis<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>    mean_matrix <span class="op">=</span> np.repeat(mean_vector, Y.shape[<span class="dv">0</span>])</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># use np.reshape to reshape into a matrix with the same size as Y. Remember to use order='F'</span></span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>    mean_matrix <span class="op">=</span> np.reshape(mean_matrix, Y.shape, order<span class="op">=</span><span class="st">'F'</span>)</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>    X <span class="op">=</span> Y <span class="op">-</span> mean_matrix</span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Go ahead and apply the <code>center_data</code> function to your data in <code>imgs_flatten</code>.</p>
<p>You can also print the image again and check that the face of the cat still looks the same. This is because the color scale is not fixed, but rather relative to the values of the pixels.</p>
<div id="cell-37" class="cell" data-tags="[]" data-execution_count="20">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> center_data(imgs_flatten)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>plt.imshow(X[<span class="dv">0</span>].reshape(<span class="dv">64</span>,<span class="dv">64</span>), cmap<span class="op">=</span><span class="st">'gray'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-17-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="cell-38" class="cell" data-editable="false" data-tags="[]" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test your solution.</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>w4_unittest.test_center_data(center_data)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
</section>
<section id="exercise-4" class="level3">
<h3 class="anchored" data-anchor-id="exercise-4">Exercise 4</h3>
<p>Now that you have your centered data, <span class="math inline">\(X\)</span>, you can go ahead and find the covariance matrix</p>
<p>You might remember from the lectures that once you have your centered data, the covariance matrix can be found by appliying the dot product between <span class="math inline">\(X^T\)</span> and <span class="math inline">\(X\)</span>, and divide by the number of observations minus 1.</p>
<p>To perform the dot product you can simply use the function <a href="https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy-dot"><code>np.dot</code></a>.</p>
<div id="cell-40" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> get_cov_matrix(X):</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">""" Calculate covariance matrix from centered data X</span></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="co">    Args:</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">        X (np.ndarray): centered data matrix</span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Outputs:</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="co">        cov_matrix (np.ndarray): covariance matrix</span></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>    <span class="co">### START CODE HERE </span><span class="al">###</span></span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>    cov_matrix <span class="op">=</span> np.dot(X.T, X)</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>    cov_matrix <span class="op">=</span> cov_matrix <span class="op">/</span> (X.shape[<span class="dv">0</span>] <span class="op">-</span> <span class="dv">1</span>)</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a>    <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> cov_matrix</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-41" class="cell" data-tags="[]" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>cov_matrix <span class="op">=</span> get_cov_matrix(X)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Check the dimensions of the covariance matrix, it should be a square matrix with 4096 rows and columns.</p>
<div id="cell-43" class="cell" data-tags="[]" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Covariance matrix shape: </span><span class="sc">{</span>cov_matrix<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Covariance matrix shape: (4096, 4096)</code></pre>
</div>
</div>
<div id="cell-44" class="cell" data-editable="false" data-tags="[]" data-execution_count="26">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test your solution.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>w4_unittest.test_cov_matrix(get_cov_matrix)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p><a name="2.3"></a> ### 2.3 - Compute the eigenvalues and eigenvectors Now you are all set to compute the eigenvalues and eigenvectors of the covariance matrix. Due to performance constaints, you will not be using <code>np.linalg.eig</code>, but rather the very similar function <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html"><code>scipy.sparse.linalg.eigsh</code></a>, which exploits the fact that <span class="math inline">\(\mathrm{cov\_matrix}^T=\mathrm{cov\_matrix}\)</span>. Also, this function allows you to compute fewer number of eigenvalue-eigenvector pairs.</p>
<p>It is outside of the scope of this course, but it can be shown that at most 55 eigenvalues of <code>cov_matrix</code> will be different from zero, which is the smallest dimension of the data matrix <code>X</code>. Thus, for computational efficiency, you will only be computing the first biggest 55 eigenvalues <span class="math inline">\(\lambda_1, \ldots, \lambda_{55}\)</span> and their corresponding eigenvectors <span class="math inline">\(v_1, \ldots, v_{55}\)</span>. Feel free to try changing the <code>k</code> parameter in <code>scipy.sparse.linalg.eigsh</code> to something slightly bigger, to verify that all the new eigenvalues are zero. Try to keep it below 80, otherwise it will take too long to compute.</p>
<p>The outputs of this scipy function are exactly the same as the ones from <code>np.linalg.eig</code>, except eigenvalues are ordered in decreasing order, so if you want to check out the largest eigenvalue you need to look into the last position of the vector.</p>
<div id="cell-46" class="cell" data-tags="[]" data-execution_count="27">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>scipy.random.seed(<span class="dv">7</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>eigenvals, eigenvecs <span class="op">=</span> scipy.sparse.linalg.eigsh(cov_matrix, k<span class="op">=</span><span class="dv">55</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ten largest eigenvalues: </span><span class="ch">\n</span><span class="sc">{</span>eigenvals[<span class="op">-</span><span class="dv">10</span>:]<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ten largest eigenvalues: 
[ 293297.76716381  383558.95285037  399091.64921256  479564.23517501
  839756.42124326  879138.93723794 1011092.7845815  1536790.5408648
 2484055.10309963 4198829.23262023]</code></pre>
</div>
</div>
<p>The random seed is fixed in the code above to help ensure the same eigenvectors are calculated each time. This is because for each eigenvector, there are actually two possible outcomes with norm 1. They fall on the same line but point in opposite directions. An example of this would be the vectors</p>
<p><span class="math display">\[\begin{bmatrix}0.25 \\0.25 \\ -0.25 \\ 0.25 \end{bmatrix} \text{and } \begin{bmatrix}-0.25 \\ -0.25 \\ 0.25 \\ -0.25 \end{bmatrix}.\]</span></p>
<p>Both possibilities are correct, but by fixing the seed you guarantee you will always get the same result.</p>
<p>In order to get a consistent result with <code>np.linalg.eig</code>, you will invert the order of <code>eigenvals</code> and <code>eigenvecs</code>, so they are both ordered from largest to smallest eigenvalue.</p>
<div id="cell-48" class="cell" data-tags="[]" data-execution_count="28">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>eigenvals <span class="op">=</span> eigenvals[::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>eigenvecs <span class="op">=</span> eigenvecs[:,::<span class="op">-</span><span class="dv">1</span>]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Ten largest eigenvalues: </span><span class="ch">\n</span><span class="sc">{</span>eigenvals[:<span class="dv">10</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Ten largest eigenvalues: 
[4198829.23262023 2484055.10309963 1536790.5408648  1011092.7845815
  879138.93723794  839756.42124326  479564.23517501  399091.64921256
  383558.95285037  293297.76716381]</code></pre>
</div>
</div>
<p>Each of the eigenvectors you found will represent one principal component. The eigenvector associated with the largest eigenvalue will be the first principal component, the eigenvector associated with the second largest eigenvalue will be the second principal component, and so on.</p>
<p>It is pretty interesting to see that each principal component usually extracts some relevant features, or patterns from each image. In the next cell you will be visualizing the first sixteen components</p>
<div id="cell-50" class="cell" data-tags="[]" data-execution_count="29">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">4</span>,<span class="dv">4</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">20</span>))</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> n <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">4</span>):</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>        ax[n,k].imshow(eigenvecs[:,n<span class="op">*</span><span class="dv">4</span><span class="op">+</span>k].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>        ax[n,k].set_title(<span class="ss">f'component number </span><span class="sc">{</span>n<span class="op">*</span><span class="dv">4</span><span class="op">+</span>k<span class="op">+</span><span class="dv">1</span><span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-25-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>What can you say about each of the principal components?</p>
<p><a name="2.4"></a> ### 2.4 Transform the centered data with PCA</p>
<p>Now that you have the first 55 eigenvalue-eivenvector pairs, you can transform your data to reduce the dimensions. Remember that your data originally consisted of 4096 variables. Suppose you want to reduce that to just 2 dimensions, then all you need to do to perform the reduction with PCA is take the dot product between your centered data and the matrix <span class="math inline">\(\boldsymbol{V}=\begin{bmatrix} v_1 &amp; v_2 \end{bmatrix}\)</span>, whose columns are the first 2 eigenvectors, or principal components, associated to the 2 largest eigenvalues.</p>
<p><a name="ex03"></a> ### Exercise 5 In the next cell you will define a function that, given the data matrix, the eigenvector matrix (always sorted according to decreasing eignevalues), and the number of principal components to use, performs PCA.</p>
<div id="cell-53" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="30">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># GRADED cell</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> perform_PCA(X, eigenvecs, k):</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""</span></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">    Perform dimensionality reduction with PCA</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a><span class="co">    Inputs:</span></span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a><span class="co">        X (ndarray): original data matrix. Has dimensions (n_observations)x(n_variables)</span></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co">        eigenvecs (ndarray): matrix of eigenvectors. Each column is one eigenvector. The k-th eigenvector </span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="co">                            is associated to the k-th eigenvalue</span></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">        k (int): number of principal components to use</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co">    Returns:</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="co">        Xred</span></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a><span class="co">    """</span></span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>    <span class="co">### START CODE HERE </span><span class="al">###</span></span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>    V <span class="op">=</span> eigenvecs[:, :k]</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a>    Xred <span class="op">=</span> np.dot(X, V)</span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>    <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> Xred</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Try out this function, reducing your data to just two components</p>
<div id="cell-55" class="cell" data-tags="[]" data-execution_count="31">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>Xred2 <span class="op">=</span> perform_PCA(X, eigenvecs,<span class="dv">2</span>)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'Xred2 shape: </span><span class="sc">{</span>Xred2<span class="sc">.</span>shape<span class="sc">}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Xred2 shape: (55, 2)</code></pre>
</div>
</div>
<div id="cell-56" class="cell" data-editable="false" data-tags="[]" data-execution_count="32">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test your solution.</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>w4_unittest.test_check_PCA(perform_PCA)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p><a name="2.5"></a> ### 2.5 Analyzing the dimensionality reduction in 2 dimensions</p>
<p>One cool thing about reducing your data to just two components is that you can clearly visualize each cat image on the plane. Remember that each axis on this new plane represents a linear combination of the original variables, given by the direction of the two eigenvectors.</p>
<p>Use the function <code>plot_reduced_data</code> in <code>utils</code>to visualize the transformed data. Each blue dot represents an image, and the number represents the index of the image. This is so you can later recover which image is which, and gain some intuition.</p>
<div id="cell-58" class="cell" data-tags="[]" data-execution_count="33">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>utils.plot_reduced_data(Xred2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-29-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>If two points end up being close to each other in this representation, it is expected that the original pictures should be similar as well. Let’s see if this is true. Consider for example the images 19, 21 and 41, which appear close to each other on the top center of the plot. Plot the corresponding cat images vertfy that they correspond to similar cats.</p>
<div id="cell-60" class="cell" data-tags="[]" data-execution_count="34">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].imshow(imgs[<span class="dv">19</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Image 19'</span>)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].imshow(imgs[<span class="dv">21</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'Image 21'</span>)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].imshow(imgs[<span class="dv">41</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_title(<span class="st">'Image 41'</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Similar cats'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="34">
<pre><code>Text(0.5, 0.98, 'Similar cats')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-30-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, all three cats have white snouts and black fur around the eyes, making them pretty similar.</p>
<p>Now, let’s choose three images that seem far appart from each other, for example image 18, on the middle right, 41 on the top center and 51 on the lower left, and also plot the images</p>
<div id="cell-62" class="cell" data-tags="[]" data-execution_count="35">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">1</span>,<span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">5</span>))</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].imshow(imgs[<span class="dv">18</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>].set_title(<span class="st">'Image 18'</span>)</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].imshow(imgs[<span class="dv">41</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>].set_title(<span class="st">'Image 41'</span>)</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].imshow(imgs[<span class="dv">51</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>].set_title(<span class="st">'Image 51'</span>)</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>plt.suptitle(<span class="st">'Different cats'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="35">
<pre><code>Text(0.5, 0.98, 'Different cats')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-31-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In this case, all three cats look really different, one being completely black, another completely white, and the the third one a mix of both colors.</p>
<p>Feel free to choose different pairs of points and check how similar (or different) the pictures are.</p>
<p><a name="2.6"></a> ### 2.6 Reconstructing the images from the eigenvectors</p>
<p>When you compress the images using PCA, you are losing some information because you are using fewer variables to represent each observation.</p>
<p>A natural question arises: how many components do you need to get a good reconstruction of the image? Of course, what determines a “good” reconstruction might depend on the application.</p>
<p>A cool thing is that with a simple dot product you can transform the data after applying PCA back to the original space. This means that you can reconstruct the original image from the transformed space and check how distorted it looks based on the number of components you kept.</p>
<p>Suppose you obtained the matrix <span class="math inline">\(X_{red}\)</span> by keeping just two eigenvectors, then <span class="math inline">\(X_{red} = \mathrm{X}\underbrace{\left[v_1\  v_2\right]}_{\boldsymbol{V_2}}\)</span>.</p>
<p>To transform the images back to the original variables space all you need to do is take the dot product between <span class="math inline">\(X_{red}\)</span> and <span class="math inline">\(\boldsymbol{V_2}^T\)</span>. If you were to keep more components, say <span class="math inline">\(k\)</span>, then simply replace <span class="math inline">\(\boldsymbol{V_2}\)</span> by <span class="math inline">\(\boldsymbol{V_k} = \left[v_1\ v_2\ \ldots\ v_k\right]\)</span>. Notice that you can’t make any combination you like, if you reduced the original data to just <span class="math inline">\(k\)</span> components, then the recovery must consider only the first <span class="math inline">\(k\)</span> eigenvectors, otherwise you will not be able to perform the matrix multiplication.</p>
<p>In the next cell you will define a function that given the transformed data <span class="math inline">\(X_{red}\)</span> and the matrix of eigenvectors returns the recovered image.</p>
<div id="cell-64" class="cell" data-tags="[]" data-execution_count="36">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> reconstruct_image(Xred, eigenvecs):</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>    X_reconstructed <span class="op">=</span> Xred.dot(eigenvecs[:,:Xred.shape[<span class="dv">1</span>]].T)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> X_reconstructed</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Let’s see what the reconstructed image looks like for different number of principal components</p>
<div id="cell-66" class="cell" data-tags="[]" data-execution_count="37">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Xred1 <span class="op">=</span> perform_PCA(X, eigenvecs,<span class="dv">1</span>) <span class="co"># reduce dimensions to 1 component</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>Xred5 <span class="op">=</span> perform_PCA(X, eigenvecs, <span class="dv">5</span>) <span class="co"># reduce dimensions to 5 components</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>Xred10 <span class="op">=</span> perform_PCA(X, eigenvecs, <span class="dv">10</span>) <span class="co"># reduce dimensions to 10 components</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>Xred20 <span class="op">=</span> perform_PCA(X, eigenvecs, <span class="dv">20</span>) <span class="co"># reduce dimensions to 20 components</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>Xred30 <span class="op">=</span> perform_PCA(X, eigenvecs, <span class="dv">30</span>) <span class="co"># reduce dimensions to 30 components</span></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>Xrec1 <span class="op">=</span> reconstruct_image(Xred1, eigenvecs) <span class="co"># reconstruct image from 1 component</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>Xrec5 <span class="op">=</span> reconstruct_image(Xred5, eigenvecs) <span class="co"># reconstruct image from 5 components</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>Xrec10 <span class="op">=</span> reconstruct_image(Xred10, eigenvecs) <span class="co"># reconstruct image from 10 components</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>Xrec20 <span class="op">=</span> reconstruct_image(Xred20, eigenvecs) <span class="co"># reconstruct image from 20 components</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>Xrec30 <span class="op">=</span> reconstruct_image(Xred30, eigenvecs) <span class="co"># reconstruct image from 30 components</span></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">2</span>,<span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">22</span>,<span class="dv">15</span>))</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].imshow(imgs[<span class="dv">21</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'original'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].imshow(Xrec1[<span class="dv">21</span>].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'reconstructed from 1 components'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].imshow(Xrec5[<span class="dv">21</span>].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">2</span>].set_title(<span class="st">'reconstructed from 5 components'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].imshow(Xrec10[<span class="dv">21</span>].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'reconstructed from 10 components'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].imshow(Xrec20[<span class="dv">21</span>].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'reconstructed from 20 components'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].imshow(Xrec30[<span class="dv">21</span>].reshape(height,width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">2</span>].set_title(<span class="st">'reconstructed from 30 components'</span>, size<span class="op">=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>Text(0.5, 1.0, 'reconstructed from 30 components')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-33-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, as the number of components increases, the reconstructed image looks more and more as the original one. Even with as little as 1 component you can are least identify where the relevant features such as eyes and nose are located.</p>
<p>What happens when you consider all of the 55 eigenvectors associated to non-zero eigenvalues? Go ahead and experiment with different number of principal components and see what happens.</p>
<p><a name="2.7"></a> ### 2.7 Explained variance</p>
<p>When deciding how many components to use for the dimensionality reduction, one good criteria to consider is the explained variance.</p>
<p>The explained variance is measure of how much variation in a dataset can be attributed to each of the principal components (eigenvectors). In other words, it tells us how much of the total variance is “explained” by each component.</p>
<p>In PCA, the first principal component, i.e.&nbsp;the eigenvector associated to the largest eigenvalue, is the one with greatest explained variance. As you might remember from the lectures, the goal of PCA is to reduce the dimensionality by projecting data in the directions with biggest variability.</p>
<p>In practical terms, the explained variance of a principal component is the ratio between its associated eigenvalue and the sum of all the eigenvalues. So, for our example, if you want the explained variance of the first principal component you will need to do <span class="math inline">\(\frac{\lambda_1}{\sum_{i=1}^{55} \lambda_i}\)</span></p>
<p>Next, let’s plot the explained variance of each of the 55 principal components, or eigenvectors. Don’t worry about the fact that you only computed 55 eigenvalue-eigenvector pairs, recall that all the remaining eigenvalues of the covariance matrix are zero, and thus won’t add enything to the explained variance.</p>
<div id="cell-69" class="cell" data-tags="[]" data-execution_count="38">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>explained_variance <span class="op">=</span> eigenvals<span class="op">/</span><span class="bu">sum</span>(eigenvals)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>plt.plot(np.arange(<span class="dv">1</span>,<span class="dv">56</span>), explained_variance)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-34-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As you can see, the explained variance falls pretty fast, and is very small after the 20th component.</p>
<p>A good way to decide on the number of components is to keep the ones that explain a very high percentage of the variance, for example 95%.</p>
<p>For an easier visualization you can plot the cumulative explained variance. You can do this with the <code>np.cumsum</code> function. Let’s see what this looks like</p>
<div id="cell-71" class="cell" data-execution_count="39">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>explained_cum_variance <span class="op">=</span> np.cumsum(explained_variance)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>plt.plot(np.arange(<span class="dv">1</span>,<span class="dv">56</span>), explained_cum_variance)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="fl">0.95</span>, color<span class="op">=</span><span class="st">'r'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-35-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In red you can see the 95% line. This means that if you want to be able to explain 95% of the variance of your data you need to keep 35 principal components.</p>
<p>Let’s see how some of the original images look after the reconstruction when using 35 principal components</p>
<div id="cell-73" class="cell" data-execution_count="40">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>Xred35 <span class="op">=</span> perform_PCA(X, eigenvecs, <span class="dv">35</span>) <span class="co"># reduce dimensions to 35 components</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>Xrec35 <span class="op">=</span> reconstruct_image(Xred35, eigenvecs) <span class="co"># reconstruct image from 35 components</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>fig, ax <span class="op">=</span> plt.subplots(<span class="dv">4</span>,<span class="dv">2</span>, figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">28</span>))</span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].imshow(imgs[<span class="dv">0</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">0</span>].set_title(<span class="st">'original'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].imshow(Xrec35[<span class="dv">0</span>].reshape(height, width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">0</span>,<span class="dv">1</span>].set_title(<span class="st">'Reconstructed'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].imshow(imgs[<span class="dv">15</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">0</span>].set_title(<span class="st">'original'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].imshow(Xrec35[<span class="dv">15</span>].reshape(height, width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">1</span>,<span class="dv">1</span>].set_title(<span class="st">'Reconstructed'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>,<span class="dv">0</span>].imshow(imgs[<span class="dv">32</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>,<span class="dv">0</span>].set_title(<span class="st">'original'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>,<span class="dv">1</span>].imshow(Xrec35[<span class="dv">32</span>].reshape(height, width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">2</span>,<span class="dv">1</span>].set_title(<span class="st">'Reconstructed'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">3</span>,<span class="dv">0</span>].imshow(imgs[<span class="dv">54</span>], cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">3</span>,<span class="dv">0</span>].set_title(<span class="st">'original'</span>, size<span class="op">=</span><span class="dv">20</span>)</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">3</span>,<span class="dv">1</span>].imshow(Xrec35[<span class="dv">54</span>].reshape(height, width), cmap<span class="op">=</span><span class="st">'gray'</span>)</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>ax[<span class="dv">3</span>,<span class="dv">1</span>].set_title(<span class="st">'Reconstructed'</span>, size<span class="op">=</span><span class="dv">20</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="40">
<pre><code>Text(0.5, 1.0, 'Reconstructed')</code></pre>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C1W4_Assignment_files/figure-html/cell-36-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Most of these reconstructions look pretty good, and you were able to save a lot of memory by reducing the data from 4096 variables to just 35!</p>
<p>Now that you understand how the explained variance works you can play around with different amount of explained variance and see how this affects the reconstructed images. You can also explore how the reconstruction for different images looks.</p>
<p>As you can see, PCA is a really useful tool for dimensionality reduction. In this assignment you saw how it works on images, but you can apply the same principle to any tabular dataset.</p>
<p>Congratulations! You have finished the assignment in this week.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->




</body></html>