<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Optimizing Functions of One Variable: Cost Minimization – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./media/favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="./math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./math/probability-statistics/index.html">
 <span class="dropdown-text">Probability &amp; Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-ai">    
        <li>
    <a class="dropdown-item" href="./ai/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/machine-learning/index.html">
 <span class="dropdown-text">Machine Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/deep-learning/index.html">
 <span class="dropdown-text">Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./ai/agentic/index.html">
 <span class="dropdown-text">Agentic AI</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="./networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="./tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="./about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#important-note" id="toc-important-note" class="nav-link active" data-scroll-target="#important-note">Important Note</a></li>
  <li><a href="#table-of-contents" id="toc-table-of-contents" class="nav-link" data-scroll-target="#table-of-contents">Table of Contents</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="./theme-toggle.js"></script>
<script src="./resume-reading.js"></script>
<script src="./search-scope.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Optimizing Functions of One Variable: Cost Minimization</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~16 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></p></div>';
    meta.appendChild(div);
  }
});
</script>

<p>In this assignment you will solve a simple optimization problem for a function of one variable. Given a dataset of historical prices of a product from two suppliers, your task is to identify what share of the product you should buy from each of the suppliers to make the best possible investment in the future. Stating the problem mathematically, you will construct a target function to minimize, evaluate its minimum and investigate how its derivative is connected with the result.</p>
<section id="important-note" class="level2">
<h2 class="anchored" data-anchor-id="important-note">Important Note</h2>
<p>Please <strong>do not delete</strong> any exercise cells or add your solutions in a different cell. <strong>Maintain your solution in the original cell provided</strong>, as altering this can disrupt the autograder.</p>
<p>Additionally, <strong>refrain from importing any new libraries</strong>, and <strong>do not import libraries within any graded cells</strong>—doing so will interfere with the autograder’s functionality.</p>
<p>Leaving any exercise unsolved (i.e., not replacing the ‘None’ values) will cause issues with the autograder. If you wish to submit your assignment without completing every exercise, for testing purposes, please follow the instructions <a href="https://www.coursera.org/learn/machine-learning-calculus/item/yjJ7W">here</a>.</p>
</section>
<section id="table-of-contents" class="level1">
<h1>Table of Contents</h1>
<ul>
<li><a href="#1">1 - Statement of the Optimization Problem</a>
<ul>
<li><a href="#1.1">1.1 - Description of the Problem</a></li>
<li><a href="#1.2">1.2 - Mathematical Statement of the Problem</a></li>
<li><a href="#1.3">1.3 - Solution Approach</a></li>
</ul></li>
<li><a href="#2">2 - Optimizing Function of One Variable in Python</a>
<ul>
<li><a href="#2.1">2.1 - Packages</a></li>
<li><a href="#2.2">2.2 - Open and Analyze the Dataset</a>
<ul>
<li><a href="#ex01">Exercise 1</a></li>
</ul></li>
<li><a href="#2.3">2.3 - Construct the Function <span class="math inline">\(L\)</span> to Optimize and Find its Minimum Point</a>
<ul>
<li><a href="#ex02">Exercise 2</a></li>
<li><a href="#ex03">Exercise 3</a></li>
<li><a href="#ex04">Exercise 4</a></li>
</ul></li>
</ul></li>
</ul>
<p><a name="1"></a> ## 1 - Statement of the Optimization Problem</p>
<p><a name="1.1"></a> ### 1.1 - Description of the Problem</p>
<p>Your Company is aiming to minimize production costs of some goods. During the production process, an essential product P is used, which can be supplied from one of two partners - supplier A and supplier B. Your consultants requested the historical prices of product P from both suppliers A and B, which were provided as monthly averages for the period from February 2018 to March 2020.</p>
<p>Preparing Company Budget for the coming twelve months period, your plan is to purchase the same amount of product P monthly. Choosing the supplier, you noticed, that there were some periods in the past, when it would be more profitable to use supplier A (the prices of product P were lower), and other periods to work with supplier B. For the Budget model you can set some percentage of the goods to be purchased from supplier A (e.g.&nbsp;60%) and the remaining part from supplier B (e.g.&nbsp;40%), but this split should be kept consistent for the whole of the twelve months period. The Budget will be used in preparation for the contract negotiations with both suppliers.</p>
<p>Based on the historical prices, is there a particular percentage which will be more profitable to supply from Company A, and the remaining part from Company B? Or maybe it does not matter and you can work just with one of the suppliers?</p>
<p><a name="1.2"></a> ### 1.2 - Mathematical Statement of the Problem</p>
<p>Denoting prices of the product P from Company A and Company B as <span class="math inline">\(p_A\)</span> (USD) and <span class="math inline">\(p_B\)</span> (USD) respectively, and the volume of the product to be supplied per month as <span class="math inline">\(n\)</span> (units), the total cost in USD is:</p>
<p><span class="math display">\[f\left(\omega\right) = p_A \omega \,n+ p_B \left(1 - \omega\right) n,\]</span></p>
<p>where <span class="math inline">\(0\leq\omega\leq1\)</span> is the parameter. If <span class="math inline">\(\omega = 1\)</span>, all goods will be supplied from Company A, and if <span class="math inline">\(\omega = 0\)</span>, from Company B. In case of <span class="math inline">\(0&lt;\omega&lt;1\)</span>, some percentage will be allocated to both.</p>
<p>As it is planned to keep the volume <span class="math inline">\(n\)</span> constant over the next twelve months, in the mathematical model the common approach is to put <span class="math inline">\(n = 1\)</span>. You can do this, because nothing depends on the volume and the end result will be the same. Now the total cost will be simpler:</p>
<p><span class="math display">\[f\left(\omega\right) = p_A \omega+ p_B \left(1 - \omega\right) \tag{1}\]</span></p>
<p>Obviously, you do not know the future prices <span class="math inline">\(p_A\)</span> and <span class="math inline">\(p_B\)</span>, only historical values (prices <span class="math inline">\(\{p_A^1, \cdots, p_A^k\}\)</span> and <span class="math inline">\(\{p_B^1, \cdots, p_B^k\}\)</span> for <span class="math inline">\(k\)</span> months). And historically there were various periods of time when it was better to take <span class="math inline">\(\omega = 1\)</span> (<span class="math inline">\(p_A^i &lt; p_B^i\)</span>) or <span class="math inline">\(\omega = 0\)</span> (<span class="math inline">\(p_A^i &gt;p_B^i\)</span>). Is it possible now to choose some <span class="math inline">\(\omega\)</span> value that would provide some evidence of minimum costs in the future?</p>
<p><a name="1.3"></a> ### 1.3 - Solution Approach</p>
<p>This is a standard <strong>portfolio management</strong> (investment) problem well known in statistics, where based on the historical prices you need to make investment decision to maximize profit (minimize costs). Since statistics has not been covered in this Course, you do not need to understand the details about the function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> (called <strong>loss function</strong>) to minimize, explained in the next paragraph.</p>
<p>The approach is to calculate <span class="math inline">\(f\left(\omega\right)\)</span> for each of the historical prices <span class="math inline">\(p_A^i\)</span> and <span class="math inline">\(p_B^i\)</span>, <span class="math inline">\(f^i\left(\omega\right)=p_A^i \omega+ p_B^i \left(1 - \omega\right)\)</span>. Then take an average of those values, <span class="math inline">\(\overline{f\left (\omega\right)}=\text{mean}\left(f^i\left(\omega\right)\right) = \frac{1}{k}\sum_{i=1}^{k}f^i\left(\omega\right)\)</span> and look for such value of <span class="math inline">\(\omega\)</span> which makes <span class="math inline">\(f^i\left(\omega\right)\)</span> as “stable” as possible - varying as little as possible from the average <span class="math inline">\(\overline{f\left (\omega\right)}\)</span>. This means that you would want to minimize the sum of the differences <span class="math inline">\(\left(f^i \left(\omega\right) -  \overline{f\left (\omega\right)}\right)\)</span>. As the differences can be negative or positive, a common approach is to take the squares of those and take an average of the squares:</p>
<p><span class="math display">\[\mathcal{L}\left(\omega\right) = \frac{1}{k}\sum_{i=1}^{k}\left(f^i \left(\omega\right) -  \overline{f\left (\omega\right)}\right)^2\tag{2}\]</span></p>
<p>In statistics <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> is called a variance of <span class="math inline">\(\{f^1 \left(\omega\right), \cdots , f^k \left(\omega\right)\}\)</span>. The aim is to minimize the variance <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span>, where <span class="math inline">\(\omega\in\left[0, 1\right]\)</span>. Again, do not worry if you do not understand deeply why particularly this function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> was chosen. You might think if it is logical to minimize an average <span class="math inline">\(\overline{f\left (\omega\right)}\)</span>, but <a href="https://www.thebalancemoney.com/minimum-variance-portfolio-overview-4155796#:~:text=A%20minimum%20variance%20portfolio%20is,other%20out%20when%20held%20together.">risk management</a> theory states that in this problem variance needs to be optimized.</p>
<p>Statistical theory shows that there is an <span class="math inline">\(\omega\in\left[0, 1\right]\)</span> value which minimizes function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> and it can be found using some properties of the datasets <span class="math inline">\(\{p_A^1, \cdots, p_A^k\}\)</span> and <span class="math inline">\(\{p_B^1, \cdots, p_B^k\}\)</span>. However, as this is not a Course about statistics, the example is taken to illustrate an optimization problem of one variable based on some dataset. It is a chance for you to check your understanding and practice this week material.</p>
<p>Now let’s upload a dataset and explore if it is possible to find a minimum point for the corresponding function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span>.</p>
<p><a name="2"></a> ## 2 - Optimizing Function of One Variable in Python</p>
<p><a name="2.1"></a> ### 2.1 - Packages</p>
<p>Let’s import all of the required packages. In addition to the ones you have been using in this Course before, you will need to import <code>pandas</code> library. It is a commonly used package for data manipulation and analysis.</p>
<div id="cell-14" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="1">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A function to perform automatic differentiation.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> jax <span class="im">import</span> grad</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># A wrapped version of NumPy to use JAX primitives.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> jax.numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># A library for programmatic plot generation.</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># A library for data manipulation and analysis.</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># A magic command to make output of plotting commands displayed inline within the Jupyter notebook.</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="op">%</span>matplotlib inline </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Load the unit tests defined for this notebook.</p>
<div id="cell-16" class="cell" data-execution_count="2">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> w1_unittest</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Please ignore the warning message about GPU/TPU if it appears.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)</code></pre>
</div>
</div>
<p><a name="2.2"></a> ### 2.2 - Open and Analyze the Dataset</p>
<p>Historical prices for both suppliers A and B are saved in the file <code>data/prices.csv</code>. To open it you can use <code>pandas</code> function <code>read_csv</code>. This example is very simple, there is no need to use any other parameters.</p>
<div id="cell-19" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="3">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'data/prices.csv'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The data is now saved in the variable <code>df</code> as a <strong>DataFrame</strong>, which is the most commonly used <code>pandas</code> object. It is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it as a table or a spreadsheet. Full documentation can be found <a href="https://pandas.pydata.org/">here</a>.</p>
<p>View the data with a standard <code>print</code> function:</p>
<div id="cell-21" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="4">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>         date  price_supplier_a_dollars_per_item  \
0   1/02/2016                                104   
1   1/03/2016                                108   
2   1/04/2016                                101   
3   1/05/2016                                104   
4   1/06/2016                                102   
5   1/07/2016                                105   
6   1/08/2016                                114   
7   1/09/2016                                102   
8   1/10/2016                                105   
9   1/11/2016                                101   
10  1/12/2016                                109   
11  1/01/2017                                103   
12  1/02/2017                                 93   
13  1/03/2017                                 98   
14  1/04/2017                                 92   
15  1/05/2017                                 97   
16  1/06/2017                                 96   
17  1/07/2017                                 94   
18  1/08/2017                                 97   
19  1/09/2017                                 93   
20  1/10/2017                                 99   
21  1/11/2017                                 93   
22  1/12/2017                                 98   
23  1/01/2018                                 94   
24  1/02/2018                                 93   
25  1/03/2018                                 92   
26  1/04/2018                                 96   
27  1/05/2018                                 98   
28  1/06/2018                                 98   
29  1/07/2018                                 93   
30  1/08/2018                                 97   
31  1/09/2018                                102   
32  1/10/2018                                103   
33  1/11/2018                                100   
34  1/12/2018                                100   
35  1/01/2019                                104   
36  1/02/2019                                100   
37  1/03/2019                                103   
38  1/04/2019                                104   
39  1/05/2019                                101   
40  1/06/2019                                102   
41  1/07/2019                                100   
42  1/08/2019                                102   
43  1/09/2019                                108   
44  1/10/2019                                107   
45  1/11/2019                                107   
46  1/12/2019                                103   
47  1/01/2020                                109   
48  1/02/2020                                108   
49  1/03/2020                                108   

    price_supplier_b_dollars_per_item  
0                                  76  
1                                  76  
2                                  84  
3                                  79  
4                                  81  
5                                  84  
6                                  90  
7                                  93  
8                                  93  
9                                  99  
10                                 98  
11                                 96  
12                                 94  
13                                104  
14                                101  
15                                102  
16                                104  
17                                106  
18                                105  
19                                103  
20                                106  
21                                104  
22                                113  
23                                115  
24                                114  
25                                124  
26                                119  
27                                115  
28                                112  
29                                111  
30                                106  
31                                107  
32                                108  
33                                108  
34                                102  
35                                104  
36                                101  
37                                101  
38                                100  
39                                103  
40                                106  
41                                100  
42                                 97  
43                                 98  
44                                 90  
45                                 92  
46                                 92  
47                                 99  
48                                 94  
49                                 91  </code></pre>
</div>
</div>
<p>To print a list of the column names use <code>columns</code> attribute of the DataFrame:</p>
<div id="cell-23" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="5">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(df.columns)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Index(['date', 'price_supplier_a_dollars_per_item',
       'price_supplier_b_dollars_per_item'],
      dtype='object')</code></pre>
</div>
</div>
<p>Reviewing the displayed table and the column names you can conclude that monthly prices are provided (in USD) and you only need the data from the columns <code>price_supplier_a_dollars_per_item</code> and <code>price_supplier_b_dollars_per_item</code>. In real life the datasets are significantly larger and require a proper review and cleaning before injection into models. But this is not the focus of this Course.</p>
<p>To access the values of one column of the DataFrame you can use the column name as an attribute. For example, the following code will output <code>date</code> column of the DataFrame <code>df</code>:</p>
<div id="cell-25" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="6">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df.date</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display" data-execution_count="6">
<pre><code>0     1/02/2016
1     1/03/2016
2     1/04/2016
3     1/05/2016
4     1/06/2016
5     1/07/2016
6     1/08/2016
7     1/09/2016
8     1/10/2016
9     1/11/2016
10    1/12/2016
11    1/01/2017
12    1/02/2017
13    1/03/2017
14    1/04/2017
15    1/05/2017
16    1/06/2017
17    1/07/2017
18    1/08/2017
19    1/09/2017
20    1/10/2017
21    1/11/2017
22    1/12/2017
23    1/01/2018
24    1/02/2018
25    1/03/2018
26    1/04/2018
27    1/05/2018
28    1/06/2018
29    1/07/2018
30    1/08/2018
31    1/09/2018
32    1/10/2018
33    1/11/2018
34    1/12/2018
35    1/01/2019
36    1/02/2019
37    1/03/2019
38    1/04/2019
39    1/05/2019
40    1/06/2019
41    1/07/2019
42    1/08/2019
43    1/09/2019
44    1/10/2019
45    1/11/2019
46    1/12/2019
47    1/01/2020
48    1/02/2020
49    1/03/2020
Name: date, dtype: object</code></pre>
</div>
</div>
<p><a name="ex01"></a> ### Exercise 1</p>
<p>Load the historical prices of supplier A and supplier B into variables <code>prices_A</code> and <code>prices_B</code>, respectively. Convert the price values into <code>NumPy</code> arrays with elements of type <code>float32</code> using <code>np.array</code> function.</p>
<details>
<summary>
<font size="3" color="darkgreen"><b>Hint</b></font>
</summary>
<p>
</p><ul>
<li>
The corresponding prices are in the DataFrame <code>df</code>, columns <code>price_supplier_a_dollars_per_item</code> and <code>price_supplier_b_dollars_per_item</code>.
</li>
<li>
Conversion into the <code>NumPy</code> array can be performed with the function <code>np.array</code>.
</li>
</ul>
<p></p>
<div id="cell-28" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="8">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co">### START CODE HERE </span><span class="al">###</span><span class="co"> (~ 4 lines of code)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>prices_A <span class="op">=</span> np.array(df[<span class="st">'price_supplier_a_dollars_per_item'</span>])</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>prices_B <span class="op">=</span> np.array(df[<span class="st">'price_supplier_b_dollars_per_item'</span>])</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>prices_A <span class="op">=</span> prices_A.astype(<span class="st">'float32'</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>prices_B <span class="op">=</span> prices_B.astype(<span class="st">'float32'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-29" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="9">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Print some elements and mean values of the prices_A and prices_B arrays.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Some prices of supplier A:"</span>, prices_A[<span class="dv">0</span>:<span class="dv">5</span>])</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Some prices of supplier B:"</span>, prices_B[<span class="dv">0</span>:<span class="dv">5</span>])</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average of the prices, supplier A:"</span>, np.mean(prices_A))</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Average of the prices, supplier B:"</span>, np.mean(prices_B))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Some prices of supplier A: [104. 108. 101. 104. 102.]
Some prices of supplier B: [76. 76. 84. 79. 81.]
Average of the prices, supplier A: 100.799995
Average of the prices, supplier B: 100.0</code></pre>
</div>
</div>
<section id="expected-output" class="level5">
<h5 class="anchored" data-anchor-id="expected-output"><strong>Expected Output</strong></h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>Some prices of supplier A: [<span class="fl">104.</span> <span class="fl">108.</span> <span class="fl">101.</span> <span class="fl">104.</span> <span class="fl">102.</span>]</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>Some prices of supplier B: [<span class="fl">76.</span> <span class="fl">76.</span> <span class="fl">84.</span> <span class="fl">79.</span> <span class="fl">81.</span>]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>Average of the prices, supplier A: <span class="fl">100.799995</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>Average of the prices, supplier B: <span class="fl">100.0</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="cell-31" class="cell" data-execution_count="10">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>w1_unittest.test_load_and_convert_data(prices_A, prices_B)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>Average prices from both suppliers are similar. But if you will plot the historical prices, you will see that there were periods of time when the prices were lower for supplier A, and vice versa.</p>
<div id="cell-33" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="11">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>plt.plot(prices_A, <span class="st">'g'</span>, label<span class="op">=</span><span class="st">"Supplier A"</span>)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>plt.plot(prices_B, <span class="st">'b'</span>, label<span class="op">=</span><span class="st">"Supplier B"</span>)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C2W1Assignment_files/figure-html/cell-11-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Based on the historical data, can you tell which supplier it will be more profitable to work with? As discussed in the section <a href="#1.3">1.3</a>, you need to find such an <span class="math inline">\(\omega \in \left[0, 1\right]\)</span> which will minimize function <span class="math inline">\((2)\)</span>.</p>
<p><a name="2.3"></a> ### 2.3 - Construct the Function <span class="math inline">\(\mathcal{L}\)</span> to Optimize and Find its Minimum Point</p>
<p><a name="ex02"></a> ### Exercise 2</p>
<p>Calculate <code>f_of_omega</code>, corresponding to the <span class="math inline">\(f^i\left(\omega\right)=p_A^i \omega+ p_B^i \left(1 - \omega\right)\)</span>. Prices <span class="math inline">\(\{p_A^1, \cdots, p_A^k\}\)</span> and <span class="math inline">\(\{p_B^1, \cdots, p_B^k\}\)</span> can be passed in the arrays <code>pA</code> and <code>pB</code>. Thus, multiplying them by the scalars <code>omega</code> and <code>1 - omega</code> and adding together the resulting arrays, you will get an array containing <span class="math inline">\(\{f^1\left(\omega\right), \cdots, f^k\left(\omega\right)\}\)</span>.</p>
<p>Then array <code>f_of_omega</code> can be taken to calculate <code>L_of_omega</code>, according to the expression <span class="math inline">\((2)\)</span>:</p>
<p><span class="math display">\[\mathcal{L}\left(\omega\right) = \frac{1}{k}\sum_{i=1}^{k}\left(f^i \left(\omega\right) -  \overline{f\left (\omega\right)}\right)^2\]</span></p>
<div id="cell-37" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="12">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> f_of_omega(omega, pA, pB):</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">### START CODE HERE </span><span class="al">###</span><span class="co"> (~ 1 line of code)</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>    f <span class="op">=</span> pA <span class="op">*</span> omega <span class="op">+</span> pB <span class="op">*</span> (<span class="dv">1</span> <span class="op">-</span> omega)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> f</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> L_of_omega(omega, pA, pB):</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="dv">1</span><span class="op">/</span><span class="bu">len</span>(f_of_omega(omega, pA, pB)) <span class="op">*</span> np.<span class="bu">sum</span>((f_of_omega(omega, pA, pB) <span class="op">-</span> np.mean(f_of_omega(omega, pA, pB)))<span class="op">**</span><span class="dv">2</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-38" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="13">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 0) ="</span>,L_of_omega(<span class="dv">0</span>, prices_A, prices_B))</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 0.2) ="</span>,L_of_omega(<span class="fl">0.2</span>, prices_A, prices_B))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 0.8) ="</span>,L_of_omega(<span class="fl">0.8</span>, prices_A, prices_B))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 1) ="</span>,L_of_omega(<span class="dv">1</span>, prices_A, prices_B))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>L(omega = 0) = 110.72
L(omega = 0.2) = 61.1568
L(omega = 0.8) = 11.212797
L(omega = 1) = 27.48</code></pre>
</div>
</div>
</section>
<section id="expected-output-1" class="level5">
<h5 class="anchored" data-anchor-id="expected-output-1"><strong>Expected Output</strong></h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="dv">0</span>) <span class="op">=</span> <span class="fl">110.72</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="fl">0.2</span>) <span class="op">=</span> <span class="fl">61.1568</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="fl">0.8</span>) <span class="op">=</span> <span class="fl">11.212797</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="dv">1</span>) <span class="op">=</span> <span class="fl">27.48</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="cell-40" class="cell" data-execution_count="14">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>w1_unittest.test_f_of_omega(f_of_omega)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>Analysing the output above, you can notice that values of the function <span class="math inline">\(\mathcal{L}\)</span> are decreasing for <span class="math inline">\(\omega\)</span> increasing from <span class="math inline">\(0\)</span> to <span class="math inline">\(0.2\)</span>, then to <span class="math inline">\(0.8\)</span>, but there is an increase of the function <span class="math inline">\(\mathcal{L}\)</span> when <span class="math inline">\(\omega = 1\)</span>. What will be the <span class="math inline">\(\omega\)</span> giving the minimum value of the function <span class="math inline">\(\mathcal{L}\)</span>?</p>
<p>In this simple example <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> is a function of one variable and the problem of finding its minimum point with a certain accuracy is a trivial task. You just need to calculate function values for each <span class="math inline">\(\omega = 0, 0.001, 0.002, \cdots , 1\)</span> and find minimum element of the resulting array.</p>
<p>Function <code>L_of_omega</code> will not work if you will pass an array instead of a single value of <code>omega</code> (it was not designed for that). It is possible to rewrite it in a way that it would be possible, but here there is no need in that right now - you can calculate the resulting values in the loop as there will be not as many of them.</p>
<p><a name="ex03"></a> ### Exercise 3</p>
<p>Evaluate function <code>L_of_omega</code> for each of the elements of the array <code>omega_array</code> and pass the result into the corresponding element of the array <code>L_array</code> with the function <code>.at[&lt;index&gt;].set(&lt;value&gt;)</code>.</p>
<p><em>Note</em>: <code>jax.numpy</code> has been uploaded instead of the original <code>NumPy</code>. Up to this moment <code>jax</code> functionality has not been actually used, but it will be called in the cells below. Thus there was no need to upload both versions of the package, and you have to use <code>.at[&lt;index&gt;].set(&lt;value&gt;)</code> function to update the array.</p>
<div id="cell-43" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="15">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Parameter endpoint=True will allow ending point 1 to be included in the array.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co"># This is why it is better to take N = 1001, not N = 1000</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>N <span class="op">=</span> <span class="dv">1001</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>omega_array <span class="op">=</span> np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, N, endpoint<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a><span class="co"># This is organised as a function only for grading purposes.</span></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> L_of_omega_array(omega_array, pA, pB):</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(omega_array)</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>    L_array <span class="op">=</span> np.zeros(N)</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N):</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>        <span class="co">### START CODE HERE </span><span class="al">###</span><span class="co"> (~ 2 lines of code)</span></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>        L <span class="op">=</span> L_of_omega(omega_array[i], pA, pB)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>        L_array <span class="op">=</span> L_array.at[i].<span class="bu">set</span>(L)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>        <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> L_array</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a>L_array <span class="op">=</span> L_of_omega_array(omega_array, prices_A, prices_B)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-44" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="16">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 0) ="</span>,L_array[<span class="dv">0</span>])</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L(omega = 1) ="</span>,L_array[N<span class="op">-</span><span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>L(omega = 0) = 110.72
L(omega = 1) = 27.48</code></pre>
</div>
</div>
</section>
<section id="expected-output-2" class="level5">
<h5 class="anchored" data-anchor-id="expected-output-2"><strong>Expected Output</strong></h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="dv">0</span>) <span class="op">=</span> <span class="fl">110.72</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>L(omega <span class="op">=</span> <span class="dv">1</span>) <span class="op">=</span> <span class="fl">27.48</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="cell-46" class="cell" data-execution_count="17">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>w1_unittest.test_L_of_omega_array(L_of_omega_array)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>Now a minimum point of the function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> can be found with a <code>NumPy</code> function <code>argmin()</code>. As there were <span class="math inline">\(N = 1001\)</span> points taken in the segment <span class="math inline">\(\left[0, 1\right]\)</span>, the result will be accurate to three decimal places:</p>
<div id="cell-48" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="18">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>i_opt <span class="op">=</span> L_array.argmin()</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>omega_opt <span class="op">=</span> omega_array[i_opt]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>L_opt <span class="op">=</span> L_array[i_opt]</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'omega_min = </span><span class="sc">{</span>omega_opt<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">L_of_omega_min = </span><span class="sc">{</span>L_opt<span class="sc">:.7f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>omega_min = 0.702
L_of_omega_min = 9.2497196</code></pre>
</div>
</div>
<p>This result means that, based on the historical data, <span class="math inline">\(\omega = 0.702\)</span> is expected to be the most profitable choice for the share between suppliers A and B. It is reasonable to plan <span class="math inline">\(70.2\%\)</span> of product P to be supplied from Company A, and <span class="math inline">\(29.8\%\)</span> from Company B.</p>
<p>If you would like to improve the accuracy, you just need to increase the number of points N. This is a very simple example of a model with one parameter, resulting in optimization of a function of one variable. It is computationally cheap to evaluate it in many points to find the minimum with certain accuracy. But in machine learning the models have hundreds of parameters, using similar approach you would need to perform millions of target function evaluations. This is not possible in most of the cases, and that’s where Calculus with its methods and approaches comes into play.</p>
<p>In the next weeks of this Course you will learn how to optimize multivariate functions using differentiation. But for now as you are on the learning curve, let’s evaluate the derivative of the function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> at the points saved in the array <code>omega_array</code> to check that at the minimum point the derivative is actually the closest to zero.</p>
<p><a name="ex04"></a> ### Exercise 4</p>
<p>For each <span class="math inline">\(\omega\)</span> in the <code>omega_array</code> calculate <span class="math inline">\(\frac{d\mathcal{L}}{d\omega}\)</span> using <code>grad()</code> function from <code>JAX</code> library. Remember that you need to pass the function which you want to differentiate (here <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span>) as an argument of <code>grad()</code> function and then evaluate the derivative for the corresponding element of the <code>omega_array</code>. Then pass the result into the corresponding element of the array <code>dLdOmega_array</code> with the function <code>.at[&lt;index&gt;].set(&lt;value&gt;)</code>.</p>
<details>
<summary>
<font size="3" color="darkgreen"><b>Hint</b></font>
</summary>
<p>
</p><ul>
<li>
Function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> is implemented in the code as <code>L_of_omega</code>.
</li>
</ul>
<p></p>
<div id="cell-52" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="21">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># This is organised as a function only for grading purposes.</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> dLdOmega_of_omega_array(omega_array, pA, pB):</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>    N <span class="op">=</span> <span class="bu">len</span>(omega_array)</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>    dLdOmega_array <span class="op">=</span> np.zeros(N)</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> i <span class="kw">in</span> <span class="bu">range</span>(N):</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a>        <span class="co">### START CODE HERE </span><span class="al">###</span><span class="co"> (~ 2 lines of code)</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a>        dLdOmega <span class="op">=</span> grad(L_of_omega)(omega_array[i], pA, pB)</span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>        dLdOmega_array <span class="op">=</span> dLdOmega_array.at[i].<span class="bu">set</span>(dLdOmega)</span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>        <span class="co">### </span><span class="re">END</span><span class="co"> CODE HERE </span><span class="al">###</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a>        </span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> dLdOmega_array</span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a>dLdOmega_array <span class="op">=</span> dLdOmega_of_omega_array(omega_array, prices_A, prices_B)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div id="cell-53" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="22">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dLdOmega(omega = 0) ="</span>,dLdOmega_array[<span class="dv">0</span>])</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"dLdOmega(omega = 1) ="</span>,dLdOmega_array[N<span class="op">-</span><span class="dv">1</span>])</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>dLdOmega(omega = 0) = -288.96
dLdOmega(omega = 1) = 122.47999</code></pre>
</div>
</div>
</details></section>
<section id="expected-output-3" class="level5">
<h5 class="anchored" data-anchor-id="expected-output-3"><strong>Expected Output</strong></h5>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>dLdOmega(omega <span class="op">=</span> <span class="dv">0</span>) <span class="op">=</span> <span class="op">-</span><span class="fl">288.96</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>dLdOmega(omega <span class="op">=</span> <span class="dv">1</span>) <span class="op">=</span> <span class="fl">122.47999</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="cell-55" class="cell" data-execution_count="23">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>w1_unittest.test_dLdOmega_of_omega_array(dLdOmega_of_omega_array)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<div class="ansi-escaped-output">
<pre><span class="ansi-bright-green-fg"> All tests passed
</span></pre>
</div>
</div>
</div>
<p>Now to find the closest value of the derivative to <span class="math inline">\(0\)</span>, take absolute values <span class="math inline">\(\left|\frac{d\mathcal{L}}{d\omega}\right|\)</span> for each omega and find minimum of them.</p>
<div id="cell-57" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="24">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>i_opt_2 <span class="op">=</span> np.<span class="bu">abs</span>(dLdOmega_array).argmin()</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>omega_opt_2 <span class="op">=</span> omega_array[i_opt_2]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>dLdOmega_opt_2 <span class="op">=</span> dLdOmega_array[i_opt_2]</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'omega_min = </span><span class="sc">{</span>omega_opt_2<span class="sc">:.3f}</span><span class="ch">\n</span><span class="ss">dLdOmega_min = </span><span class="sc">{</span>dLdOmega_opt_2<span class="sc">:.7f}</span><span class="ss">'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>omega_min = 0.702
dLdOmega_min = -0.1290760</code></pre>
</div>
</div>
<p>The result is the same: <span class="math inline">\(\omega = 0.702\)</span>. Let’s plot <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> and <span class="math inline">\(\frac{d\mathcal{L}}{d\omega}\)</span> to visualize the graphs of them, minimum point of the function <span class="math inline">\(\mathcal{L}\left(\omega\right)\)</span> and the point where its derivative is around <span class="math inline">\(0\)</span>:</p>
<div id="cell-59" class="cell" data-tags="[&quot;graded&quot;]" data-execution_count="25">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure()</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>ax <span class="op">=</span> fig.add_subplot(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting the axes at the origin.</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'left'</span>].set_position(<span class="st">'zero'</span>)</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'bottom'</span>].set_position(<span class="st">'zero'</span>)</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'right'</span>].set_color(<span class="st">'none'</span>)</span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a>ax.spines[<span class="st">'top'</span>].set_color(<span class="st">'none'</span>)</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>ax.xaxis.set_ticks_position(<span class="st">'bottom'</span>)</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>ax.yaxis.set_ticks_position(<span class="st">'left'</span>)</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>plt.plot(omega_array,  L_array, <span class="st">"black"</span>, label <span class="op">=</span> <span class="st">"$</span><span class="er">\</span><span class="st">mathcal</span><span class="sc">{L}</span><span class="ch">\\</span><span class="st">left(</span><span class="er">\</span><span class="st">omega</span><span class="ch">\\</span><span class="st">right)$"</span>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a>plt.plot(omega_array,  dLdOmega_array, <span class="st">"orange"</span>, label <span class="op">=</span> <span class="st">"$</span><span class="er">\</span><span class="st">mathcal</span><span class="sc">{L}</span><span class="ch">\'\\</span><span class="st">left(</span><span class="er">\</span><span class="st">omega</span><span class="ch">\\</span><span class="st">right)$"</span>)</span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a>plt.plot([omega_opt, omega_opt_2], [L_opt,dLdOmega_opt_2], <span class="st">'ro'</span>, markersize<span class="op">=</span><span class="dv">3</span>)</span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="C2W1Assignment_files/figure-html/cell-23-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Congratulations, you have finished the assignment for this week! This example illustrates how optimization problems may appear in real life, and gives you an opportunity to explore the simple case of minimizing a function with one variable. Now it is time to learn about optimization of multivariate functions!</p>


</section>
</details></section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
</div> <!-- /content -->




</body></html>