<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-07">
<meta name="description" content="Single number evaluation metrics, satisficing versus optimizing metrics, choosing dev and test set distributions and sizes, and when to change your target.">

<title>Setting Up Your Goal – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../deep-learning/structuring-machine-learning-projects/comparing-to-human-level-performance.html" rel="next">
<link href="../../deep-learning/structuring-machine-learning-projects/introduction-to-ml-strategy.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-87fe4da730787eeec4a7ec728bf0e0b5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Setting Up Your Goal – H’s Notes">
<meta property="og:description" content="Single number evaluation metrics, satisficing versus optimizing metrics, choosing dev and test set distributions and sizes, and when to change your target.">
<meta property="og:image" content="https://h.oliabak.com/deep-learning/structuring-machine-learning-projects/setting-up-your-goal_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Setting Up Your Goal – H’s Notes">
<meta name="twitter:description" content="Single number evaluation metrics, satisficing versus optimizing metrics, choosing dev and test set distributions and sizes, and when to change your target.">
<meta name="twitter:image" content="https://h.oliabak.com/deep-learning/structuring-machine-learning-projects/setting-up-your-goal_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/improving-deep-neural-networks/index.html">
 <span class="dropdown-text">Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/structuring-machine-learning-projects/index.html">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../networking/archive.html">
 <span class="dropdown-text">Archive</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../tools/asn-converter.html">
 <span class="dropdown-text">ASN Converter</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/subnet-calculator.html">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/network-toolkit.html">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/markdown-preview.html">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/color-palette.html">
 <span class="dropdown-text">Color Palette Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/typography.html">
 <span class="dropdown-text">Typography Designer</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/daily-chess.html">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../deep-learning/structuring-machine-learning-projects/setting-up-your-goal.html">Setting Up Your Goal</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/structuring-machine-learning-projects/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Structuring Machine Learning Projects</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/structuring-machine-learning-projects/introduction-to-ml-strategy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to ML Strategy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/structuring-machine-learning-projects/setting-up-your-goal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Setting Up Your Goal</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/structuring-machine-learning-projects/comparing-to-human-level-performance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Comparing to Human-Level Performance</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#single-number-evaluation-metric" id="toc-single-number-evaluation-metric" class="nav-link active" data-scroll-target="#single-number-evaluation-metric">Single Number Evaluation Metric</a>
  <ul class="collapse">
  <li><a href="#precision-recall-and-the-tradeoff-between-them" id="toc-precision-recall-and-the-tradeoff-between-them" class="nav-link" data-scroll-target="#precision-recall-and-the-tradeoff-between-them">Precision, Recall, and the Tradeoff Between Them</a></li>
  <li><a href="#f1-score" id="toc-f1-score" class="nav-link" data-scroll-target="#f1-score">F1 Score</a></li>
  <li><a href="#averaging-across-categories" id="toc-averaging-across-categories" class="nav-link" data-scroll-target="#averaging-across-categories">Averaging Across Categories</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#satisficing-and-optimizing-metrics" id="toc-satisficing-and-optimizing-metrics" class="nav-link" data-scroll-target="#satisficing-and-optimizing-metrics">Satisficing and Optimizing Metrics</a>
  <ul class="collapse">
  <li><a href="#wake-word-detection" id="toc-wake-word-detection" class="nav-link" data-scroll-target="#wake-word-detection">Wake Word Detection</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#train-dev-and-test-distributions" id="toc-train-dev-and-test-distributions" class="nav-link" data-scroll-target="#train-dev-and-test-distributions">Train, Dev, and Test Distributions</a>
  <ul class="collapse">
  <li><a href="#where-you-place-the-target" id="toc-where-you-place-the-target" class="nav-link" data-scroll-target="#where-you-place-the-target">Where You Place the Target</a></li>
  <li><a href="#story-about-zip-codes" id="toc-story-about-zip-codes" class="nav-link" data-scroll-target="#story-about-zip-codes">Story About Zip Codes</a></li>
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#size-of-dev-and-test-sets" id="toc-size-of-dev-and-test-sets" class="nav-link" data-scroll-target="#size-of-dev-and-test-sets">Size of Dev and Test Sets</a>
  <ul class="collapse">
  <li><a href="#how-big-should-the-test-set-be" id="toc-how-big-should-the-test-set-be" class="nav-link" data-scroll-target="#how-big-should-the-test-set-be">How Big Should the Test Set Be?</a></li>
  <li><a href="#when-you-might-not-need-a-test-set" id="toc-when-you-might-not-need-a-test-set" class="nav-link" data-scroll-target="#when-you-might-not-need-a-test-set">When You Might Not Need a Test Set</a></li>
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#when-to-change-dev-and-test-sets-and-metrics" id="toc-when-to-change-dev-and-test-sets-and-metrics" class="nav-link" data-scroll-target="#when-to-change-dev-and-test-sets-and-metrics">When to Change Dev and Test Sets and Metrics</a>
  <ul class="collapse">
  <li><a href="#metric-that-ranks-the-wrong-algorithm-first" id="toc-metric-that-ranks-the-wrong-algorithm-first" class="nav-link" data-scroll-target="#metric-that-ranks-the-wrong-algorithm-first">Metric That Ranks the Wrong Algorithm First</a></li>
  <li><a href="#placing-the-target-and-shooting-at-it-are-separate-knobs" id="toc-placing-the-target-and-shooting-at-it-are-separate-knobs" class="nav-link" data-scroll-target="#placing-the-target-and-shooting-at-it-are-separate-knobs">Placing the Target and Shooting at It Are Separate Knobs</a></li>
  <li><a href="#dev-set-that-does-not-look-like-production" id="toc-dev-set-that-does-not-look-like-production" class="nav-link" data-scroll-target="#dev-set-that-does-not-look-like-production">Dev Set That Does Not Look Like Production</a></li>
  <li><a href="#set-something-up-quickly-then-refine" id="toc-set-something-up-quickly-then-refine" class="nav-link" data-scroll-target="#set-something-up-quickly-then-refine">Set Something Up Quickly, Then Refine</a></li>
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../nav-columns.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Setting Up Your Goal</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">ml-strategy</div>
    <div class="quarto-category">evaluation-metrics</div>
    <div class="quarto-category">dev-test-sets</div>
  </div>
  </div>

<div>
  <div class="description">
    Single number evaluation metrics, satisficing versus optimizing metrics, choosing dev and test set distributions and sizes, and when to change your target.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 7, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~65 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~6,100 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>Before you can improve a machine learning system, you have to decide what “better” means and how you will measure it. This page covers how to define that target, how big the data behind it should be, and what to do when you discover you placed the target in the wrong spot.</p>
<section id="single-number-evaluation-metric" class="level2">
<h2 class="anchored" data-anchor-id="single-number-evaluation-metric">Single Number Evaluation Metric</h2>
<p>Whether you are tuning hyperparameters, trying out different ideas for learning algorithms, or just trying different options for building your system, your progress will be much faster if you have a <strong>single real number evaluation metric</strong> that lets you quickly tell whether the new thing you just tried is working better or worse than your last idea. When teams are starting on a machine learning project, setting up a single number evaluation metric for the problem is one of the first things worth doing.</p>
<p>Recall that <a href="../../deep-learning/improving-deep-neural-networks/setting-up-your-machine-learning-application.html">applied machine learning is a highly iterative process</a>. You have an idea, you code it up, you run the experiment to see how it did, and then you use the outcome of the experiment to refine your idea. Then you keep going around that loop as you improve your algorithm.</p>
<div id="560e9032" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="setting-up-your-goal_files/figure-html/cell-2-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A single number metric is what makes each pass around the loop fast.</p>
<section id="precision-recall-and-the-tradeoff-between-them" class="level3">
<h3 class="anchored" data-anchor-id="precision-recall-and-the-tradeoff-between-them">Precision, Recall, and the Tradeoff Between Them</h3>
<p>Say that for your cat classifier you previously built classifier A, and by changing the hyperparameters, the training set, or something else, you have now trained a new classifier B. One reasonable way to evaluate their performance is to look at <strong>precision</strong> and <strong>recall</strong>.</p>
<p>The exact details do not matter too much here, and <a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html#precision-and-recall">Skewed Datasets</a> works through both measures with the confusion matrix behind them. Briefly, precision asks a question about the examples your classifier recognizes as cats. What percentage of them actually are cats? So if classifier A has 95 percent precision, then when classifier A says something is a cat, there is a 95 percent chance it really is a cat. Recall asks the reverse question. Of all the images that really are cats, what percentage were correctly recognized? If classifier A has 90 percent recall, then of all the images in your dev set that really are cats, classifier A accurately pulled out 90 percent of them.</p>
<p>There is often a tradeoff between precision and recall, and you care about both. You want that when the classifier says something is a cat, there is a high chance it really is a cat. But of all the images that are cats, you also want it to pull out a large fraction of them.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Classifier</th>
<th>Precision</th>
<th>Recall</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>95%</td>
<td>90%</td>
</tr>
<tr class="even">
<td>B</td>
<td>98%</td>
<td>85%</td>
</tr>
</tbody>
</table>
<p>The problem with using precision and recall as your evaluation metric is visible right there in the table. Classifier A does better on recall, and classifier B does better on precision, so you are not sure which classifier is better. And if you are trying out a lot of different ideas and a lot of different hyperparameters, you want to quickly try out not just two classifiers but maybe a dozen, and quickly pick out the best ones so you can keep iterating from there. With two evaluation metrics it is difficult to know how to quickly pick one of two, let alone one of ten.</p>
</section>
<section id="f1-score" class="level3">
<h3 class="anchored" data-anchor-id="f1-score">F1 Score</h3>
<p>Rather than using two numbers to pick a classifier, find a new evaluation metric that combines precision and recall. In the machine learning literature, the standard way to combine them is something called the <strong>F1 score</strong>. The details are not too important here, and the <a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html#f1-score">F1 Score</a> section of the Advanced Learning Algorithms course derives it in full, including why the plain average would crown a useless classifier that the harmonic mean rejects. Informally, you can think of it as the average of precision <span class="math inline">\(P\)</span> and recall <span class="math inline">\(R\)</span>. Formally it is defined as</p>
<p><span class="math display">\[
F_1 = \frac{2}{\frac{1}{P} + \frac{1}{R}}
\]</span></p>
<p>In mathematics this function is called the <strong>harmonic mean</strong> of <span class="math inline">\(P\)</span> and <span class="math inline">\(R\)</span>. Less formally, think of it as some way of averaging precision and recall, except that instead of taking the arithmetic mean you take the harmonic mean, which has some advantages in terms of trading the two off.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Classifier</th>
<th>Precision</th>
<th>Recall</th>
<th>F1 score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>95%</td>
<td>90%</td>
<td>92.4%</td>
</tr>
<tr class="even">
<td>B</td>
<td>98%</td>
<td>85%</td>
<td>91.0%</td>
</tr>
</tbody>
</table>
<p>Now you can see right away that classifier A has the better F1 score. Assuming F1 is a reasonable way to combine precision and recall for your problem, you can quickly select classifier A over classifier B.</p>
<p>What a lot of machine learning teams find is that a well-defined dev set, which is what you measure precision and recall on, plus a single number evaluation metric, allows you to quickly tell whether classifier A or classifier B is better. Together they speed up the iterative process of improving your algorithm.</p>
</section>
<section id="averaging-across-categories" class="level3">
<h3 class="anchored" data-anchor-id="averaging-across-categories">Averaging Across Categories</h3>
<p>Here is another example. Say you are building a cat app for cat lovers in four major geographies, the US, China, India, and Other, meaning the rest of the world. Your classifiers achieve different errors on data from these four geographies. It is reasonable to keep track of how well your classifiers do in these different markets.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Algorithm</th>
<th>US</th>
<th>China</th>
<th>India</th>
<th>Other</th>
<th>Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>3%</td>
<td>7%</td>
<td>5%</td>
<td>9%</td>
<td>6.00%</td>
</tr>
<tr class="even">
<td>B</td>
<td>5%</td>
<td>6%</td>
<td>5%</td>
<td>10%</td>
<td>6.50%</td>
</tr>
<tr class="odd">
<td>C</td>
<td>2%</td>
<td>3%</td>
<td>4%</td>
<td>5%</td>
<td><strong>3.50%</strong></td>
</tr>
<tr class="even">
<td>D</td>
<td>5%</td>
<td>8%</td>
<td>7%</td>
<td>2%</td>
<td>5.50%</td>
</tr>
<tr class="odd">
<td>E</td>
<td>4%</td>
<td>5%</td>
<td>2%</td>
<td>4%</td>
<td>3.75%</td>
</tr>
<tr class="even">
<td>F</td>
<td>7%</td>
<td>11%</td>
<td>8%</td>
<td>12%</td>
<td>9.50%</td>
</tr>
</tbody>
</table>
<p>But by tracking four numbers per algorithm, it is very difficult to look at the table and quickly decide whether algorithm A or algorithm B is superior. If you are testing a lot of different classifiers, it becomes even harder to pick one. So in addition to tracking performance in the four different geographies, also compute the average. Assuming that average performance is a reasonable single real number evaluation metric, you can quickly tell that algorithm C has the lowest average error, and you might go ahead with that one if you have to pick an algorithm to keep iterating from.</p>
<p>Your workload in machine learning is often that you have an idea, you implement it and try it out, and you want to know whether your idea helped. Having a single number evaluation metric really improves the efficiency of you and your team in making those decisions.</p>
</section>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Classifier A has 95 percent precision and 90 percent recall. Classifier B has 98 percent precision and 85 percent recall. Why is this pair of numbers a bad evaluation metric, and what fixes it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Neither classifier dominates the other, since A wins on recall and B wins on precision, so the pair does not rank them. With a dozen candidate classifiers the problem gets worse. The fix is to collapse the two numbers into one, and the standard choice is the F1 score, the harmonic mean of precision and recall. Here A scores 92.4 percent and B scores 91.0 percent, so A wins.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What does 90 percent recall mean for a cat classifier, in plain terms?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Of all the images in your dev set that really are cats, the classifier correctly pulled out 90 percent of them. Recall looks at the set of true cats and asks how many you found. Precision looks at the set of images you called cats and asks how many of those were right.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. You track error in four geographies for six algorithms. Why add an average column rather than reading the four columns directly?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because twenty-four numbers do not rank six algorithms. Scanning four columns per algorithm makes it slow and ambiguous to decide which is best, and it gets worse as you test more classifiers. Assuming the average is a reasonable summary for your application, it turns the table into one number per algorithm, and you can immediately see that algorithm C has the lowest average error at 3.5 percent.</p>
</div>
</div>
</div>
</section>
</section>
<section id="satisficing-and-optimizing-metrics" class="level2">
<h2 class="anchored" data-anchor-id="satisficing-and-optimizing-metrics">Satisficing and Optimizing Metrics</h2>
<p>It is not always easy to combine all the things you care about into a single number evaluation metric. In those cases it is sometimes useful to set up <strong>satisficing</strong> and <strong>optimizing</strong> metrics.</p>
<p>Say you have decided you care about the classification accuracy of your cat classifier. This could be the F1 score or some other measure of accuracy. But say that in addition to accuracy you also care about the running time, meaning how long it takes to classify an image.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Classifier</th>
<th>Accuracy</th>
<th>Running time</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>90%</td>
<td>80 ms</td>
</tr>
<tr class="even">
<td>B</td>
<td>92%</td>
<td>95 ms</td>
</tr>
<tr class="odd">
<td>C</td>
<td>95%</td>
<td>1,500 ms</td>
</tr>
</tbody>
</table>
<p>One thing you could do is combine accuracy and running time into an overall evaluation metric, such as</p>
<p><span class="math display">\[
\text{cost} = \text{accuracy} - 0.5 \times \text{running time}
\]</span></p>
<p>But it seems a bit artificial to combine accuracy and running time with a linear weighted sum like this. Here is something else you could do instead. Choose a classifier that maximizes accuracy, subject to the running time being less than or equal to 100 milliseconds.</p>
<p>In this case accuracy is the <strong>optimizing metric</strong>, because you want to do as well as possible on it. Running time is the <strong>satisficing metric</strong>, meaning it just has to be good enough. It needs to be under 100 milliseconds, and beyond that you do not really care, or at least you do not care that much. It may well be the case that as long as the running time is under 100 milliseconds, your users will not notice whether it is 100 milliseconds or 50 milliseconds.</p>
<p>Defining optimizing and satisficing metrics gives you a clear way to pick the best classifier, which here is classifier B, because of all the ones with a running time better than 100 milliseconds, it has the best accuracy. Classifier C has the highest accuracy of all, but it takes 1.5 seconds to classify an image, so it fails the threshold and is out of the running.</p>
<p>More generally, if you have <span class="math inline">\(N\)</span> metrics that you care about, it is sometimes reasonable to pick one of them to be optimizing, so you do as well as possible on that one, and the other <span class="math inline">\(N - 1\)</span> to be satisficing. As long as they reach some threshold you do not care how much better they are beyond it, but they do have to reach it.</p>
<section id="wake-word-detection" class="level3">
<h3 class="anchored" data-anchor-id="wake-word-detection">Wake Word Detection</h3>
<p>Here is another example. Say you are building a system to detect <strong>wake words</strong>, also called trigger words. This refers to voice control devices such as the Amazon Echo, which wakes up when you say “Alexa”, some Google devices that wake up when you say “Okay Google”, some Apple devices that wake up when you say “Hey Siri”, and some Baidu devices that wake up when you say “Ni hao Baidu”.</p>
<p>You might care about the accuracy of your trigger word detection system, meaning that when someone says one of these trigger words, how likely are you to actually wake up the device. You might also care about the number of <strong>false positives</strong>, meaning that when no one actually said the trigger word, how often does it randomly wake up.</p>
<p>A reasonable way of combining these two is to maximize accuracy, so that when someone says one of the trigger words you maximize the chance that the device wakes up, subject to having at most one false positive every 24 hours of operation. That way the device randomly wakes up only about once per day when no one is actually talking to it. Accuracy is the optimizing metric here, and the number of false positives per 24 hours is the satisficing metric.</p>
<p>To summarize, if there are multiple things you care about, pick one as the optimizing metric that you want to do as well as possible on, and one or more as satisficing metrics where you are satisfied as long as they do better than some threshold. You then have an almost automatic way of quickly looking at multiple classifiers and picking the best one.</p>
<p>These evaluation metrics have to be calculated on a training set, a dev set, or maybe a test set, so the next thing you need to do is set those up.</p>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. What is the difference between an optimizing metric and a satisficing metric?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>An optimizing metric is one you want to push as far as possible, so you maximize or minimize it. A satisficing metric only has to clear a threshold, and once it does you stop caring how much better it gets. With <span class="math inline">\(N\)</span> metrics, a common setup is one optimizing metric and <span class="math inline">\(N - 1\)</span> satisficing ones.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Given the accuracy and running time table above and a 100 millisecond threshold, which classifier wins, and why is it not the most accurate one?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Classifier B wins. C has the best accuracy at 95 percent, but at 1,500 milliseconds it fails the satisficing constraint entirely, so it is not eligible. Among A and B, which both run in under 100 milliseconds, B has the higher accuracy at 92 percent.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. For a wake word system, why is “at most one false positive every 24 hours” a better formulation than folding false positives into a weighted sum with accuracy?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because it matches what users actually experience. A device that wakes up once a day unprompted is tolerable, and cutting that to once every two days buys you very little, so the extra performance is not worth trading accuracy for. A weighted sum would keep rewarding improvements past the point where anyone notices, and the weights themselves would be arbitrary.</p>
</div>
</div>
</div>
</section>
</section>
<section id="train-dev-and-test-distributions" class="level2">
<h2 class="anchored" data-anchor-id="train-dev-and-test-distributions">Train, Dev, and Test Distributions</h2>
<p>The way you set up your training, dev, and test sets can have a huge impact on how rapidly you or your team make progress. Even teams at very large companies set up these data sets in ways that slow the team down rather than speed it up. The dev set is also called the development set, or sometimes the hold-out cross validation set. The workflow is that you try a lot of ideas, train up different models on the training set, then use the dev set to evaluate the different ideas and pick one, and keep innovating to improve dev set performance until finally you have one model you are happy with, which you then evaluate on your test set.</p>
<p>Say you are building a cat classifier and you are operating in these eight regions: the US, the UK, other European countries, South America, India, China, other Asian countries, and Australia. How do you set up your dev set and your test set?</p>
<p>One thing you could do is pick four of these regions, possibly four chosen at random, and say that data from those four regions goes into the dev set, and data from the other four goes into the test set. This turns out to be a very bad idea, because your dev and test sets then come from different distributions. Instead, find a way to make your dev and test sets come from the same distribution.</p>
<section id="where-you-place-the-target" class="level3">
<h3 class="anchored" data-anchor-id="where-you-place-the-target">Where You Place the Target</h3>
<p>One picture to keep in mind is that setting up your dev set plus your single number evaluation metric is like placing a target and telling your team where you think the bullseye is. Once you have established that dev set and that metric, the team can innovate very quickly, try different ideas, run experiments, and use the dev set and the metric to evaluate classifiers and pick the best one. Machine learning teams are often very good at shooting arrows into targets and innovating to get closer and closer to the bullseye.</p>
<div id="ef3dd90d" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="setting-up-your-goal_files/figure-html/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Each pass around the idea, code, experiment loop is one of those arrows. The team tries a different idea, codes it up, runs the experiment, and then reads the dev set and the metric to see how close the arrow landed. That is why the target has to be in the right place before the shooting starts.</p>
<div id="4f8de13b" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="setting-up-your-goal_files/figure-html/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The problem with the split on the left is that your team might spend months innovating to do well on the dev set, only to find when they finally test on the test set that data from those other four regions is very different. You get a nasty surprise, and all the months of work spent optimizing on the dev set do not give good performance on the test set. Having dev and test sets from different distributions is like setting a target, having your team spend months aiming closer and closer to the bullseye, and then announcing that the target is actually somewhere else. The team would reasonably ask why they spent months optimizing for a bullseye that you then moved.</p>
<p>To avoid this, take all the data, shuffle it randomly into the dev and test sets, so that both sets have data from all eight regions and both really do come from the same distribution, which is the distribution of all your data mixed together.</p>
</section>
<section id="story-about-zip-codes" class="level3">
<h3 class="anchored" data-anchor-id="story-about-zip-codes">Story About Zip Codes</h3>
<p>Here is a true story with some details changed. A machine learning team spent several months optimizing on a dev set made up of loan approvals for medium income zip codes. The problem was that given an input <span class="math inline">\(x\)</span> about a loan application, predict <span class="math inline">\(y\)</span>, whether or not the applicant will repay the loan, which helps you decide whether to approve it. Zip codes are what postal codes are called in the United States.</p>
<p>After working on this for a few months, the team suddenly decided to test the model on data from low income zip codes. The distribution of data for medium income and low income zip codes is very different, and the classifier they had spent so much time optimizing simply did not work well on the new data. That team wasted about three months and had to go back and redo a lot of work. What happened was that they spent three months aiming for one target, and then the manager asked how they were doing on a completely different target. It was a very frustrating experience for the team.</p>
<p>So the recommendation for setting up a dev set and a test set is to choose them to reflect data you expect to get in the future and consider important to do well on. In particular, the dev set and the test set should come from the same distribution. Whatever type of data you expect to get in the future and want to do well on, try to get data that looks like that, and put it into both your dev set and your test set. That way you are putting the target where you actually want to hit, and the team can innovate efficiently toward that same target.</p>
<p>The important takeaway is that setting up the dev set together with the evaluation metric is what defines the target you are aiming at. The way you choose your training set affects how well you can actually hit that target, and that is covered separately in a later section. Some machine learning teams could have saved themselves months of work by following these guidelines.</p>
</section>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. You have data from eight regions. Why is it a bad idea to build the dev set from four of them and the test set from the other four?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dev and test sets would come from different distributions. The team optimizes hard against the dev set for months, and then the test set measures something else, so the work does not transfer. It is the equivalent of moving the target after the team has spent months learning to hit it. Shuffle all eight regions into both sets instead.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In the loan approval story, what exactly went wrong, and how much did it cost?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The dev set was built from loan applications in medium income zip codes, and the team was later evaluated on low income zip codes. Those two distributions are very different, so the classifier tuned on the first did not work on the second. About three months of work had to be redone.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is the guideline for choosing a dev set and a test set?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Choose them to reflect data you expect to get in the future and consider important to do well on, and make sure both come from the same distribution. The dev set plus the evaluation metric is what defines the target, so put the target where you actually want to hit.</p>
</div>
</div>
</div>
</section>
</section>
<section id="size-of-dev-and-test-sets" class="level2">
<h2 class="anchored" data-anchor-id="size-of-dev-and-test-sets">Size of Dev and Test Sets</h2>
<p>The guidelines for how big the dev and test sets should be are also changing in the deep learning era. You may have heard the rule of thumb of taking all the data you have and using a 70/30 split into a train and test set, or a 60/20/20 split if you also set up a dev set. In earlier eras of machine learning this was pretty reasonable, especially when data set sizes were smaller. With a hundred, a thousand, or ten thousand examples in total, these rules of thumb are not unreasonable. The <a href="../../deep-learning/improving-deep-neural-networks/setting-up-your-machine-learning-application.html">Course 2 discussion of train, dev, and test sets</a> introduced these ratios and how they shift with data set size.</p>
<p>In the modern era we are used to working with much larger data sets. Say you have a million training examples. It might be quite reasonable to set up your data so that you have 98 percent in the training set, 1 percent dev, and 1 percent test. With a million examples, 1 percent is 10,000 examples, and that might be plenty for a dev set or a test set. So it is quite reasonable to use much less than 20 or 30 percent of your data for dev and test. Because deep learning algorithms have such a huge hunger for data, in problems with large data sets a much larger fraction goes into the training set.</p>
<section id="how-big-should-the-test-set-be" class="level3">
<h3 class="anchored" data-anchor-id="how-big-should-the-test-set-be">How Big Should the Test Set Be?</h3>
<p>The purpose of your test set is that, after you finish developing a system, it helps you evaluate how good your final system is. So the guideline is to make your test set big enough to give <strong>high confidence in the overall performance of your system</strong>. Unless you need a very accurate measure of how well your final system performs, you do not need millions and millions of examples in your test set. For many applications, 10,000 examples give enough confidence in the measured performance, and that could be much less than 30 percent of your overall data set, depending on how much data you have.</p>
</section>
<section id="when-you-might-not-need-a-test-set" class="level3">
<h3 class="anchored" data-anchor-id="when-you-might-not-need-a-test-set">When You Might Not Need a Test Set</h3>
<p>For some applications you may not need high confidence in the overall performance of your final system. Maybe all you need is a train set and a dev set, and not having a test set might be okay. In fact, what has sometimes happened is that people talk about using a train/test split when what they are actually doing is iterating on the test set. Rather than a test set, what they have is a train/dev split and no test set. If you are tuning to that set, it is better to call it a dev set. Not everyone in the history of machine learning has been completely rigorous about this terminology.</p>
<p>If all you care about is having some data to train on and some data to tune to, and you are not going to worry too much about an unbiased measure of how well the final system is doing, then it is healthier to just call it a train/dev set and acknowledge that you have no test set. This is a bit unusual, and it is definitely not the recommendation when building a system. A separate test set is reassuring, because it gives you an unbiased estimate of performance before you ship. But if you have a very large dev set, so that you do not think you will overfit it too badly, it is not totally unreasonable to have only a train/dev split, even though it is not the usual recommendation.</p>
<p>To summarize, in the era of big data the old rule of thumb of a 70/30 split no longer applies. The trend is to use more data for training and less for dev and test, especially when you have a very large data set. Set the dev set big enough for its purpose, which is to help you evaluate different ideas and pick between them, and set the test set big enough for its purpose, which is to evaluate your final system with confidence. That could be much less than 30 percent of the data.</p>
</section>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. You have 1,000,000 examples. Why is a 60/20/20 split wasteful, and what would you use instead?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>A 20 percent dev set would be 200,000 examples, far more than you need just to rank a handful of candidate models, and every example spent there is one the training set does not get. A 98/1/1 split gives 10,000 examples each for dev and test, which is typically plenty, and hands the other 980,000 to training, where deep learning algorithms actually use them.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What determines how big the test set should be?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Its purpose, which is giving high confidence in the overall performance of the final system. That is a question about how precise your estimate needs to be, not about a fixed percentage. For many applications 10,000 examples is enough, and for a large data set that is a tiny fraction of the total.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A team tells you they use a train/test split and that they have been tuning their model against that test set for months. What is actually going on?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>They have a train/dev split with no test set. Once you tune to a set, it stops giving an unbiased estimate of performance, so it is functioning as a dev set no matter what it is called. That setup can be acceptable if you do not need an unbiased final estimate, but it is more honest to call it a dev set and acknowledge that there is no test set.</p>
</div>
</div>
</div>
</section>
</section>
<section id="when-to-change-dev-and-test-sets-and-metrics" class="level2">
<h2 class="anchored" data-anchor-id="when-to-change-dev-and-test-sets-and-metrics">When to Change Dev and Test Sets and Metrics</h2>
<p>Setting up a dev set and an evaluation metric is like placing a target somewhere for your team to aim at. But sometimes partway through a project you realize you put the target in the wrong place. In that case you should move it.</p>
<section id="metric-that-ranks-the-wrong-algorithm-first" class="level3">
<h3 class="anchored" data-anchor-id="metric-that-ranks-the-wrong-algorithm-first">Metric That Ranks the Wrong Algorithm First</h3>
<p>Say you build a cat classifier to find lots of pictures of cats to show to your cat loving users, and the metric you decided to use is classification error. Algorithms A and B have 3 percent and 5 percent error respectively, so it seems like algorithm A is doing better. But when you look at these algorithms, algorithm A for some reason is letting through a lot of pornographic images. If you ship algorithm A, users see more cat images, since it has lower error at identifying cats, but it also shows users pornographic images, which is totally unacceptable both for your company and for your users. Algorithm B has 5 percent error, so it classifies fewer images correctly, but it does not let pornographic images through.</p>
<p>From your company’s point of view and from a user acceptance point of view, algorithm B is a much better algorithm. So algorithm A is doing better on your evaluation metric while actually being the worse algorithm. When your evaluation metric is no longer correctly rank ordering preferences between algorithms, that is a sign that you should change the evaluation metric, or perhaps the dev set or test set.</p>
<p>The misclassification error metric you are using can be written as follows, where <span class="math inline">\(m_{\text{dev}}\)</span> is the number of examples in your dev set,</p>
<p><span class="math display">\[
\text{Error} = \frac{1}{m_{\text{dev}}} \sum_{i=1}^{m_{\text{dev}}} \mathcal{I}\{\hat{y}^{(i)} \neq y^{(i)}\}
\]</span></p>
<p>The indicator function <span class="math inline">\(\mathcal{I}\{\cdot\}\)</span> equals 1 when the thing inside it is true and 0 otherwise, so this formula just counts up the number of misclassified examples and divides by how many there are.</p>
<p>The problem with this metric is that it treats pornographic and non-pornographic images equally, when you really do not want your classifier to mislabel a pornographic image as a cat image and show it to an unsuspecting user. One way to change the metric is to add a weight term <span class="math inline">\(w^{(i)}\)</span>,</p>
<p><span class="math display">\[
\text{Error} = \frac{1}{\sum_i w^{(i)}} \sum_{i=1}^{m_{\text{dev}}} w^{(i)} \, \mathcal{I}\{\hat{y}^{(i)} \neq y^{(i)}\}
\]</span></p>
<p>where</p>
<p><span class="math display">\[
w^{(i)} = \begin{cases}
1 &amp; \text{if } x^{(i)} \text{ is non-porn} \\
10 &amp; \text{if } x^{(i)} \text{ is porn}
\end{cases}
\]</span></p>
<p>This gives a much larger weight to pornographic examples, so the error goes up much more if the algorithm misclassifies one of them as a cat image. Here the weight is 10, and you could use a larger number such as 100. The normalization constant <span class="math inline">\(\sum_i w^{(i)}\)</span> keeps the error between zero and one.</p>
<p>The details of this weighting are not important, and to actually implement it you have to go through your dev and test sets and label the pornographic images so you can evaluate the weighting function. The high level takeaway is that if you find your evaluation metric is not giving the correct rank order preference for what is actually a better algorithm, then it is time to define a new evaluation metric. The goal of the evaluation metric is to accurately tell you, given two classifiers, which one is better for your application. If you are not satisfied with your old error metric, do not keep coasting with it. Define a new one that better captures your preferences.</p>
</section>
<section id="placing-the-target-and-shooting-at-it-are-separate-knobs" class="level3">
<h3 class="anchored" data-anchor-id="placing-the-target-and-shooting-at-it-are-separate-knobs">Placing the Target and Shooting at It Are Separate Knobs</h3>
<p>This is an example of <a href="../../deep-learning/structuring-machine-learning-projects/introduction-to-ml-strategy.html#orthogonalization">orthogonalization</a>. Take the machine learning problem and break it into distinct steps. One knob is figuring out how to define a metric that captures what you want to do. A separate knob is how to actually do well on that metric. To use the target analogy, the first step is placing the target, meaning defining where you want to aim. Then as a completely separate step you worry about how to aim accurately and shoot at it.</p>
<p>Defining the metric is step one, and you do something else for step two. In terms of shooting at the target, your learning algorithm is optimizing some cost function of the form <span class="math inline">\(J = \frac{1}{m} \sum_{i=1}^{m} \mathcal{L}(\hat{y}^{(i)}, y^{(i)})\)</span>. One thing you could do is modify it to incorporate the same weights, changing the normalization constant as well,</p>
<p><span class="math display">\[
J = \frac{1}{\sum_i w^{(i)}} \sum_{i=1}^{m} w^{(i)} \, \mathcal{L}(\hat{y}^{(i)}, y^{(i)})
\]</span></p>
<p>Again the details of how you define <span class="math inline">\(J\)</span> are not important. The point is that with the philosophy of orthogonalization you think of placing the target as one step, and aiming and shooting at the target as a distinct step that you handle separately. Define the metric first, and only after you have defined it, figure out how to do well on it, which might mean changing the cost function your network optimizes.</p>
</section>
<section id="dev-set-that-does-not-look-like-production" class="level3">
<h3 class="anchored" data-anchor-id="dev-set-that-does-not-look-like-production">Dev Set That Does Not Look Like Production</h3>
<p>Here is one more example. Say your two cat classifiers A and B have 3 percent and 5 percent error respectively as evaluated on your dev set, or even on your test set, which are images downloaded off the internet, so high quality well framed images. But when you deploy the product, algorithm B looks like it is performing better, even though A did better on your dev set. You have been training on very nice high quality images downloaded off the internet, but when users upload pictures through the mobile app they are much less well framed, they do not always cover only the cat, the cats have funny facial expressions, and the images are much blurrier. On that kind of data, algorithm B is actually doing better.</p>
<p>This is another example of your metric and dev/test sets falling down. You are evaluating on very nice high resolution well framed images, but what your users care about is doing well on the images they actually upload. So the guideline is that if doing well on your metric and your current dev and test set distribution does not correspond to doing well on the application you actually care about, then change your metric, or your dev and test sets, or both, so that your data better reflects the type of data you need to do well on.</p>
</section>
<section id="set-something-up-quickly-then-refine" class="level3">
<h3 class="anchored" data-anchor-id="set-something-up-quickly-then-refine">Set Something Up Quickly, Then Refine</h3>
<p>Having an evaluation metric and a dev set lets you much more quickly decide whether algorithm A or algorithm B is better, which really speeds up how quickly your team can iterate. So even if you cannot define the perfect evaluation metric and dev set, set something up quickly and use it to drive the speed of your team iterating. If later on you find out that it was not a good choice and you have a better idea, change it at that point. That is perfectly okay. What is not recommended is running for too long with no evaluation metric and no dev set at all, because that slows down how quickly your team can iterate and improve.</p>
</section>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Algorithm A has 3 percent error and algorithm B has 5 percent error, but A lets pornographic images through and B does not. What does this tell you about your metric?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The metric is no longer rank ordering the algorithms the way you and your users would. It says A is better while B is clearly the one you would ship. That is the signal to change the evaluation metric, or the dev and test sets, or both. Plain misclassification error treats a mislabeled pornographic image the same as any other mistake, which is not what you want.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Write the weighted error metric for the pornography example and explain the role of the normalization constant.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[
\text{Error} = \frac{1}{\sum_i w^{(i)}} \sum_{i=1}^{m_{\text{dev}}} w^{(i)} \, \mathcal{I}\{\hat{y}^{(i)} \neq y^{(i)}\}
\]</span></p>
<p>with <span class="math inline">\(w^{(i)} = 1\)</span> for non-pornographic examples and <span class="math inline">\(w^{(i)} = 10\)</span> (or larger) for pornographic ones. Weighting alone would push the error above 1, so dividing by <span class="math inline">\(\sum_i w^{(i)}\)</span> instead of by <span class="math inline">\(m_{\text{dev}}\)</span> keeps the value between zero and one. Note that implementing this requires actually labeling the pornographic images in the dev and test sets.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. How does changing the metric illustrate orthogonalization?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It separates two questions that are easy to tangle together. Defining a metric that captures what you want is placing the target. Doing well on that metric, which might involve putting the same weights into the cost function <span class="math inline">\(J\)</span>, is aiming and shooting. They are distinct knobs, and you handle the first one completely before worrying about the second.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Your dev set is high quality internet photos, but users upload blurry, poorly framed pictures, and the algorithm that wins on the dev set loses in production. What do you do?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Change the dev and test sets, and possibly the metric, so they reflect the blurry user-uploaded images you actually need to do well on. Doing well on the current dev set is not predictive of doing well on the application, which means the target is in the wrong place. The general guideline is that when the metric and the data you evaluate on stop corresponding to what you care about, change them.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. You cannot yet define a perfect evaluation metric for your problem. Should you wait until you can?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;Set something up quickly and use it to drive the speed of iteration, then change it later if you find a better one. Running for a long time with no metric and no dev set is the worse failure, because the team has no fast way to tell whether any given idea helped.</p>
</div>
</div>
</div>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 61%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">61% completed (90 of 147 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../deep-learning/structuring-machine-learning-projects/introduction-to-ml-strategy.html" class="pagination-link" aria-label="Introduction to ML Strategy">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Introduction to ML Strategy</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../deep-learning/structuring-machine-learning-projects/comparing-to-human-level-performance.html" class="pagination-link" aria-label="Comparing to Human-Level Performance">
        <span class="nav-page-text">Comparing to Human-Level Performance</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>