<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-08-13">
<meta name="description" content="A complete LeNet-inspired ConvNet with its activation shapes and parameter counts, and why parameter sharing and sparse connections make convolutions work so well.">

<title>Full ConvNet Example and Why Convolutions – H’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../deep-learning/convolutional-neural-networks/lab-convolutional-model-step-by-step.html" rel="next">
<link href="../../deep-learning/convolutional-neural-networks/pooling-layers.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-87fe4da730787eeec4a7ec728bf0e0b5.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Full ConvNet Example and Why Convolutions – H’s Notes">
<meta property="og:description" content="A complete LeNet-inspired ConvNet with its activation shapes and parameter counts, and why parameter sharing and sparse connections make convolutions work so well.">
<meta property="og:image" content="https://h.oliabak.com/deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="H’s Notes">
<meta name="twitter:title" content="Full ConvNet Example and Why Convolutions – H’s Notes">
<meta name="twitter:description" content="A complete LeNet-inspired ConvNet with its activation shapes and parameter counts, and why parameter sharing and sparse connections make convolutions work so well.">
<meta name="twitter:image" content="https://h.oliabak.com/deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">H’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.html">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/federated-learning/index.html">
 <span class="dropdown-text">Federated Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/improving-deep-neural-networks/index.html">
 <span class="dropdown-text">Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/structuring-machine-learning-projects/index.html">
 <span class="dropdown-text">Structuring Machine Learning Projects</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/convolutional-neural-networks/index.html">
 <span class="dropdown-text">Convolutional Neural Networks</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../networking/archive.html">
 <span class="dropdown-text">Archive</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Networking</li>
        <li>
    <a class="dropdown-item" href="../../tools/client-info.html">
 <span class="dropdown-text">Client Info</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/asn-conversion.html">
 <span class="dropdown-text">ASN Conversion</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/subnet-calculator.html">
 <span class="dropdown-text">Subnet Calculator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/network-toolkit.html">
 <span class="dropdown-text">Network Toolkit</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Share and Copy</li>
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Math and Writing</li>
        <li>
    <a class="dropdown-item" href="../../tools/function-graphs.html">
 <span class="dropdown-text">Function Graphs</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/markdown-preview.html">
 <span class="dropdown-text">Markdown Preview</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Astronomy</li>
        <li>
    <a class="dropdown-item" href="../../tools/eclipse-atlas.html">
 <span class="dropdown-text">Eclipse Atlas</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/planetarium.html">
 <span class="dropdown-text">Planetarium</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Design</li>
        <li>
    <a class="dropdown-item" href="../../tools/svg-preview.html">
 <span class="dropdown-text">SVG Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/color-pallet.html">
 <span class="dropdown-text">Color Pallet</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/typography.html">
 <span class="dropdown-text">Typography</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li class="dropdown-header">Games</li>
        <li>
    <a class="dropdown-item" href="../../tools/chess.html">
 <span class="dropdown-text">Chess Coach</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/reassess-your-chess.html">
 <span class="dropdown-text">Reassess Your Chess</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/daily-chess.html">
 <span class="dropdown-text">Daily Chess Puzzles</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions.html">Full ConvNet Example and Why Convolutions</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutional Neural Networks</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/convolutions-and-edge-detection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutions and Edge Detection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/strided-convolutions-and-volumes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Strided Convolutions and Convolutions Over Volume</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/one-layer-of-a-convolutional-network.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">One Layer of a Convolutional Network</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/pooling-layers.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pooling Layers</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/full-convnet-example-and-why-convolutions.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Full ConvNet Example and Why Convolutions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/lab-convolutional-model-step-by-step.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab: Convolutional Model Step by Step</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/lab-convolutional-model-application.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab: Convolutional Model Application</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/classic-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classic Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/modern-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modern Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/mobilenet-and-efficientnet.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">MobileNet and EfficientNet</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../deep-learning/convolutional-neural-networks/practical-advice-for-convnets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Practical Advice for Using ConvNets</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#complete-convnet-example" id="toc-complete-convnet-example" class="nav-link active" data-scroll-target="#complete-convnet-example">Complete ConvNet Example</a>
  <ul class="collapse">
  <li><a href="#activation-shapes-and-parameter-counts" id="toc-activation-shapes-and-parameter-counts" class="nav-link" data-scroll-target="#activation-shapes-and-parameter-counts">Activation Shapes and Parameter Counts</a></li>
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#why-convolutions" id="toc-why-convolutions" class="nav-link" data-scroll-target="#why-convolutions">Why Convolutions</a>
  <ul class="collapse">
  <li><a href="#parameter-sharing" id="toc-parameter-sharing" class="nav-link" data-scroll-target="#parameter-sharing">Parameter Sharing</a></li>
  <li><a href="#sparsity-of-connections" id="toc-sparsity-of-connections" class="nav-link" data-scroll-target="#sparsity-of-connections">Sparsity of Connections</a></li>
  <li><a href="#translation-invariance" id="toc-translation-invariance" class="nav-link" data-scroll-target="#translation-invariance">Translation Invariance</a></li>
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#training-a-convnet" id="toc-training-a-convnet" class="nav-link" data-scroll-target="#training-a-convnet">Training a ConvNet</a>
  <ul class="collapse">
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../auth.js"></script>
<script src="../../giscus-note.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../nav-columns.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Full ConvNet Example and Why Convolutions</h1>
  <div class="quarto-categories">
    <div class="quarto-category">deep-learning</div>
    <div class="quarto-category">convolutional-neural-networks</div>
    <div class="quarto-category">computer-vision</div>
    <div class="quarto-category">architecture</div>
    <div class="quarto-category">parameter-sharing</div>
  </div>
  </div>

<div>
  <div class="description">
    A complete LeNet-inspired ConvNet with its activation shapes and parameter counts, and why parameter sharing and sparse connections make convolutions work so well.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">August 13, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~50 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~3,600 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>You now know pretty much all the building blocks of a full convolutional neural network. This page puts them together into one complete network, counts every activation and every parameter in it, and then explains why convolutional layers are such a good idea in the first place.</p>
<section id="complete-convnet-example" class="level2">
<h2 class="anchored" data-anchor-id="complete-convnet-example">Complete ConvNet Example</h2>
<p>Suppose you are inputting an image which is 32 by 32 by 3, so it is an RGB image, and you are trying to do handwritten digit recognition. You have a number such as a 7 in a 32 by 32 RGB image, and you are trying to recognize which one of the ten digits from zero to nine it is.</p>
<p>The network used here is inspired by one of the classic neural networks called <strong>LeNet-5</strong>, created by Yann LeCun many years ago. What is shown here is not exactly LeNet-5, but many of the parameter choices were inspired by it.</p>
<p>With a 32 by 32 by 3 input, say the first layer uses a 5 by 5 filter, a stride of 1, and no padding. The output of this layer, if you use 6 filters, is 28 by 28 by 6, and this layer is called Conv 1. So you apply 6 filters, add a bias, apply the non-linearity, maybe a ReLU, and that is the Conv 1 output.</p>
<p>Next, apply a pooling layer. Use max pooling with a 2 by 2 filter and a stride of 2, so <span class="math inline">\(f = 2\)</span> and <span class="math inline">\(s = 2\)</span>. When no padding is written, it is <span class="math inline">\(p = 0\)</span>. This reduces the height and the width of the representation by a factor of 2, so 28 by 28 becomes 14 by 14, and the number of channels stays the same, giving 14 by 14 by 6. This is called the Pool 1 output.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Counting Layers
</div>
</div>
<div class="callout-body-container callout-body">
<p>In the ConvNet literature there are two conventions that are inconsistent with each other about what counts as a layer. One convention calls the conv layer a layer and the pool layer another layer.</p>
<p>When people report the number of layers in a neural network, they usually count only the layers that have weights, that have parameters. Because the pooling layer has no weights and no parameters, only a few hyperparameters, the convention used here is that Conv 1 and Pool 1 together are Layer 1. The 1 at the end of the names Conv 1 and Pool 1 also reflects the fact that both are viewed as part of Layer 1 of the neural network. Pool 1 is grouped into Layer 1 because it does not have its own weights.</p>
<p>If you read articles online and research papers, you will sometimes hear the conv layer and the pooling layer described as if they were two separate layers. Both are slightly inconsistent terminologies, and on these pages the counting is by layers that have weights.</p>
</div>
</div>
<p>Given a 14 by 14 by 6 volume, apply another convolutional layer with a filter size of 5 by 5, a stride of 1, no padding, and 16 filters this time. That gives a 10 by 10 by 16 volume, called Conv 2. Then do max pooling again with <span class="math inline">\(f = 2\)</span> and <span class="math inline">\(s = 2\)</span>, which halves the height and the width, leaving 5 by 5 by 16 with the same number of channels as before. That is Pool 2, and in this convention Conv 2 and Pool 2 together are Layer 2.</p>
<p>Now <span class="math inline">\(5 \times 5 \times 16 = 400\)</span>, so flatten Pool 2 into a 400 by 1 dimensional vector. Think of this as flattening the volume out into a set of 400 neurons.</p>
<p>Take those 400 units and build the next layer with 120 units. This is the first <strong>fully connected</strong> layer, called FC3, because 400 units are densely connected to 120 units. This fully connected layer is just like the single neural network layer seen in the earlier courses, a standard layer with a weight matrix <span class="math inline">\(W^{[3]}\)</span> of dimension 120 by 400, and a bias parameter that is 120 dimensional, since there are 120 outputs. It is called fully connected because each of the 400 units is connected to each of the 120 units.</p>
<p>Lastly, take the 120 units and add another layer, this time smaller, with 84 units, called fully connected Layer 4. That leaves 84 real numbers that you can feed to a softmax unit. Since the task is recognizing a handwritten digit from 0 to 9, this is a softmax with 10 outputs.</p>
<div id="11c0ef7f" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="full-convnet-example-and-why-convolutions_files/figure-html/cell-2-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>This is a reasonably typical example of what a convolutional neural network might look like. It seems like a lot of hyperparameters, and later sections give more specific suggestions for how to choose them. One common guideline is to not try to invent your own settings of hyperparameters, but to look in the literature to see which hyperparameters worked for others, and to choose an architecture that has worked well for someone else, since there is a good chance it will work for your application as well.</p>
<p>For now, notice again that as you go deeper in the neural network, usually the height and the width decrease. Here it goes from 32 by 32, to 28 by 28, to 14 by 14, to 10 by 10, to 5 by 5. Meanwhile the number of channels increases, going from 3 to 6 to 16, and then the fully connected layers come at the end.</p>
<p>Another pretty common pattern you see in neural networks is to have one or more conv layers followed by a pooling layer, then one or more conv layers followed by a pooling layer, and then at the end a few fully connected layers followed by a softmax.</p>
<section id="activation-shapes-and-parameter-counts" class="level3">
<h3 class="anchored" data-anchor-id="activation-shapes-and-parameter-counts">Activation Shapes and Parameter Counts</h3>
<p>Let us go through this network in more detail and look at the activation shape, the activation size, and the number of parameters at each stage. The input was 32 by 32 by 3, and multiplying those numbers out gives 3072, so the activation <span class="math inline">\(a^{[0]}\)</span> has 3072 numbers in it, and the input layer has no parameters.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Layer</th>
<th>Activation shape</th>
<th>Activation size</th>
<th>Parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Input</td>
<td>(32, 32, 3)</td>
<td>3072</td>
<td>0</td>
</tr>
<tr class="even">
<td>CONV 1 (<span class="math inline">\(f=5\)</span>, <span class="math inline">\(s=1\)</span>)</td>
<td>(28, 28, 6)</td>
<td>4704</td>
<td>456</td>
</tr>
<tr class="odd">
<td>POOL 1</td>
<td>(14, 14, 6)</td>
<td>1176</td>
<td>0</td>
</tr>
<tr class="even">
<td>CONV 2 (<span class="math inline">\(f=5\)</span>, <span class="math inline">\(s=1\)</span>)</td>
<td>(10, 10, 16)</td>
<td>1600</td>
<td>2416</td>
</tr>
<tr class="odd">
<td>POOL 2</td>
<td>(5, 5, 16)</td>
<td>400</td>
<td>0</td>
</tr>
<tr class="even">
<td>FC 3</td>
<td>(120, 1)</td>
<td>120</td>
<td>48120</td>
</tr>
<tr class="odd">
<td>FC 4</td>
<td>(84, 1)</td>
<td>84</td>
<td>10164</td>
</tr>
<tr class="even">
<td>Softmax</td>
<td>(10, 1)</td>
<td>10</td>
<td>850</td>
</tr>
</tbody>
</table>
<p>The parameter count of a convolutional layer follows from the shape of its filters.</p>
<p><span class="math display">\[
\left(f^{[l]} \times f^{[l]} \times n_c^{[l-1]} + 1\right) \times n_c^{[l]}
\]</span></p>
<p>The 1 inside the brackets is the bias, one per filter. For Conv 1 this gives <span class="math inline">\((5 \times 5 \times 3 + 1) \times 6 = 456\)</span>, and for Conv 2 it gives <span class="math inline">\((5 \times 5 \times 6 + 1) \times 16 = 2416\)</span>. A fully connected layer counts as the size of its weight matrix plus its biases, so FC 3 has <span class="math inline">\(400 \times 120 + 120 = 48120\)</span> parameters.</p>
<p>There are a few things worth pointing out.</p>
<p>First, notice that the max pooling layers have no parameters at all.</p>
<p>Second, notice that the conv layers tend to have relatively few parameters, as discussed in the earlier sections. In fact a lot of the parameters tend to be in the fully connected layers of the neural network.</p>
<p>Third, notice that the activation size tends to go down gradually as you go deeper in the neural network. If it drops too quickly, that is usually not great for performance. Here it starts at 3072, goes to 4704 and 1600, and then slowly falls to 84 before the softmax output. You will find that a lot of ConvNets have properties and patterns similar to these.</p>
</section>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. Why do Conv 1 and Pool 1 count as a single layer here?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the convention used is to count only layers that have weights, and the pooling layer has no weights, only hyperparameters. Some papers do count the pooling layer separately, so the terminology is not universal.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Conv 2 takes a 14 by 14 by 6 input with <span class="math inline">\(f = 5\)</span>, <span class="math inline">\(s = 1\)</span>, <span class="math inline">\(p = 0\)</span>, and 16 filters. Work out both the output shape and the parameter count.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The output side is <span class="math inline">\(\lfloor (14 - 5)/1 + 1 \rfloor = 10\)</span>, and the number of channels is the number of filters, so the output is 10 by 10 by 16. The parameters are <span class="math inline">\((5 \times 5 \times 6 + 1) \times 16 = 151 \times 16 = 2416\)</span>.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which layers hold most of the parameters in this network, and why?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The fully connected layers. FC 3 alone has 48120 parameters, more than everything else combined, because it connects every one of the 400 flattened units to every one of the 120 units. The conv layers reuse a small filter across all positions, so they need far fewer numbers.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What does it mean when the activation size drops too quickly between layers?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It usually hurts performance. A good architecture tends to reduce the activation size gradually, which is what happens here as it goes from 3072 down to 84 over several layers rather than all at once.</p>
</div>
</div>
</div>
</section>
</section>
<section id="why-convolutions" class="level2">
<h2 class="anchored" data-anchor-id="why-convolutions">Why Convolutions</h2>
<p>Now let us talk about why convolutions are so useful when you include them in your neural networks. There are two main advantages of convolutional layers over just using fully connected layers, called <strong>parameter sharing</strong> and <strong>sparsity of connections</strong>.</p>
<p>Take a 32 by 32 by 3 image, the same one as in the example above, and say you use a 5 by 5 filter with 6 filters, which gives a 28 by 28 by 6 output. Now, <span class="math inline">\(32 \times 32 \times 3\)</span> is 3072, and <span class="math inline">\(28 \times 28 \times 6\)</span> is 4704.</p>
<p>If you were to create a neural network with 3072 units in one layer and 4704 units in the next layer, and connect every one of these neurons to every one of those, then the number of parameters in the weight matrix would be</p>
<p><span class="math display">\[
3072 \times 4704 \approx 14 \text{ million}
\]</span></p>
<p>That is a lot of parameters to train. Today you can train neural networks with even more parameters than 14 million, but considering that this is a pretty small image, it is a lot. And of course, if the image were 1000 by 1000, the weight matrix would become impossibly large.</p>
<p>But if you look at the number of parameters in the convolutional layer, each filter is 5 by 5 by 3, so each filter has 75 parameters plus a bias, giving 76 parameters per filter. With 6 filters, the total number of parameters is</p>
<p><span class="math display">\[
(5 \times 5 \times 3 + 1) \times 6 = 456
\]</span></p>
<p>So the number of parameters in this conv layer remains quite small. The reason a ConvNet gets away with so few parameters comes down to two things.</p>
<section id="parameter-sharing" class="level3">
<h3 class="anchored" data-anchor-id="parameter-sharing">Parameter Sharing</h3>
<p>Parameter sharing is motivated by the observation that a feature detector, such as a vertical edge detector, that is useful in one part of the image is probably useful in another part of the image as well.</p>
<p>What that means is that if you have figured out, say, a 3 by 3 filter for detecting vertical edges, you can apply that same 3 by 3 filter here, and then at the next position over, and the next position over, and so on. Each of these feature detectors, each of these outputs, can use the same parameters in lots of different positions in the input image in order to detect a vertical edge or some other feature. This is true for low level features such as edges, as well as for higher level features, such as detecting the eye that indicates a face or a cat.</p>
<p>Sharing the same nine parameters to compute all 16 of these outputs is one of the ways the number of parameters is reduced. It also seems intuitive that a feature detector such as a vertical edge detector that is useful for the upper left hand corner of the image has a good chance of being useful for the lower right hand corner of the image too, so you do not need to learn separate feature detectors for the two corners. You might have a dataset where the upper left corner and the lower right corner have different distributions, so they may look a little bit different, but they are usually similar enough that sharing feature detectors all across the image works just fine.</p>
</section>
<section id="sparsity-of-connections" class="level3">
<h3 class="anchored" data-anchor-id="sparsity-of-connections">Sparsity of Connections</h3>
<p>The second way a ConvNet gets away with relatively few parameters is by having sparse connections.</p>
<p>Here is what that means. Look at one output value computed by a 3 by 3 convolution. It depends only on that 3 by 3 grid of input cells. It is as if that output unit on the right is connected only to nine out of the 36 input features of a 6 by 6 input, and all of the other pixel values have no effect at all on that output. As another example, a different output value depends only on its own nine input features, and the other pixels just do not affect it.</p>
<div id="b444dd58" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="full-convnet-example-and-why-convolutions_files/figure-html/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Through these two mechanisms, a neural network has far fewer parameters, which allows it to be trained with smaller training sets and makes it less prone to overfitting.</p>
</section>
<section id="translation-invariance" class="level3">
<h3 class="anchored" data-anchor-id="translation-invariance">Translation Invariance</h3>
<p>You also sometimes hear that convolutional neural networks are very good at capturing <strong>translation invariance</strong>. That is the observation that a picture of a cat shifted a couple of pixels to the right is still pretty clearly a cat.</p>
<p>The convolutional structure helps the neural network encode the fact that an image shifted a few pixels should result in pretty similar features, and should probably be assigned the same output label. The fact that you are applying the same filter at all the positions of the image, both in the early layers and in the later layers, helps a neural network automatically learn to be more robust, or to better capture the desirable property of translation invariance.</p>
<p>These are a couple of the reasons why convolutional neural networks work so well in computer vision.</p>
</section>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. State the two properties that keep the parameter count of a conv layer small.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Parameter sharing, meaning the same filter is reused at every position of the image rather than learning separate weights per position, and sparsity of connections, meaning each output value depends on only a small window of the input rather than on every input pixel.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A fully connected layer mapping 3072 units to 4704 units has about 14 million weights. What makes the equivalent conv layer need only 456 parameters?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The conv layer has 6 filters of size 5 by 5 by 3, so <span class="math inline">\((75 + 1) \times 6 = 456\)</span> numbers, and those same numbers are reused at all 784 output positions. The fully connected layer instead learns a separate weight for every pair of input and output units.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What is translation invariance, and how does the convolutional structure help with it?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It is the property that shifting an image by a few pixels should not change what it is a picture of. Because the same filter is applied at every position, a shifted input produces essentially the same features, just shifted too, so the network naturally tends to assign it the same label.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of the following statements about parameter sharing in ConvNets are true? Check all that apply.</strong></p>
<ol type="a">
<li><p>It allows gradient descent to set many of the parameters to zero, thus making the connections sparse.</p></li>
<li><p>It reduces the total number of parameters, thus reducing overfitting.</p></li>
<li><p>It allows parameters learned for one task to be shared even for a different task, which is transfer learning.</p></li>
<li><p>It allows a feature detector to be used in multiple locations throughout the whole input image or input volume.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b and d.</strong> Sliding one filter over the entire input is what lets a single feature detector work everywhere in the image, and it is why a conv layer needs so many fewer parameters than a fully connected one, which in turn leaves less room to overfit. Option a describes what regularization can do, and sparsity of connections is a separate property of conv layers rather than a consequence of sharing. Option c describes transfer learning, which reuses parameters across tasks and is a different idea altogether.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. In lecture, sparsity of connections was given as a benefit of convolutional layers. What does it mean?</strong></p>
<ol type="a">
<li><p>Each layer in a convolutional network is connected only to two other layers.</p></li>
<li><p>Each activation in the next layer depends on only a small number of activations from the previous layer.</p></li>
<li><p>Regularization causes gradient descent to set many of the parameters to zero.</p></li>
<li><p>Each filter is connected to every channel in the previous layer.</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>b.</strong> Every value in the output volume is produced by one filter applied to one small window of the input, so with a 3 by 3 filter it depends on 9 input values and on nothing else. Option d is true of a filter, since a filter does span all input channels, but that is not what sparsity of connections refers to.</p>
</div>
</div>
</div>
</section>
</section>
<section id="training-a-convnet" class="level2">
<h2 class="anchored" data-anchor-id="training-a-convnet">Training a ConvNet</h2>
<p>Finally, let us put it all together and see how you can train one of these networks.</p>
<p>Suppose you want to build a cat detector and you have a labelled training set, where now <span class="math inline">\(x\)</span> is an image, and the labels <span class="math inline">\(y\)</span> can be binary, or one of <span class="math inline">\(k\)</span> classes. Suppose you have chosen a convolutional neural network structure, taking in the image and then having several convolutional and pooling layers, followed by some fully connected layers, followed by a softmax output that produces <span class="math inline">\(\hat{y}\)</span>.</p>
<p>The conv layers and the fully connected layers have various parameters <span class="math inline">\(W\)</span> as well as biases <span class="math inline">\(b\)</span>. Any setting of these parameters lets you define a cost function similar to the ones seen in the earlier courses. Starting from randomly initialized parameters <span class="math inline">\(W\)</span> and <span class="math inline">\(b\)</span>, you compute the cost <span class="math inline">\(J\)</span> as the sum of the losses of the neural network’s predictions over the entire training set, divided by <span class="math inline">\(m\)</span>.</p>
<p><span class="math display">\[
J = \frac{1}{m} \sum_{i=1}^{m} \mathcal{L}(\hat{y}^{(i)}, y^{(i)})
\]</span></p>
<p>To train this neural network, all you need to do is use gradient descent, or one of the algorithms such as gradient descent with momentum, RMSProp, Adam, or something else, in order to optimize all the parameters of the neural network so as to reduce the cost function <span class="math inline">\(J\)</span>. If you do this, you can build a very effective cat detector or some other detector.</p>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. Which parameters of a ConvNet does gradient descent update?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The filters and biases of the conv layers, and the weight matrices and biases of the fully connected layers. Pooling layers contribute nothing, because they have no parameters.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Is anything different about the training procedure compared with a standard neural network?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>No.&nbsp;You define the cost as the average loss over the training set, initialize the parameters randomly, and run gradient descent or one of its variants such as momentum, RMSProp, or Adam. The gradients come from backpropagation exactly as before.</p>
</div>
</div>
</div>
<p>You have now seen all the basic building blocks of a convolutional neural network, the conv layer, the pooling layer, and the fully connected layer, and how to put them together into an effective image recognition system.</p>
<p>A lot of computer vision research has gone into figuring out how to put these basic building blocks together to build effective neural networks, and doing it well requires quite a bit of insight. One of the best ways to build that intuition is to see a number of concrete examples of how others have done it, which is what the following sections cover.</p>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 36%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">36% completed (281 of 779 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../deep-learning/convolutional-neural-networks/pooling-layers.html" class="pagination-link" aria-label="Pooling Layers">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Pooling Layers</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../deep-learning/convolutional-neural-networks/lab-convolutional-model-step-by-step.html" class="pagination-link" aria-label="Lab: Convolutional Model Step by Step">
        <span class="nav-page-text">Lab: Convolutional Model Step by Step</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>