<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-07-16">
<meta name="description" content="Why accuracy misleads on rare classes, and how the confusion matrix, precision, recall, and the F1 score evaluate classifiers on skewed data.">

<title>Skewed Datasets: Precision, Recall, and the F1 Score – Hossein’s Notes</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../machine-learning/advanced-learning-algorithms/lab-advice-for-applying-ml.html" rel="next">
<link href="../../machine-learning/advanced-learning-algorithms/machine-learning-development-process.html" rel="prev">
<link href="../../media/favicon.ico" rel="icon">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-a06763021a52c43c40a351ac8b799b8f.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-285f71f7c7ab2eebc0170294332e2983.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Skewed Datasets: Precision, Recall, and the F1 Score – Hossein’s Notes">
<meta property="og:description" content="Why accuracy misleads on rare classes, and how the confusion matrix, precision, recall, and the F1 score evaluate classifiers on skewed data.">
<meta property="og:image" content="https://h.oliabak.com/machine-learning/advanced-learning-algorithms/skewed-datasets_files/figure-html/cell-2-output-1.svg">
<meta property="og:site_name" content="Hossein’s Notes">
<meta name="twitter:title" content="Skewed Datasets: Precision, Recall, and the F1 Score – Hossein’s Notes">
<meta name="twitter:description" content="Why accuracy misleads on rare classes, and how the confusion matrix, precision, recall, and the F1 score evaluate classifiers on skewed data.">
<meta name="twitter:image" content="https://h.oliabak.com/machine-learning/advanced-learning-algorithms/skewed-datasets_files/figure-html/cell-2-output-1.svg">
<meta name="twitter:card" content="summary_large_image">
</head>

<body class="nav-sidebar docked nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Hossein’s Notes</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-math" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Math</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-math">    
        <li>
    <a class="dropdown-item" href="../../math/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/linear-algebra/index.html">
 <span class="dropdown-text">Linear Algebra</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/calculus/index.html">
 <span class="dropdown-text">Calculus</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/probability/index.html">
 <span class="dropdown-text">Probability</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../math/statistics/index.html">
 <span class="dropdown-text">Statistics</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-machine-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Machine Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-machine-learning">    
        <li>
    <a class="dropdown-item" href="../../machine-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/supervised-machine-learning/index.html">
 <span class="dropdown-text">Supervised Machine Learning: Regression and Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/advanced-learning-algorithms/index.html">
 <span class="dropdown-text">Advanced Learning Algorithms</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../machine-learning/unsupervised-learning/index.qmd">
 <span class="dropdown-text">Unsupervised Learning, Recommenders, Reinforcement Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-deep-learning" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Deep Learning</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-deep-learning">    
        <li>
    <a class="dropdown-item" href="../../deep-learning/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../deep-learning/neural-networks-and-deep-learning/index.html">
 <span class="dropdown-text">Neural Networks and Deep Learning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-agentic-ai" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Agentic AI</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-agentic-ai">    
        <li>
    <a class="dropdown-item" href="../../agentic/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/frameworks.html">
 <span class="dropdown-text">Frameworks</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/agent-architecture.html">
 <span class="dropdown-text">Agent Architecture</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../agentic/async-io.html">
 <span class="dropdown-text">Async I/O</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-networking" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Networking</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-networking">    
        <li>
    <a class="dropdown-item" href="../../networking/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../networking/ccde-written/index.html">
 <span class="dropdown-text">CCDE Written</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-tools" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Tools</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-tools">    
        <li>
    <a class="dropdown-item" href="../../tools/index.html">
 <span class="dropdown-text">Overview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/pastebin.html">
 <span class="dropdown-text">Pastebin</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/qr-code.html">
 <span class="dropdown-text">QR Code Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/svg-viewer.html">
 <span class="dropdown-text">SVG Viewer</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/graph.html">
 <span class="dropdown-text">Function Grapher</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/math-formula.html">
 <span class="dropdown-text">Math Formula Generator</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/latex-preview.html">
 <span class="dropdown-text">LaTeX Preview</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../tools/fancy-text.html">
 <span class="dropdown-text">Fancy Text Generator</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../about.html">
 <span class="dropdown-text">About Me</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../about/about-this-website.html">
 <span class="dropdown-text">About This Website</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="https://github.com/sponsors/hosseinoliabak"><i class="bi bi-github" role="img">
</i> 
 <span class="dropdown-text">Sponsor ♡</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html">Skewed Datasets: Precision, Recall, and the F1 Score</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Advanced Learning Algorithms</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/neural-networks-intuition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Networks Intuition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/neural-network-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Network Model</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/forward-propagation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Forward Propagation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/tensorflow-implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TensorFlow Implementation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/neural-networks-in-numpy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Networks in NumPy</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/lab-digit-recognition.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab: Handwritten Digit Recognition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/training-neural-networks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Training Neural Networks</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/activation-functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Activation Functions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/multiclass-classification.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multiclass Classification</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/advanced-optimization.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Additional Neural Network Concepts</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/lab-digit-recognition-multiclass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab: Handwritten Digit Recognition (Multiclass)</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/model-evaluation-and-selection.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model Evaluation and Selection</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/bias-and-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bias and Variance</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/machine-learning-development-process.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Machine Learning Development Process</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/skewed-datasets.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Skewed Datasets: Precision, Recall, and the F1 Score</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/lab-advice-for-applying-ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab: Advice for Applying Machine Learning</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../machine-learning/advanced-learning-algorithms/decision-trees.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Trees</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar"><div class="quarto-margin-header"><div class="margin-header-item">
<div id="page-qr" style="text-align:center; margin-bottom:12px;">
  <canvas id="page-qr-canvas"></canvas>
  <div style="font-size:11px; color:#888; margin-top:4px;">Scan to open on mobile</div>
</div>
<script src="https://cdn.jsdelivr.net/npm/qrcode/build/qrcode.min.js"></script>
<script>
(function() {
  var canvas = document.getElementById('page-qr-canvas');
  if (!canvas || typeof QRCode === 'undefined') return;
  QRCode.toCanvas(canvas, window.location.href, {
    width: 120,
    errorCorrectionLevel: 'M',
    margin: 1
  }, function(err) {
    if (err) canvas.style.display = 'none';
  });
})();
</script>

</div></div>
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#why-accuracy-fails-on-skewed-data" id="toc-why-accuracy-fails-on-skewed-data" class="nav-link active" data-scroll-target="#why-accuracy-fails-on-skewed-data">Why Accuracy Fails on Skewed Data</a>
  <ul class="collapse">
  <li><a href="#review-questions" id="toc-review-questions" class="nav-link" data-scroll-target="#review-questions">Review Questions</a></li>
  </ul></li>
  <li><a href="#confusion-matrix" id="toc-confusion-matrix" class="nav-link" data-scroll-target="#confusion-matrix">Confusion Matrix</a>
  <ul class="collapse">
  <li><a href="#review-questions-1" id="toc-review-questions-1" class="nav-link" data-scroll-target="#review-questions-1">Review Questions</a></li>
  </ul></li>
  <li><a href="#precision-and-recall" id="toc-precision-and-recall" class="nav-link" data-scroll-target="#precision-and-recall">Precision and Recall</a>
  <ul class="collapse">
  <li><a href="#review-questions-2" id="toc-review-questions-2" class="nav-link" data-scroll-target="#review-questions-2">Review Questions</a></li>
  </ul></li>
  <li><a href="#trading-off-precision-and-recall" id="toc-trading-off-precision-and-recall" class="nav-link" data-scroll-target="#trading-off-precision-and-recall">Trading Off Precision and Recall</a>
  <ul class="collapse">
  <li><a href="#review-questions-3" id="toc-review-questions-3" class="nav-link" data-scroll-target="#review-questions-3">Review Questions</a></li>
  </ul></li>
  <li><a href="#f1-score" id="toc-f1-score" class="nav-link" data-scroll-target="#f1-score">F1 Score</a>
  <ul class="collapse">
  <li><a href="#review-questions-4" id="toc-review-questions-4" class="nav-link" data-scroll-target="#review-questions-4">Review Questions</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">
<script src="../../theme-toggle.js"></script>
<script src="../../resume-reading.js"></script>
<script src="../../search-scope.js"></script>
<script src="../../review-numbering.js"></script>
<script src="../../breadcrumb-path.js"></script>
<script src="../../activation-colors.js"></script>
<script src="../../visit-history.js"></script>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Skewed Datasets: Precision, Recall, and the F1 Score</h1>
  <div class="quarto-categories">
    <div class="quarto-category">machine-learning</div>
    <div class="quarto-category">neural-networks</div>
  </div>
  </div>

<div>
  <div class="description">
    Why accuracy misleads on rare classes, and how the confusion matrix, precision, recall, and the F1 score evaluate classifiers on skewed data.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">July 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<script>
document.addEventListener("DOMContentLoaded", function () {
  var meta = document.querySelector(".quarto-title-meta");
  if (meta) {
    var div = document.createElement("div");
    div.style.order = "3";
    div.innerHTML = '<div class="quarto-title-meta-heading">Reading Time</div><div class="quarto-title-meta-contents"><p>~46 min read <span class="rt-info" style="cursor:help;opacity:0.6;font-size:0.85em;position:relative;">ⓘ<span class="rt-tooltip">Estimated based on 150 words/min reading speed, code complexity, math blocks, and interactive tools. Adjusted by difficulty level and capped at 3 hours.</span></span></p></div>';
    meta.appendChild(div);
    var lenDiv = document.createElement("div");
    lenDiv.style.order = "1";
    lenDiv.innerHTML = '<div class="quarto-title-meta-heading">Length</div><div class="quarto-title-meta-contents"><p>~3,800 words</p></div>';
    meta.appendChild(lenDiv);
    var diffDiv = document.createElement("div");
    diffDiv.style.order = "4";
    diffDiv.innerHTML = '<div class="quarto-title-meta-heading">Difficulty</div><div class="quarto-title-meta-contents"><p><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;background:#333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span><span style="display:inline-block;width:14px;height:14px;border-radius:50%;border:2px solid #333;margin-right:3px;vertical-align:middle;"></span></p></div>';
    meta.appendChild(diffDiv);
    var dateEl = meta.querySelector(".date");
    if (dateEl) {
      var pw = dateEl.parentNode && dateEl.parentNode.parentNode;
      if (pw) pw.style.order = "2";      if (!dateEl.dataset.weekdayified) {
        var d = new Date(dateEl.textContent.trim());
        if (!isNaN(d.getTime())) {
          var days = ["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
          dateEl.textContent = days[d.getDay()] + ", " + dateEl.textContent.trim();
        }
        dateEl.dataset.weekdayified = "1";
      }
    }
  }
});
</script>

<p>The <a href="../../machine-learning/advanced-learning-algorithms/machine-learning-development-process.html">machine learning development process</a> closed with a promise. There is one more practical tool for the toolbox, and it applies when you are working on an application where the ratio of positive to negative examples is very <strong>skewed</strong>, very far from 50-50. It turns out that in this situation the usual error metrics, like accuracy, do not work that well, and a different pair of metrics, <strong>precision</strong> and <strong>recall</strong>, takes their place.</p>
<section id="why-accuracy-fails-on-skewed-data" class="level2">
<h2 class="anchored" data-anchor-id="why-accuracy-fails-on-skewed-data">Why Accuracy Fails on Skewed Data</h2>
<p>Say you are training a binary classifier to detect a <strong>rare disease</strong> in patients, based on lab tests or other data from the patients. The label is <span class="math inline">\(y = 1\)</span> if the disease is present and <span class="math inline">\(y = 0\)</span> otherwise.</p>
<p>Suppose you find that your classifier achieves <strong>1% error</strong> on the test set, so it makes a correct diagnosis 99% of the time. That seems like a great outcome. But if the disease is rare, say only <strong>0.5%</strong> of the patients in the population have it, then this result is not as impressive as it sounds. Consider a program that is just one line long and does no learning at all.</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"y = 0"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>This program predicts <span class="math inline">\(y = 0\)</span> every single time. Since 99.5% of patients do not have the disease, it is right 99.5% of the time, so it has <strong>0.5% error</strong>, beating the learning algorithm that had 1% error.</p>
<div id="811ac0ab" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skewed-datasets_files/figure-html/cell-2-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A piece of software that just prints <span class="math inline">\(y = 0\)</span> is not a very useful diagnostic tool. It never diagnoses any patient as having the disease. What this really means is that on a skewed dataset, <strong>you cannot tell whether 1% error is a good result or a bad result</strong>. If one algorithm achieves 99.5% accuracy, another 99.2%, and a third 99.6%, it is difficult to know which is actually the best, because the one with the lowest error may be a not particularly useful predictor like the always-zero program. Quite possibly the algorithm with 1% error, which at least diagnoses some patients as having the disease, is more useful than the one with 0.5% error that diagnoses no one.</p>
<p>When working on problems with skewed datasets, we therefore usually use a different error metric rather than plain classification error. The most common pair of metrics is <strong>precision and recall</strong>, and building up to them starts with a small table called the confusion matrix.</p>
<section id="review-questions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions">Review Questions</h3>
<p><strong>1. A classifier for a rare condition reports 99% accuracy. Why is this number, on its own, not enough to conclude that the classifier is good?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because with a skewed dataset a trivial program can beat it. If only 0.5% of examples are positive, always predicting <span class="math inline">\(y = 0\)</span> scores 99.5% accuracy while being completely useless, since it never detects a single positive case. High accuracy on skewed data can simply reflect the skew, not any real predictive ability.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. What does it mean for a dataset to be skewed?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The ratio of positive to negative examples is very far from 50-50. In the rare disease example, only 0.5% of patients have the disease (<span class="math inline">\(y = 1\)</span>) and 99.5% do not (<span class="math inline">\(y = 0\)</span>), so the positive class is very rare.</p>
</div>
</div>
</div>
</section>
</section>
<section id="confusion-matrix" class="level2">
<h2 class="anchored" data-anchor-id="confusion-matrix">Confusion Matrix</h2>
<p>To evaluate how a learning algorithm performs when one class is rare, it is useful to construct a <strong>confusion matrix</strong>, a two-by-two table. Along the top goes the <strong>actual class</strong>, 1 or 0. Along the vertical axis goes the <strong>predicted class</strong>, what the learning algorithm predicted on a given example.</p>
<p>Say you have 100 <a href="../../machine-learning/advanced-learning-algorithms/model-evaluation-and-selection.html">cross-validation examples</a>. For each example, it lands in one of four cells depending on the prediction and the truth. Suppose the counts come out as in the matrix below. On 15 examples the algorithm predicted 1 and the actual label was also 1; on 5 it predicted 1 but the actual class was 0; on 10 it predicted 0 but the actual class was 1; and on 70 it predicted 0 and the actual class was 0.</p>
<div id="ae389343" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skewed-datasets_files/figure-html/cell-3-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>Adding the columns vertically, these 100 examples contain 25 where the actual class is 1 and 75 where it is 0, so the skew here is not as extreme as the 0.5% disease example, but the positive class is still the minority. Each of the four cells has a name.</p>
<ul>
<li><strong>True positive (15).</strong> The algorithm predicted positive, and that was true. The example really is positive.</li>
<li><strong>True negative (70).</strong> The algorithm predicted negative, and that was true. The example really is negative.</li>
<li><strong>False positive (5).</strong> The algorithm predicted positive, but that was false. The actual class is 0.</li>
<li><strong>False negative (10).</strong> The algorithm predicted negative, but that was false. The actual class is 1.</li>
</ul>
<p>The first word (<em>true</em> or <em>false</em>) says whether the prediction was correct, and the second word (<em>positive</em> or <em>negative</em>) says what the prediction was.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Same table in the statistics course
</div>
</div>
<div class="callout-body-container callout-body">
<p>This table may look familiar. The <a href="../../math/statistics/hypothesis-testing.html#type-i-and-type-ii-errors">hypothesis testing notes</a> lay out the exact same four cells for a spam detector, with Reality across the top and Decision down the side. In that language, a false positive is a <strong>Type I error</strong> (rejecting a true <span class="math inline">\(H_0\)</span>) and a false negative is a <strong>Type II error</strong> (failing to reject a false <span class="math inline">\(H_0\)</span>). The machine learning version simply fills the cells with counts from a whole cross-validation set instead of reasoning about a single decision.</p>
</div>
</div>
<section id="review-questions-1" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-1">Review Questions</h3>
<p><strong>1. Your algorithm predicts <span class="math inline">\(y = 1\)</span> for a patient who does not have the disease. Which cell of the confusion matrix does this example land in?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>False positive. The prediction was positive (<span class="math inline">\(y = 1\)</span>), and it was false because the actual class is 0. The second word records the prediction, and the first word records whether that prediction was right.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Using the counts above (15 true positives, 5 false positives, 10 false negatives, 70 true negatives), how many examples did the algorithm classify correctly, and how many actual positive examples are there?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>It classified <span class="math inline">\(15 + 70 = 85\)</span> examples correctly (the true positives plus the true negatives). There are <span class="math inline">\(15 + 10 = 25\)</span> actual positives, the true positives plus the false negatives, which is the sum down the “actual class 1” column.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A “false negative” means which of the following?</strong></p>
<ol type="a">
<li><p>The algorithm predicted 1 and the actual class was 1</p></li>
<li><p>The algorithm predicted 0 and the actual class was 0</p></li>
<li><p>The algorithm predicted 1 and the actual class was 0</p></li>
<li><p>The algorithm predicted 0 and the actual class was 1</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>d.</strong> The prediction was negative (predicted 0), and it was false, meaning the actual class was 1. Option (c) is a false positive, and options (a) and (b) are the true positive and true negative cells.</p>
</div>
</div>
</div>
</section>
</section>
<section id="precision-and-recall" class="level2">
<h2 class="anchored" data-anchor-id="precision-and-recall">Precision and Recall</h2>
<p>Having divided the classifications into the four cells, two common metrics to compute are precision and recall. In these definitions, <span class="math inline">\(y = 1\)</span> is the rare class we want to detect.</p>
<p><strong>Precision</strong> asks, of all the patients where we predicted <span class="math inline">\(y = 1\)</span>, what fraction actually has the rare disease? In other words, of all the examples predicted positive, what fraction did we get right?</p>
<p><span class="math display">\[
\text{precision} = \frac{\text{true positives}}{\text{\# predicted positive}} = \frac{\text{true positives}}{\text{true positives} + \text{false positives}} = \frac{15}{15 + 5} = 0.75
\]</span></p>
<p><strong>Recall</strong> asks, of all the patients that actually have the rare disease, what fraction did we correctly detect as having it?</p>
<p><span class="math display">\[
\text{recall} = \frac{\text{true positives}}{\text{\# actual positives}} = \frac{\text{true positives}}{\text{true positives} + \text{false negatives}} = \frac{15}{15 + 10} = 0.6
\]</span></p>
<p>The two metrics read off different slices of the confusion matrix. Precision looks across the <em>predicted positive</em> row, and recall looks down the <em>actual positive</em> column.</p>
<div id="b313bcba" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skewed-datasets_files/figure-html/cell-4-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In this example the algorithm has a precision of 75% and a recall of 60%. A precision of 75% means that of all the patients it thought had this rare disease, it was right 75% of the time. A recall of 60% means that of all the patients who actually have the disease, it correctly found 60% of them.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Connection to Bayes theorem
</div>
</div>
<div class="callout-body-container callout-body">
<p>Both metrics are conditional probabilities from the <a href="../../math/probability/bayes-theorem.html#medical-test-example">probability course</a>. Precision estimates <span class="math inline">\(P(\text{actually } 1 \mid \text{predicted } 1)\)</span>, which is exactly the quantity the medical test example computed with Bayes theorem, and recall estimates <span class="math inline">\(P(\text{predicted } 1 \mid \text{actually } 1)\)</span>, the effectiveness of the test on sick patients. The surprise on that page, a 99% accurate test whose positive results are almost all false alarms because the disease is so rare, is precisely what low precision on a skewed dataset looks like. The base rate there is the skew here.</p>
</div>
</div>
<p>Notice how this pair of metrics catches the useless always-zero program. If an algorithm predicts <span class="math inline">\(y = 0\)</span> all the time, it has <strong>no true positives</strong>, so the numerator of both quantities is zero. The recall in particular becomes <span class="math inline">\(0\)</span> divided by the number of actual positives, which equals <span class="math inline">\(0\)</span>. In general, a learning algorithm with either zero precision or zero recall is not a useful algorithm.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Side note on zero precision
</div>
</div>
<div class="callout-body-container callout-body">
<p>If an algorithm truly never predicts a single positive, the precision formula becomes <span class="math inline">\(0/0\)</span>, which is undefined. In practice, when an algorithm does not predict even one positive example, we just say its precision is also equal to <span class="math inline">\(0\)</span>.</p>
</div>
</div>
<p>Computing both precision and recall makes it easier to spot whether an algorithm is both reasonably accurate, in that when it says a patient has the disease there is a good chance it is right (such as the 0.75 chance here), and also catching a reasonable fraction of the actual cases (here, finding 60% of them). When you have a rare class, checking that both numbers are decently high helps reassure you that the learning algorithm is actually useful. The term <em>recall</em> itself was motivated by the question, of all the patients in a population who have the disease, how many would the algorithm have accurately diagnosed, or “recalled,” as having it?</p>
<section id="review-questions-2" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-2">Review Questions</h3>
<p><strong>1. In plain language, what different questions do precision and recall answer?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Precision answers, of all the examples the algorithm <em>predicted</em> as positive, what fraction really are positive? Recall answers, of all the examples that really <em>are</em> positive, what fraction did the algorithm find? Precision measures how trustworthy a positive prediction is, and recall measures how many of the actual positives get detected.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. A classifier evaluated on 200 cross-validation examples produces 30 true positives, 20 false positives, 10 false negatives, and 140 true negatives. Compute its precision and recall.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[\text{precision} = \frac{30}{30 + 20} = \frac{30}{50} = 0.6 \qquad \text{recall} = \frac{30}{30 + 10} = \frac{30}{40} = 0.75\]</span> When it predicts positive it is right 60% of the time, and it finds 75% of the actual positive examples.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which metric, precision or recall, is guaranteed to expose the program that always prints <span class="math inline">\(y = 0\)</span>, and why?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Recall. The always-zero program has no true positives, so its recall is <span class="math inline">\(0\)</span> divided by the number of actual positives, which is exactly <span class="math inline">\(0\)</span>. (Its precision is <span class="math inline">\(0/0\)</span>, which is undefined, and by convention we also call it <span class="math inline">\(0\)</span> when no positives are ever predicted.) A recall of zero flags the algorithm as useless no matter how high its accuracy is.</p>
</div>
</div>
</div>
</section>
</section>
<section id="trading-off-precision-and-recall" class="level2">
<h2 class="anchored" data-anchor-id="trading-off-precision-and-recall">Trading Off Precision and Recall</h2>
<p>In the ideal case we would like algorithms with <strong>high precision and high recall</strong>. High precision would mean that if it diagnoses a patient with the rare disease, the patient probably does have it. High recall means that if there is a patient with the rare disease, the algorithm will probably correctly identify them. In practice, though, there is often a <strong>trade-off</strong> between the two.</p>
<p>Recall how <a href="../../machine-learning/supervised-machine-learning/logistic-regression.html">logistic regression</a> makes predictions. The model outputs a number between 0 and 1, and we typically threshold at 0.5, predicting 1 if <span class="math inline">\(f_{\vec{w},b}(\vec{x}) \geq 0.5\)</span> and 0 if <span class="math inline">\(f_{\vec{w},b}(\vec{x}) &lt; 0.5\)</span>.</p>
<p><strong>Raising the threshold raises precision and lowers recall.</strong> Suppose we want to predict <span class="math inline">\(y = 1\)</span>, the disease is present, only if we are very confident, perhaps because a positive diagnosis sends the patient to an invasive and expensive treatment, and the consequences of the disease are not that bad if it is left untreated for a while. Then we might set a higher threshold and predict 1 only when <span class="math inline">\(f_{\vec{w},b}(\vec{x}) \geq 0.7\)</span>, that is, only when we are at least 70% sure. Whenever the algorithm predicts 1, it is now more likely to be right, so precision increases. But it predicts 1 less often, so of the total number of patients with the disease, it correctly diagnoses fewer of them, and recall drops. Raise the threshold to 0.9 and precision goes even higher, while recall goes even further down.</p>
<p><strong>Lowering the threshold lowers precision and raises recall.</strong> Now suppose we want to avoid missing too many cases of the disease. When in doubt, predict <span class="math inline">\(y = 1\)</span>. This might be the right philosophy when treatment is not too invasive, painful, or expensive, but leaving the disease untreated has much worse consequences for the patient. In that case we might set the threshold to 0.3, predicting 1 whenever there is a 30% chance or better of the disease being present. We are now looser, more willing to predict 1 even when unsure, so precision falls, but of all the patients who do have the disease, we correctly identify more of them, so recall rises.</p>
<p>More generally, we have the flexibility to predict 1 only when <span class="math inline">\(f_{\vec{w},b}(\vec{x})\)</span> is above <em>some</em> threshold, and by choosing the threshold we can make different trade-offs. For most learning algorithms, sweeping the threshold from very high to very low traces out a curve like the one below.</p>
<div id="320208a2" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skewed-datasets_files/figure-html/cell-5-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<p>A very high threshold, say 0.99, lands at the top left, very high precision but low recall. As the threshold decreases, the operating point slides along the curve, until a very low threshold, say 0.01, ends up at the bottom right with very low precision but relatively high recall. By plotting this curve, you can pick the point, that is, the threshold, that best balances the cost of false positives against the cost of false negatives for your application.</p>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Picking the threshold is your job, not cross-validation’s
</div>
</div>
<div class="callout-body-container callout-body">
<p>Choosing the threshold is not something you can really do with <a href="../../machine-learning/advanced-learning-algorithms/model-evaluation-and-selection.html">cross-validation</a>, because it is up to <em>you</em> to specify the best trade-off point. Whether missing a disease case is worse than an unnecessary treatment depends on the application, not on any error number the data can minimize. For many applications, manually picking the threshold to trade off precision and recall is what you will end up doing.</p>
</div>
</div>
<section id="review-questions-3" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-3">Review Questions</h3>
<p><strong>1. You raise the prediction threshold from 0.5 to 0.9. What happens to precision and recall, and why?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Precision goes up and recall goes down. The algorithm now predicts 1 only when it is very confident, so when it does predict 1 it is more likely to be right (higher precision). But it predicts 1 much less often, so it correctly identifies a smaller fraction of the patients who actually have the disease (lower recall).</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Give a situation where you would deliberately <em>lower</em> the threshold below 0.5, and explain the reasoning.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>When missing a positive case is much worse than a false alarm. For example, if a disease has terrible consequences when left untreated but the treatment is cheap and not very invasive, you might predict <span class="math inline">\(y = 1\)</span> whenever the model estimates even a 30% chance of disease. Precision falls, since more of the positive predictions are wrong, but recall rises, since far fewer true cases slip through undetected.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Why can the best threshold not simply be chosen automatically by minimizing the cross-validation error?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because the right trade-off depends on the real-world costs of the two kinds of mistakes, false positives versus false negatives, and those costs are not in the data. Whether an invasive treatment for a healthy patient is better or worse than an untreated sick patient is an application-level judgment, so for many applications the threshold is picked manually from the precision-recall curve.</p>
</div>
</div>
</div>
</section>
</section>
<section id="f1-score" class="level2">
<h2 class="anchored" data-anchor-id="f1-score">F1 Score</h2>
<p>If you want to automatically trade off precision and recall rather than judging the balance yourself, there is another metric, the <strong>F1 score</strong>, that combines them into a single number. One challenge with precision and recall is that you are now evaluating algorithms with <em>two</em> different metrics. Suppose you have trained three algorithms and their numbers come out as follows.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 28%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Precision <span class="math inline">\(P\)</span></th>
<th style="text-align: center;">Recall <span class="math inline">\(R\)</span></th>
<th style="text-align: center;"><span style="text-decoration:line-through; text-decoration-color:#CC0000; text-decoration-thickness:2.5px;">Average</span> <span style="color:#CC0000; font-weight:700;">✗</span></th>
<th style="text-align: center;"><span class="math inline">\(F_1\)</span> score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Algorithm 1</td>
<td style="text-align: center;">0.5</td>
<td style="text-align: center;">0.4</td>
<td style="text-align: center;"><span style="text-decoration:line-through; text-decoration-color:#CC0000; text-decoration-thickness:2px; color:#999;">0.45</span></td>
<td style="text-align: center;"><span style="display:inline-block; border:2.5px solid #2E8B57; border-radius:999px; padding:0.05em 0.45em; font-weight:700;">0.444</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Algorithm 2</td>
<td style="text-align: center;">0.7</td>
<td style="text-align: center;">0.1</td>
<td style="text-align: center;"><span style="text-decoration:line-through; text-decoration-color:#CC0000; text-decoration-thickness:2px; color:#999;">0.40</span></td>
<td style="text-align: center;">0.175</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Algorithm 3</td>
<td style="text-align: center;">0.02</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: center;"><span style="text-decoration:line-through; text-decoration-color:#CC0000; text-decoration-thickness:2px; color:#999;">0.51</span></td>
<td style="text-align: center;">0.0392</td>
</tr>
</tbody>
</table>
<p>If one algorithm were better on both precision and recall, you would probably just pick that one. But here, Algorithm 2 has the highest precision, Algorithm 3 has the highest recall, and Algorithm 1 trades off the two in between, so no algorithm is obviously the best choice. To decide, it helps to combine precision and recall into a single score and pick the algorithm with the highest one.</p>
<p><strong>Taking the plain average does not work well.</strong> The averages are 0.45, 0.40, and 0.51, which would crown Algorithm 3. But look at its numbers. A recall of 1.0 with a precision of 0.02 corresponds to an algorithm that more or less prints <span class="math inline">\(y = 1\)</span> all the time and diagnoses every patient as having the disease. Recall is perfect, precision is dreadful, and the algorithm is not actually useful. An algorithm with very low precision or very low recall is pretty much not useful, so let us not use the plain average.</p>
<p>The most common way of combining the two is the <strong>F1 score</strong>, an average of sorts that pays more attention to whichever value is lower. Instead of averaging <span class="math inline">\(P\)</span> and <span class="math inline">\(R\)</span>, average <span class="math inline">\(\frac{1}{P}\)</span> and <span class="math inline">\(\frac{1}{R}\)</span>, and then take the inverse of that.</p>
<p><span class="math display">\[
F_1 = \frac{1}{\dfrac{1}{2}\left(\dfrac{1}{P} + \dfrac{1}{R}\right)} = 2\,\frac{PR}{P + R}
\]</span></p>
<p>Averaging <span class="math inline">\(1/P\)</span> and <span class="math inline">\(1/R\)</span> gives much greater emphasis to whichever of <span class="math inline">\(P\)</span> or <span class="math inline">\(R\)</span> is very small, because a tiny value makes its reciprocal huge. Computing the F1 score for the three algorithms gives 0.444, 0.175, and 0.0392. Notice how 0.175 sits much closer to Algorithm 2’s <em>lower</em> value (0.1) than to its higher one (0.7), and Algorithm 3’s near-zero precision drags its F1 score to nearly zero despite the perfect recall. By the F1 score, Algorithm 1 is the best of the three, which matches the intuition that it strikes the most sensible balance.</p>
<div id="dc8a6a79" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="skewed-datasets_files/figure-html/cell-6-output-1.svg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Harmonic mean
</div>
</div>
<div class="callout-body-container callout-body">
<p>In math, the F1 formula is also called the <strong>harmonic mean</strong> of <span class="math inline">\(P\)</span> and <span class="math inline">\(R\)</span>. The harmonic mean is a way of taking an average that emphasizes the smaller values more. For this course, you do not need to worry about that terminology.</p>
</div>
</div>
<p>That completes the advice for applying machine learning, from <a href="../../machine-learning/advanced-learning-algorithms/model-evaluation-and-selection.html">evaluating models</a> and <a href="../../machine-learning/advanced-learning-algorithms/bias-and-variance.html">diagnosing bias and variance</a> through the <a href="../../machine-learning/advanced-learning-algorithms/machine-learning-development-process.html">development process</a> and, on this page, the tools for skewed datasets. By applying these ideas, you will be very effective at building machine learning systems. The next part of the course turns to another very powerful machine learning algorithm. Among the advanced techniques used in many commercial production settings, at the top of the list alongside neural networks sit <strong>decision trees</strong>, which are covered in the pages ahead.</p>
<section id="review-questions-4" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="review-questions-4">Review Questions</h3>
<p><strong>1. Why is the plain average of precision and recall a poor way to rank algorithms on a skewed problem?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because a useless extreme can still score well. Algorithm 3, with precision 0.02 and recall 1.0, behaves like a program that predicts <span class="math inline">\(y = 1\)</span> for everyone; its recall is perfect only because it diagnoses every patient as sick. Its average, 0.51, is the highest of the three, yet the algorithm is not useful. An algorithm with very low precision or very low recall should be ranked low, and the plain average fails to do that.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. An algorithm has precision <span class="math inline">\(P = 0.6\)</span> and recall <span class="math inline">\(R = 0.2\)</span>. Compute its F1 score and compare it with the plain average.</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><span class="math display">\[F_1 = 2\,\frac{PR}{P + R} = 2 \times \frac{0.6 \times 0.2}{0.6 + 0.2} = \frac{0.24}{0.8} = 0.3\]</span> The plain average is <span class="math inline">\((0.6 + 0.2)/2 = 0.4\)</span>. The F1 score of 0.3 sits closer to the lower value (0.2), reflecting that the weak recall limits how useful the algorithm really is.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Which of the following statements about the F1 score is true?</strong></p>
<ol type="a">
<li><p>It is the plain average of precision and recall</p></li>
<li><p>It always equals whichever of precision and recall is larger</p></li>
<li><p>It combines precision and recall while giving more emphasis to whichever is lower</p></li>
<li><p>It can only be computed when precision equals recall</p></li>
</ol>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>c.</strong> The F1 score averages the reciprocals <span class="math inline">\(1/P\)</span> and <span class="math inline">\(1/R\)</span> and inverts the result, which makes a very small precision or a very small recall dominate the score. That is exactly why it is preferred over the plain average (a) for picking among algorithms on skewed data.</p>
</div>
</div>
</div>
<hr>
<p><strong>1. Of the three algorithms in the table, Algorithm 2 has the highest precision (0.7). Why does the F1 score rank it below Algorithm 1?</strong></p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tip</span>Answer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Because its recall is only 0.1, and the F1 score pays the most attention to the lower of the two numbers. Its F1 score of 0.175 lands much closer to 0.1 than to 0.7. Algorithm 1’s more balanced 0.5 precision and 0.4 recall give the higher F1 score of 0.444, so it wins despite not leading on either individual metric.</p>
</div>
</div>
</div>


<div id="section-progress-widget" style="display:none; padding: 0.8em 1em; background: inherit; border-top: 1px solid var(--bs-border-color, #dee2e6); position: sticky; bottom: 0; z-index: 10;">
  <p style="font-size: 0.8em; color: var(--bs-secondary-color, #6c757d); margin: 0 0 0.4em 0; font-weight: 600;">Progress</p>
  <div style="background: var(--bs-secondary-bg, #e9ecef); border-radius: 6px; height: 8px; width: 100%; overflow: hidden;">
    <div style="background: var(--bs-primary, #2c3e50); height: 100%; width: 88%; border-radius: 6px;"></div>
  </div>
  <p style="font-size: 0.75em; color: var(--bs-tertiary-color, #adb5bd); margin: 0.3em 0 0 0;">88% completed (1697 of 1920 min)</p>
</div>
<script>
document.addEventListener("DOMContentLoaded", function() {
  var w = document.getElementById("section-progress-widget");
  var sb = document.getElementById("quarto-sidebar");
  if (w && sb) { w.style.display = "block"; sb.appendChild(w); }
});
</script>

</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/h\.oliabak\.com");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<input type="hidden" id="giscus-base-theme" value="https://h.oliabak.com/giscus-theme.css">
<input type="hidden" id="giscus-alt-theme" value="https://h.oliabak.com/giscus-theme.css">
<script>
  function loadGiscus() {
    // Function to get the theme based on body class
    const getTheme = () => {
      let baseTheme = document.getElementById('giscus-base-theme').value;
      let altTheme = document.getElementById('giscus-alt-theme').value;
      return document.body.classList.contains('quarto-dark') ? altTheme : baseTheme;
    };
    const script = document.createElement("script");
    script.src = "https://giscus.app/client.js";
    script.async = true;
    script.dataset.repo = "hosseinoliabak/h";
    script.dataset.repoId = "R_kgDOR0RoEw";
    script.dataset.category = "Announcements";
    script.dataset.categoryId = "DIC_kwDOR0RoE84C5n1Q";
    script.dataset.mapping = "pathname";
    script.dataset.reactionsEnabled = "1";
    script.dataset.emitMetadata = "0";
    script.dataset.inputPosition = "top";
    script.dataset.theme = getTheme();
    script.dataset.lang = "en";
    script.crossOrigin = "anonymous";
    // Append the script to the desired div instead of at the end of the body
    document.getElementById("quarto-content").appendChild(script);
  }
  loadGiscus();
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../machine-learning/advanced-learning-algorithms/machine-learning-development-process.html" class="pagination-link" aria-label="Machine Learning Development Process">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Machine Learning Development Process</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../machine-learning/advanced-learning-algorithms/lab-advice-for-applying-ml.html" class="pagination-link" aria-label="Lab: Advice for Applying Machine Learning">
        <span class="nav-page-text">Lab: Advice for Applying Machine Learning</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>